In [1]:
import pandas as pd
pd.set_option('display.max_columns', None)
pd.set_option('display.max_rows', None) 
import numpy as np
#pd.set_option('display.max_info_columns', None)

# funtion

In [67]:
# Function to get the name of a DataFrame
def get_variable_name(df):
    for name, value in globals().items():
        if value is df:
            return name
        

# Function to measure how many CASEID values are repetitive in a DataFrame
# def count_repetitive_caseids(df):
#     if 'CASEID' in df.columns:  # Check if 'CASEID' column exists
#         duplicate_count = df['CASEID'].duplicated().sum()  # Count duplicates
#         total_count = df['CASEID'].count()  # Count total rows
#         unique_count = df['CASEID'].nunique()  # Count unique CASEID
#         return duplicate_count, total_count, unique_count
#     else:
#         return None, None, None  # If 'CASEID' column is missing


def count_repetitive_caseids(df):
    if 'CASEID' in df.columns:  # Check if 'CASEID' column exists
        duplicate_count = df['CASEID'].duplicated().sum()  # Count duplicates
        total_count = df['CASEID'].count()  # Count total rows
        unique_count = df['CASEID'].nunique()  # Count unique CASEID
        return duplicate_count, total_count, unique_count
    else:
        return None, None, None  # If 'CASEID' column is missing

In [103]:
# Replace with the actual path to your file
df = pd.read_csv("C:/Users/linoc/OneDrive/Encoder/03_partos/01_raws/2023/910-Modulo1633/910-Modulo1633/REC41_2023.csv")
df.head()

C:\Users\linoc\AppData\Local\Temp\ipykernel_16920\303823266.py:2: DtypeWarning: Columns (51) have mixed types. Specify dtype option on import or set low_memory=False.
  df = pd.read_csv("C:/Users/linoc/OneDrive/Encoder/03_partos/01_raws/2023/910-Modulo1633/910-Modulo1633/REC41_2023.csv")

,ID1,CASEID,MIDX,M1,M1A,M1B,M1C,M1D,M1E,M2A,M2B,M2C,M2D,M2E,M2F,M2G,M2H,M2I,M2J,M2K,M2L,M2M,M2N,M3A,M3B,M3C,M3D,M3E,M3F,M3G,M3H,M3I,M3J,M3K,M3L,M3M,M3N,M4,M5,M6,M7,M8,M9,M10,M11,M13,M14,M15,M17,M18,M19,M19A,M27,M28,M29,M34,M35,M36,M38,M39,M42A,M42B,M42C,M42D,M42E,M43,M44,M45,M46,M47,M48,M49A,M49B,M49C,M49D,M49E,M49F,M49G,M49X,M49Z,M51A,M54,M55A,M55B,M55C,M55D,M55E,M55F,M55G,M55H,M55I,M55J,M55K,M55L,M55M,M55N,M55X,M55Z,M57A,M57B,M57C,M57D,M57E,M57F,M57G,M57H,M57I,M57J,M57K,M57L,M57M,M57N,M57O,M57P,M57Q,M57R,M57S,M57T,M57U,M57V,M57X,M60,M61,M62,M63,M64,M65A,M65B,M65C,M65D,M65E,M65F,M65G,M65H,M65I,M65J,M65K,M65L,M65X,M66,M67,M68,M69,M70,M71,M72,M73
0,2023,000100601 2,1,0,2,98,2017,,1411,0,0,0,0,0,,0,,,,0,,,1,0,0,0,0,0,,0,1,,,0,,,0,18,18,10,10,3,3,3,,,0,11,0,5,9996,0,0,0,0,230,,,0,6,,,,,,,,0,,0,0,,,,,,,,,,,0,0,0,0,,0,0,0,0,0,,,,,,0,1,,,,,,,,,,,,,,,,,,,,,,,,0,,,,,,,,,,,,,,,,,,1,101,12,22,1,101,11,22
1,2023,000102201 2,1,2,,,,,,0,0,1,0,0,,0,,,,0,,,0,1,1,1,0,0,,0,0,,,0,,,0,18,18,6,6,1,1,2,203,2,13,21,0,3,3160,1,0,0,0,0,,,0,5,1,,1,1,1,1,1,1,80,0,0,,,,,,,,,,,0,0,0,0,,0,0,0,0,0,,,,,,0,1,,,,,0,0,1,,0,0,0,0,0,,0,0,0,,0,,,,0,0,,,,,,,,,,,,,,,,,,1,104,12,21,1,103,11,21
2,2023,000102801 1,1,0,2,7,2015,,1387,0,0,1,0,0,,0,,,,0,,,0,1,1,1,1,0,,0,0,,,0,,,0,18,18,18,18,96,24,3,,1,7,22,1,4,2290,1,0,0,0,201,,,0,6,1,,1,1,1,1,1,1,120,0,0,,,,,,,,,,,0,0,0,0,,0,0,0,0,0,,,,,,0,1,,,,,0,0,0,,1,0,0,0,0,,0,0,0,,0,,,,0,0,,,,,,,,,,,,,,,,,,1,102,11,22,1,100,11,22
3,2023,000106501 2,1,1,0,,,,,0,0,1,0,0,,0,,,,0,,,0,1,1,1,0,0,,0,0,,,0,,,0,14,14,6,6,6,6,1,,1,15,21,0,2,3303,1,0,0,0,0,,,0,5,1,,1,1,1,1,1,1,135,0,0,,,,,,,,,,,1,0,0,0,,0,0,1,0,0,,,,,,0,0,,,,,0,0,1,,0,0,0,0,0,,0,0,0,,0,,,,0,0,,,,,,,,,,,,,,,,,,1,101,13,21,1,101,11,21
4,2023,000108001 1,1,1,8,98,9998,7,1389,0,0,1,0,0,,0,,,,0,,,0,0,1,1,0,0,,0,0,,,0,,,0,18,18,1,1,3,3,2,205,5,4,22,0,3,2900,2,0,0,0,102,,,1,4,1,,1,1,1,0,,1,120,0,0,,,,,,,,,,,0,0,0,0,,0,0,0,0,0,,,,,,0,1,,,,,0,0,1,,0,0,0,0,0,,0,0,0,,0,,,,0,0,,,,,,,,,,,,,,,,,,1,104,13,22,1,104,13,22

In [82]:
df['CASEID_count'] = df.groupby('CASEID')['CASEID'].transform('count')
#df.sort_values(by='CASEID_count').head(10)
df['CASEID_count'].value_counts()

CASEID_count
1    35657
Name: count, dtype: int64

In [88]:
df.shape

(35657, 85)

In [91]:
df.CASEID.nunique()

35657

In [3]:
df['CASEID']  = df['CASEID'].str.replace(" ", "")

In [104]:
#df[df['CASEID']=='100601']

df[df['CASEID'].astype(str).str.contains('000100601')]


#000100601 2

,ID1,CASEID,MIDX,M1,M1A,M1B,M1C,M1D,M1E,M2A,M2B,M2C,M2D,M2E,M2F,M2G,M2H,M2I,M2J,M2K,M2L,M2M,M2N,M3A,M3B,M3C,M3D,M3E,M3F,M3G,M3H,M3I,M3J,M3K,M3L,M3M,M3N,M4,M5,M6,M7,M8,M9,M10,M11,M13,M14,M15,M17,M18,M19,M19A,M27,M28,M29,M34,M35,M36,M38,M39,M42A,M42B,M42C,M42D,M42E,M43,M44,M45,M46,M47,M48,M49A,M49B,M49C,M49D,M49E,M49F,M49G,M49X,M49Z,M51A,M54,M55A,M55B,M55C,M55D,M55E,M55F,M55G,M55H,M55I,M55J,M55K,M55L,M55M,M55N,M55X,M55Z,M57A,M57B,M57C,M57D,M57E,M57F,M57G,M57H,M57I,M57J,M57K,M57L,M57M,M57N,M57O,M57P,M57Q,M57R,M57S,M57T,M57U,M57V,M57X,M60,M61,M62,M63,M64,M65A,M65B,M65C,M65D,M65E,M65F,M65G,M65H,M65I,M65J,M65K,M65L,M65X,M66,M67,M68,M69,M70,M71,M72,M73
0,2023,000100601 2,1,0,2,98,2017,,1411,0,0,0,0,0,,0,,,,0,,,1,0,0,0,0,0,,0,1,,,0,,,0,18,18,10,10,3,3,3,,,0,11,0,5,9996,0,0,0,0,230,,,0,6,,,,,,,,0,,0,0,,,,,,,,,,,0,0,0,0,,0,0,0,0,0,,,,,,0,1,,,,,,,,,,,,,,,,,,,,,,,,0,,,,,,,,,,,,,,,,,,1,101,12,22,1,101,11,22

In [ ]:
df.MIDX.value_counts()

MIDX
1    18435
2     2308
3       97
Name: count, dtype: int64

In [94]:
df[df['CASEID']=='0549080012']

Empty DataFrame
Columns: [ID1, CASEID, V501, V502, V503, V504, V505, V506, V507, V508, V509, V510, V511, V512, V513, V525, V527, V528, V529, V530, V531, V532, V535, V536, V537, V538, V539, V540, V541, V602, V603, V604, V605, V613, V614, V616, V621, V623, V624, V625, V626, V627, V628, V629, V631, V632, V633A, V633B, V633C, V633D, V633E, V633F, V633G, V634, V701, V702, V704, V705, V714, V714A, V715, V716, V717, V719, V721, V729, V730, V731, V732, V739, V740, V741, V743A, V743B, V743C, V743D, V743E, V743F, V744A, V744B, V744C, V744D, V744E, V746, CASEID_count]
Index: []

In [95]:
df['Pre'] = np.where(df['M19'] < 2500, 1, 0)
df.head()

KeyError: 'M19'

In [7]:
df[['M19']].info(verbose = True)

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 20840 entries, 0 to 20839
Data columns (total 1 columns):
 #   Column  Non-Null Count  Dtype
---  ------  --------------  -----
 0   M19     20840 non-null  int64
dtypes: int64(1)
memory usage: 162.9 KB

In [8]:
df[['M19']].describe(percentiles= [0.1,0.2,0.5,0.7,0.90,.95])

                M19
count  20840.000000
mean    3450.731622
std     1243.104810
min      450.000000
10%     2600.000000
20%     2860.000000
50%     3300.000000
70%     3560.000000
90%     4000.000000
95%     4320.000000
max     9998.000000

In [9]:
df_group = df.groupby(["CASEID"], as_index=False).agg({
    "Pre": "sum"
})
df_group.head()

       CASEID  Pre
0  0001006012    0
1  0001022012    0
2  0001028011    1
3  0001065012    0
4  0001080011    0

In [10]:
df_group.Pre.value_counts()

Pre
0    17164
1     1169
2       99
3        3
Name: count, dtype: int64

In [11]:
df_group.shape

(18435, 2)

In [12]:
(1169+99+3)/18435

0.0689449416870084

In [ ]:
''''
grupo 1 : No tuvieron pre : 1169
groupo 2: si tuvieron : 1200
'''

# 02 Read Tables

In [ ]:

Modulo1631_REC91_2023 = pd.read_csv("C:/Users/linoc/OneDrive/Encoder/03_partos/01_raws/2023/910-Modulo1631/REC91_2023.csv", low_memory=False)
Modulo1632_RE223132_2023 = pd.read_csv("C:/Users/linoc/OneDrive/Encoder/03_partos/01_raws/2023/910-Modulo1632/RE223132_2023.csv", low_memory=False)
Modulo1632_REC21_2023 = pd.read_csv("C:/Users/linoc/OneDrive/Encoder/03_partos/01_raws/2023/910-Modulo1632/REC21_2023.csv", low_memory=False)
Modulo1633_REC41_2023 = pd.read_csv("C:/Users/linoc/OneDrive/Encoder/03_partos/01_raws/2023/910-Modulo1633/910-Modulo1633/REC41_2023.csv", low_memory=False)
Modulo1633_REC94_2023 = pd.read_csv("C:/Users/linoc/OneDrive/Encoder/03_partos/01_raws/2023/910-Modulo1633//910-Modulo1633/REC94_2023.csv", low_memory=False)
Modulo1635_RE516171_2023 = pd.read_csv("C:/Users/linoc/OneDrive/Encoder/03_partos/01_raws/2023/910-Modulo1635/RE516171_2023.csv", low_memory=False)
Modulo1635_RE516171_2024 = pd.read_csv("C:/Users/linoc/OneDrive/Encoder/03_partos/01_raws/2023/910-Modulo1635/RE516171_2023.csv", low_memory=False)
#Modulo1640_CSALUD01_2023 = pd.read_csv("C:/Users/linoc/OneDrive/Encoder/03_partos/01_raws/2023/910-Modulo1640/CSALUD01_2023.csv", low_memory=False)

print(f"size file: {get_variable_name(Modulo1631_REC91_2023)}: {Modulo1631_REC91_2023.shape}")
print(f"size file: {get_variable_name(Modulo1632_RE223132_2023)}: {Modulo1632_RE223132_2023.shape}")
print(f"size file: {get_variable_name(Modulo1632_REC21_2023)}: {Modulo1632_REC21_2023.shape}")
print(f"size file: {get_variable_name(Modulo1633_REC41_2023)}: {Modulo1633_REC41_2023.shape}")
print(f"size file: {get_variable_name(Modulo1633_REC94_2023)}: {Modulo1633_REC94_2023.shape}")
print(f"size file: {get_variable_name(Modulo1635_RE516171_2023)}: {Modulo1635_RE516171_2023.shape}")
print(f"size file: {get_variable_name(Modulo1635_RE516171_2024)}: {Modulo1635_RE516171_2024.shape}")
#print(f"size file: {get_variable_name(Modulo1640_CSALUD01_2023)}: {Modulo1640_CSALUD01_2023.shape}")

size file: Modulo1631_REC91_2023: (38352, 343)
size file: Modulo1632_RE223132_2023: (35657, 149)
size file: Modulo1632_REC21_2023: (63593, 34)
size file: Modulo1633_REC41_2023: (20840, 147)
size file: Modulo1633_REC94_2023: (20840, 61)
size file: Modulo1635_RE516171_2023: (35657, 84)

In [78]:
# List of DataFrames and their variable names
# Dictionary with DataFrame names as keys and DataFrame objects as values
# dataframes = {
#     "Modulo1631_REC91_2023": Modulo1631_REC91_2023,
#     "Modulo1632_RE223132_2023": Modulo1632_RE223132_2023,
#     "Modulo1632_REC21_2023": Modulo1632_REC21_2023,
#     "Modulo1633_REC41_2023": Modulo1633_REC41_2023,
#     "Modulo1633_REC94_2023": Modulo1633_REC94_2023,
#     "Modulo1635_RE516171_2023": Modulo1635_RE516171_2023,
# #    "Modulo1640_CSALUD01_2023": Modulo1640_CSALUD01_2023
# }

dataframes = [df,
    Modulo1631_REC91_2023,
    Modulo1632_RE223132_2023,
    Modulo1632_REC21_2023,
    Modulo1633_REC41_2023,
    Modulo1633_REC94_2023,
    Modulo1635_RE516171_2023,
 #   Modulo1640_CSALUD01_2023
]


# Loop over each dataframe and print the repetitive CASEID information
for df in dataframes:
    duplicate_count, total_count, unique_count = count_repetitive_caseids(df)
    if duplicate_count is not None:
        print(f"DataFrame {get_variable_name(df)}:")
        print(f"  Total CASEIDs: {total_count}")
        print(f"  Unique CASEIDs: {unique_count}")
        print(f"  Repetitive CASEIDs: {duplicate_count}")
    else:
        print(f"'CASEID' column not found in {get_variable_name(df)}")

DataFrame df:
  Total CASEIDs: 20840
  Unique CASEIDs: 18435
  Repetitive CASEIDs: 2405
DataFrame df:
  Total CASEIDs: 38352
  Unique CASEIDs: 38352
  Repetitive CASEIDs: 0
DataFrame df:
  Total CASEIDs: 35657
  Unique CASEIDs: 35657
  Repetitive CASEIDs: 0
DataFrame df:
  Total CASEIDs: 63593
  Unique CASEIDs: 25642
  Repetitive CASEIDs: 37951
DataFrame df:
  Total CASEIDs: 20840
  Unique CASEIDs: 18435
  Repetitive CASEIDs: 2405
DataFrame df:
  Total CASEIDs: 20840
  Unique CASEIDs: 18435
  Repetitive CASEIDs: 2405
DataFrame df:
  Total CASEIDs: 35657
  Unique CASEIDs: 35657
  Repetitive CASEIDs: 0

In [83]:
Modulo1632_REC21_2023.info(verbose = True, show_counts = True)

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 63593 entries, 0 to 63592
Data columns (total 34 columns):
 #   Column   Non-Null Count  Dtype
---  ------   --------------  -----
 0   ID1      63593 non-null  int64
 1   CASEID   63593 non-null  object
 2   BIDX     63593 non-null  int64
 3   BORD     63593 non-null  int64
 4   B0       63593 non-null  int64
 5   B1       63593 non-null  int64
 6   B2       63593 non-null  int64
 7   B3       63593 non-null  int64
 8   B4       63593 non-null  int64
 9   B5       63593 non-null  int64
 10  B6       63593 non-null  object
 11  B7       63593 non-null  object
 12  B8       63593 non-null  object
 13  B9       63593 non-null  object
 14  B10      63593 non-null  int64
 15  B11      63593 non-null  object
 16  B12      63593 non-null  object
 17  B13      63593 non-null  object
 18  B15      63593 non-null  object
 19  B16      63593 non-null  object
 20  BD       63593 non-null  int64
 21  BDD      63593 non-null  int64
 22  BMM      63593 non-null  int64
 23  BAA      63593 non-null  int64
 24  BCMC     63593 non-null  int64
 25  BEDAD    63593 non-null  int64
 26  QD333_1  63593 non-null  object
 27  QD333_2  63593 non-null  object
 28  QD333_3  63593 non-null  object
 29  QD333_4  63593 non-null  object
 30  QD333_5  63593 non-null  object
 31  QD333_6  63593 non-null  object
 32  Q220A    63593 non-null  object
 33  QULT5    63593 non-null  int64
dtypes: int64(17), object(17)
memory usage: 16.5+ MB

In [86]:
Modulo1632_REC21_2023.sort_values(by='CASEID').head(10)

,ID1,CASEID,BIDX,BORD,B0,B1,B2,B3,B4,B5,B6,B7,B8,B9,B10,B11,B12,B13,B15,B16,BD,BDD,BMM,BAA,BCMC,BEDAD,QD333_1,QD333_2,QD333_3,QD333_4,QD333_5,QD333_6,Q220A,QULT5
0,2023,000100601 2,4,1,0,6,2001,1218,1,1,,,21,0,1,,21,,,6,8,14,2,2023,1478,260,,,,,,,,0
43923,2023,000100601 2,2,3,0,10,2015,1390,2,1,,,7,0,1,151,46,,0,4,2,14,2,2023,1478,88,,,,,,,,0
54142,2023,000100601 2,1,4,0,7,2019,1436,2,1,,,3,0,1,46,,,0,5,27,14,2,2023,1478,42,2,2,2,2,2,2,6,1
25642,2023,000100601 2,3,2,0,2,2003,1239,2,1,,,19,0,1,21,151,,0,3,16,14,2,2023,1478,239,,,,,,,,0
1,2023,000102201 2,1,1,0,11,2020,1451,2,1,,,2,0,1,,,,,3,14,15,2,2023,1478,27,2,2,2,2,2,2,9,1
25643,2023,000102801 1,1,2,0,1,2021,1454,2,1,,,2,0,1,63,,,0,3,27,13,2,2023,1478,24,2,2,2,2,2,2,8,1
2,2023,000102801 1,2,1,0,10,2015,1391,1,1,,,7,0,1,,63,,,2,26,13,2,2023,1478,87,,,,,,,,0
3,2023,000106501 2,1,1,0,6,2018,1423,2,1,,,4,0,1,,,,,3,25,14,2,2023,1478,55,2,2,2,2,2,2,9,1
4,2023,000108001 1,2,1,0,6,2012,1351,1,1,,,10,0,1,,99,,,3,24,13,2,2023,1478,127,,,,,,,,0
25644,2023,000108001 1,1,2,0,9,2020,1450,2,1,,,2,0,1,99,,,0,4,19,13,2,2023,1478,28,2,2,2,2,2,2,9,1

In [92]:
Modulo1632_REC21_2023.CASEID.nunique()

25642

In [87]:
Modulo1632_REC21_2023.Q220A.value_counts()

Q220A
     41259
9    17989
8     3617
7      614
6       97
5       17
Name: count, dtype: int64

In [ ]:
Modulo1640_CSALUD01_2023.head()

,ID1,HHID,QHCLUSTER,QHNUMBER,QHHOME,QSNUMERO,QSINTM,QSINTY,QSTOTVISIT,QSRESULT,QSNINOS,QSRESINF,QS20C,QSSEXO,QSMEF,QSDIA,QS22M,QS22A,QS23,QS24,QS25N,QS25AG,QS25A,QS25G,QS25AA,QS25BB,QS26,QS27,QS28,QS29A,QS29B,QS100,QS101,QS102,QS103U,QS103C,QS104,QS105,QS106,QS107,QS108,QS109,QS110U,QS110C,QS111,QS112,QS113,QS202,QS203U,QS203C,QS204U,QS204C,QS205U,QS205C,QS206,QS207U,QS207C,QS208,QS209,QS210,QS211U,QS211C,QS212T,QS212A,QS212AV,QS212AB,QS212B,QS212BV,QS212BB,QS212C,QS212CV,QS212CB,QS212D,QS212DV,QS212DB,QS212E,QS212EV,QS212EB,QS212F,QS212FV,QS212FB,QS212G,QS212GV,QS212GB,QS212O,QS212XV,QS212XB,QS212Z,QS213U,QS213C,QS214U,QS214C,QS215U,QS215C,QS216U,QS216C,QS217U,QS217C,QS218U,QS218C,QS219U,QS219C,QS220U,QS220CV,QS220CC,QS200,QS201,QS302C,QS303,QS304,QS305U,QS305C,QS306,QS307,QS308,QS309,QS311,QS312U,QS312C,QS313,QS301,QS302U,QS403,QS404,QS406,QS407,QS409,QS410U,QS410C,QS411,QS412U,QS412C,QS413,QS413A,QS413B,QS413B_A,QS413C,QS413D,QS413E,QS413E_A,QS413F,QS415,QS416U,QS416C,QS401,QS402,QS500,QS501U,QS501C,QS503,QS505A,QS505B,QS505C,QS505D,QS506,QS603,QS604,QS606,QS607,QS608,QS609,QS610,QS611,QS601A,QS601B,QS700A,QS700B,QS700C,QS700D,QS700E,QS700F,QS700G,QS700H,QS700I,QS702,QS703,QS704T,QS704A,QS704B,QS704C,QS704D,QS704E,QS704F,QS704G,QS704H,QS704I,QS706,QS707,QS709,QS710,QS711,QS713,QS714,QS715,QS716,QS717,QS719,QS720,QS721,QS722,QS723,QS724,QS725,QS726,QS727,QS728,QS729,QS730,QFIN,QS8INICIO,QS900,QS901,QS902,QS903S,QS903D,QS905S,QS905D,QS906,QS25C1,QS25C2,QS25C3,QS25C4,QS25C5,QS25C6,QS907,QS908,QS506B,QS708_A,QS708_AA,QS708_AB,QS708_B,QS708_C,QS708_D,QS708_E,QS708_EA,QS708_F,QS708_G,QS708_H,QS708_I,QS708_J,QS708_X,QS708_Y,QS731_A,QS731_AA,QS731_AB,QS731_B,QS731_C,QS731_D,QS731_E,QS731_EA,QS731_F,QS731_G,QS731_H,QS731_I,QS731_J,QS731_X,QS731_Y,Peso15_amas
0,2023,100601,1,6,1,1,2,2023,2,1,,1,1,1,2,4,7,1982,40,1,2,1,5,,10,7,2,,,,,2,,2,,,,,,2,,2,,,,,,,,,,,,,1,1,17,1,1,1,1,3,A,1,0,4,2,,,2,,,2,,,2,,,2,,,2,,,2,,,0,1,7,1,1,3,,,,3,,,,1,3,1,1,,2,,,,,,,,,,,,,,,,,1,8,2,,,,,,,,,,,,,,,,,,,,1,1,2,,,1,1,1,2,1,1,2,,,,,,,,1,1,0,0,0,0,0,0,0,0,0,,2,,,,,,,,,,,,2,1,1,1,2,2,,2,1,2,2,2,2,2,2,2,2,2,2,2,2,,,70.7,164.5,1,119,71,110,68,1,2,2,2,2,2,2,87.5,1,2,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,331396.597020675
1,2023,101001,1,10,1,1,4,2023,4,1,,1,1,1,2,1,2,1950,73,1,1,1,5,,10,7,1,A,,,,2,,2,,,,,,2,,2,,,,,,,,,,,,,1,1,30,1,2,2,,,,,,,,,,,,,,,,,,,,,,,,,,,,,1,3,1,1,3,,,,3,,,,1,2,1,5,,1,2,2,98,2,,,2,,,,1,2,56,20,1,2,1,1,2,,,,,,,,,,,,,,,,,,,,1,1,2,,,1,1,1,1,1,1,,,,,,,,,,,0,0,0,0,0,0,0,0,0,,2,,,,,,,,,,,,2,1,1,1,,,,,,,,,,,,,,,,,2,,,63.9,172.7,1,109,73,101,74,1,2,2,2,2,2,2,85.5,1,2,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,294239.85770727
2,2023,101901,1,19,1,2,2,2023,1,1,,1,2,2,2,1,1,1973,50,1,2,1,5,,10,7,2,,,,,2,,2,,,,,,2,,2,,,,,,,,,,,,,1,1,22,2,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,1,3,1,1,3,,,,3,,,,1,1,1,1,,2,,4,21,2,,,2,,,,,,,,1,2,1,1,2,,2,,,2,,,,2,,,,2,,,,2,,,1,1,1,1,2,1,2,2,2,2,2,,,,,,,,,,,0,0,2,0,0,0,0,0,0,3,2,,,,,,,,,,,,2,1,1,1,,,,,,,,,,,,,,,,,2,,,95.5,163,1,127,76,115,73,1,2,2,2,2,2,2,115.5,1,1,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,580777.258893703
3,2023,102201,1,22,1,1,4,2023,3,1,,1,1,1,2,22,1,1994,29,1,4,1,5,,10,7,1,A,,,,2,,2,,,,,,1,20,2,,,,,,,,,,,,,1,1,18,1,1,1,1,3,A,1,0,3,2,,,2,,,2,,,2,,,2,,,2,,,2,,,0,1,3,1,2,3,,,,3,,,,1,7,1,1,,2,,,,,,,,,,,,,,,,,1,1,2,,,,,,,,,,,,,,,,,,,,1,1,2,,,1,1,1,2,1,1,2,,1,1,2,2,2,1,1,1,0,0,0,0,0,0,0,0,0,,1,,0,0,0,0,0,1,1,0,0,3,2,1,1,1,2,2,,2,2,,,,,,,,,,,,2,,,97.7,167.4,1,138,75,136,74,1,2,2,2,2,2,2,107.3,1,2,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,254754.5887036
4,2023,102801,1,28,1,1,2,2023,1,1,,1,1,2,1,30,1,1988,35,1,3,1,3,,10,7,1,A,1,1,1,2,,2,,,,,,2,,2,,,,,,,,,,,,,1,1,23,1,2,2,,,,,,,,,,,,,,,,,,,,,,,,,,,,,1,7,1,3,1,3,1,1,3,,,,1,3,1,1,,2,,,,,,,,,,,,,,,,,1,1,1,,2,,,1,1,12,1,1,1,18,1,1,1,12,1,,,,1,1,2,,,,1,1,2,1,1,2,,,,,,,,,,1,1,0,1,0,0,0,0,0,2,1,,1,1,0,1,0,0,2,0,0,2,2,2,,,,,,,,,,,,,,,,,,,2,,,46.1,154.2,4,119,87,119,84,1,2,2,2,2,2,2,69,1,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,188680.807227799

In [73]:
Modulo1640_CSALUD01_2023.tail()

,ID1,HHID,QHCLUSTER,QHNUMBER,QHHOME,QSNUMERO,QSINTM,QSINTY,QSTOTVISIT,QSRESULT,QSNINOS,QSRESINF,QS20C,QSSEXO,QSMEF,QSDIA,QS22M,QS22A,QS23,QS24,QS25N,QS25AG,QS25A,QS25G,QS25AA,QS25BB,QS26,QS27,QS28,QS29A,QS29B,QS100,QS101,QS102,QS103U,QS103C,QS104,QS105,QS106,QS107,QS108,QS109,QS110U,QS110C,QS111,QS112,QS113,QS202,QS203U,QS203C,QS204U,QS204C,QS205U,QS205C,QS206,QS207U,QS207C,QS208,QS209,QS210,QS211U,QS211C,QS212T,QS212A,QS212AV,QS212AB,QS212B,QS212BV,QS212BB,QS212C,QS212CV,QS212CB,QS212D,QS212DV,QS212DB,QS212E,QS212EV,QS212EB,QS212F,QS212FV,QS212FB,QS212G,QS212GV,QS212GB,QS212O,QS212XV,QS212XB,QS212Z,QS213U,QS213C,QS214U,QS214C,QS215U,QS215C,QS216U,QS216C,QS217U,QS217C,QS218U,QS218C,QS219U,QS219C,QS220U,QS220CV,QS220CC,QS200,QS201,QS302C,QS303,QS304,QS305U,QS305C,QS306,QS307,QS308,QS309,QS311,QS312U,QS312C,QS313,QS301,QS302U,QS403,QS404,QS406,QS407,QS409,QS410U,QS410C,QS411,QS412U,QS412C,QS413,QS413A,QS413B,QS413B_A,QS413C,QS413D,QS413E,QS413E_A,QS413F,QS415,QS416U,QS416C,QS401,QS402,QS500,QS501U,QS501C,QS503,QS505A,QS505B,QS505C,QS505D,QS506,QS603,QS604,QS606,QS607,QS608,QS609,QS610,QS611,QS601A,QS601B,QS700A,QS700B,QS700C,QS700D,QS700E,QS700F,QS700G,QS700H,QS700I,QS702,QS703,QS704T,QS704A,QS704B,QS704C,QS704D,QS704E,QS704F,QS704G,QS704H,QS704I,QS706,QS707,QS709,QS710,QS711,QS713,QS714,QS715,QS716,QS717,QS719,QS720,QS721,QS722,QS723,QS724,QS725,QS726,QS727,QS728,QS729,QS730,QFIN,QS8INICIO,QS900,QS901,QS902,QS903S,QS903D,QS905S,QS905D,QS906,QS25C1,QS25C2,QS25C3,QS25C4,QS25C5,QS25C6,QS907,QS908,QS506B,QS708_A,QS708_AA,QS708_AB,QS708_B,QS708_C,QS708_D,QS708_E,QS708_EA,QS708_F,QS708_G,QS708_H,QS708_I,QS708_J,QS708_X,QS708_Y,QS731_A,QS731_AA,QS731_AB,QS731_B,QS731_C,QS731_D,QS731_E,QS731_EA,QS731_F,QS731_G,QS731_H,QS731_I,QS731_J,QS731_X,QS731_Y,Peso15_amas
34531,2023,542903401,5429,34,1,2,9,2023,5,2,,2,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,
34532,2023,542904501,5429,45,1,2,9,2023,2,1,,1,2,2,2,22,6,1967,56,1,1,1,4,,1,1,1,B,,,,1,14,2,,,,,,2,,2,,,,,,,,,,,,,1,1,20,1,2,2,,,,,,,,,,,,,,,,,,,,,,,,,,,,,1,3,1,2,3,,,,3,,,,1,2,1,1.5,,2,,2,11,1,,,2,,,,,,,,1,1,2,,1,,1,2,2,1,2,5,2,1,8,,2,2,,,,1,2,3,1,1,2,,,1,1,1,2,1,1,,,,,,,,,,,0,0,0,0,0,0,0,0,1,2,1,,1,1,1,1,1,0,0,1,1,2,2,1,1,1,,,,,,,,,,,,,,,,,2,,,52.3,144.3,1,107,75,106,76,1,2,2,2,2,2,2,82.8,1,2,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,67122.4164722046
34533,2023,542904701,5429,47,1,1,9,2023,3,1,,1,1,1,2,16,10,1955,67,1,1,1,5,,1,1,1,A,,,,1,14,1,,,1,1,1,2,,2,,,,,,,,,,,,,1,1,18,2,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,1,1,1,2,3,,,,3,,,,1,1,1,1,,2,,6,14,2,,,2,,,,1,1,1,14,1,1,2,,2,,,,,,,,,,,,,,,,,,,,2,1,1,1,7,1,1,1,1,1,1,,,,,,,,,,,3,3,0,1,0,0,2,0,0,2,2,,,,,,,,,,,,2,2,,,,,,,,,,,,,,,,,,,2,,,67,158.2,1,126,78,130,81,1,2,2,2,2,2,2,99.2,1,2,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,61242.6731763664
34534,2023,542904901,5429,49,1,4,9,2023,1,5,,5,4,2,2,14,8,1968,55,1,1,1,5,,1,1,1,A,,,,2,,2,,,,,,2,,2,,,,,,,,,,,,,1,1,22,2,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,1,7,1,1,3,,,,3,,,,3,,,,,2,,,,2,,,1,,,,,,,,2,,2,,2,,2,,,2,,,,2,,,,2,,,,2,,,1,1,2,,,1,8,2,8,2,1,,,,,,,,,,,0,0,1,0,1,1,0,1,0,1,1,,0,1,2,1,1,0,0,0,1,3,2,1,1,1,,,,,,,,,,,,,,,,,2,,,68,151,1,96,60,94,59,1,2,2,2,2,2,2,106.2,1,2,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,
34535,2023,542905001,5429,50,1,2,9,2023,2,1,,1,2,2,2,23,8,1966,57,1,1,1,1,,1,1,1,B,,,,1,14,1,,,1,1,1,1,14,1,,,1,1,1,,,,,,,,1,1,35,1,2,2,,,,,,,,,,,,,,,,,,,,,,,,,,,,,1,7,1,2,3,,,,3,,,,1,2,1,1,,2,,0,14,2,,,2,,,,,,,,1,1,2,,2,,2,,,1,2,5,1,2,,,,2,,,,2,,,8,1,2,,,1,1,1,2,1,1,,,,,,,,,,,3,3,0,2,1,3,1,2,2,1,2,,,,,,,,,,,,2,1,1,1,,,,,,,,,,,,,,,,,2,,,58.3,152.9,1,115,71,126,76,1,2,2,2,2,2,2,92.6,1,1,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,67122.4164722046

In [ ]:
Modulo1640_CSALUD01_2023.QSMEF.value_counts()

## 2 = No
## 1 = Si. 

## regla. HHID + INDIVIDUI + QSMEF = 1.

QSMEF
2    17905
1    14226
      2405
Name: count, dtype: int64

In [ ]:
""" 
hijos <= 8 meses es prematuro. 
hijos <- 2.5K tambien premaaturo 
key = caseIF + orden de nacimiento
"""