In [1]:
import pandas as pd
pd.set_option('display.max_columns', None)
pd.set_option('display.max_rows', None) 
import numpy as np
#pd.set_option('display.max_info_columns', None)

In [2]:
# Function to get the name of a DataFrame
def get_variable_name(df):
    for name, value in globals().items():
        if value is df:
            return name


def count_repetitive_caseids(df):
    if 'CASEID' in df.columns:  # Check if 'CASEID' column exists
        duplicate_count = df['CASEID'].duplicated().sum()  # Count duplicates
        total_count = df['CASEID'].count()  # Count total rows
        unique_count = df['CASEID'].nunique()  # Count unique CASEID
        return duplicate_count, total_count, unique_count
    else:
        return None, None, None  # If 'CASEID' column is missing
    


def add_prefix_except_caseid(df, prefix):
    """
    Add a prefix to all columns in the dataframe except 'CASEID'.

    Parameters:
        df (pd.DataFrame): The input dataframe.
        prefix (str): The prefix to add.

    Returns:
        pd.DataFrame: A new dataframe with prefixed column names.
    """
    df = df.copy()
    new_columns = {
        col: f"{prefix}_{col}" if col != 'CASEID' else col
        for col in df.columns
    }
    return df.rename(columns=new_columns)

def get_dummy_variables(df):
    """
    Identify dummy (binary) variables in a DataFrame.
    A dummy variable is defined as having only 0, 1, or NaN values.
    Columns that are entirely NaN are excluded.

    Parameters:
        df (pd.DataFrame): Input DataFrame.

    Returns:
        List[str]: List of column names that are dummy variables.
    """
    dummy_cols = []
    for col in df.columns:
        # Skip if all values are NaN
        if df[col].isna().all():
            continue
        
        unique_vals = df[col].dropna().unique()
        if set(unique_vals).issubset({0, 1}):
            dummy_cols.append(col)
    return dummy_cols



def convert_objects_to_int64_safe(df: pd.DataFrame) -> pd.DataFrame:
    """
    Convert object columns in a DataFrame to Int64 if possible.
    If conversion is not possible (non-integer strings), keep the column as object.
    """
    df_converted = df.copy()

    for col in df_converted.select_dtypes(include=["object"]).columns:
        s = df_converted[col].astype(str).str.strip()   # remove extra spaces
        s = s.mask(s == "", np.nan)                     # empty string -> NaN (no downcasting warning)
        
        # Try converting
        try:
            converted = pd.to_numeric(s, errors="raise").astype("Int64")
            df_converted[col] = converted
        except Exception:
            df_converted[col] = df_converted[col]  # keep original if fails
    
    return df_converted

def drop_null_and_list(df, exclude_list):
    """
    Drop columns that are entirely NaN or present in the exclude_list.

    Parameters:
        df (pd.DataFrame): Input DataFrame.
        exclude_list (list): List of column names to exclude.

    Returns:
        pd.DataFrame: DataFrame with specified columns removed.
    """
    # Drop all-null columns
    df_filtered = df.dropna(axis=1, how="all")
    
    # Drop columns from exclude_list
    df_filtered = df_filtered.drop(columns=[col for col in exclude_list if col in df_filtered.columns], errors="ignore")
    
    return df_filtered

def aggregate_sum_by_caseid(df, caseid_col="CASEID"):
    """
    Aggregate a DataFrame at the CASEID level by summing numeric columns.

    Parameters:
        df (pd.DataFrame): Input DataFrame.
        caseid_col (str): Name of the column that identifies the case/group.

    Returns:
        pd.DataFrame: Aggregated DataFrame with one row per CASEID.
    """
    # Group by CASEID and sum only numeric columns
    aggregated_df = (
        df.groupby(caseid_col, as_index=False)
          .sum(numeric_only=True)
    )
    return aggregated_df


def aggregate_with_value_suffix(df, caseid_col="CASEID", exclude_cols=None):
    """
    Aggregate at CASEID level by creating dummy columns for each unique value in selected columns,
    and summing the counts. Excludes columns specified in exclude_cols.

    Parameters:
        df (pd.DataFrame): Input DataFrame
        caseid_col (str): Column name to group by
        exclude_cols (list): List of columns to exclude from processing

    Returns:
        pd.DataFrame: Aggregated DataFrame with CASEID and dummy count columns
    """
    if exclude_cols is None:
        exclude_cols = []

    # Columns to process: all except caseid_col and excluded ones
    cols_to_process = [c for c in df.columns if c not in [caseid_col] + exclude_cols]

    # Create dummy variables for the selected columns
    df_dummies = pd.get_dummies(df[cols_to_process].astype(str), prefix=cols_to_process)

    # Combine CASEID with the dummies
    df_combined = pd.concat([df[[caseid_col]], df_dummies], axis=1)

    # Aggregate by CASEID summing the dummy counts
    agg_df = df_combined.groupby(caseid_col, as_index=False).sum()

    return agg_df


def aggregate_by_caseid_mean(df, caseid_col="CASEID"):
    """
    Aggregate a DataFrame by caseid_col and compute the mean of all other columns.
    
    Parameters:
    - df (pd.DataFrame): Input DataFrame
    - caseid_col (str): Column to group by (default = "CASEID")
    
    Returns:
    - pd.DataFrame: Aggregated DataFrame with mean values
    """
    # Group by CASEID and calculate mean for numeric columns
    df_agg = df.groupby(caseid_col, as_index=False).mean(numeric_only=True)
    
    return df_agg


def analyze_matches(left_df, right_df, label):
    original_rows = len(left_df)
    right_rows = len(right_df)
    
    merged = left_df.merge(right_df, on='CASEID', how='left', indicator=True)
    merged_rows = len(merged)

    match_count = (merged['_merge'] == 'both').sum()
    match_pct = match_count / original_rows * 100

    print(f"🔎 {label}")
    print(f" - Rows in target_final: {original_rows}")
    print(f" - Rows in right dataframe ({label}): {right_rows}")
    print(f" - Rows after merge: {merged_rows}")
    print(f" ✅ Matches on CASEID: {match_count} ({match_pct:.2f}%)\n")


def analyze_matches_explicit_keys(target_df, right_df, label, right_key):
    # Drop duplicates in right dataframe based on CASEID and the specific key
    right_df_clean = right_df.drop_duplicates(subset=['CASEID', right_key])

    # Perform merge using explicit keys
    merged = target_df.merge(
        right_df_clean,
        left_on=['CASEID', 'BIDX'],
        right_on=['CASEID', right_key],
        how='left',
        indicator=True
    )

    # Count and summarize
    original_rows = len(target_df)
    right_rows = len(right_df)
    merged_rows = len(merged)
    match_count = (merged['_merge'] == 'both').sum()
    match_pct = match_count / original_rows * 100

    # Print results
    print(f"🔎 {label}")
    print(f" - Rows in target_final: {original_rows}")
    print(f" - Rows in right dataframe: {right_rows}")
    print(f" - Matches on CASEID + {right_key}: {match_count} ({match_pct:.2f}%)\n")

# 01 Target

In [3]:
Modulo1632_REC21_2023 = pd.read_csv("C:/Users/linoc/OneDrive/Encoder/03_partos/01_raws/2024/968-Modulo1632/968-Modulo1632/REC21_2024.csv", low_memory=False)
Modulo1632_REC21_2023.info(verbose = True, show_counts = True)

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 60693 entries, 0 to 60692
Data columns (total 34 columns):
 #   Column   Non-Null Count  Dtype
---  ------   --------------  -----
 0   ID1      60693 non-null  int64
 1   CASEID   60693 non-null  object
 2   BIDX     60693 non-null  int64
 3   BORD     60693 non-null  int64
 4   B0       60693 non-null  int64
 5   B1       60693 non-null  int64
 6   B2       60693 non-null  int64
 7   B3       60693 non-null  object
 8   B4       60693 non-null  int64
 9   B5       60693 non-null  int64
 10  B6       60693 non-null  object
 11  B7       60693 non-null  object
 12  B8       60693 non-null  object
 13  B9       60693 non-null  object
 14  B10      60693 non-null  int64
 15  B11      60693 non-null  object
 16  B12      60693 non-null  object
 17  B13      60693 non-null  object
 18  B15      60693 non-null  object
 19  B16      60693 non-null  object
 20  BD       60693 non-null  int64
 21  BDD      60693 non-null  int64
 22  BMM      60693 non-null  int64
 23  BAA      60693 non-null  int64
 24  BCMC     60693 non-null  int64
 25  BEDAD    60693 non-null  object
 26  QD333_1  60693 non-null  object
 27  QD333_2  60693 non-null  object
 28  QD333_3  60693 non-null  object
 29  QD333_4  60693 non-null  object
 30  QD333_5  60693 non-null  object
 31  QD333_6  60693 non-null  object
 32  Q220A    60693 non-null  object
 33  QULT5    60693 non-null  int64
dtypes: int64(15), object(19)
memory usage: 15.7+ MB

In [4]:
target = Modulo1632_REC21_2023[['CASEID', 'BIDX','Q220A']]
target.drop_duplicates().shape

(60693, 3)

In [5]:
# # de meses de nascimento
target.Q220A.value_counts()

Q220A
     39575
9    16932
8     3467
7      580
6      122
5       17
Name: count, dtype: int64

In [6]:
target=target[target['Q220A']!= " " ]
target.Q220A.value_counts()

Q220A
9    16932
8     3467
7      580
6      122
5       17
Name: count, dtype: int64

In [7]:
target.BIDX.value_counts()

BIDX
1    18335
2     2637
3      143
4        3
Name: count, dtype: int64

In [8]:

target.shape, target.CASEID.nunique()

# come:numero de CASEID y numero de CASEID unicos. O sea, un CASEID puede tener mais de un hijo en la encuenta.

((21118, 3), 18335)

In [16]:
target['Q220A'] = pd.to_numeric(target['Q220A'],)

target.info()

<class 'pandas.core.frame.DataFrame'>
Index: 21118 entries, 0 to 60690
Data columns (total 3 columns):
 #   Column  Non-Null Count  Dtype
---  ------  --------------  -----
 0   CASEID  21118 non-null  object
 1   BIDX    21118 non-null  int64
 2   Q220A   21118 non-null  int64
dtypes: int64(2), object(1)
memory usage: 659.9+ KB

In [17]:
target.shape,  target.CASEID.nunique()

((21118, 3), 18335)

In [18]:
target['premature'] =  np.where(target['Q220A'] <= 8, 1, 0)
target_final = target.groupby('CASEID', as_index=False)['premature'].sum()
target_final['premature_flag'] = np.where(target_final['premature'] >= 1, 1, 0)
target_final.premature_flag.value_counts()

premature_flag
0    14517
1     3818
Name: count, dtype: int64

In [19]:
3818/(3818+ 14517)

0.20823561494409598

In [20]:
target_final.info(verbose = True)

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 18335 entries, 0 to 18334
Data columns (total 3 columns):
 #   Column          Non-Null Count  Dtype
---  ------          --------------  -----
 0   CASEID          18335 non-null  object
 1   premature       18335 non-null  int32
 2   premature_flag  18335 non-null  int32
dtypes: int32(2), object(1)
memory usage: 286.6+ KB

In [21]:
target_final.premature_flag.value_counts(1)
# come: 20% tuvieron al menos 1 parto prematuro.

premature_flag
0    0.791764
1    0.208236
Name: proportion, dtype: float64

In [60]:
# File name only
output_file = "target_final.csv"

# Go one level up from the current working directory
base_dir = os.path.dirname(os.getcwd())   # gives "c:\\Users\\linoc\\OneDrive\\Encoder\\03_partos"
output_dir = os.path.join(base_dir, "03_bases_intermediarios")

#Full path
output_path = os.path.join(output_dir, output_file)

# Save DataFrame
target_final.to_csv(output_path, index=False, encoding="utf-8-sig")

# 2 join other tables

In [26]:
Modulo1631_REC91_2024 = pd.read_csv("C:/Users/linoc/OneDrive/Encoder/03_partos/01_raws/2024/968-Modulo1631/968-Modulo1631/REC91_2024.csv", low_memory=False)
Modulo1632_RE223132_2024 = pd.read_csv("C:/Users/linoc/OneDrive/Encoder/03_partos/01_raws/2024/968-Modulo1632/968-Modulo1632/RE223132_2024.csv", low_memory=False)
Modulo1633_REC41_2024 = pd.read_csv("C:/Users/linoc/OneDrive/Encoder/03_partos/01_raws/2024/968-Modulo1633/968-Modulo1633/REC41_2024.csv", low_memory=False)
Modulo1633_REC94_2024 = pd.read_csv("C:/Users/linoc/OneDrive/Encoder/03_partos/01_raws/2024/968-Modulo1633/968-Modulo1633/REC94_2024.csv", low_memory=False)
Modulo1635_RE516171_2024 = pd.read_csv("C:/Users/linoc/OneDrive/Encoder/03_partos/01_raws/2024/968-Modulo1635/968-Modulo1635/RE516171_2024.csv", low_memory=False)
Modulo1640_CSALUD01_2024 = pd.read_csv("C:/Users/linoc/OneDrive/Encoder/03_partos/01_raws/2024/968-Modulo1640/968-Modulo1640/CSALUD01_2024.csv", low_memory=False)

print(f"size file: {get_variable_name(Modulo1631_REC91_2024)}: {Modulo1631_REC91_2024.shape}")
print(f"size file: {get_variable_name(Modulo1632_RE223132_2024)}: {Modulo1632_RE223132_2024.shape}")
print(f"size file: {get_variable_name(Modulo1633_REC41_2024)}: {Modulo1633_REC41_2024.shape}")
print(f"size file: {get_variable_name(Modulo1633_REC94_2024)}: {Modulo1633_REC94_2024.shape}")
print(f"size file: {get_variable_name(Modulo1635_RE516171_2024)}: {Modulo1635_RE516171_2024.shape}")
print(f"size file: {get_variable_name(Modulo1640_CSALUD01_2024)}: {Modulo1640_CSALUD01_2024.shape}")

size file: Modulo1631_REC91_2024: (37117, 343)
size file: Modulo1632_RE223132_2024: (34252, 149)
size file: Modulo1633_REC41_2024: (19751, 147)
size file: Modulo1633_REC94_2024: (19751, 61)
size file: Modulo1635_RE516171_2024: (34252, 84)
size file: Modulo1640_CSALUD01_2024: (34018, 258)

## 2.1 match with CASEID level

In [27]:
Modulo1631_REC91_2024 = Modulo1631_REC91_2024.drop_duplicates()
Modulo1632_RE223132_2024 = Modulo1632_RE223132_2024.drop_duplicates()
Modulo1635_RE516171_2024 = Modulo1635_RE516171_2024.drop_duplicates()

In [28]:
Modulo1631_REC91_2024.shape,Modulo1632_RE223132_2024.shape, Modulo1635_RE516171_2024.shape

((37117, 343), (34252, 149), (34252, 84))

In [29]:
analyze_matches(target_final, Modulo1631_REC91_2024, 'Modulo1631_REC91_2024')
analyze_matches(target_final, Modulo1632_RE223132_2024, 'Modulo1632_RE223132_2024')
analyze_matches(target_final, Modulo1635_RE516171_2024, 'Modulo1635_RE516171_2024')

🔎 Modulo1631_REC91_2024
 - Rows in target_final: 18335
 - Rows in right dataframe (Modulo1631_REC91_2024): 37117
 - Rows after merge: 18335
 ✅ Matches on CASEID: 18335 (100.00%)

🔎 Modulo1632_RE223132_2024
 - Rows in target_final: 18335
 - Rows in right dataframe (Modulo1632_RE223132_2024): 34252
 - Rows after merge: 18335
 ✅ Matches on CASEID: 18335 (100.00%)

🔎 Modulo1635_RE516171_2024
 - Rows in target_final: 18335
 - Rows in right dataframe (Modulo1635_RE516171_2024): 34252
 - Rows after merge: 18335
 ✅ Matches on CASEID: 18335 (100.00%)

In [30]:
print(Modulo1631_REC91_2024.shape[0]), print(Modulo1631_REC91_2024.CASEID.nunique())
print(Modulo1632_RE223132_2024.shape[0]), print(Modulo1632_RE223132_2024.CASEID.nunique())
print(Modulo1635_RE516171_2024.shape[0]), print(Modulo1635_RE516171_2024.CASEID.nunique())

37117
37117
34252
34252
34252
34252

(None, None)

In [31]:
Modulo1631_REC91_2024 = add_prefix_except_caseid(Modulo1631_REC91_2024, 'REC91')
Modulo1632_RE223132_2024 = add_prefix_except_caseid(Modulo1631_REC91_2024, 'RE223132')
Modulo1635_RE516171_2024 = add_prefix_except_caseid(Modulo1635_RE516171_2024, 'RE516171')

# Perform left merges one by one
target_merged = target_final.merge(Modulo1631_REC91_2024, on='CASEID', how='left') \
                            .merge(Modulo1632_RE223132_2024, on='CASEID', how='left') \
                            .merge(Modulo1635_RE516171_2024, on='CASEID', how='left')
target_merged.info(verbose  = True, show_counts = True)

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 18335 entries, 0 to 18334
Data columns (total 770 columns):
 #    Column                   Non-Null Count  Dtype
---   ------                   --------------  -----
 0    CASEID                   18335 non-null  object
 1    premature                18335 non-null  int32
 2    premature_flag           18335 non-null  int32
 3    REC91_ID1                18335 non-null  int64
 4    REC91_SVER               18335 non-null  int64
 5    REC91_SREGION            18335 non-null  int64
 6    REC91_SSEMES             18335 non-null  int64
 7    REC91_SPROVIN            18335 non-null  int64
 8    REC91_SDISTRI            18335 non-null  int64
 9    REC91_S108N              18335 non-null  object
 10   REC91_S108Y              18335 non-null  object
 11   REC91_S108G              18335 non-null  object
 12   REC91_S111               18335 non-null  object
 13   REC91_S112               18335 non-null  object
 14   REC91_S119               18335 non-null  object
 15   REC91_S119NA             18335 non-null  object
 16   REC91_S119NB             18335 non-null  object
 17   REC91_S119D              18335 non-null  object
 18   REC91_S229A              18335 non-null  object
 19   REC91_S229B              18335 non-null  object
 20   REC91_S229C              18335 non-null  object
 21   REC91_S229D              18335 non-null  object
 22   REC91_S229E              18335 non-null  object
 23   REC91_S229F              18335 non-null  object
 24   REC91_S229G              18335 non-null  object
 25   REC91_S229H              18335 non-null  object
 26   REC91_S229I              18335 non-null  object
 27   REC91_S229J              18335 non-null  object
 28   REC91_S229K              18335 non-null  object
 29   REC91_S229L              18335 non-null  object
 30   REC91_S229X              18335 non-null  object
 31   REC91_S229Y              18335 non-null  object
 32   REC91_S229A1             18335 non-null  object
 33   REC91_S229B1             18335 non-null  object
 34   REC91_S229CDAY           18335 non-null  object
 35   REC91_S229CM             18335 non-null  object
 36   REC91_S229CY             18335 non-null  object
 37   REC91_S229DA             18335 non-null  object
 38   REC91_S229DB             18335 non-null  object
 39   REC91_S229DC             18335 non-null  object
 40   REC91_S229DD             18335 non-null  object
 41   REC91_S229DE             18335 non-null  object
 42   REC91_S229DF             18335 non-null  object
 43   REC91_S229DX             18335 non-null  object
 44   REC91_S239A              18335 non-null  object
 45   REC91_S239B              18335 non-null  object
 46   REC91_S239C              18335 non-null  object
 47   REC91_S239D              18335 non-null  object
 48   REC91_S239E              18335 non-null  object
 49   REC91_S239F              18335 non-null  object
 50   REC91_S239X              18335 non-null  object
 51   REC91_S314               18335 non-null  object
 52   REC91_S315B              18335 non-null  object
 53   REC91_S317AC             18335 non-null  object
 54   REC91_S317AD             18335 non-null  object
 55   REC91_S317C              18335 non-null  object
 56   REC91_S321A              18335 non-null  object
 57   REC91_S325A              18335 non-null  object
 58   REC91_S325B              18335 non-null  object
 59   REC91_S325CA             18335 non-null  object
 60   REC91_S325CB             18335 non-null  object
 61   REC91_S325CX             18335 non-null  object
 62   REC91_S325D              18335 non-null  object
 63   REC91_S325E              18335 non-null  object
 64   REC91_S325GA             18335 non-null  object
 65   REC91_S325GB             18335 non-null  object
 66   REC91_S325GC             18335 non-null  object
 67   REC91_S325GD             18335 non-null  object
 68   REC91_S325GE             18335 non-null  object
 69   REC91_S325GF             18335 non-null  object
 70   REC91_S325GG             18335 non-null  object
 71   REC91_S325GH             18335 non-null  object
 72   REC91_S325GI             18335 non-null  object
 73   REC91_S325GJ             18335 non-null  object
 74   REC91_S325GK             18335 non-null  object
 75   REC91_S327B              18335 non-null  object
 76   REC91_S327C              18335 non-null  object
 77   REC91_S481AA             18335 non-null  object
 78   REC91_S481AB             18335 non-null  object
 79   REC91_S481AC             18335 non-null  object
 80   REC91_S481AD             18335 non-null  object
 81   REC91_S481AE             18335 non-null  object
 82   REC91_S481AF             18335 non-null  object
 83   REC91_S481AG             18335 non-null  object
 84   REC91_S481AX             18335 non-null  object
 85   REC91_S481AZ             18335 non-null  object
 86   REC91_S484               18335 non-null  object
 87   REC91_S484D              18335 non-null  object
 88   REC91_S484M              18335 non-null  object
 89   REC91_S484Y              18335 non-null  object
 90   REC91_S485               18335 non-null  object
 91   REC91_S485A              18335 non-null  object
 92   REC91_S486               18335 non-null  object
 93   REC91_S486A              18335 non-null  object
 94   REC91_S486B              18335 non-null  object
 95   REC91_S489C              18335 non-null  object
 96   REC91_S489D              18335 non-null  object
 97   REC91_S490               18335 non-null  object
 98   REC91_S490AA             18335 non-null  object
 99   REC91_S490AB             18335 non-null  object
 100  REC91_S490AC             18335 non-null  object
 101  REC91_S490AD             18335 non-null  object
 102  REC91_S490AE             18335 non-null  object
 103  REC91_S490AF             18335 non-null  object
 104  REC91_S490AG             18335 non-null  object
 105  REC91_S490AX             18335 non-null  object
 106  REC91_S490BA             18335 non-null  object
 107  REC91_S490BB             18335 non-null  object
 108  REC91_S490BC             18335 non-null  object
 109  REC91_S490BD             18335 non-null  object
 110  REC91_S490BX             18335 non-null  object
 111  REC91_S492A              18335 non-null  object
 112  REC91_S492B              18335 non-null  object
 113  REC91_S492C              18335 non-null  object
 114  REC91_S492D              18335 non-null  object
 115  REC91_S492E              18335 non-null  object
 116  REC91_S492F              18335 non-null  object
 117  REC91_S492G              18335 non-null  object
 118  REC91_S493A              18335 non-null  object
 119  REC91_S493B              18335 non-null  object
 120  REC91_S493C              18335 non-null  object
 121  REC91_S493D              18335 non-null  object
 122  REC91_S493E              18335 non-null  object
 123  REC91_S493F              18335 non-null  object
 124  REC91_S493G              18335 non-null  object
 125  REC91_S493H              18335 non-null  object
 126  REC91_S493I              18335 non-null  object
 127  REC91_S493J              18335 non-null  object
 128  REC91_S493K              18335 non-null  object
 129  REC91_S493L              18335 non-null  object
 130  REC91_S493M              18335 non-null  object
 131  REC91_S493N              18335 non-null  object
 132  REC91_S493O              18335 non-null  object
 133  REC91_S493P              18335 non-null  object
 134  REC91_S494               18335 non-null  object
 135  REC91_S494A              18335 non-null  object
 136  REC91_S494B              18335 non-null  object
 137  REC91_S495A              18335 non-null  object
 138  REC91_S496               18335 non-null  object
 139  REC91_S500A              18335 non-null  object
 140  REC91_S500B              18335 non-null  object
 141  REC91_S500C              18335 non-null  object
 142  REC91_S500D              18335 non-null  object
 143  REC91_S508A              18335 non-null  object
 144  REC91_S512C              18335 non-null  object
 145  REC91_S616               18335 non-null  object
 146  REC91_S618A              18335 non-null  object
 147  REC91_S618B              18335 non-null  object
 148  REC91_S618C              18335 non-null  object
 149  REC91_S618D              18335 non-null  object
 150  REC91_S618E              18335 non-null  object
 151  REC91_S618F              18335 non-null  object
 152  REC91_S618G              18335 non-null  object
 153  REC91_S618H              18335 non-null  object
 154  REC91_S618I              18335 non-null  object
 155  REC91_S618J              18335 non-null  object
 156  REC91_S618K              18335 non-null  object
 157  REC91_S618L              18335 non-null  object
 158  REC91_S618M              18335 non-null  object
 159  REC91_S618X              18335 non-null  object
 160  REC91_S621               18335 non-null  object
 161  REC91_S621A              18335 non-null  object
 162  REC91_S704N              18335 non-null  object
 163  REC91_S704Y              18335 non-null  object
 164  REC91_S704G              18335 non-null  object
 165  REC91_S718               18335 non-null  object
 166  REC91_S720A              18335 non-null  object
 167  REC91_S802               18335 non-null  object
 168  REC91_S802D              18335 non-null  object
 169  REC91_S802E              18335 non-null  object
 170  REC91_S802F              18335 non-null  object
 171  REC91_S802H              18335 non-null  object
 172  REC91_S802I              18335 non-null  object
 173  REC91_S803AF             18335 non-null  object
 174  REC91_S803AG             18335 non-null  object
 175  REC91_S803AM             18335 non-null  object
 176  REC91_S804A              18335 non-null  object
 177  REC91_S804C              18335 non-null  object
 178  REC91_S806AX             18335 non-null  object
 179  REC91_S806AZ             18335 non-null  object
 180  REC91_S807               18335 non-null  object
 181  REC91_S809               18335 non-null  object
 182  REC91_S810               18335 non-null  object
 183  REC91_S811               18335 non-null  object
 184  REC91_S815AA             18335 non-null  object
 185  REC91_S815AB             18335 non-null  object
 186  REC91_S815AC             18335 non-null  object
 187  REC91_S815AD             18335 non-null  object
 188  REC91_S815AE             18335 non-null  object
 189  REC91_S815AX             18335 non-null  object
 190  REC91_S815AZ             18335 non-null  object
 191  REC91_S816A              18335 non-null  object
 192  REC91_S816B              18335 non-null  object
 193  REC91_S816C              18335 non-null  object
 194  REC91_S816D              18335 non-null  object
 195  REC91_S816E              18335 non-null  object
 196  REC91_S816F              18335 non-null  object
 197  REC91_S816G              18335 non-null  object
 198  REC91_S816H              18335 non-null  object
 199  REC91_S816I              18335 non-null  object
 200  REC91_S816J              18335 non-null  object
 201  REC91_S816K              18335 non-null  object
 202  REC91_S816L              18335 non-null  object
 203  REC91_S816M              18335 non-null  object
 204  REC91_S816W              18335 non-null  object
 205  REC91_S816Z              18335 non-null  object
 206  REC91_S816AA             18335 non-null  object
 207  REC91_S816AB             18335 non-null  object
 208  REC91_S816AC             18335 non-null  object
 209  REC91_S816AD             18335 non-null  object
 210  REC91_S816AE             18335 non-null  object
 211  REC91_S816AF             18335 non-null  object
 212  REC91_S816AG             18335 non-null  object
 213  REC91_S816AH             18335 non-null  object
 214  REC91_S816AI             18335 non-null  object
 215  REC91_S816AJ             18335 non-null  object
 216  REC91_S816AK             18335 non-null  object
 217  REC91_S816AL             18335 non-null  object
 218  REC91_S816AW             18335 non-null  object
 219  REC91_S816AZ             18335 non-null  object
 220  REC91_S817               18335 non-null  object
 221  REC91_S817GF             18335 non-null  object
 222  REC91_S817GG             18335 non-null  object
 223  REC91_S817GM             18335 non-null  object
 224  REC91_S818               18335 non-null  object
 225  REC91_S1002A             18335 non-null  object
 226  REC91_S1002B             18335 non-null  object
 227  REC91_S1002C             18335 non-null  object
 228  REC91_S1002D             18335 non-null  object
 229  REC91_S1002E             18335 non-null  object
 230  REC91_S1008AN            18335 non-null  object
 231  REC91_S1008BN            18335 non-null  object
 232  REC91_S1008CN            18335 non-null  object
 233  REC91_S1008DN            18335 non-null  object
 234  REC91_S1012B             18335 non-null  object
 235  REC91_S1012BN            18335 non-null  object
 236  REC91_S1017              18335 non-null  object
 237  REC91_S1023AA            18335 non-null  object
 238  REC91_S1023AB            18335 non-null  object
 239  REC91_S1023AC            18335 non-null  object
 240  REC91_S1023AD            18335 non-null  object
 241  REC91_S1023AE            18335 non-null  object
 242  REC91_S1023AF            18335 non-null  object
 243  REC91_S1023AG            18335 non-null  object
 244  REC91_S1023AH            18335 non-null  object
 245  REC91_S1023AX            18335 non-null  object
 246  REC91_S1023AZ            18335 non-null  object
 247  REC91_S1026              18335 non-null  object
 248  REC91_S1030AA            18335 non-null  object
 249  REC91_S1030AB            18335 non-null  object
 250  REC91_S1030AC            18335 non-null  object
 251  REC91_S1030AD            18335 non-null  object
 252  REC91_S1030AE            18335 non-null  object
 253  REC91_S1030AF            18335 non-null  object
 254  REC91_S1030AG            18335 non-null  object
 255  REC91_S1030AH            18335 non-null  object
 256  REC91_S1030AI            18335 non-null  object
 257  REC91_S1030AJ            18335 non-null  object
 258  REC91_S1030AK            18335 non-null  object
 259  REC91_S1030AL            18335 non-null  object
 260  REC91_S1030AM            18335 non-null  object
 261  REC91_S1030AX            18335 non-null  object
 262  REC91_S1030BA            18335 non-null  object
 263  REC91_S1030BB            18335 non-null  object
 264  REC91_S1030BC            18335 non-null  object
 265  REC91_S1030BD            18335 non-null  object
 266  REC91_S1030BE            18335 non-null  object
 267  REC91_S1030BF            18335 non-null  object
 268  REC91_S1030BG            18335 non-null  object
 269  REC91_S1030BH            18335 non-null  object
 270  REC91_S1030BI            18335 non-null  object
 271  REC91_S1030BJ            18335 non-null  object
 272  REC91_S1030BK            18335 non-null  object
 273  REC91_S1030BL            18335 non-null  object
 274  REC91_S1030BM            18335 non-null  object
 275  REC91_S1030BX            18335 non-null  object
 276  REC91_S1030CA            18335 non-null  object
 277  REC91_S1030CB            18335 non-null  object
 278  REC91_S1030CC            18335 non-null  object
 279  REC91_S1030CD            18335 non-null  object
 280  REC91_S1030CE            18335 non-null  object
 281  REC91_S1030CF            18335 non-null  object
 282  REC91_S1030CG            18335 non-null  object
 283  REC91_S1030CH            18335 non-null  object
 284  REC91_S1030CI            18335 non-null  object
 285  REC91_S1030CJ            18335 non-null  object
 286  REC91_S1030CK            18335 non-null  object
 287  REC91_S1030CL            18335 non-null  object
 288  REC91_S1030CM            18335 non-null  object
 289  REC91_S1030CX            18335 non-null  object
 290  REC91_S1031              18335 non-null  object
 291  REC91_S1032A             18335 non-null  object
 292  REC91_S1032B             18335 non-null  object
 293  REC91_S1032C             18335 non-null  object
 294  REC91_S1032D             18335 non-null  object
 295  REC91_S1032E             18335 non-null  object
 296  REC91_S1032F             18335 non-null  object
 297  REC91_S1032G             18335 non-null  object
 298  REC91_S1032H             18335 non-null  object
 299  REC91_S1032I             18335 non-null  object
 300  REC91_S1032J             18335 non-null  object
 301  REC91_S1032K             18335 non-null  object
 302  REC91_S1032L             18335 non-null  object
 303  REC91_S1032M             18335 non-null  object
 304  REC91_S1032N             18335 non-null  object
 305  REC91_S1032X             18335 non-null  object
 306  REC91_S1032Y             18335 non-null  object
 307  REC91_S1033              18335 non-null  object
 308  REC91_S1034A             18335 non-null  object
 309  REC91_S1034B             18335 non-null  object
 310  REC91_QI479E_A           18335 non-null  object
 311  REC91_QI479E_B           18335 non-null  object
 312  REC91_QI479E_C           18335 non-null  object
 313  REC91_QI479E_D           18335 non-null  object
 314  REC91_QI479E_E           18335 non-null  object
 315  REC91_QI479E_F           18335 non-null  object
 316  REC91_QI479E_G           18335 non-null  object
 317  REC91_QI479E_H           18335 non-null  object
 318  REC91_QI479E_I           18335 non-null  object
 319  REC91_QI479E_J           18335 non-null  object
 320  REC91_QI479E_X           18335 non-null  object
 321  REC91_QI479E_Y           18335 non-null  object
 322  REC91_QI479F_A           18335 non-null  object
 323  REC91_QI479F_B           18335 non-null  object
 324  REC91_QI479F_C           18335 non-null  object
 325  REC91_QI479F_D           18335 non-null  object
 326  REC91_QI479F_E           18335 non-null  object
 327  REC91_QI479F_F           18335 non-null  object
 328  REC91_QI479F_G           18335 non-null  object
 329  REC91_QI479F_H           18335 non-null  object
 330  REC91_QI479F_I           18335 non-null  object
 331  REC91_QI479F_J           18335 non-null  object
 332  REC91_QI479F_K           18335 non-null  object
 333  REC91_QI479F_L           18335 non-null  object
 334  REC91_QI479F_M           18335 non-null  object
 335  REC91_QI479F_X           18335 non-null  object
 336  REC91_QI479F_Y           18335 non-null  object
 337  REC91_Q479A              18335 non-null  object
 338  REC91_Q479B              18335 non-null  object
 339  REC91_Q479C              18335 non-null  object
 340  REC91_Q479D              18335 non-null  object
 341  REC91_S1028A             18335 non-null  object
 342  REC91_S1028B             18335 non-null  object
 343  REC91_S1028X             18335 non-null  object
 344  REC91_S1028Y             18335 non-null  object
 345  RE223132_REC91_ID1       18335 non-null  int64
 346  RE223132_REC91_SVER      18335 non-null  int64
 347  RE223132_REC91_SREGION   18335 non-null  int64
 348  RE223132_REC91_SSEMES    18335 non-null  int64
 349  RE223132_REC91_SPROVIN   18335 non-null  int64
 350  RE223132_REC91_SDISTRI   18335 non-null  int64
 351  RE223132_REC91_S108N     18335 non-null  object
 352  RE223132_REC91_S108Y     18335 non-null  object
 353  RE223132_REC91_S108G     18335 non-null  object
 354  RE223132_REC91_S111      18335 non-null  object
 355  RE223132_REC91_S112      18335 non-null  object
 356  RE223132_REC91_S119      18335 non-null  object
 357  RE223132_REC91_S119NA    18335 non-null  object
 358  RE223132_REC91_S119NB    18335 non-null  object
 359  RE223132_REC91_S119D     18335 non-null  object
 360  RE223132_REC91_S229A     18335 non-null  object
 361  RE223132_REC91_S229B     18335 non-null  object
 362  RE223132_REC91_S229C     18335 non-null  object
 363  RE223132_REC91_S229D     18335 non-null  object
 364  RE223132_REC91_S229E     18335 non-null  object
 365  RE223132_REC91_S229F     18335 non-null  object

## 2.2 match with CASEID and BIRD

In [37]:
target = target.drop_duplicates()
target.shape

(21118, 4)

In [38]:
Modulo1633_REC41_2024.shape, Modulo1633_REC94_2024.shape

((19751, 147), (19751, 61))

In [39]:
#Modulo1632_REC21_2024 = Modulo1632_REC21_2024.drop_duplicates()
Modulo1633_REC41_2024 = Modulo1633_REC41_2024.drop_duplicates()
Modulo1633_REC94_2024  = Modulo1633_REC94_2024.drop_duplicates()

In [40]:
Modulo1633_REC41_2024.shape, Modulo1633_REC94_2024.shape

((19751, 147), (19751, 61))

In [41]:
#analyze_matches_explicit_keys(target, Modulo1632_REC21_2024, 'Modulo1632_REC21_2024', 'BIDX')
analyze_matches_explicit_keys(target, Modulo1633_REC41_2024, 'Modulo1633_REC41_2024', 'MIDX')
analyze_matches_explicit_keys(target, Modulo1633_REC94_2024, 'Modulo1633_REC94_2024', 'IDX94')

🔎 Modulo1633_REC41_2024
 - Rows in target_final: 21118
 - Rows in right dataframe: 19751
 - Matches on CASEID + MIDX: 19751 (93.53%)

🔎 Modulo1633_REC94_2024
 - Rows in target_final: 21118
 - Rows in right dataframe: 19751
 - Matches on CASEID + IDX94: 19751 (93.53%)

### 2.2.1 Modulo1633_REC41_2024

In [42]:
Modulo1633_REC41_2024_M = convert_objects_to_int64_safe(Modulo1633_REC41_2024)
Modulo1633_REC41_2024_M.info(verbose = True, show_counts = True)

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 19751 entries, 0 to 19750
Data columns (total 147 columns):
 #    Column  Non-Null Count  Dtype
---   ------  --------------  -----
 0    ID1     19751 non-null  int64
 1    CASEID  19751 non-null  object
 2    MIDX    19751 non-null  int64
 3    M1      17608 non-null  Int64
 4    M1A     8385 non-null   Int64
 5    M1B     6079 non-null   Int64
 6    M1C     6079 non-null   Int64
 7    M1D     534 non-null    Int64
 8    M1E     6079 non-null   Int64
 9    M2A     17608 non-null  Int64
 10   M2B     17608 non-null  Int64
 11   M2C     17608 non-null  Int64
 12   M2D     17608 non-null  Int64
 13   M2E     17608 non-null  Int64
 14   M2F     0 non-null      Int64
 15   M2G     17608 non-null  Int64
 16   M2H     0 non-null      Int64
 17   M2I     0 non-null      Int64
 18   M2J     0 non-null      Int64
 19   M2K     17608 non-null  Int64
 20   M2L     0 non-null      Int64
 21   M2M     0 non-null      Int64
 22   M2N     17608 non-null  Int64
 23   M3A     19751 non-null  int64
 24   M3B     19751 non-null  int64
 25   M3C     19751 non-null  int64
 26   M3D     19751 non-null  int64
 27   M3E     19751 non-null  int64
 28   M3F     0 non-null      Int64
 29   M3G     19751 non-null  int64
 30   M3H     19751 non-null  int64
 31   M3I     0 non-null      Int64
 32   M3J     0 non-null      Int64
 33   M3K     19751 non-null  int64
 34   M3L     0 non-null      Int64
 35   M3M     0 non-null      Int64
 36   M3N     19751 non-null  int64
 37   M4      19751 non-null  int64
 38   M5      19751 non-null  int64
 39   M6      19751 non-null  int64
 40   M7      19751 non-null  int64
 41   M8      19751 non-null  int64
 42   M9      19751 non-null  int64
 43   M10     19751 non-null  int64
 44   M11     6006 non-null   Int64
 45   M13     17426 non-null  Int64
 46   M14     17608 non-null  Int64
 47   M15     19751 non-null  int64
 48   M17     19751 non-null  int64
 49   M18     19751 non-null  int64
 50   M19     19751 non-null  int64
 51   M19A    19543 non-null  Int64
 52   M27     19751 non-null  int64
 53   M28     19751 non-null  int64
 54   M29     19751 non-null  int64
 55   M34     19561 non-null  Int64
 56   M35     7589 non-null   Int64
 57   M36     7589 non-null   Int64
 58   M38     19582 non-null  Int64
 59   M39     19582 non-null  Int64
 60   M42A    17426 non-null  Int64
 61   M42B    0 non-null      Int64
 62   M42C    17426 non-null  Int64
 63   M42D    17426 non-null  Int64
 64   M42E    17426 non-null  Int64
 65   M43     17426 non-null  Int64
 66   M44     16736 non-null  Int64
 67   M45     17608 non-null  Int64
 68   M46     16727 non-null  Int64
 69   M47     17608 non-null  Int64
 70   M48     17608 non-null  Int64
 71   M49A    0 non-null      Int64
 72   M49B    0 non-null      Int64
 73   M49C    0 non-null      Int64
 74   M49D    0 non-null      Int64
 75   M49E    0 non-null      Int64
 76   M49F    0 non-null      Int64
 77   M49G    0 non-null      Int64
 78   M49X    0 non-null      Int64
 79   M49Z    0 non-null      Int64
 80   M51A    0 non-null      Int64
 81   M54     17608 non-null  Int64
 82   M55A    19751 non-null  int64
 83   M55B    19751 non-null  int64
 84   M55C    19751 non-null  int64
 85   M55D    0 non-null      Int64
 86   M55E    19751 non-null  int64
 87   M55F    19751 non-null  int64
 88   M55G    19751 non-null  int64
 89   M55H    19751 non-null  int64
 90   M55I    19751 non-null  int64
 91   M55J    0 non-null      Int64
 92   M55K    0 non-null      Int64
 93   M55L    0 non-null      Int64
 94   M55M    0 non-null      Int64
 95   M55N    0 non-null      Int64
 96   M55X    19751 non-null  int64
 97   M55Z    19751 non-null  int64
 98   M57A    0 non-null      Int64
 99   M57B    0 non-null      Int64
 100  M57C    0 non-null      Int64
 101  M57D    0 non-null      Int64
 102  M57E    17426 non-null  Int64
 103  M57F    17426 non-null  Int64
 104  M57G    17426 non-null  Int64
 105  M57H    0 non-null      Int64
 106  M57I    17426 non-null  Int64
 107  M57J    17426 non-null  Int64
 108  M57K    17426 non-null  Int64
 109  M57L    17426 non-null  Int64
 110  M57M    17426 non-null  Int64
 111  M57N    0 non-null      Int64
 112  M57O    17426 non-null  Int64
 113  M57P    17426 non-null  Int64
 114  M57Q    17426 non-null  Int64
 115  M57R    0 non-null      Int64
 116  M57S    17426 non-null  Int64
 117  M57T    0 non-null      Int64
 118  M57U    0 non-null      Int64
 119  M57V    0 non-null      Int64
 120  M57X    17426 non-null  Int64
 121  M60     17608 non-null  Int64
 122  M61     0 non-null      Int64
 123  M62     0 non-null      Int64
 124  M63     0 non-null      Int64
 125  M64     0 non-null      Int64
 126  M65A    0 non-null      Int64
 127  M65B    0 non-null      Int64
 128  M65C    0 non-null      Int64
 129  M65D    0 non-null      Int64
 130  M65E    0 non-null      Int64
 131  M65F    0 non-null      Int64
 132  M65G    0 non-null      Int64
 133  M65H    0 non-null      Int64
 134  M65I    0 non-null      Int64
 135  M65J    0 non-null      Int64
 136  M65K    0 non-null      Int64
 137  M65L    0 non-null      Int64
 138  M65X    0 non-null      Int64
 139  M66     19751 non-null  int64
 140  M67     17217 non-null  Int64
 141  M68     17288 non-null  Int64
 142  M69     17288 non-null  Int64
 143  M70     17608 non-null  Int64
 144  M71     17422 non-null  Int64
 145  M72     17422 non-null  Int64
 146  M73     17422 non-null  Int64
dtypes: Int64(110), int64(36), object(1)
memory usage: 24.2+ MB

In [44]:
dummy_variables  = get_dummy_variables(Modulo1633_REC41_2024_M)
Modulo1633_REC41_2024_M[dummy_variables].describe().T

        count      mean       std  min  25%  50%  75%  max
M2A   17608.0  0.252385  0.434393  0.0  0.0  0.0  1.0  1.0
M2B   17608.0  0.075193   0.26371  0.0  0.0  0.0  0.0  1.0
M2C   17608.0  0.888346  0.314949  0.0  1.0  1.0  1.0  1.0
M2D   17608.0  0.020275  0.140943  0.0  0.0  0.0  0.0  1.0
M2E   17608.0  0.000114  0.010657  0.0  0.0  0.0  0.0  1.0
M2G   17608.0   0.00017  0.013052  0.0  0.0  0.0  0.0  1.0
M2K   17608.0  0.000398  0.019935  0.0  0.0  0.0  0.0  1.0
M2N   17608.0  0.010336  0.101143  0.0  0.0  0.0  0.0  1.0
M3A   19751.0  0.663612  0.472485  0.0  0.0  1.0  1.0  1.0
M3B   19751.0  0.774087  0.418192  0.0  1.0  1.0  1.0  1.0
M3C   19751.0  0.741481  0.437831  0.0  0.0  1.0  1.0  1.0
M3D   19751.0  0.186775  0.389741  0.0  0.0  0.0  0.0  1.0
M3E   19751.0  0.000506  0.022496  0.0  0.0  0.0  0.0  1.0
M3G   19751.0  0.023492  0.151465  0.0  0.0  0.0  0.0  1.0
M3H   19751.0   0.03377  0.180642  0.0  0.0  0.0  0.0  1.0
M3K   19751.0  0.008962  0.094243  0.0  0.0  0.0  0.0  1.0
M3N   19751.0  0.001873  0.043242  0.0  0.0  0.0  0.0  1.0
M17   19751.0  0.352235  0.477679  0.0  0.0  0.0  1.0  1.0
M54   17608.0  0.140788  0.347813  0.0  0.0  0.0  0.0  1.0
M57E  17426.0  0.103294  0.304351  0.0  0.0  0.0  0.0  1.0
M57F  17426.0  0.442155  0.496657  0.0  0.0  0.0  1.0  1.0
M57G  17426.0  0.309193  0.462174  0.0  0.0  0.0  1.0  1.0
M57I  17426.0  0.109262  0.311977  0.0  0.0  0.0  0.0  1.0
M57J  17426.0  0.004247  0.065029  0.0  0.0  0.0  0.0  1.0
M57K  17426.0  0.055492  0.228944  0.0  0.0  0.0  0.0  1.0
M57L  17426.0  0.001607  0.040054  0.0  0.0  0.0  0.0  1.0
M57M  17426.0  0.105417  0.307099  0.0  0.0  0.0  0.0  1.0
M57O  17426.0  0.037186  0.189222  0.0  0.0  0.0  0.0  1.0
M57P  17426.0  0.000574  0.023949  0.0  0.0  0.0  0.0  1.0
M57Q  17426.0  0.002582  0.050753  0.0  0.0  0.0  0.0  1.0
M57S  17426.0  0.000115  0.010713  0.0  0.0  0.0  0.0  1.0
M57X  17426.0  0.006771  0.082012  0.0  0.0  0.0  0.0  1.0
M66   19751.0  0.977773  0.147424  0.0  1.0  1.0  1.0  1.0

In [45]:
no_dummy = drop_null_and_list(Modulo1633_REC41_2024_M, dummy_variables)
no_dummy_list =no_dummy.columns.to_list()
no_dummy_list

remove_items = {"M1C", "M1E", "M4","M46","M34", "M19","M6","M7","M8","M9","M11","M13","M14"}
no_dummy_list = [col for col in no_dummy_list if col not in remove_items]

In [46]:
df_dummy_variables = aggregate_sum_by_caseid(Modulo1633_REC41_2024_M[dummy_variables + ['CASEID']])
df_dummy_variables.describe().T

        count      mean       std  min  25%  50%  75%  max
M2A   17608.0  0.252385  0.434393  0.0  0.0  0.0  1.0  1.0
M2B   17608.0  0.075193   0.26371  0.0  0.0  0.0  0.0  1.0
M2C   17608.0  0.888346  0.314949  0.0  1.0  1.0  1.0  1.0
M2D   17608.0  0.020275  0.140943  0.0  0.0  0.0  0.0  1.0
M2E   17608.0  0.000114  0.010657  0.0  0.0  0.0  0.0  1.0
M2G   17608.0   0.00017  0.013052  0.0  0.0  0.0  0.0  1.0
M2K   17608.0  0.000398  0.019935  0.0  0.0  0.0  0.0  1.0
M2N   17608.0  0.010336  0.101143  0.0  0.0  0.0  0.0  1.0
M3A   17608.0  0.744378  0.559132  0.0  0.0  1.0  1.0  4.0
M3B   17608.0  0.868299  0.515318  0.0  1.0  1.0  1.0  4.0
M3C   17608.0  0.831724  0.545244  0.0  1.0  1.0  1.0  4.0
M3D   17608.0  0.209507  0.439187  0.0  0.0  0.0  0.0  4.0
M3E   17608.0  0.000568  0.023825  0.0  0.0  0.0  0.0  1.0
M3G   17608.0  0.026352  0.176383  0.0  0.0  0.0  0.0  2.0
M3H   17608.0  0.037881  0.224036  0.0  0.0  0.0  0.0  3.0
M3K   17608.0  0.010052  0.100891  0.0  0.0  0.0  0.0  2.0
M3N   17608.0  0.002101  0.053779  0.0  0.0  0.0  0.0  4.0
M17   17608.0  0.395104  0.549697  0.0  0.0  0.0  1.0  3.0
M54   17608.0  0.140788  0.347813  0.0  0.0  0.0  0.0  1.0
M57E  17608.0  0.102226  0.302954  0.0  0.0  0.0  0.0  1.0
M57F  17608.0  0.437585  0.496103  0.0  0.0  0.0  1.0  1.0
M57G  17608.0  0.305997  0.460842  0.0  0.0  0.0  1.0  1.0
M57I  17608.0  0.108133  0.310557  0.0  0.0  0.0  0.0  1.0
M57J  17608.0  0.004203  0.064693  0.0  0.0  0.0  0.0  1.0
M57K  17608.0  0.054918  0.227827  0.0  0.0  0.0  0.0  1.0
M57L  17608.0   0.00159  0.039847  0.0  0.0  0.0  0.0  1.0
M57M  17608.0  0.104328  0.305694  0.0  0.0  0.0  0.0  1.0
M57O  17608.0  0.036801  0.188279  0.0  0.0  0.0  0.0  1.0
M57P  17608.0  0.000568  0.023825  0.0  0.0  0.0  0.0  1.0
M57Q  17608.0  0.002556   0.05049  0.0  0.0  0.0  0.0  1.0
M57S  17608.0  0.000114  0.010657  0.0  0.0  0.0  0.0  1.0
M57X  17608.0  0.006701   0.08159  0.0  0.0  0.0  0.0  1.0
M66   17608.0  1.096774  0.357882  0.0  1.0  1.0  1.0  4.0

In [47]:
df_no_dummy_list = aggregate_with_value_suffix(Modulo1633_REC41_2024_M[no_dummy_list], caseid_col="CASEID")
df_no_dummy_list.describe().T

             count      mean       std  min  25%  50%  75%  max
ID1_2024   17608.0  1.121706  0.342896  1.0  1.0  1.0  1.0  4.0
MIDX_1     17608.0  1.000000  0.000000  1.0  1.0  1.0  1.0  1.0
MIDX_2     17608.0  0.116538  0.320878  0.0  0.0  0.0  0.0  1.0
MIDX_3     17608.0  0.004998  0.070520  0.0  0.0  0.0  0.0  1.0
MIDX_4     17608.0  0.000170  0.013052  0.0  0.0  0.0  0.0  1.0
M1_0       17608.0  0.184234  0.387686  0.0  0.0  0.0  0.0  1.0
M1_1       17608.0  0.269309  0.443614  0.0  0.0  0.0  1.0  1.0
M1_2       17608.0  0.516811  0.499732  0.0  0.0  1.0  1.0  1.0
M1_3       17608.0  0.006815  0.082274  0.0  0.0  0.0  0.0  1.0
M1_4       17608.0  0.000057  0.007536  0.0  0.0  0.0  0.0  1.0
M1_5       17608.0  0.000057  0.007536  0.0  0.0  0.0  0.0  1.0
M1_7       17608.0  0.000057  0.007536  0.0  0.0  0.0  0.0  1.0
M1_8       17608.0  0.022660  0.148822  0.0  0.0  0.0  0.0  1.0
M1_<NA>    17608.0  0.121706  0.342896  0.0  0.0  0.0  0.0  3.0
M1A_0      17608.0  0.109666  0.312482  0.0  0.0  0.0  0.0  1.0
M1A_1      17608.0  0.120741  0.325835  0.0  0.0  0.0  0.0  1.0
M1A_2      17608.0  0.133746  0.340389  0.0  0.0  0.0  0.0  1.0
M1A_3      17608.0  0.055543  0.229043  0.0  0.0  0.0  0.0  1.0
M1A_4      17608.0  0.006418  0.079854  0.0  0.0  0.0  0.0  1.0
M1A_5      17608.0  0.007553  0.086584  0.0  0.0  0.0  0.0  1.0
M1A_6      17608.0  0.001079  0.032832  0.0  0.0  0.0  0.0  1.0
M1A_7      17608.0  0.000284  0.016849  0.0  0.0  0.0  0.0  1.0
M1A_8      17608.0  0.041174  0.198699  0.0  0.0  0.0  0.0  1.0
M1A_<NA>   17608.0  0.645502  0.593753  0.0  0.0  1.0  1.0  4.0
M1B_1      17608.0  0.011415  0.106234  0.0  0.0  0.0  0.0  1.0
M1B_10     17608.0  0.011586  0.107014  0.0  0.0  0.0  0.0  1.0
M1B_11     17608.0  0.009939  0.099199  0.0  0.0  0.0  0.0  1.0
M1B_12     17608.0  0.008519  0.091906  0.0  0.0  0.0  0.0  1.0
M1B_2      17608.0  0.010052  0.099759  0.0  0.0  0.0  0.0  1.0
M1B_3      17608.0  0.013289  0.114514  0.0  0.0  0.0  0.0  1.0
M1B_4      17608.0  0.011699  0.107531  0.0  0.0  0.0  0.0  1.0
M1B_5      17608.0  0.014539  0.119701  0.0  0.0  0.0  0.0  1.0
M1B_6      17608.0  0.017946  0.132760  0.0  0.0  0.0  0.0  1.0
M1B_7      17608.0  0.014993  0.121529  0.0  0.0  0.0  0.0  1.0
M1B_8      17608.0  0.015504  0.123551  0.0  0.0  0.0  0.0  1.0
M1B_9      17608.0  0.010507  0.101965  0.0  0.0  0.0  0.0  1.0
M1B_98     17608.0  0.195252  0.396406  0.0  0.0  0.0  0.0  1.0
M1B_<NA>   17608.0  0.776465  0.569484  0.0  0.0  1.0  1.0  4.0
M1D_1      17608.0  0.000738  0.027162  0.0  0.0  0.0  0.0  1.0
M1D_10     17608.0  0.001590  0.039847  0.0  0.0  0.0  0.0  1.0
M1D_11     17608.0  0.000625  0.024987  0.0  0.0  0.0  0.0  1.0
M1D_12     17608.0  0.000398  0.019935  0.0  0.0  0.0  0.0  1.0
M1D_13     17608.0  0.000341  0.018457  0.0  0.0  0.0  0.0  1.0
M1D_14     17608.0  0.000341  0.018457  0.0  0.0  0.0  0.0  1.0
M1D_15     17608.0  0.000795  0.028187  0.0  0.0  0.0  0.0  1.0
M1D_16     17608.0  0.000284  0.016849  0.0  0.0  0.0  0.0  1.0
M1D_17     17608.0  0.000114  0.010657  0.0  0.0  0.0  0.0  1.0
M1D_18     17608.0  0.000227  0.015071  0.0  0.0  0.0  0.0  1.0
M1D_2      17608.0  0.000795  0.028187  0.0  0.0  0.0  0.0  1.0
M1D_20     17608.0  0.000795  0.028187  0.0  0.0  0.0  0.0  1.0
M1D_22     17608.0  0.000170  0.013052  0.0  0.0  0.0  0.0  1.0
M1D_24     17608.0  0.000057  0.007536  0.0  0.0  0.0  0.0  1.0
M1D_25     17608.0  0.000284  0.016849  0.0  0.0  0.0  0.0  1.0
M1D_27     17608.0  0.000057  0.007536  0.0  0.0  0.0  0.0  1.0
M1D_3      17608.0  0.000909  0.030131  0.0  0.0  0.0  0.0  1.0
M1D_4      17608.0  0.001022  0.031957  0.0  0.0  0.0  0.0  1.0
M1D_5      17608.0  0.001533  0.039130  0.0  0.0  0.0  0.0  1.0
M1D_6      17608.0  0.001136  0.033684  0.0  0.0  0.0  0.0  1.0
M1D_7      17608.0  0.001136  0.033684  0.0  0.0  0.0  0.0  1.0
M1D_8      17608.0  0.000965  0.031058  0.0  0.0  0.0  0.0  1.0
M1D_9      17608.0  0.000341  0.018457  0.0  0.0  0.0  0.0  1.0
M1D_98     17608.0  0.015675  0.124217  0.0  0.0  0.0  0.0  1.0
M1D_<NA>   17608.0  1.091379  0.386926  0.0  1.0  1.0  1.0  4.0
M5_0       17608.0  0.016527  0.130574  0.0  0.0  0.0  0.0  3.0
M5_1       17608.0  0.020843  0.148323  0.0  0.0  0.0  0.0  2.0
M5_10      17608.0  0.027260  0.165612  0.0  0.0  0.0  0.0  2.0
M5_11      17608.0  0.027885  0.167724  0.0  0.0  0.0  0.0  2.0
M5_12      17608.0  0.093196  0.296519  0.0  0.0  0.0  0.0  2.0
M5_13      17608.0  0.029816  0.172735  0.0  0.0  0.0  0.0  2.0
M5_14      17608.0  0.051397  0.226401  0.0  0.0  0.0  0.0  2.0
M5_15      17608.0  0.050148  0.222380  0.0  0.0  0.0  0.0  2.0
M5_16      17608.0  0.036234  0.188991  0.0  0.0  0.0  0.0  2.0
M5_17      17608.0  0.026408  0.162462  0.0  0.0  0.0  0.0  2.0
M5_18      17608.0  0.101147  0.307870  0.0  0.0  0.0  0.0  3.0
M5_19      17608.0  0.028680  0.168603  0.0  0.0  0.0  0.0  2.0
M5_2       17608.0  0.021411  0.146314  0.0  0.0  0.0  0.0  2.0
M5_20      17608.0  0.045945  0.211531  0.0  0.0  0.0  0.0  2.0
M5_21      17608.0  0.018287  0.134415  0.0  0.0  0.0  0.0  2.0
M5_22      17608.0  0.018969  0.139302  0.0  0.0  0.0  0.0  2.0
M5_23      17608.0  0.016583  0.128594  0.0  0.0  0.0  0.0  2.0
M5_24      17608.0  0.119037  0.327330  0.0  0.0  0.0  0.0  2.0
M5_25      17608.0  0.010847  0.104134  0.0  0.0  0.0  0.0  2.0
M5_26      17608.0  0.013801  0.117635  0.0  0.0  0.0  0.0  2.0
M5_27      17608.0  0.012892  0.112811  0.0  0.0  0.0  0.0  1.0
M5_28      17608.0  0.011075  0.105734  0.0  0.0  0.0  0.0  2.0
M5_29      17608.0  0.008008  0.089129  0.0  0.0  0.0  0.0  1.0
M5_3       17608.0  0.025443  0.159264  0.0  0.0  0.0  0.0  2.0
M5_30      17608.0  0.027488  0.165231  0.0  0.0  0.0  0.0  2.0
M5_31      17608.0  0.005736  0.075521  0.0  0.0  0.0  0.0  1.0
M5_32      17608.0  0.007553  0.088530  0.0  0.0  0.0  0.0  2.0
M5_33      17608.0  0.005282  0.072485  0.0  0.0  0.0  0.0  1.0
M5_34      17608.0  0.004543  0.068093  0.0  0.0  0.0  0.0  2.0
M5_35      17608.0  0.003805  0.061570  0.0  0.0  0.0  0.0  1.0
M5_36      17608.0  0.025500  0.158002  0.0  0.0  0.0  0.0  2.0
M5_37      17608.0  0.002045  0.045171  0.0  0.0  0.0  0.0  1.0
M5_38      17608.0  0.003351  0.057790  0.0  0.0  0.0  0.0  1.0
M5_39      17608.0  0.003010  0.054782  0.0  0.0  0.0  0.0  1.0
M5_4       17608.0  0.024137  0.154584  0.0  0.0  0.0  0.0  2.0
M5_40      17608.0  0.002385  0.048782  0.0  0.0  0.0  0.0  1.0
M5_41      17608.0  0.001193  0.034515  0.0  0.0  0.0  0.0  1.0
M5_42      17608.0  0.003464  0.059717  0.0  0.0  0.0  0.0  2.0
M5_43      17608.0  0.001477  0.038399  0.0  0.0  0.0  0.0  1.0
M5_44      17608.0  0.001306  0.036119  0.0  0.0  0.0  0.0  1.0
M5_45      17608.0  0.001193  0.034515  0.0  0.0  0.0  0.0  1.0
M5_46      17608.0  0.000965  0.031058  0.0  0.0  0.0  0.0  1.0
M5_47      17608.0  0.000568  0.023825  0.0  0.0  0.0  0.0  1.0
M5_48      17608.0  0.002442  0.049358  0.0  0.0  0.0  0.0  1.0
M5_49      17608.0  0.000625  0.024987  0.0  0.0  0.0  0.0  1.0
M5_5       17608.0  0.023228  0.151384  0.0  0.0  0.0  0.0  2.0
M5_50      17608.0  0.000511  0.022603  0.0  0.0  0.0  0.0  1.0
M5_51      17608.0  0.000568  0.023825  0.0  0.0  0.0  0.0  1.0
M5_52      17608.0  0.000227  0.015071  0.0  0.0  0.0  0.0  1.0
M5_53      17608.0  0.000341  0.018457  0.0  0.0  0.0  0.0  1.0
M5_54      17608.0  0.000114  0.010657  0.0  0.0  0.0  0.0  1.0
M5_55      17608.0  0.000625  0.024987  0.0  0.0  0.0  0.0  1.0
M5_56      17608.0  0.000341  0.018457  0.0  0.0  0.0  0.0  1.0
M5_57      17608.0  0.000454  0.021311  0.0  0.0  0.0  0.0  1.0
M5_58      17608.0  0.000398  0.019935  0.0  0.0  0.0  0.0  1.0
M5_59      17608.0  0.000341  0.018457  0.0  0.0  0.0  0.0  1.0
M5_6       17608.0  0.033564  0.183546  0.0  0.0  0.0  0.0  2.0
M5_7       17608.0  0.027033  0.164272  0.0  0.0  0.0  0.0  2.0
M5_8       17608.0  0.031861  0.178202  0.0  0.0  0.0  0.0  2.0
M5_9       17608.0  0.031236  0.177194  0.0  0.0  0.0  0.0  2.0
M5_94      17608.0  0.010791  0.107097  0.0  0.0  0.0  0.0  3.0
M5_98      17608.0  0.000170  0.013052  0.0  0.0  0.0  0.0  1.0
M10_1      17608.0  0.536234  0.550246  0.0  0.0  1.0  1.0  4.0
M10_2      17608.0  0.341095  0.517836  0.0  0.0  0.0  1.0  3.0
M10_3      17608.0  0.244378  0.465389  0.0  0.0  0.0  0.0  3.0
M15_11     17608.0  0.061165  0.281692  0.0  0.0  0.0  0.0  4.0
M15_12     17608.0  0.001079  0.034519  0.0  0.0  0.0  0.0  2.0
M15_21     17608.0  0.560030  0.576836  0.0  0.0  1.0  1.0  3.0
M15_22     17608.0  0.163846  0.398377  0.0  0.0  0.0  0.0  4.0
M15_23     17608.0  0.001420  0.039134  0.0  0.0  0.0  0.0  2.0
M15_24     17608.0  0.202522  0.435400  0.0  0.0  0.0  0.0  3.0
M15_25     17608.0  0.018798  0.146285  0.0  0.0  0.0  0.0  3.0
M15_26     17608.0  0.001817  0.045181  0.0  0.0  0.0  0.0  2.0
M15_27     17608.0  0.000511  0.024990  0.0  0.0  0.0  0.0  2.0
M15_31     17608.0  0.094162  0.308701  0.0  0.0  0.0  0.0  2.0
M15_32     17608.0  0.002669  0.053754  0.0  0.0  0.0  0.0  2.0
M15_41     17608.0  0.000170  0.013052  0.0  0.0  0.0  0.0  1.0
M15_42     17608.0  0.001817  0.045181  0.0  0.0  0.0  0.0  2.0
M15_96     17608.0  0.011699  0.111677  0.0  0.0  0.0  0.0  2.0
M18_1      17608.0  0.019707  0.140620  0.0  0.0  0.0  0.0  2.0
M18_2      17608.0  0.277544  0.475362  0.0  0.0  0.0  1.0  3.0
M18_3      17608.0  0.546513  0.568873  0.0  0.0  1.0  1.0  3.0
M18_4      17608.0  0.239437  0.452713  0.0  0.0  0.0  0.0  3.0
M18_5      17608.0  0.037710  0.197238  0.0  0.0  0.0  0.0  3.0
M18_8      17608.0  0.000795  0.028187  0.0  0.0  0.0  0.0  1.0
M19A_0     17608.0  0.022319  0.180907  0.0  0.0  0.0  0.0  4.0
M19A_1     17608.0  0.618582  0.566797  0.0  0.0  1.0  1.0  3.0
M19A_2     17608.0  0.468537  0.566805  0.0  0.0  0.0  1.0  3.0
M19A_8     17608.0  0.000454  0.021311  0.0  0.0  0.0  0.0  1.0
M19A_<NA>  17608.0  0.011813  0.115170  0.0  0.0  0.0  0.0  2.0
M27_0      17608.0  1.121592  0.342770  1.0  1.0  1.0  1.0  4.0
M27_3      17608.0  0.000114  0.010657  0.0  0.0  0.0  0.0  1.0
M28_0      17608.0  1.120457  0.343171  0.0  1.0  1.0  1.0  4.0
M28_1      17608.0  0.000170  0.013052  0.0  0.0  0.0  0.0  1.0
M28_2      17608.0  0.000170  0.013052  0.0  0.0  0.0  0.0  1.0
M28_4      17608.0  0.000909  0.030131  0.0  0.0  0.0  0.0  1.0
M29_0      17608.0  1.121081  0.342703  0.0  1.0  1.0  1.0  4.0
M29_1      17608.0  0.000170  0.013052  0.0  0.0  0.0  0.0  1.0
M29_2      17608.0  0.000057  0.007536  0.0  0.0  0.0  0.0  1.0
M29_4      17608.0  0.000398  0.019935  0.0  0.0  0.0  0.0  1.0
M35_0      17608.0  0.004203  0.064693  0.0  0.0  0.0  0.0  1.0
M35_1      17608.0  0.041345  0.199092  0.0  0.0  0.0  0.0  1.0
M35_10     17608.0  0.009825  0.098636  0.0  0.0  0.0  0.0  1.0
M35_11     17608.0  0.000114  0.010657  0.0  0.0  0.0  0.0  1.0
M35_12     17608.0  0.001817  0.042593  0.0  0.0  0.0  0.0  1.0
M35_14     17608.0  0.000114  0.010657  0.0  0.0  0.0  0.0  1.0
M35_15     17608.0  0.000568  0.023825  0.0  0.0  0.0  0.0  1.0
M35_16     17608.0  0.000170  0.013052  0.0  0.0  0.0  0.0  1.0
M35_18     17608.0  0.000114  0.010657  0.0  0.0  0.0  0.0  1.0
M35_2      17608.0  0.073887  0.261594  0.0  0.0  0.0  0.0  1.0
M35_20     17608.0  0.000341  0.018457  0.0  0.0  0.0  0.0  1.0
M35_22     17608.0  0.000057  0.007536  0.0  0.0  0.0  0.0  1.0
M35_23     17608.0  0.000057  0.007536  0.0  0.0  0.0  0.0  1.0
M35_3      17608.0  0.102397  0.303178  0.0  0.0  0.0  0.0  1.0
M35_30     17608.0  0.000057  0.007536  0.0  0.0  0.0  0.0  1.0
M35_4      17608.0  0.084393  0.277985  0.0  0.0  0.0  0.0  1.0
M35_5      17608.0  0.053271  0.224580  0.0  0.0  0.0  0.0  1.0
M35_6      17608.0  0.035041  0.183888  0.0  0.0  0.0  0.0  1.0
M35_7      17608.0  0.010223  0.100592  0.0  0.0  0.0  0.0  1.0
M35_8      17608.0  0.011529  0.106755  0.0  0.0  0.0  0.0  1.0
M35_9      17608.0  0.001477  0.038399  0.0  0.0  0.0  0.0  1.0
M35_<NA>   17608.0  0.690709  0.549560  0.0  0.0  1.0  1.0  3.0
M36_0      17608.0  0.017776  0.132140  0.0  0.0  0.0  0.0  1.0
M36_1      17608.0  0.019196  0.137217  0.0  0.0  0.0  0.0  1.0
M36_10     17608.0  0.035041  0.183888  0.0  0.0  0.0  0.0  1.0
M36_11     17608.0  0.001420  0.037655  0.0  0.0  0.0  0.0  1.0
M36_12     17608.0  0.007951  0.088815  0.0  0.0  0.0  0.0  1.0
M36_13     17608.0  0.000738  0.027162  0.0  0.0  0.0  0.0  1.0
M36_14     17608.0  0.000398  0.019935  0.0  0.0  0.0  0.0  1.0
M36_15     17608.0  0.004032  0.063374  0.0  0.0  0.0  0.0  1.0
M36_16     17608.0  0.000284  0.016849  0.0  0.0  0.0  0.0  1.0
M36_17     17608.0  0.000057  0.007536  0.0  0.0  0.0  0.0  1.0
M36_18     17608.0  0.000114  0.010657  0.0  0.0  0.0  0.0  1.0
M36_2      17608.0  0.038789  0.193098  0.0  0.0  0.0  0.0  1.0
M36_20     17608.0  0.001874  0.043252  0.0  0.0  0.0  0.0  1.0
M36_24     17608.0  0.000114  0.010657  0.0  0.0  0.0  0.0  1.0
M36_25     17608.0  0.000114  0.010657  0.0  0.0  0.0  0.0  1.0
M36_3      17608.0  0.057531  0.232860  0.0  0.0  0.0  0.0  1.0
M36_30     17608.0  0.000057  0.007536  0.0  0.0  0.0  0.0  1.0
M36_36     17608.0  0.000057  0.007536  0.0  0.0  0.0  0.0  1.0
M36_4      17608.0  0.059973  0.237443  0.0  0.0  0.0  0.0  1.0
M36_5      17608.0  0.064914  0.246380  0.0  0.0  0.0  0.0  1.0
M36_6      17608.0  0.063778  0.244364  0.0  0.0  0.0  0.0  1.0
M36_7      17608.0  0.023058  0.150091  0.0  0.0  0.0  0.0  1.0
M36_8      17608.0  0.029589  0.169455  0.0  0.0  0.0  0.0  1.0
M36_9      17608.0  0.004146  0.064256  0.0  0.0  0.0  0.0  1.0
M36_<NA>   17608.0  0.690709  0.549560  0.0  0.0  1.0  1.0  3.0
M38_0      17608.0  0.783962  0.561147  0.0  0.0  1.0  1.0  4.0
M38_1      17608.0  0.326102  0.500441  0.0  0.0  0.0  1.0  3.0
M38_8      17608.0  0.002045  0.045171  0.0  0.0  0.0  0.0  1.0
M38_<NA>   17608.0  0.009598  0.102054  0.0  0.0  0.0  0.0  3.0
M39_0      17608.0  0.082349  0.276962  0.0  0.0  0.0  0.0  2.0
M39_1      17608.0  0.009655  0.104523  0.0  0.0  0.0  0.0  3.0
M39_2      17608.0  0.027601  0.171289  0.0  0.0  0.0  0.0  2.0
M39_3      17608.0  0.141072  0.374211  0.0  0.0  0.0  0.0  3.0
M39_4      17608.0  0.267946  0.472197  0.0  0.0  0.0  1.0  3.0
M39_5      17608.0  0.485518  0.553304  0.0  0.0  0.0  1.0  3.0
M39_6      17608.0  0.077862  0.278154  0.0  0.0  0.0  0.0  2.0
M39_7      17608.0  0.016356  0.129941  0.0  0.0  0.0  0.0  2.0
M39_8      17608.0  0.003748  0.062033  0.0  0.0  0.0  0.0  2.0
M39_<NA>   17608.0  0.009598  0.102054  0.0  0.0  0.0  0.0  3.0
M42A_0     17608.0  0.001761  0.041923  0.0  0.0  0.0  0.0  1.0
M42A_1     17608.0  0.987733  0.110079  0.0  1.0  1.0  1.0  1.0
M42A_8     17608.0  0.000170  0.013052  0.0  0.0  0.0  0.0  1.0
M42A_<NA>  17608.0  0.132042  0.362526  0.0  0.0  0.0  0.0  3.0
M42C_0     17608.0  0.001817  0.042593  0.0  0.0  0.0  0.0  1.0
M42C_1     17608.0  0.987619  0.110581  0.0  1.0  1.0  1.0  1.0
M42C_8     17608.0  0.000227  0.015071  0.0  0.0  0.0  0.0  1.0
M42C_<NA>  17608.0  0.132042  0.362526  0.0  0.0  0.0  0.0  3.0
M42D_0     17608.0  0.020218  0.140750  0.0  0.0  0.0  0.0  1.0
M42D_1     17608.0  0.968537  0.174570  0.0  1.0  1.0  1.0  1.0
M42D_8     17608.0  0.000909  0.030131  0.0  0.0  0.0  0.0  1.0
M42D_<NA>  17608.0  0.132042  0.362526  0.0  0.0  0.0  0.0  3.0
M42E_0     17608.0  0.015504  0.123551  0.0  0.0  0.0  0.0  1.0
M42E_1     17608.0  0.973478  0.160686  0.0  1.0  1.0  1.0  1.0
M42E_8     17608.0  0.000682  0.026098  0.0  0.0  0.0  0.0  1.0
M42E_<NA>  17608.0  0.132042  0.362526  0.0  0.0  0.0  0.0  3.0
M43_0      17608.0  0.038903  0.193369  0.0  0.0  0.0  0.0  1.0
M43_1      17608.0  0.950477  0.216963  0.0  1.0  1.0  1.0  1.0
M43_8      17608.0  0.000284  0.016849  0.0  0.0  0.0  0.0  1.0
M43_<NA>   17608.0  0.132042  0.362526  0.0  0.0  0.0  0.0  3.0
M44_0      17608.0  0.007326  0.085282  0.0  0.0  0.0  0.0  1.0
M44_1      17608.0  0.943094  0.231669  0.0  1.0  1.0  1.0  1.0
M44_8      17608.0  0.000057  0.007536  0.0  0.0  0.0  0.0  1.0
M44_<NA>   17608.0  0.171229  0.409377  0.0  0.0  0.0  0.0  3.0
M45_0      17608.0  0.049750  0.217434  0.0  0.0  0.0  0.0  1.0
M45_1      17608.0  0.949966  0.218021  0.0  1.0  1.0  1.0  1.0
M45_8      17608.0  0.000284  0.016849  0.0  0.0  0.0  0.0  1.0
M45_<NA>   17608.0  0.121706  0.342896  0.0  0.0  0.0  0.0  3.0
M47_0      17608.0  0.937131  0.242734  0.0  1.0  1.0  1.0  1.0
M47_1      17608.0  0.062756  0.242530  0.0  0.0  0.0  0.0  1.0
M47_8      17608.0  0.000114  0.010657  0.0  0.0  0.0  0.0  1.0
M47_<NA>   17608.0  0.121706  0.342896  0.0  0.0  0.0  0.0  3.0
M48_0      17608.0  0.966493  0.179963  0.0  1.0  1.0  1.0  1.0
M48_1      17608.0  0.033337  0.179520  0.0  0.0  0.0  0.0  1.0
M48_8      17608.0  0.000170  0.013052  0.0  0.0  0.0  0.0  1.0
M48_<NA>   17608.0  0.121706  0.342896  0.0  0.0  0.0  0.0  3.0
M55A_0     17608.0  1.106826  0.361589  0.0  1.0  1.0  1.0  4.0
M55A_1     17608.0  0.004089  0.068950  0.0  0.0  0.0  0.0  3.0
M55A_8     17608.0  0.010791  0.106566  0.0  0.0  0.0  0.0  2.0
M55B_0     17608.0  1.109723  0.359538  0.0  1.0  1.0  1.0  4.0
M55B_1     17608.0  0.001193  0.036123  0.0  0.0  0.0  0.0  2.0
M55B_8     17608.0  0.010791  0.106566  0.0  0.0  0.0  0.0  2.0
M55C_0     17608.0  1.108644  0.360418  0.0  1.0  1.0  1.0  4.0
M55C_1     17608.0  0.002272  0.047609  0.0  0.0  0.0  0.0  1.0
M55C_8     17608.0  0.010791  0.106566  0.0  0.0  0.0  0.0  2.0
M55E_0     17608.0  1.110461  0.358283  0.0  1.0  1.0  1.0  4.0
M55E_1     17608.0  0.000454  0.021311  0.0  0.0  0.0  0.0  1.0
M55E_8     17608.0  0.010791  0.106566  0.0  0.0  0.0  0.0  2.0
M55F_0     17608.0  1.110518  0.358028  0.0  1.0  1.0  1.0  4.0
M55F_1     17608.0  0.000398  0.019935  0.0  0.0  0.0  0.0  1.0
M55F_8     17608.0  0.010791  0.106566  0.0  0.0  0.0  0.0  2.0
M55G_0     17608.0  0.672535  0.600630  0.0  0.0  1.0  1.0  4.0
M55G_1     17608.0  0.438380  0.543822  0.0  0.0  0.0  1.0  3.0
M55G_8     17608.0  0.010791  0.106566  0.0  0.0  0.0  0.0  2.0
M55H_0     17608.0  1.108019  0.361471  0.0  1.0  1.0  1.0  4.0
M55H_1     17608.0  0.002896  0.055815  0.0  0.0  0.0  0.0  2.0
M55H_8     17608.0  0.010791  0.106566  0.0  0.0  0.0  0.0  2.0
M55I_0     17608.0  1.110234  0.358511  0.0  1.0  1.0  1.0  4.0
M55I_1     17608.0  0.000682  0.028190  0.0  0.0  0.0  0.0  2.0
M55I_8     17608.0  0.010791  0.106566  0.0  0.0  0.0  0.0  2.0
M55X_0     17608.0  1.108076  0.361218  0.0  1.0  1.0  1.0  4.0
M55X_1     17608.0  0.002840  0.055307  0.0  0.0  0.0  0.0  2.0
M55X_8     17608.0  0.010791  0.106566  0.0  0.0  0.0  0.0  2.0
M55Z_0     17608.0  0.449796  0.546452  0.0  0.0  0.0  1.0  3.0
M55Z_1     17608.0  0.661120  0.600397  0.0  0.0  1.0  1.0  4.0
M55Z_8     17608.0  0.010791  0.106566  0.0  0.0  0.0  0.0  2.0
M60_0      17608.0  0.943094  0.231669  0.0  1.0  1.0  1.0  1.0
M60_1      17608.0  0.053669  0.225369  0.0  0.0  0.0  0.0  1.0
M60_8      17608.0  0.003237  0.056806  0.0  0.0  0.0  0.0  1.0
M60_<NA>   17608.0  0.121706  0.342896  0.0  0.0  0.0  0.0  3.0
M67_100    17608.0  0.259541  0.438395  0.0  0.0  0.0  1.0  1.0
M67_101    17608.0  0.266981  0.442395  0.0  0.0  0.0  1.0  1.0
M67_102    17608.0  0.191958  0.393852  0.0  0.0  0.0  0.0  1.0
M67_103    17608.0  0.098080  0.297432  0.0  0.0  0.0  0.0  1.0
M67_104    17608.0  0.052703  0.223447  0.0  0.0  0.0  0.0  1.0
M67_105    17608.0  0.034700  0.183024  0.0  0.0  0.0  0.0  1.0
M67_106    17608.0  0.020786  0.142671  0.0  0.0  0.0  0.0  1.0
M67_107    17608.0  0.010847  0.103587  0.0  0.0  0.0  0.0  1.0
M67_108    17608.0  0.010791  0.103319  0.0  0.0  0.0  0.0  1.0
M67_109    17608.0  0.003975  0.062928  0.0  0.0  0.0  0.0  1.0
M67_110    17608.0  0.005509  0.074019  0.0  0.0  0.0  0.0  1.0
M67_111    17608.0  0.002726  0.052142  0.0  0.0  0.0  0.0  1.0
M67_112    17608.0  0.004146  0.064256  0.0  0.0  0.0  0.0  1.0
M67_113    17608.0  0.000682  0.026098  0.0  0.0  0.0  0.0  1.0
M67_114    17608.0  0.000909  0.030131  0.0  0.0  0.0  0.0  1.0
M67_115    17608.0  0.000625  0.024987  0.0  0.0  0.0  0.0  1.0
M67_116    17608.0  0.000568  0.023825  0.0  0.0  0.0  0.0  1.0

In [48]:
continue_var_REC41 = ["M6","M7","M8","M9","M11","M13","M14"]

df_continue_var_REC41 = aggregate_by_caseid_mean(Modulo1633_REC41_2024_M[continue_var_REC41 + ['CASEID']], caseid_col="CASEID")
df_continue_var_REC41.head()

               CASEID    M6    M7   M8   M9   M11  M13   M14
0        325503101  2  12.0  12.0  8.0  8.0  <NA>  1.0   6.0
1        325504701  2   4.0   4.0  4.0  4.0  <NA>  4.0   8.0
2        325505001  1   3.0   3.0  3.0  3.0  <NA>  1.0  11.0
3        325508901  2   6.0   6.0  4.0  4.0  <NA>  1.0  12.0
4        325509701  2  96.0  18.0  1.0  1.0  <NA>  2.0  10.0

In [49]:
Modulo1633_REC41_2024_fil = df_dummy_variables.merge(df_no_dummy_list, how='left', on='CASEID')
Modulo1633_REC41_2024_fil =Modulo1633_REC41_2024_fil.merge(df_continue_var_REC41, how = 'left', on = 'CASEID')
Modulo1633_REC41_2024_fil.info(verbose = True, show_counts = True)

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 17608 entries, 0 to 17607
Data columns (total 467 columns):
 #    Column     Non-Null Count  Dtype
---   ------     --------------  -----
 0    CASEID     17608 non-null  object
 1    M2A        17608 non-null  Int64
 2    M2B        17608 non-null  Int64
 3    M2C        17608 non-null  Int64
 4    M2D        17608 non-null  Int64
 5    M2E        17608 non-null  Int64
 6    M2G        17608 non-null  Int64
 7    M2K        17608 non-null  Int64
 8    M2N        17608 non-null  Int64
 9    M3A        17608 non-null  int64
 10   M3B        17608 non-null  int64
 11   M3C        17608 non-null  int64
 12   M3D        17608 non-null  int64
 13   M3E        17608 non-null  int64
 14   M3G        17608 non-null  int64
 15   M3H        17608 non-null  int64
 16   M3K        17608 non-null  int64
 17   M3N        17608 non-null  int64
 18   M17        17608 non-null  int64
 19   M54        17608 non-null  Int64
 20   M57E       17608 non-null  Int64
 21   M57F       17608 non-null  Int64
 22   M57G       17608 non-null  Int64
 23   M57I       17608 non-null  Int64
 24   M57J       17608 non-null  Int64
 25   M57K       17608 non-null  Int64
 26   M57L       17608 non-null  Int64
 27   M57M       17608 non-null  Int64
 28   M57O       17608 non-null  Int64
 29   M57P       17608 non-null  Int64
 30   M57Q       17608 non-null  Int64
 31   M57S       17608 non-null  Int64
 32   M57X       17608 non-null  Int64
 33   M66        17608 non-null  int64
 34   ID1_2024   17608 non-null  int64
 35   MIDX_1     17608 non-null  int64
 36   MIDX_2     17608 non-null  int64
 37   MIDX_3     17608 non-null  int64
 38   MIDX_4     17608 non-null  int64
 39   M1_0       17608 non-null  int64
 40   M1_1       17608 non-null  int64
 41   M1_2       17608 non-null  int64
 42   M1_3       17608 non-null  int64
 43   M1_4       17608 non-null  int64
 44   M1_5       17608 non-null  int64
 45   M1_7       17608 non-null  int64
 46   M1_8       17608 non-null  int64
 47   M1_<NA>    17608 non-null  int64
 48   M1A_0      17608 non-null  int64
 49   M1A_1      17608 non-null  int64
 50   M1A_2      17608 non-null  int64
 51   M1A_3      17608 non-null  int64
 52   M1A_4      17608 non-null  int64
 53   M1A_5      17608 non-null  int64
 54   M1A_6      17608 non-null  int64
 55   M1A_7      17608 non-null  int64
 56   M1A_8      17608 non-null  int64
 57   M1A_<NA>   17608 non-null  int64
 58   M1B_1      17608 non-null  int64
 59   M1B_10     17608 non-null  int64
 60   M1B_11     17608 non-null  int64
 61   M1B_12     17608 non-null  int64
 62   M1B_2      17608 non-null  int64
 63   M1B_3      17608 non-null  int64
 64   M1B_4      17608 non-null  int64
 65   M1B_5      17608 non-null  int64
 66   M1B_6      17608 non-null  int64
 67   M1B_7      17608 non-null  int64
 68   M1B_8      17608 non-null  int64
 69   M1B_9      17608 non-null  int64
 70   M1B_98     17608 non-null  int64
 71   M1B_<NA>   17608 non-null  int64
 72   M1D_1      17608 non-null  int64
 73   M1D_10     17608 non-null  int64
 74   M1D_11     17608 non-null  int64
 75   M1D_12     17608 non-null  int64
 76   M1D_13     17608 non-null  int64
 77   M1D_14     17608 non-null  int64
 78   M1D_15     17608 non-null  int64
 79   M1D_16     17608 non-null  int64
 80   M1D_17     17608 non-null  int64
 81   M1D_18     17608 non-null  int64
 82   M1D_2      17608 non-null  int64
 83   M1D_20     17608 non-null  int64
 84   M1D_22     17608 non-null  int64
 85   M1D_24     17608 non-null  int64
 86   M1D_25     17608 non-null  int64
 87   M1D_27     17608 non-null  int64
 88   M1D_3      17608 non-null  int64
 89   M1D_4      17608 non-null  int64
 90   M1D_5      17608 non-null  int64
 91   M1D_6      17608 non-null  int64
 92   M1D_7      17608 non-null  int64
 93   M1D_8      17608 non-null  int64
 94   M1D_9      17608 non-null  int64
 95   M1D_98     17608 non-null  int64
 96   M1D_<NA>   17608 non-null  int64
 97   M5_0       17608 non-null  int64
 98   M5_1       17608 non-null  int64
 99   M5_10      17608 non-null  int64
 100  M5_11      17608 non-null  int64
 101  M5_12      17608 non-null  int64
 102  M5_13      17608 non-null  int64
 103  M5_14      17608 non-null  int64
 104  M5_15      17608 non-null  int64
 105  M5_16      17608 non-null  int64
 106  M5_17      17608 non-null  int64
 107  M5_18      17608 non-null  int64
 108  M5_19      17608 non-null  int64
 109  M5_2       17608 non-null  int64
 110  M5_20      17608 non-null  int64
 111  M5_21      17608 non-null  int64
 112  M5_22      17608 non-null  int64
 113  M5_23      17608 non-null  int64
 114  M5_24      17608 non-null  int64
 115  M5_25      17608 non-null  int64
 116  M5_26      17608 non-null  int64
 117  M5_27      17608 non-null  int64
 118  M5_28      17608 non-null  int64
 119  M5_29      17608 non-null  int64
 120  M5_3       17608 non-null  int64
 121  M5_30      17608 non-null  int64
 122  M5_31      17608 non-null  int64
 123  M5_32      17608 non-null  int64
 124  M5_33      17608 non-null  int64
 125  M5_34      17608 non-null  int64
 126  M5_35      17608 non-null  int64
 127  M5_36      17608 non-null  int64
 128  M5_37      17608 non-null  int64
 129  M5_38      17608 non-null  int64
 130  M5_39      17608 non-null  int64
 131  M5_4       17608 non-null  int64
 132  M5_40      17608 non-null  int64
 133  M5_41      17608 non-null  int64
 134  M5_42      17608 non-null  int64
 135  M5_43      17608 non-null  int64
 136  M5_44      17608 non-null  int64
 137  M5_45      17608 non-null  int64
 138  M5_46      17608 non-null  int64
 139  M5_47      17608 non-null  int64
 140  M5_48      17608 non-null  int64
 141  M5_49      17608 non-null  int64
 142  M5_5       17608 non-null  int64
 143  M5_50      17608 non-null  int64
 144  M5_51      17608 non-null  int64
 145  M5_52      17608 non-null  int64
 146  M5_53      17608 non-null  int64
 147  M5_54      17608 non-null  int64
 148  M5_55      17608 non-null  int64
 149  M5_56      17608 non-null  int64
 150  M5_57      17608 non-null  int64
 151  M5_58      17608 non-null  int64
 152  M5_59      17608 non-null  int64
 153  M5_6       17608 non-null  int64
 154  M5_7       17608 non-null  int64
 155  M5_8       17608 non-null  int64
 156  M5_9       17608 non-null  int64
 157  M5_94      17608 non-null  int64
 158  M5_98      17608 non-null  int64
 159  M10_1      17608 non-null  int64
 160  M10_2      17608 non-null  int64
 161  M10_3      17608 non-null  int64
 162  M15_11     17608 non-null  int64
 163  M15_12     17608 non-null  int64
 164  M15_21     17608 non-null  int64
 165  M15_22     17608 non-null  int64
 166  M15_23     17608 non-null  int64
 167  M15_24     17608 non-null  int64
 168  M15_25     17608 non-null  int64
 169  M15_26     17608 non-null  int64
 170  M15_27     17608 non-null  int64
 171  M15_31     17608 non-null  int64
 172  M15_32     17608 non-null  int64
 173  M15_41     17608 non-null  int64
 174  M15_42     17608 non-null  int64
 175  M15_96     17608 non-null  int64
 176  M18_1      17608 non-null  int64
 177  M18_2      17608 non-null  int64
 178  M18_3      17608 non-null  int64
 179  M18_4      17608 non-null  int64
 180  M18_5      17608 non-null  int64
 181  M18_8      17608 non-null  int64
 182  M19A_0     17608 non-null  int64
 183  M19A_1     17608 non-null  int64
 184  M19A_2     17608 non-null  int64
 185  M19A_8     17608 non-null  int64
 186  M19A_<NA>  17608 non-null  int64
 187  M27_0      17608 non-null  int64
 188  M27_3      17608 non-null  int64
 189  M28_0      17608 non-null  int64
 190  M28_1      17608 non-null  int64
 191  M28_2      17608 non-null  int64
 192  M28_4      17608 non-null  int64
 193  M29_0      17608 non-null  int64
 194  M29_1      17608 non-null  int64
 195  M29_2      17608 non-null  int64
 196  M29_4      17608 non-null  int64
 197  M35_0      17608 non-null  int64
 198  M35_1      17608 non-null  int64
 199  M35_10     17608 non-null  int64
 200  M35_11     17608 non-null  int64
 201  M35_12     17608 non-null  int64
 202  M35_14     17608 non-null  int64
 203  M35_15     17608 non-null  int64
 204  M35_16     17608 non-null  int64
 205  M35_18     17608 non-null  int64
 206  M35_2      17608 non-null  int64
 207  M35_20     17608 non-null  int64
 208  M35_22     17608 non-null  int64
 209  M35_23     17608 non-null  int64
 210  M35_3      17608 non-null  int64
 211  M35_30     17608 non-null  int64
 212  M35_4      17608 non-null  int64
 213  M35_5      17608 non-null  int64
 214  M35_6      17608 non-null  int64
 215  M35_7      17608 non-null  int64
 216  M35_8      17608 non-null  int64
 217  M35_9      17608 non-null  int64
 218  M35_<NA>   17608 non-null  int64
 219  M36_0      17608 non-null  int64
 220  M36_1      17608 non-null  int64
 221  M36_10     17608 non-null  int64
 222  M36_11     17608 non-null  int64
 223  M36_12     17608 non-null  int64
 224  M36_13     17608 non-null  int64
 225  M36_14     17608 non-null  int64
 226  M36_15     17608 non-null  int64
 227  M36_16     17608 non-null  int64
 228  M36_17     17608 non-null  int64
 229  M36_18     17608 non-null  int64
 230  M36_2      17608 non-null  int64
 231  M36_20     17608 non-null  int64
 232  M36_24     17608 non-null  int64
 233  M36_25     17608 non-null  int64
 234  M36_3      17608 non-null  int64
 235  M36_30     17608 non-null  int64
 236  M36_36     17608 non-null  int64
 237  M36_4      17608 non-null  int64
 238  M36_5      17608 non-null  int64
 239  M36_6      17608 non-null  int64
 240  M36_7      17608 non-null  int64
 241  M36_8      17608 non-null  int64
 242  M36_9      17608 non-null  int64
 243  M36_<NA>   17608 non-null  int64
 244  M38_0      17608 non-null  int64
 245  M38_1      17608 non-null  int64
 246  M38_8      17608 non-null  int64
 247  M38_<NA>   17608 non-null  int64
 248  M39_0      17608 non-null  int64
 249  M39_1      17608 non-null  int64
 250  M39_2      17608 non-null  int64
 251  M39_3      17608 non-null  int64
 252  M39_4      17608 non-null  int64
 253  M39_5      17608 non-null  int64
 254  M39_6      17608 non-null  int64
 255  M39_7      17608 non-null  int64
 256  M39_8      17608 non-null  int64
 257  M39_<NA>   17608 non-null  int64
 258  M42A_0     17608 non-null  int64
 259  M42A_1     17608 non-null  int64
 260  M42A_8     17608 non-null  int64
 261  M42A_<NA>  17608 non-null  int64
 262  M42C_0     17608 non-null  int64
 263  M42C_1     17608 non-null  int64
 264  M42C_8     17608 non-null  int64
 265  M42C_<NA>  17608 non-null  int64
 266  M42D_0     17608 non-null  int64
 267  M42D_1     17608 non-null  int64
 268  M42D_8     17608 non-null  int64
 269  M42D_<NA>  17608 non-null  int64
 270  M42E_0     17608 non-null  int64
 271  M42E_1     17608 non-null  int64
 272  M42E_8     17608 non-null  int64
 273  M42E_<NA>  17608 non-null  int64
 274  M43_0      17608 non-null  int64
 275  M43_1      17608 non-null  int64
 276  M43_8      17608 non-null  int64
 277  M43_<NA>   17608 non-null  int64
 278  M44_0      17608 non-null  int64
 279  M44_1      17608 non-null  int64
 280  M44_8      17608 non-null  int64
 281  M44_<NA>   17608 non-null  int64
 282  M45_0      17608 non-null  int64
 283  M45_1      17608 non-null  int64
 284  M45_8      17608 non-null  int64
 285  M45_<NA>   17608 non-null  int64
 286  M47_0      17608 non-null  int64
 287  M47_1      17608 non-null  int64
 288  M47_8      17608 non-null  int64
 289  M47_<NA>   17608 non-null  int64
 290  M48_0      17608 non-null  int64
 291  M48_1      17608 non-null  int64
 292  M48_8      17608 non-null  int64
 293  M48_<NA>   17608 non-null  int64
 294  M55A_0     17608 non-null  int64
 295  M55A_1     17608 non-null  int64
 296  M55A_8     17608 non-null  int64
 297  M55B_0     17608 non-null  int64
 298  M55B_1     17608 non-null  int64
 299  M55B_8     17608 non-null  int64
 300  M55C_0     17608 non-null  int64
 301  M55C_1     17608 non-null  int64
 302  M55C_8     17608 non-null  int64
 303  M55E_0     17608 non-null  int64
 304  M55E_1     17608 non-null  int64
 305  M55E_8     17608 non-null  int64
 306  M55F_0     17608 non-null  int64
 307  M55F_1     17608 non-null  int64
 308  M55F_8     17608 non-null  int64
 309  M55G_0     17608 non-null  int64
 310  M55G_1     17608 non-null  int64
 311  M55G_8     17608 non-null  int64
 312  M55H_0     17608 non-null  int64
 313  M55H_1     17608 non-null  int64
 314  M55H_8     17608 non-null  int64
 315  M55I_0     17608 non-null  int64
 316  M55I_1     17608 non-null  int64
 317  M55I_8     17608 non-null  int64
 318  M55X_0     17608 non-null  int64
 319  M55X_1     17608 non-null  int64
 320  M55X_8     17608 non-null  int64
 321  M55Z_0     17608 non-null  int64
 322  M55Z_1     17608 non-null  int64
 323  M55Z_8     17608 non-null  int64
 324  M60_0      17608 non-null  int64
 325  M60_1      17608 non-null  int64
 326  M60_8      17608 non-null  int64
 327  M60_<NA>   17608 non-null  int64
 328  M67_100    17608 non-null  int64
 329  M67_101    17608 non-null  int64
 330  M67_102    17608 non-null  int64
 331  M67_103    17608 non-null  int64
 332  M67_104    17608 non-null  int64
 333  M67_105    17608 non-null  int64
 334  M67_106    17608 non-null  int64
 335  M67_107    17608 non-null  int64
 336  M67_108    17608 non-null  int64
 337  M67_109    17608 non-null  int64
 338  M67_110    17608 non-null  int64
 339  M67_111    17608 non-null  int64
 340  M67_112    17608 non-null  int64
 341  M67_113    17608 non-null  int64
 342  M67_114    17608 non-null  int64
 343  M67_115    17608 non-null  int64
 344  M67_116    17608 non-null  int64
 345  M67_117    17608 non-null  int64
 346  M67_118    17608 non-null  int64
 347  M67_119    17608 non-null  int64
 348  M67_120    17608 non-null  int64
 349  M67_121    17608 non-null  int64
 350  M67_122    17608 non-null  int64
 351  M67_123    17608 non-null  int64
 352  M67_201    17608 non-null  int64
 353  M67_202    17608 non-null  int64
 354  M67_203    17608 non-null  int64
 355  M67_204    17608 non-null  int64
 356  M67_205    17608 non-null  int64
 357  M67_206    17608 non-null  int64
 358  M67_207    17608 non-null  int64
 359  M67_209    17608 non-null  int64
 360  M67_214    17608 non-null  int64
 361  M67_215    17608 non-null  int64
 362  M67_301    17608 non-null  int64
 363  M67_302    17608 non-null  int64
 364  M67_303    17608 non-null  int64
 365  M67_304    17608 non-null  int64
 366  M67_<NA>   17608 non-null  int64
 367  M68_11     17608 non-null  int64
 368  M68_12     17608 non-null  int64
 369  M68_13     17608 non-null  int64
 370  M68_14     17608 non-null  int64
 371  M68_15     17608 non-null  int64
 372  M68_21     17608 non-null  int64
 373  M68_96     17608 non-null  int64
 374  M68_<NA>   17608 non-null  int64
 375  M69_11     17608 non-null  int64
 376  M69_12     17608 non-null  int64
 377  M69_21     17608 non-null  int64
 378  M69_22     17608 non-null  int64
 379  M69_23     17608 non-null  int64
 380  M69_24     17608 non-null  int64
 381  M69_25     17608 non-null  int64
 382  M69_26     17608 non-null  int64
 383  M69_27     17608 non-null  int64
 384  M69_31     17608 non-null  int64
 385  M69_32     17608 non-null  int64
 386  M69_41     17608 non-null  int64
 387  M69_42     17608 non-null  int64
 388  M69_96     17608 non-null  int64
 389  M69_<NA>   17608 non-null  int64
 390  M70_0      17608 non-null  int64
 391  M70_1      17608 non-null  int64
 392  M70_8      17608 non-null  int64
 393  M70_<NA>   17608 non-null  int64
 394  M71_100    17608 non-null  int64
 395  M71_101    17608 non-null  int64
 396  M71_102    17608 non-null  int64
 397  M71_103    17608 non-null  int64
 398  M71_104    17608 non-null  int64
 399  M71_105    17608 non-null  int64
 400  M71_106    17608 non-null  int64
 401  M71_107    17608 non-null  int64
 402  M71_108    17608 non-null  int64
 403  M71_109    17608 non-null  int64
 404  M71_110    17608 non-null  int64
 405  M71_111    17608 non-null  int64
 406  M71_112    17608 non-null  int64
 407  M71_113    17608 non-null  int64
 408  M71_114    17608 non-null  int64
 409  M71_115    17608 non-null  int64
 410  M71_116    17608 non-null  int64
 411  M71_117    17608 non-null  int64
 412  M71_118    17608 non-null  int64
 413  M71_119    17608 non-null  int64
 414  M71_120    17608 non-null  int64
 415  M71_121    17608 non-null  int64
 416  M71_122    17608 non-null  int64
 417  M71_123    17608 non-null  int64
 418  M71_201    17608 non-null  int64
 419  M71_202    17608 non-null  int64
 420  M71_203    17608 non-null  int64
 421  M71_204    17608 non-null  int64
 422  M71_205    17608 non-null  int64
 423  M71_206    17608 non-null  int64
 424  M71_207    17608 non-null  int64
 425  M71_208    17608 non-null  int64
 426  M71_209    17608 non-null  int64
 427  M71_212    17608 non-null  int64
 428  M71_213    17608 non-null  int64
 429  M71_214    17608 non-null  int64
 430  M71_215    17608 non-null  int64
 431  M71_301    17608 non-null  int64
 432  M71_302    17608 non-null  int64
 433  M71_303    17608 non-null  int64
 434  M71_304    17608 non-null  int64
 435  M71_312    17608 non-null  int64
 436  M71_999    17608 non-null  int64
 437  M71_<NA>   17608 non-null  int64
 438  M72_11     17608 non-null  int64
 439  M72_12     17608 non-null  int64
 440  M72_13     17608 non-null  int64
 441  M72_14     17608 non-null  int64
 442  M72_15     17608 non-null  int64
 443  M72_21     17608 non-null  int64
 444  M72_96     17608 non-null  int64
 445  M72_<NA>   17608 non-null  int64
 446  M73_11     17608 non-null  int64
 447  M73_12     17608 non-null  int64
 448  M73_21     17608 non-null  int64
 449  M73_22     17608 non-null  int64
 450  M73_23     17608 non-null  int64
 451  M73_24     17608 non-null  int64
 452  M73_25     17608 non-null  int64
 453  M73_26     17608 non-null  int64
 454  M73_27     17608 non-null  int64
 455  M73_31     17608 non-null  int64
 456  M73_32     17608 non-null  int64
 457  M73_42     17608 non-null  int64
 458  M73_96     17608 non-null  int64
 459  M73_<NA>   17608 non-null  int64
 460  M6         17608 non-null  float64
 461  M7         17608 non-null  float64
 462  M8         17608 non-null  float64
 463  M9         17608 non-null  float64
 464  M11        5634 non-null   Float64
 465  M13        17426 non-null  Float64
 466  M14        17608 non-null  Float64
dtypes: Float64(3), Int64(22), float64(4), int64(437), object(1)
memory usage: 63.2+ MB

In [51]:
import os
# output_path = r"C:\Users\linoc\OneDrive\Encoder\03_partos\03_bases_intermediarios\Modulo1633_REC41_2024_fil.csv"
# Modulo1633_REC41_2024_fil.to_csv(output_path, index=False, encoding='utf-8-sig')

# File name only
output_file = "Modulo1633_REC41_2024_fil.csv"

# Go one level up from the current working directory
base_dir = os.path.dirname(os.getcwd())   # gives "c:\\Users\\linoc\\OneDrive\\Encoder\\03_partos"
output_dir = os.path.join(base_dir, "03_bases_intermediarios")

#Full path
output_path = os.path.join(output_dir, output_file)

# Save DataFrame
Modulo1633_REC41_2024_fil.to_csv(output_path, index=False, encoding="utf-8-sig")

### 2.2.1 Modulo1633_REC94_2024

In [52]:

Modulo1633_REC94_2024_M = convert_objects_to_int64_safe(Modulo1633_REC94_2024)
Modulo1633_REC94_2024_M.info(verbose = True, show_counts = True)

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 19751 entries, 0 to 19750
Data columns (total 61 columns):
 #   Column    Non-Null Count  Dtype
---  ------    --------------  -----
 0   ID1       19751 non-null  int64
 1   CASEID    19751 non-null  object
 2   IDX94     19751 non-null  int64
 3   S410B     17334 non-null  Int64
 4   S411B     17426 non-null  Int64
 5   S411F     17426 non-null  Int64
 6   S411G     17426 non-null  Int64
 7   S411H     17426 non-null  Int64
 8   S411I     17426 non-null  Int64
 9   S411J     17426 non-null  Int64
 10  S411K     17426 non-null  Int64
 11  S411L     17426 non-null  Int64
 12  S411BA    17054 non-null  Int64
 13  S411CA    17141 non-null  Int64
 14  S411DA    15366 non-null  Int64
 15  S411EA    16355 non-null  Int64
 16  S413      17608 non-null  Int64
 17  S422I     16727 non-null  Int64
 18  S426B     5993 non-null   Int64
 19  S426E     6957 non-null   Int64
 20  S426FA    0 non-null      Int64
 21  S426FB    15273 non-null  Int64
 22  S426GA    17608 non-null  Int64
 23  S426GB    17608 non-null  Int64
 24  S426GC    17608 non-null  Int64
 25  S426GD    17608 non-null  Int64
 26  S426GE    17608 non-null  Int64
 27  S430C     19751 non-null  int64
 28  S430D     17431 non-null  Int64
 29  S431A     16586 non-null  Int64
 30  S425A     0 non-null      Int64
 31  S432      19751 non-null  int64
 32  S432AD    0 non-null      Int64
 33  S432AM    0 non-null      Int64
 34  S432AY    0 non-null      Int64
 35  S427DA    17608 non-null  Int64
 36  S427DB    17608 non-null  Int64
 37  S427DC    17608 non-null  Int64
 38  S427DD    17608 non-null  Int64
 39  S427DE    17608 non-null  Int64
 40  S427DF    17608 non-null  Int64
 41  S427DG    17608 non-null  Int64
 42  S427F     5569 non-null   Int64
 43  S435      190 non-null    Int64
 44  S436C     19561 non-null  Int64
 45  S440      11894 non-null  Int64
 46  S441      19751 non-null  int64
 47  S442      14237 non-null  Int64
 48  S446AA    0 non-null      Int64
 49  S446AB    0 non-null      Int64
 50  S446A     0 non-null      Int64
 51  S447      19582 non-null  Int64
 52  S448A     0 non-null      Int64
 53  S448B     0 non-null      Int64
 54  QI411_M   17426 non-null  Int64
 55  QI411F    14576 non-null  Int64
 56  QI422A_A  17608 non-null  Int64
 57  QI422A_B  16949 non-null  Int64
 58  QI422A_C  4900 non-null   Int64
 59  QI422A_D  4741 non-null   Int64
 60  QI440B    10483 non-null  Int64
dtypes: Int64(55), int64(5), object(1)
memory usage: 10.2+ MB

In [53]:
dummy_variables_REC94  = get_dummy_variables(Modulo1633_REC94_2024_M)
Modulo1633_REC94_2024_M[dummy_variables_REC94].describe().T

          count      mean       std  min  25%  50%  75%  max
S413    17608.0  0.809121  0.393005  0.0  1.0  1.0  1.0  1.0
S426E    6957.0  0.424608  0.494319  0.0  0.0  0.0  1.0  1.0
S426GA  17608.0  0.104498  0.305914  0.0  0.0  0.0  0.0  1.0
S426GB  17608.0  0.089334  0.285234  0.0  0.0  0.0  0.0  1.0
S426GC  17608.0  0.018458  0.134603  0.0  0.0  0.0  0.0  1.0
S426GD  17608.0  0.009144  0.095187  0.0  0.0  0.0  0.0  1.0
S426GE  17608.0  0.048898  0.215661  0.0  0.0  0.0  0.0  1.0
S430D   17431.0  0.998738  0.035505  0.0  1.0  1.0  1.0  1.0
S427DA  17608.0  0.045264  0.207887  0.0  0.0  0.0  0.0  1.0
S427DB  17608.0  0.020275  0.140943  0.0  0.0  0.0  0.0  1.0
S427DC  17608.0  0.129941  0.336248  0.0  0.0  0.0  0.0  1.0
S427DD  17608.0  0.112279  0.315718  0.0  0.0  0.0  0.0  1.0
S427DE  17608.0   0.13704  0.343899  0.0  0.0  0.0  0.0  1.0
S427DF  17608.0  0.055089   0.22816  0.0  0.0  0.0  0.0  1.0
S427DG  17608.0  0.061393  0.240056  0.0  0.0  0.0  0.0  1.0
S427F    5569.0  0.559346   0.49651  0.0  0.0  1.0  1.0  1.0
S436C   19561.0  0.563621  0.495948  0.0  0.0  1.0  1.0  1.0
S441    19751.0  0.720824  0.448605  0.0  0.0  1.0  1.0  1.0

In [54]:
df_dummy_variables_REC94 = aggregate_sum_by_caseid(Modulo1633_REC94_2024_M[dummy_variables_REC94 + ['CASEID']])
df_dummy_variables_REC94.describe().T

          count      mean       std  min  25%  50%  75%  max
S413    17608.0  0.809121  0.393005  0.0  1.0  1.0  1.0  1.0
S426E   17608.0  0.167765  0.405591  0.0  0.0  0.0  0.0  3.0
S426GA  17608.0  0.104498  0.305914  0.0  0.0  0.0  0.0  1.0
S426GB  17608.0  0.089334  0.285234  0.0  0.0  0.0  0.0  1.0
S426GC  17608.0  0.018458  0.134603  0.0  0.0  0.0  0.0  1.0
S426GD  17608.0  0.009144  0.095187  0.0  0.0  0.0  0.0  1.0
S426GE  17608.0  0.048898  0.215661  0.0  0.0  0.0  0.0  1.0
S430D   17608.0  0.988698    0.4492  0.0  1.0  1.0  1.0  3.0
S427DA  17608.0  0.045264  0.207887  0.0  0.0  0.0  0.0  1.0
S427DB  17608.0  0.020275  0.140943  0.0  0.0  0.0  0.0  1.0
S427DC  17608.0  0.129941  0.336248  0.0  0.0  0.0  0.0  1.0
S427DD  17608.0  0.112279  0.315718  0.0  0.0  0.0  0.0  1.0
S427DE  17608.0   0.13704  0.343899  0.0  0.0  0.0  0.0  1.0
S427DF  17608.0  0.055089   0.22816  0.0  0.0  0.0  0.0  1.0
S427DG  17608.0  0.061393  0.240056  0.0  0.0  0.0  0.0  1.0
S427F   17608.0  0.176908  0.381602  0.0  0.0  0.0  0.0  1.0
S436C   17608.0  0.626136  0.583459  0.0  0.0  1.0  1.0  3.0
S441    17608.0  0.808553  0.551316  0.0  0.0  1.0  1.0  4.0

In [55]:
no_dummy_REC94 = drop_null_and_list(Modulo1633_REC94_2024_M, dummy_variables_REC94)
no_dummy_list_REC94 =no_dummy_REC94.columns.to_list()
remove_items = {"S411BA","S411CA","S411DA","S411EA","S422I"}
no_dummy_list = [col for col in no_dummy_list if col not in remove_items]

In [56]:
df_no_dummy_list_REC94 = aggregate_with_value_suffix(Modulo1633_REC94_2024_M[no_dummy_list_REC94], caseid_col="CASEID")
df_no_dummy_list_REC94.describe().T

                 count      mean       std  min  25%  50%  75%  max
ID1_2024       17608.0  1.121706  0.342896  1.0  1.0  1.0  1.0  4.0
IDX94_1        17608.0  1.000000  0.000000  1.0  1.0  1.0  1.0  1.0
IDX94_2        17608.0  0.116538  0.320878  0.0  0.0  0.0  0.0  1.0
IDX94_3        17608.0  0.004998  0.070520  0.0  0.0  0.0  0.0  1.0
IDX94_4        17608.0  0.000170  0.013052  0.0  0.0  0.0  0.0  1.0
S410B_1        17608.0  0.000114  0.010657  0.0  0.0  0.0  0.0  1.0
S410B_2        17608.0  0.000170  0.013052  0.0  0.0  0.0  0.0  1.0
S410B_3        17608.0  0.000341  0.018457  0.0  0.0  0.0  0.0  1.0
S410B_4        17608.0  0.001079  0.032832  0.0  0.0  0.0  0.0  1.0
S410B_5        17608.0  0.003635  0.060181  0.0  0.0  0.0  0.0  1.0
S410B_6        17608.0  0.010279  0.100868  0.0  0.0  0.0  0.0  1.0
S410B_7        17608.0  0.035268  0.184462  0.0  0.0  0.0  0.0  1.0
S410B_8        17608.0  0.251761  0.434037  0.0  0.0  0.0  1.0  1.0
S410B_9        17608.0  0.681508  0.465905  0.0  0.0  1.0  1.0  1.0
S410B_98       17608.0  0.000284  0.016849  0.0  0.0  0.0  0.0  1.0
S410B_<NA>     17608.0  0.137267  0.371442  0.0  0.0  0.0  0.0  4.0
S411B_0        17608.0  0.005906  0.076628  0.0  0.0  0.0  0.0  1.0
S411B_1        17608.0  0.983360  0.127923  0.0  1.0  1.0  1.0  1.0
S411B_8        17608.0  0.000398  0.019935  0.0  0.0  0.0  0.0  1.0
S411B_<NA>     17608.0  0.132042  0.362526  0.0  0.0  0.0  0.0  3.0
S411F_0        17608.0  0.002840  0.053214  0.0  0.0  0.0  0.0  1.0
S411F_1        17608.0  0.986483  0.115476  0.0  1.0  1.0  1.0  1.0
S411F_8        17608.0  0.000341  0.018457  0.0  0.0  0.0  0.0  1.0
S411F_<NA>     17608.0  0.132042  0.362526  0.0  0.0  0.0  0.0  3.0
S411G_0        17608.0  0.065709  0.247779  0.0  0.0  0.0  0.0  1.0
S411G_1        17608.0  0.872672  0.333350  0.0  1.0  1.0  1.0  1.0
S411G_8        17608.0  0.051284  0.220582  0.0  0.0  0.0  0.0  1.0
S411G_<NA>     17608.0  0.132042  0.362526  0.0  0.0  0.0  0.0  3.0
S411H_0        17608.0  0.039073  0.193775  0.0  0.0  0.0  0.0  1.0
S411H_1        17608.0  0.928839  0.257101  0.0  1.0  1.0  1.0  1.0
S411H_8        17608.0  0.021751  0.145875  0.0  0.0  0.0  0.0  1.0
S411H_<NA>     17608.0  0.132042  0.362526  0.0  0.0  0.0  0.0  3.0
S411I_0        17608.0  0.036177  0.186735  0.0  0.0  0.0  0.0  1.0
S411I_1        17608.0  0.953146  0.211331  0.0  1.0  1.0  1.0  1.0
S411I_8        17608.0  0.000341  0.018457  0.0  0.0  0.0  0.0  1.0
S411I_<NA>     17608.0  0.132042  0.362526  0.0  0.0  0.0  0.0  3.0
S411J_0        17608.0  0.144423  0.351528  0.0  0.0  0.0  0.0  1.0
S411J_1        17608.0  0.843764  0.363089  0.0  1.0  1.0  1.0  1.0
S411J_8        17608.0  0.001477  0.038399  0.0  0.0  0.0  0.0  1.0
S411J_<NA>     17608.0  0.132042  0.362526  0.0  0.0  0.0  0.0  3.0
S411K_0        17608.0  0.272774  0.445398  0.0  0.0  0.0  1.0  1.0
S411K_1        17608.0  0.716265  0.450822  0.0  0.0  1.0  1.0  1.0
S411K_8        17608.0  0.000625  0.024987  0.0  0.0  0.0  0.0  1.0
S411K_<NA>     17608.0  0.132042  0.362526  0.0  0.0  0.0  0.0  3.0
S411L_0        17608.0  0.267946  0.442902  0.0  0.0  0.0  1.0  1.0
S411L_1        17608.0  0.721433  0.448306  0.0  0.0  1.0  1.0  1.0
S411L_8        17608.0  0.000284  0.016849  0.0  0.0  0.0  0.0  1.0
S411L_<NA>     17608.0  0.132042  0.362526  0.0  0.0  0.0  0.0  3.0
S411BA_0       17608.0  0.001647  0.040551  0.0  0.0  0.0  0.0  1.0
S411BA_1       17608.0  0.115402  0.319516  0.0  0.0  0.0  0.0  1.0
S411BA_2       17608.0  0.237562  0.425602  0.0  0.0  0.0  0.0  1.0
S411BA_3       17608.0  0.281804  0.449891  0.0  0.0  0.0  1.0  1.0
S411BA_4       17608.0  0.142038  0.349099  0.0  0.0  0.0  0.0  1.0
S411BA_5       17608.0  0.086779  0.281519  0.0  0.0  0.0  0.0  1.0
S411BA_6       17608.0  0.061620  0.240470  0.0  0.0  0.0  0.0  1.0
S411BA_7       17608.0  0.025500  0.157642  0.0  0.0  0.0  0.0  1.0
S411BA_8       17608.0  0.011529  0.106755  0.0  0.0  0.0  0.0  1.0
S411BA_9       17608.0  0.001590  0.039847  0.0  0.0  0.0  0.0  1.0
S411BA_98      17608.0  0.003067  0.055295  0.0  0.0  0.0  0.0  1.0
S411BA_<NA>    17608.0  0.153169  0.389991  0.0  0.0  0.0  0.0  3.0
S411CA_0       17608.0  0.001477  0.038399  0.0  0.0  0.0  0.0  1.0
S411CA_1       17608.0  0.114721  0.318693  0.0  0.0  0.0  0.0  1.0
S411CA_2       17608.0  0.229157  0.420303  0.0  0.0  0.0  0.0  1.0
S411CA_3       17608.0  0.277885  0.447969  0.0  0.0  0.0  1.0  1.0
S411CA_4       17608.0  0.146354  0.353471  0.0  0.0  0.0  0.0  1.0
S411CA_5       17608.0  0.091663  0.288558  0.0  0.0  0.0  0.0  1.0
S411CA_6       17608.0  0.065538  0.247480  0.0  0.0  0.0  0.0  1.0
S411CA_7       17608.0  0.027885  0.164648  0.0  0.0  0.0  0.0  1.0
S411CA_8       17608.0  0.013005  0.113301  0.0  0.0  0.0  0.0  1.0
S411CA_9       17608.0  0.001988  0.044541  0.0  0.0  0.0  0.0  1.0
S411CA_98      17608.0  0.003805  0.061570  0.0  0.0  0.0  0.0  1.0
S411CA_<NA>    17608.0  0.148228  0.385687  0.0  0.0  0.0  0.0  3.0
S411DA_0       17608.0  0.001022  0.031957  0.0  0.0  0.0  0.0  1.0
S411DA_1       17608.0  0.085984  0.280348  0.0  0.0  0.0  0.0  1.0
S411DA_2       17608.0  0.187528  0.390346  0.0  0.0  0.0  0.0  1.0
S411DA_3       17608.0  0.234836  0.423909  0.0  0.0  0.0  0.0  1.0
S411DA_4       17608.0  0.133405  0.340022  0.0  0.0  0.0  0.0  1.0
S411DA_5       17608.0  0.091152  0.287833  0.0  0.0  0.0  0.0  1.0
S411DA_6       17608.0  0.070025  0.255196  0.0  0.0  0.0  0.0  1.0
S411DA_7       17608.0  0.032883  0.178335  0.0  0.0  0.0  0.0  1.0
S411DA_8       17608.0  0.016527  0.127493  0.0  0.0  0.0  0.0  1.0
S411DA_9       17608.0  0.002556  0.050490  0.0  0.0  0.0  0.0  1.0
S411DA_98      17608.0  0.016754  0.128351  0.0  0.0  0.0  0.0  1.0
S411DA_<NA>    17608.0  0.249035  0.482380  0.0  0.0  0.0  0.0  3.0
S411EA_0       17608.0  0.000909  0.030131  0.0  0.0  0.0  0.0  1.0
S411EA_1       17608.0  0.092288  0.289440  0.0  0.0  0.0  0.0  1.0
S411EA_2       17608.0  0.197865  0.398401  0.0  0.0  0.0  0.0  1.0
S411EA_3       17608.0  0.245797  0.430571  0.0  0.0  0.0  0.0  1.0
S411EA_4       17608.0  0.142719  0.349796  0.0  0.0  0.0  0.0  1.0
S411EA_5       17608.0  0.098421  0.297892  0.0  0.0  0.0  0.0  1.0
S411EA_6       17608.0  0.076045  0.265078  0.0  0.0  0.0  0.0  1.0
S411EA_7       17608.0  0.037313  0.189532  0.0  0.0  0.0  0.0  1.0
S411EA_8       17608.0  0.021524  0.145128  0.0  0.0  0.0  0.0  1.0
S411EA_9       17608.0  0.003975  0.062928  0.0  0.0  0.0  0.0  1.0
S411EA_98      17608.0  0.011983  0.108813  0.0  0.0  0.0  0.0  1.0
S411EA_<NA>    17608.0  0.192867  0.432863  0.0  0.0  0.0  0.0  3.0
S422I_0        17608.0  0.901863  0.297509  0.0  1.0  1.0  1.0  1.0
S422I_1        17608.0  0.010223  0.100592  0.0  0.0  0.0  0.0  1.0
S422I_10       17608.0  0.000795  0.028187  0.0  0.0  0.0  0.0  1.0
S422I_12       17608.0  0.000341  0.018457  0.0  0.0  0.0  0.0  1.0
S422I_14       17608.0  0.000057  0.007536  0.0  0.0  0.0  0.0  1.0
S422I_15       17608.0  0.000227  0.015071  0.0  0.0  0.0  0.0  1.0
S422I_16       17608.0  0.000114  0.010657  0.0  0.0  0.0  0.0  1.0
S422I_18       17608.0  0.000057  0.007536  0.0  0.0  0.0  0.0  1.0
S422I_2        17608.0  0.011870  0.108302  0.0  0.0  0.0  0.0  1.0
S422I_20       17608.0  0.000114  0.010657  0.0  0.0  0.0  0.0  1.0
S422I_24       17608.0  0.000057  0.007536  0.0  0.0  0.0  0.0  1.0
S422I_3        17608.0  0.010677  0.102779  0.0  0.0  0.0  0.0  1.0
S422I_30       17608.0  0.000170  0.013052  0.0  0.0  0.0  0.0  1.0
S422I_36       17608.0  0.000057  0.007536  0.0  0.0  0.0  0.0  1.0
S422I_4        17608.0  0.003124  0.055803  0.0  0.0  0.0  0.0  1.0
S422I_5        17608.0  0.001817  0.042593  0.0  0.0  0.0  0.0  1.0
S422I_6        17608.0  0.002215  0.047012  0.0  0.0  0.0  0.0  1.0
S422I_60       17608.0  0.000114  0.010657  0.0  0.0  0.0  0.0  1.0
S422I_7        17608.0  0.000965  0.031058  0.0  0.0  0.0  0.0  1.0
S422I_8        17608.0  0.001647  0.040551  0.0  0.0  0.0  0.0  1.0
S422I_80       17608.0  0.000057  0.007536  0.0  0.0  0.0  0.0  1.0
S422I_9        17608.0  0.000284  0.016849  0.0  0.0  0.0  0.0  1.0
S422I_98       17608.0  0.003124  0.055803  0.0  0.0  0.0  0.0  1.0
S422I_<NA>     17608.0  0.171740  0.412825  0.0  0.0  0.0  0.0  3.0
S426B_11       17608.0  0.002953  0.065633  0.0  0.0  0.0  0.0  2.0
S426B_12       17608.0  0.013573  0.132209  0.0  0.0  0.0  0.0  3.0
S426B_13       17608.0  0.004771  0.069726  0.0  0.0  0.0  0.0  2.0
S426B_14       17608.0  0.177590  0.413307  0.0  0.0  0.0  0.0  4.0
S426B_15       17608.0  0.012267  0.115123  0.0  0.0  0.0  0.0  2.0
S426B_16       17608.0  0.002556  0.054805  0.0  0.0  0.0  0.0  2.0
S426B_17       17608.0  0.004827  0.070933  0.0  0.0  0.0  0.0  2.0
S426B_18       17608.0  0.019764  0.176279  0.0  0.0  0.0  0.0  4.0
S426B_19       17608.0  0.000795  0.030135  0.0  0.0  0.0  0.0  2.0
S426B_20       17608.0  0.056906  0.244318  0.0  0.0  0.0  0.0  2.0
S426B_21       17608.0  0.001136  0.035330  0.0  0.0  0.0  0.0  2.0
S426B_22       17608.0  0.004203  0.064693  0.0  0.0  0.0  0.0  1.0
S426B_23       17608.0  0.001193  0.036123  0.0  0.0  0.0  0.0  2.0
S426B_24       17608.0  0.008235  0.091001  0.0  0.0  0.0  0.0  2.0
S426B_25       17608.0  0.016867  0.133115  0.0  0.0  0.0  0.0  2.0
S426B_96       17608.0  0.012721  0.116056  0.0  0.0  0.0  0.0  2.0
S426B_<NA>     17608.0  0.781349  0.567888  0.0  0.0  1.0  1.0  3.0
S426FB_100     17608.0  0.753067  0.556785  0.0  0.0  1.0  1.0  3.0
S426FB_101     17608.0  0.075875  0.270953  0.0  0.0  0.0  0.0  2.0
S426FB_102     17608.0  0.022774  0.151827  0.0  0.0  0.0  0.0  2.0
S426FB_103     17608.0  0.008008  0.090395  0.0  0.0  0.0  0.0  2.0
S426FB_104     17608.0  0.002953  0.056319  0.0  0.0  0.0  0.0  2.0
S426FB_105     17608.0  0.001647  0.040551  0.0  0.0  0.0  0.0  1.0
S426FB_106     17608.0  0.000625  0.024987  0.0  0.0  0.0  0.0  1.0
S426FB_107     17608.0  0.000057  0.007536  0.0  0.0  0.0  0.0  1.0
S426FB_108     17608.0  0.000852  0.029175  0.0  0.0  0.0  0.0  1.0
S426FB_110     17608.0  0.000284  0.016849  0.0  0.0  0.0  0.0  1.0
S426FB_113     17608.0  0.000057  0.007536  0.0  0.0  0.0  0.0  1.0
S426FB_115     17608.0  0.000170  0.013052  0.0  0.0  0.0  0.0  1.0
S426FB_116     17608.0  0.000057  0.007536  0.0  0.0  0.0  0.0  1.0
S426FB_120     17608.0  0.000114  0.010657  0.0  0.0  0.0  0.0  1.0
S426FB_201     17608.0  0.000057  0.007536  0.0  0.0  0.0  0.0  1.0
S426FB_202     17608.0  0.000057  0.007536  0.0  0.0  0.0  0.0  1.0
S426FB_203     17608.0  0.000057  0.007536  0.0  0.0  0.0  0.0  1.0
S426FB_304     17608.0  0.000057  0.007536  0.0  0.0  0.0  0.0  1.0
S426FB_998     17608.0  0.000625  0.024987  0.0  0.0  0.0  0.0  1.0
S426FB_<NA>    17608.0  0.254316  0.489753  0.0  0.0  0.0  0.0  4.0
S430C_0        17608.0  0.016527  0.137357  0.0  0.0  0.0  0.0  3.0
S430C_1        17608.0  0.989948  0.448470  0.0  1.0  1.0  1.0  3.0
S430C_2        17608.0  0.115175  0.347031  0.0  0.0  0.0  0.0  4.0
S430C_8        17608.0  0.000057  0.007536  0.0  0.0  0.0  0.0  1.0
S431A_0        17608.0  0.598421  0.490231  0.0  0.0  1.0  1.0  1.0
S431A_1        17608.0  0.329850  0.470172  0.0  0.0  0.0  1.0  1.0
S431A_8        17608.0  0.013687  0.116191  0.0  0.0  0.0  0.0  1.0
S431A_<NA>     17608.0  0.179748  0.433195  0.0  0.0  0.0  0.0  4.0
S432_0         17608.0  0.264596  0.488422  0.0  0.0  0.0  0.0  4.0
S432_1         17608.0  0.856259  0.558153  0.0  1.0  1.0  1.0  4.0
S432_8         17608.0  0.000852  0.031061  0.0  0.0  0.0  0.0  2.0
S435_1         17608.0  0.001590  0.041247  0.0  0.0  0.0  0.0  2.0
S435_2         17608.0  0.002045  0.049948  0.0  0.0  0.0  0.0  3.0
S435_3         17608.0  0.003124  0.055803  0.0  0.0  0.0  0.0  1.0
S435_4         17608.0  0.001079  0.032832  0.0  0.0  0.0  0.0  1.0
S435_5         17608.0  0.000398  0.019935  0.0  0.0  0.0  0.0  1.0
S435_6         17608.0  0.001647  0.041928  0.0  0.0  0.0  0.0  2.0
S435_7         17608.0  0.000114  0.010657  0.0  0.0  0.0  0.0  1.0
S435_8         17608.0  0.000341  0.018457  0.0  0.0  0.0  0.0  1.0
S435_96        17608.0  0.000454  0.021311  0.0  0.0  0.0  0.0  1.0
S435_<NA>      17608.0  1.110915  0.346373  0.0  1.0  1.0  1.0  4.0
S440_1         17608.0  0.038448  0.195794  0.0  0.0  0.0  0.0  2.0
S440_10        17608.0  0.043446  0.209091  0.0  0.0  0.0  0.0  2.0
S440_11        17608.0  0.000398  0.019935  0.0  0.0  0.0  0.0  1.0
S440_12        17608.0  0.140731  0.355347  0.0  0.0  0.0  0.0  3.0
S440_2         17608.0  0.015902  0.127349  0.0  0.0  0.0  0.0  2.0
S440_3         17608.0  0.004259  0.067693  0.0  0.0  0.0  0.0  2.0
S440_4         17608.0  0.003237  0.056806  0.0  0.0  0.0  0.0  1.0
S440_5         17608.0  0.004941  0.072509  0.0  0.0  0.0  0.0  2.0
S440_6         17608.0  0.051908  0.233814  0.0  0.0  0.0  0.0  3.0
S440_7         17608.0  0.063323  0.248857  0.0  0.0  0.0  0.0  2.0
S440_8         17608.0  0.058155  0.237895  0.0  0.0  0.0  0.0  2.0
S440_9         17608.0  0.246252  0.441388  0.0  0.0  0.0  0.0  2.0
S440_96        17608.0  0.004487  0.066834  0.0  0.0  0.0  0.0  1.0
S440_<NA>      17608.0  0.446218  0.510083  0.0  0.0  0.0  1.0  4.0
S442_21        17608.0  0.071218  0.273671  0.0  0.0  0.0  0.0  3.0
S442_22        17608.0  0.074057  0.274576  0.0  0.0  0.0  0.0  2.0
S442_23        17608.0  0.002045  0.048798  0.0  0.0  0.0  0.0  2.0
S442_24        17608.0  0.333769  0.525676  0.0  0.0  0.0  1.0  3.0
S442_25        17608.0  0.244605  0.481585  0.0  0.0  0.0  0.0  4.0
S442_26        17608.0  0.033621  0.187364  0.0  0.0  0.0  0.0  2.0
S442_27        17608.0  0.000682  0.028190  0.0  0.0  0.0  0.0  2.0
S442_31        17608.0  0.035325  0.191847  0.0  0.0  0.0  0.0  2.0
S442_32        17608.0  0.006418  0.081960  0.0  0.0  0.0  0.0  2.0
S442_41        17608.0  0.000284  0.016849  0.0  0.0  0.0  0.0  1.0
S442_42        17608.0  0.001363  0.038403  0.0  0.0  0.0  0.0  2.0
S442_96        17608.0  0.005168  0.076310  0.0  0.0  0.0  0.0  2.0
S442_<NA>      17608.0  0.313153  0.521110  0.0  0.0  0.0  1.0  4.0
S447_0         17608.0  0.225977  0.435532  0.0  0.0  0.0  0.0  3.0
S447_1         17608.0  0.883860  0.500667  0.0  1.0  1.0  1.0  3.0
S447_8         17608.0  0.002272  0.047609  0.0  0.0  0.0  0.0  1.0
S447_<NA>      17608.0  0.009598  0.102054  0.0  0.0  0.0  0.0  3.0
QI411_M_1      17608.0  0.827806  0.377560  0.0  1.0  1.0  1.0  1.0
QI411_M_2      17608.0  0.103249  0.304292  0.0  0.0  0.0  0.0  1.0
QI411_M_8      17608.0  0.058610  0.234899  0.0  0.0  0.0  0.0  1.0
QI411_M_<NA>   17608.0  0.132042  0.362526  0.0  0.0  0.0  0.0  3.0
QI411F_0       17608.0  0.000795  0.028187  0.0  0.0  0.0  0.0  1.0
QI411F_1       17608.0  0.078033  0.268231  0.0  0.0  0.0  0.0  1.0
QI411F_2       17608.0  0.170207  0.375825  0.0  0.0  0.0  0.0  1.0
QI411F_3       17608.0  0.213937  0.410094  0.0  0.0  0.0  0.0  1.0
QI411F_4       17608.0  0.125398  0.331179  0.0  0.0  0.0  0.0  1.0
QI411F_5       17608.0  0.087687  0.282848  0.0  0.0  0.0  0.0  1.0
QI411F_6       17608.0  0.072751  0.259735  0.0  0.0  0.0  0.0  1.0
QI411F_7       17608.0  0.033678  0.180404  0.0  0.0  0.0  0.0  1.0
QI411F_8       17608.0  0.020672  0.142289  0.0  0.0  0.0  0.0  1.0
QI411F_9       17608.0  0.002726  0.052142  0.0  0.0  0.0  0.0  1.0
QI411F_98      17608.0  0.021922  0.146433  0.0  0.0  0.0  0.0  1.0
QI411F_<NA>    17608.0  0.293900  0.512471  0.0  0.0  0.0  1.0  3.0
QI422A_A_1     17608.0  0.962574  0.189809  0.0  1.0  1.0  1.0  1.0
QI422A_A_2     17608.0  0.034927  0.183601  0.0  0.0  0.0  0.0  1.0
QI422A_A_8     17608.0  0.002499  0.049928  0.0  0.0  0.0  0.0  1.0
QI422A_A_<NA>  17608.0  0.121706  0.342896  0.0  0.0  0.0  0.0  3.0
QI422A_B_1     17608.0  0.278283  0.448166  0.0  0.0  0.0  1.0  1.0
QI422A_B_2     17608.0  0.682871  0.465371  0.0  0.0  1.0  1.0  1.0
QI422A_B_8     17608.0  0.001420  0.037655  0.0  0.0  0.0  0.0  1.0
QI422A_B_<NA>  17608.0  0.159132  0.397507  0.0  0.0  0.0  0.0  4.0
QI422A_C_1     17608.0  0.269253  0.443584  0.0  0.0  0.0  1.0  1.0
QI422A_C_2     17608.0  0.008916  0.094007  0.0  0.0  0.0  0.0  1.0
QI422A_C_8     17608.0  0.000114  0.010657  0.0  0.0  0.0  0.0  1.0
QI422A_C_<NA>  17608.0  0.843423  0.554177  0.0  1.0  1.0  1.0  4.0
QI422A_D_1     17608.0  0.140845  0.347872  0.0  0.0  0.0  0.0  1.0
QI422A_D_2     17608.0  0.128351  0.334489  0.0  0.0  0.0  0.0  1.0
QI422A_D_8     17608.0  0.000057  0.007536  0.0  0.0  0.0  0.0  1.0
QI422A_D_<NA>  17608.0  0.852453  0.551472  0.0  1.0  1.0  1.0  4.0
QI440B_1       17608.0  0.445763  0.561552  0.0  0.0  0.0  1.0  3.0
QI440B_2       17608.0  0.149080  0.375581  0.0  0.0  0.0  0.0  3.0
QI440B_8       17608.0  0.000511  0.022603  0.0  0.0  0.0  0.0  1.0
QI440B_<NA>    17608.0  0.526352  0.561935  0.0  0.0  0.0  1.0  4.0

In [57]:
continue_var = list(remove_items)
df_continue_var = aggregate_by_caseid_mean(Modulo1633_REC94_2024_M[continue_var + ['CASEID']], caseid_col="CASEID")
df_continue_var.head()

               CASEID  S422I  S411CA  S411BA  S411EA  S411DA
0        325503101  2    0.0     2.0     2.0     2.0     2.0
1        325504701  2    0.0     4.0     4.0     4.0     4.0
2        325505001  1    0.0     2.0     2.0     2.0     2.0
3        325508901  2    0.0     1.0     1.0     1.0     1.0
4        325509701  2    0.0     3.0     3.0     3.0     3.0

In [58]:
Modulo1633_REC94_2024_fil = df_dummy_variables_REC94.merge(df_no_dummy_list_REC94, how='left', on='CASEID')
Modulo1633_REC94_2024_fil= Modulo1633_REC94_2024_fil.merge(df_continue_var, how ='left', on ='CASEID')
Modulo1633_REC94_2024_fil.info(verbose = True, show_counts = True)

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 17608 entries, 0 to 17607
Data columns (total 269 columns):
 #    Column         Non-Null Count  Dtype
---   ------         --------------  -----
 0    CASEID         17608 non-null  object
 1    S413           17608 non-null  Int64
 2    S426E          17608 non-null  Int64
 3    S426GA         17608 non-null  Int64
 4    S426GB         17608 non-null  Int64
 5    S426GC         17608 non-null  Int64
 6    S426GD         17608 non-null  Int64
 7    S426GE         17608 non-null  Int64
 8    S430D          17608 non-null  Int64
 9    S427DA         17608 non-null  Int64
 10   S427DB         17608 non-null  Int64
 11   S427DC         17608 non-null  Int64
 12   S427DD         17608 non-null  Int64
 13   S427DE         17608 non-null  Int64
 14   S427DF         17608 non-null  Int64
 15   S427DG         17608 non-null  Int64
 16   S427F          17608 non-null  Int64
 17   S436C          17608 non-null  Int64
 18   S441           17608 non-null  int64
 19   ID1_2024       17608 non-null  int64
 20   IDX94_1        17608 non-null  int64
 21   IDX94_2        17608 non-null  int64
 22   IDX94_3        17608 non-null  int64
 23   IDX94_4        17608 non-null  int64
 24   S410B_1        17608 non-null  int64
 25   S410B_2        17608 non-null  int64
 26   S410B_3        17608 non-null  int64
 27   S410B_4        17608 non-null  int64
 28   S410B_5        17608 non-null  int64
 29   S410B_6        17608 non-null  int64
 30   S410B_7        17608 non-null  int64
 31   S410B_8        17608 non-null  int64
 32   S410B_9        17608 non-null  int64
 33   S410B_98       17608 non-null  int64
 34   S410B_<NA>     17608 non-null  int64
 35   S411B_0        17608 non-null  int64
 36   S411B_1        17608 non-null  int64
 37   S411B_8        17608 non-null  int64
 38   S411B_<NA>     17608 non-null  int64
 39   S411F_0        17608 non-null  int64
 40   S411F_1        17608 non-null  int64
 41   S411F_8        17608 non-null  int64
 42   S411F_<NA>     17608 non-null  int64
 43   S411G_0        17608 non-null  int64
 44   S411G_1        17608 non-null  int64
 45   S411G_8        17608 non-null  int64
 46   S411G_<NA>     17608 non-null  int64
 47   S411H_0        17608 non-null  int64
 48   S411H_1        17608 non-null  int64
 49   S411H_8        17608 non-null  int64
 50   S411H_<NA>     17608 non-null  int64
 51   S411I_0        17608 non-null  int64
 52   S411I_1        17608 non-null  int64
 53   S411I_8        17608 non-null  int64
 54   S411I_<NA>     17608 non-null  int64
 55   S411J_0        17608 non-null  int64
 56   S411J_1        17608 non-null  int64
 57   S411J_8        17608 non-null  int64
 58   S411J_<NA>     17608 non-null  int64
 59   S411K_0        17608 non-null  int64
 60   S411K_1        17608 non-null  int64
 61   S411K_8        17608 non-null  int64
 62   S411K_<NA>     17608 non-null  int64
 63   S411L_0        17608 non-null  int64
 64   S411L_1        17608 non-null  int64
 65   S411L_8        17608 non-null  int64
 66   S411L_<NA>     17608 non-null  int64
 67   S411BA_0       17608 non-null  int64
 68   S411BA_1       17608 non-null  int64
 69   S411BA_2       17608 non-null  int64
 70   S411BA_3       17608 non-null  int64
 71   S411BA_4       17608 non-null  int64
 72   S411BA_5       17608 non-null  int64
 73   S411BA_6       17608 non-null  int64
 74   S411BA_7       17608 non-null  int64
 75   S411BA_8       17608 non-null  int64
 76   S411BA_9       17608 non-null  int64
 77   S411BA_98      17608 non-null  int64
 78   S411BA_<NA>    17608 non-null  int64
 79   S411CA_0       17608 non-null  int64
 80   S411CA_1       17608 non-null  int64
 81   S411CA_2       17608 non-null  int64
 82   S411CA_3       17608 non-null  int64
 83   S411CA_4       17608 non-null  int64
 84   S411CA_5       17608 non-null  int64
 85   S411CA_6       17608 non-null  int64
 86   S411CA_7       17608 non-null  int64
 87   S411CA_8       17608 non-null  int64
 88   S411CA_9       17608 non-null  int64
 89   S411CA_98      17608 non-null  int64
 90   S411CA_<NA>    17608 non-null  int64
 91   S411DA_0       17608 non-null  int64
 92   S411DA_1       17608 non-null  int64
 93   S411DA_2       17608 non-null  int64
 94   S411DA_3       17608 non-null  int64
 95   S411DA_4       17608 non-null  int64
 96   S411DA_5       17608 non-null  int64
 97   S411DA_6       17608 non-null  int64
 98   S411DA_7       17608 non-null  int64
 99   S411DA_8       17608 non-null  int64
 100  S411DA_9       17608 non-null  int64
 101  S411DA_98      17608 non-null  int64
 102  S411DA_<NA>    17608 non-null  int64
 103  S411EA_0       17608 non-null  int64
 104  S411EA_1       17608 non-null  int64
 105  S411EA_2       17608 non-null  int64
 106  S411EA_3       17608 non-null  int64
 107  S411EA_4       17608 non-null  int64
 108  S411EA_5       17608 non-null  int64
 109  S411EA_6       17608 non-null  int64
 110  S411EA_7       17608 non-null  int64
 111  S411EA_8       17608 non-null  int64
 112  S411EA_9       17608 non-null  int64
 113  S411EA_98      17608 non-null  int64
 114  S411EA_<NA>    17608 non-null  int64
 115  S422I_0        17608 non-null  int64
 116  S422I_1        17608 non-null  int64
 117  S422I_10       17608 non-null  int64
 118  S422I_12       17608 non-null  int64
 119  S422I_14       17608 non-null  int64
 120  S422I_15       17608 non-null  int64
 121  S422I_16       17608 non-null  int64
 122  S422I_18       17608 non-null  int64
 123  S422I_2        17608 non-null  int64
 124  S422I_20       17608 non-null  int64
 125  S422I_24       17608 non-null  int64
 126  S422I_3        17608 non-null  int64
 127  S422I_30       17608 non-null  int64
 128  S422I_36       17608 non-null  int64
 129  S422I_4        17608 non-null  int64
 130  S422I_5        17608 non-null  int64
 131  S422I_6        17608 non-null  int64
 132  S422I_60       17608 non-null  int64
 133  S422I_7        17608 non-null  int64
 134  S422I_8        17608 non-null  int64
 135  S422I_80       17608 non-null  int64
 136  S422I_9        17608 non-null  int64
 137  S422I_98       17608 non-null  int64
 138  S422I_<NA>     17608 non-null  int64
 139  S426B_11       17608 non-null  int64
 140  S426B_12       17608 non-null  int64
 141  S426B_13       17608 non-null  int64
 142  S426B_14       17608 non-null  int64
 143  S426B_15       17608 non-null  int64
 144  S426B_16       17608 non-null  int64
 145  S426B_17       17608 non-null  int64
 146  S426B_18       17608 non-null  int64
 147  S426B_19       17608 non-null  int64
 148  S426B_20       17608 non-null  int64
 149  S426B_21       17608 non-null  int64
 150  S426B_22       17608 non-null  int64
 151  S426B_23       17608 non-null  int64
 152  S426B_24       17608 non-null  int64
 153  S426B_25       17608 non-null  int64
 154  S426B_96       17608 non-null  int64
 155  S426B_<NA>     17608 non-null  int64
 156  S426FB_100     17608 non-null  int64
 157  S426FB_101     17608 non-null  int64
 158  S426FB_102     17608 non-null  int64
 159  S426FB_103     17608 non-null  int64
 160  S426FB_104     17608 non-null  int64
 161  S426FB_105     17608 non-null  int64
 162  S426FB_106     17608 non-null  int64
 163  S426FB_107     17608 non-null  int64
 164  S426FB_108     17608 non-null  int64
 165  S426FB_110     17608 non-null  int64
 166  S426FB_113     17608 non-null  int64
 167  S426FB_115     17608 non-null  int64
 168  S426FB_116     17608 non-null  int64
 169  S426FB_120     17608 non-null  int64
 170  S426FB_201     17608 non-null  int64
 171  S426FB_202     17608 non-null  int64
 172  S426FB_203     17608 non-null  int64
 173  S426FB_304     17608 non-null  int64
 174  S426FB_998     17608 non-null  int64
 175  S426FB_<NA>    17608 non-null  int64
 176  S430C_0        17608 non-null  int64
 177  S430C_1        17608 non-null  int64
 178  S430C_2        17608 non-null  int64
 179  S430C_8        17608 non-null  int64
 180  S431A_0        17608 non-null  int64
 181  S431A_1        17608 non-null  int64
 182  S431A_8        17608 non-null  int64
 183  S431A_<NA>     17608 non-null  int64
 184  S432_0         17608 non-null  int64
 185  S432_1         17608 non-null  int64
 186  S432_8         17608 non-null  int64
 187  S435_1         17608 non-null  int64
 188  S435_2         17608 non-null  int64
 189  S435_3         17608 non-null  int64
 190  S435_4         17608 non-null  int64
 191  S435_5         17608 non-null  int64
 192  S435_6         17608 non-null  int64
 193  S435_7         17608 non-null  int64
 194  S435_8         17608 non-null  int64
 195  S435_96        17608 non-null  int64
 196  S435_<NA>      17608 non-null  int64
 197  S440_1         17608 non-null  int64
 198  S440_10        17608 non-null  int64
 199  S440_11        17608 non-null  int64
 200  S440_12        17608 non-null  int64
 201  S440_2         17608 non-null  int64
 202  S440_3         17608 non-null  int64
 203  S440_4         17608 non-null  int64
 204  S440_5         17608 non-null  int64
 205  S440_6         17608 non-null  int64
 206  S440_7         17608 non-null  int64
 207  S440_8         17608 non-null  int64
 208  S440_9         17608 non-null  int64
 209  S440_96        17608 non-null  int64
 210  S440_<NA>      17608 non-null  int64
 211  S442_21        17608 non-null  int64
 212  S442_22        17608 non-null  int64
 213  S442_23        17608 non-null  int64
 214  S442_24        17608 non-null  int64
 215  S442_25        17608 non-null  int64
 216  S442_26        17608 non-null  int64
 217  S442_27        17608 non-null  int64
 218  S442_31        17608 non-null  int64
 219  S442_32        17608 non-null  int64
 220  S442_41        17608 non-null  int64
 221  S442_42        17608 non-null  int64
 222  S442_96        17608 non-null  int64
 223  S442_<NA>      17608 non-null  int64
 224  S447_0         17608 non-null  int64
 225  S447_1         17608 non-null  int64
 226  S447_8         17608 non-null  int64
 227  S447_<NA>      17608 non-null  int64
 228  QI411_M_1      17608 non-null  int64
 229  QI411_M_2      17608 non-null  int64
 230  QI411_M_8      17608 non-null  int64
 231  QI411_M_<NA>   17608 non-null  int64
 232  QI411F_0       17608 non-null  int64
 233  QI411F_1       17608 non-null  int64
 234  QI411F_2       17608 non-null  int64
 235  QI411F_3       17608 non-null  int64
 236  QI411F_4       17608 non-null  int64
 237  QI411F_5       17608 non-null  int64
 238  QI411F_6       17608 non-null  int64
 239  QI411F_7       17608 non-null  int64
 240  QI411F_8       17608 non-null  int64
 241  QI411F_9       17608 non-null  int64
 242  QI411F_98      17608 non-null  int64
 243  QI411F_<NA>    17608 non-null  int64
 244  QI422A_A_1     17608 non-null  int64
 245  QI422A_A_2     17608 non-null  int64
 246  QI422A_A_8     17608 non-null  int64
 247  QI422A_A_<NA>  17608 non-null  int64
 248  QI422A_B_1     17608 non-null  int64
 249  QI422A_B_2     17608 non-null  int64
 250  QI422A_B_8     17608 non-null  int64
 251  QI422A_B_<NA>  17608 non-null  int64
 252  QI422A_C_1     17608 non-null  int64
 253  QI422A_C_2     17608 non-null  int64
 254  QI422A_C_8     17608 non-null  int64
 255  QI422A_C_<NA>  17608 non-null  int64
 256  QI422A_D_1     17608 non-null  int64
 257  QI422A_D_2     17608 non-null  int64
 258  QI422A_D_8     17608 non-null  int64
 259  QI422A_D_<NA>  17608 non-null  int64
 260  QI440B_1       17608 non-null  int64
 261  QI440B_2       17608 non-null  int64
 262  QI440B_8       17608 non-null  int64
 263  QI440B_<NA>    17608 non-null  int64
 264  S422I          16727 non-null  Float64
 265  S411CA         17141 non-null  Float64
 266  S411BA         17054 non-null  Float64
 267  S411EA         16355 non-null  Float64
 268  S411DA         15366 non-null  Float64
dtypes: Float64(5), Int64(17), int64(246), object(1)
memory usage: 36.5+ MB

In [59]:
# File name only
output_file = "Modulo1633_REC94_2024_fil.csv"

# Go one level up from the current working directory
base_dir = os.path.dirname(os.getcwd())   # gives "c:\\Users\\linoc\\OneDrive\\Encoder\\03_partos"
output_dir = os.path.join(base_dir, "03_bases_intermediarios")

#Full path
output_path = os.path.join(output_dir, output_file)

# Save DataFrame
Modulo1633_REC94_2024_fil.to_csv(output_path, index=False, encoding="utf-8-sig")

In [ ]:
# Modulo1633_REC41_2024 = add_prefix_except_caseid(Modulo1633_REC41_2024, 'REC41')
# Modulo1633_REC94_2024 = add_prefix_except_caseid(Modulo1633_REC94_2024, 'REC94')


# # 1. Merge com Modulo1633_REC41_2024 usando CASEID e MIDX
# df_merged = target[['CASEID','BIDX']].merge(
#     Modulo1633_REC41_2024.drop_duplicates(subset=['CASEID', 'REC41_MIDX']),
#     left_on=['CASEID', 'BIDX'],
#     right_on=['CASEID', 'REC41_MIDX'],
#     how='left',
# #    suffixes=('', '_rec41')
# )

# # 2. Merge com Modulo1633_REC94_2024 usando CASEID e IDX94
# df_merged = df_merged.merge(
#     Modulo1633_REC94_2024.drop_duplicates(subset=['CASEID', 'REC94_IDX94']),
#     left_on=['CASEID', 'BIDX'],
#     right_on=['CASEID', 'REC94_IDX94'],
#     how='left',
# #    suffixes=('', '_rec94')
# )

# df_merged.info(verbose = True, show_counts = True)

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 21118 entries, 0 to 21117
Data columns (total 208 columns):
 #    Column          Non-Null Count  Dtype
---   ------          --------------  -----
 0    CASEID          21118 non-null  object
 1    BIDX            21118 non-null  int64
 2    REC41_ID1       19751 non-null  float64
 3    REC41_MIDX      19751 non-null  float64
 4    REC41_M1        19751 non-null  object
 5    REC41_M1A       19751 non-null  object
 6    REC41_M1B       19751 non-null  object
 7    REC41_M1C       19751 non-null  object
 8    REC41_M1D       19751 non-null  object
 9    REC41_M1E       19751 non-null  object
 10   REC41_M2A       19751 non-null  object
 11   REC41_M2B       19751 non-null  object
 12   REC41_M2C       19751 non-null  object
 13   REC41_M2D       19751 non-null  object
 14   REC41_M2E       19751 non-null  object
 15   REC41_M2F       19751 non-null  object
 16   REC41_M2G       19751 non-null  object
 17   REC41_M2H       19751 non-null  object
 18   REC41_M2I       19751 non-null  object
 19   REC41_M2J       19751 non-null  object
 20   REC41_M2K       19751 non-null  object
 21   REC41_M2L       19751 non-null  object
 22   REC41_M2M       19751 non-null  object
 23   REC41_M2N       19751 non-null  object
 24   REC41_M3A       19751 non-null  float64
 25   REC41_M3B       19751 non-null  float64
 26   REC41_M3C       19751 non-null  float64
 27   REC41_M3D       19751 non-null  float64
 28   REC41_M3E       19751 non-null  float64
 29   REC41_M3F       19751 non-null  object
 30   REC41_M3G       19751 non-null  float64
 31   REC41_M3H       19751 non-null  float64
 32   REC41_M3I       19751 non-null  object
 33   REC41_M3J       19751 non-null  object
 34   REC41_M3K       19751 non-null  float64
 35   REC41_M3L       19751 non-null  object
 36   REC41_M3M       19751 non-null  object
 37   REC41_M3N       19751 non-null  float64
 38   REC41_M4        19751 non-null  float64
 39   REC41_M5        19751 non-null  float64
 40   REC41_M6        19751 non-null  float64
 41   REC41_M7        19751 non-null  float64
 42   REC41_M8        19751 non-null  float64
 43   REC41_M9        19751 non-null  float64
 44   REC41_M10       19751 non-null  float64
 45   REC41_M11       19751 non-null  object
 46   REC41_M13       19751 non-null  object
 47   REC41_M14       19751 non-null  object
 48   REC41_M15       19751 non-null  float64
 49   REC41_M17       19751 non-null  float64
 50   REC41_M18       19751 non-null  float64
 51   REC41_M19       19751 non-null  float64
 52   REC41_M19A      19751 non-null  object
 53   REC41_M27       19751 non-null  float64
 54   REC41_M28       19751 non-null  float64
 55   REC41_M29       19751 non-null  float64
 56   REC41_M34       19751 non-null  object
 57   REC41_M35       19751 non-null  object
 58   REC41_M36       19751 non-null  object
 59   REC41_M38       19751 non-null  object
 60   REC41_M39       19751 non-null  object
 61   REC41_M42A      19751 non-null  object
 62   REC41_M42B      19751 non-null  object
 63   REC41_M42C      19751 non-null  object
 64   REC41_M42D      19751 non-null  object
 65   REC41_M42E      19751 non-null  object
 66   REC41_M43       19751 non-null  object
 67   REC41_M44       19751 non-null  object
 68   REC41_M45       19751 non-null  object
 69   REC41_M46       19751 non-null  object
 70   REC41_M47       19751 non-null  object
 71   REC41_M48       19751 non-null  object
 72   REC41_M49A      19751 non-null  object
 73   REC41_M49B      19751 non-null  object
 74   REC41_M49C      19751 non-null  object
 75   REC41_M49D      19751 non-null  object
 76   REC41_M49E      19751 non-null  object
 77   REC41_M49F      19751 non-null  object
 78   REC41_M49G      19751 non-null  object
 79   REC41_M49X      19751 non-null  object
 80   REC41_M49Z      19751 non-null  object
 81   REC41_M51A      19751 non-null  object
 82   REC41_M54       19751 non-null  object
 83   REC41_M55A      19751 non-null  float64
 84   REC41_M55B      19751 non-null  float64
 85   REC41_M55C      19751 non-null  float64
 86   REC41_M55D      19751 non-null  object
 87   REC41_M55E      19751 non-null  float64
 88   REC41_M55F      19751 non-null  float64
 89   REC41_M55G      19751 non-null  float64
 90   REC41_M55H      19751 non-null  float64
 91   REC41_M55I      19751 non-null  float64
 92   REC41_M55J      19751 non-null  object
 93   REC41_M55K      19751 non-null  object
 94   REC41_M55L      19751 non-null  object
 95   REC41_M55M      19751 non-null  object
 96   REC41_M55N      19751 non-null  object
 97   REC41_M55X      19751 non-null  float64
 98   REC41_M55Z      19751 non-null  float64
 99   REC41_M57A      19751 non-null  object
 100  REC41_M57B      19751 non-null  object
 101  REC41_M57C      19751 non-null  object
 102  REC41_M57D      19751 non-null  object
 103  REC41_M57E      19751 non-null  object
 104  REC41_M57F      19751 non-null  object
 105  REC41_M57G      19751 non-null  object
 106  REC41_M57H      19751 non-null  object
 107  REC41_M57I      19751 non-null  object
 108  REC41_M57J      19751 non-null  object
 109  REC41_M57K      19751 non-null  object
 110  REC41_M57L      19751 non-null  object
 111  REC41_M57M      19751 non-null  object
 112  REC41_M57N      19751 non-null  object
 113  REC41_M57O      19751 non-null  object
 114  REC41_M57P      19751 non-null  object
 115  REC41_M57Q      19751 non-null  object
 116  REC41_M57R      19751 non-null  object
 117  REC41_M57S      19751 non-null  object
 118  REC41_M57T      19751 non-null  object
 119  REC41_M57U      19751 non-null  object
 120  REC41_M57V      19751 non-null  object
 121  REC41_M57X      19751 non-null  object
 122  REC41_M60       19751 non-null  object
 123  REC41_M61       19751 non-null  object
 124  REC41_M62       19751 non-null  object
 125  REC41_M63       19751 non-null  object
 126  REC41_M64       19751 non-null  object
 127  REC41_M65A      19751 non-null  object
 128  REC41_M65B      19751 non-null  object
 129  REC41_M65C      19751 non-null  object
 130  REC41_M65D      19751 non-null  object
 131  REC41_M65E      19751 non-null  object
 132  REC41_M65F      19751 non-null  object
 133  REC41_M65G      19751 non-null  object
 134  REC41_M65H      19751 non-null  object
 135  REC41_M65I      19751 non-null  object
 136  REC41_M65J      19751 non-null  object
 137  REC41_M65K      19751 non-null  object
 138  REC41_M65L      19751 non-null  object
 139  REC41_M65X      19751 non-null  object
 140  REC41_M66       19751 non-null  float64
 141  REC41_M67       19751 non-null  object
 142  REC41_M68       19751 non-null  object
 143  REC41_M69       19751 non-null  object
 144  REC41_M70       19751 non-null  object
 145  REC41_M71       19751 non-null  object
 146  REC41_M72       19751 non-null  object
 147  REC41_M73       19751 non-null  object
 148  REC94_ID1       19751 non-null  float64
 149  REC94_IDX94     19751 non-null  float64
 150  REC94_S410B     19751 non-null  object
 151  REC94_S411B     19751 non-null  object
 152  REC94_S411F     19751 non-null  object
 153  REC94_S411G     19751 non-null  object
 154  REC94_S411H     19751 non-null  object
 155  REC94_S411I     19751 non-null  object
 156  REC94_S411J     19751 non-null  object
 157  REC94_S411K     19751 non-null  object
 158  REC94_S411L     19751 non-null  object
 159  REC94_S411BA    19751 non-null  object
 160  REC94_S411CA    19751 non-null  object
 161  REC94_S411DA    19751 non-null  object
 162  REC94_S411EA    19751 non-null  object
 163  REC94_S413      19751 non-null  object
 164  REC94_S422I     19751 non-null  object
 165  REC94_S426B     19751 non-null  object
 166  REC94_S426E     19751 non-null  object
 167  REC94_S426FA    19751 non-null  object
 168  REC94_S426FB    19751 non-null  object
 169  REC94_S426GA    19751 non-null  object
 170  REC94_S426GB    19751 non-null  object
 171  REC94_S426GC    19751 non-null  object
 172  REC94_S426GD    19751 non-null  object
 173  REC94_S426GE    19751 non-null  object
 174  REC94_S430C     19751 non-null  float64
 175  REC94_S430D     19751 non-null  object
 176  REC94_S431A     19751 non-null  object
 177  REC94_S425A     19751 non-null  object
 178  REC94_S432      19751 non-null  float64
 179  REC94_S432AD    19751 non-null  object
 180  REC94_S432AM    19751 non-null  object
 181  REC94_S432AY    19751 non-null  object
 182  REC94_S427DA    19751 non-null  object
 183  REC94_S427DB    19751 non-null  object
 184  REC94_S427DC    19751 non-null  object
 185  REC94_S427DD    19751 non-null  object
 186  REC94_S427DE    19751 non-null  object
 187  REC94_S427DF    19751 non-null  object
 188  REC94_S427DG    19751 non-null  object
 189  REC94_S427F     19751 non-null  object
 190  REC94_S435      19751 non-null  object
 191  REC94_S436C     19751 non-null  object
 192  REC94_S440      19751 non-null  object
 193  REC94_S441      19751 non-null  float64
 194  REC94_S442      19751 non-null  object
 195  REC94_S446AA    19751 non-null  object
 196  REC94_S446AB    19751 non-null  object
 197  REC94_S446A     19751 non-null  object
 198  REC94_S447      19751 non-null  object
 199  REC94_S448A     19751 non-null  object
 200  REC94_S448B     19751 non-null  object
 201  REC94_QI411_M   19751 non-null  object
 202  REC94_QI411F    19751 non-null  object
 203  REC94_QI422A_A  19751 non-null  object
 204  REC94_QI422A_B  19751 non-null  object
 205  REC94_QI422A_C  19751 non-null  object
 206  REC94_QI422A_D  19751 non-null  object
 207  REC94_QI440B    19751 non-null  object
dtypes: float64(41), int64(1), object(166)
memory usage: 33.5+ MB