In [1]:
import pandas as pd
import numpy as np
import sys
import os
pd.set_option('display.max_columns', None)
pd.set_option('display.max_rows', None) 
#pd.set_option('display.max_info_columns', None)

sys.path.append(os.path.abspath(".."))

# Import the function
from scripts.utils import (get_variable_name,
                           count_repetitive_caseids,
                            add_prefix_except_caseid, 
                            get_dummy_variables, 
                            convert_objects_to_int64_safe,
                            drop_null_and_list,
                            aggregate_sum_by_caseid,
                            analyze_matches,
                            analyze_matches_explicit_keys, 
                            aggregate_with_value_suffix          
                            )

# 01 Target

In [2]:
Modulo1632_REC21_2023 = pd.read_csv("C:/Users/linoc/OneDrive/Encoder/03_partos/01_raws/2024/968-Modulo1632/968-Modulo1632/REC21_2024.csv", low_memory=False)
Modulo1632_REC21_2023.info(verbose = True, show_counts = True)

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 60693 entries, 0 to 60692
Data columns (total 34 columns):
 #   Column   Non-Null Count  Dtype
---  ------   --------------  -----
 0   ID1      60693 non-null  int64
 1   CASEID   60693 non-null  object
 2   BIDX     60693 non-null  int64
 3   BORD     60693 non-null  int64
 4   B0       60693 non-null  int64
 5   B1       60693 non-null  int64
 6   B2       60693 non-null  int64
 7   B3       60693 non-null  object
 8   B4       60693 non-null  int64
 9   B5       60693 non-null  int64
 10  B6       60693 non-null  object
 11  B7       60693 non-null  object
 12  B8       60693 non-null  object
 13  B9       60693 non-null  object
 14  B10      60693 non-null  int64
 15  B11      60693 non-null  object
 16  B12      60693 non-null  object
 17  B13      60693 non-null  object
 18  B15      60693 non-null  object
 19  B16      60693 non-null  object
 20  BD       60693 non-null  int64
 21  BDD      60693 non-null  int64
 22  BMM      60693 non-null  int64
 23  BAA      60693 non-null  int64
 24  BCMC     60693 non-null  int64
 25  BEDAD    60693 non-null  object
 26  QD333_1  60693 non-null  object
 27  QD333_2  60693 non-null  object
 28  QD333_3  60693 non-null  object
 29  QD333_4  60693 non-null  object
 30  QD333_5  60693 non-null  object
 31  QD333_6  60693 non-null  object
 32  Q220A    60693 non-null  object
 33  QULT5    60693 non-null  int64
dtypes: int64(15), object(19)
memory usage: 15.7+ MB

In [3]:
target = Modulo1632_REC21_2023[['CASEID', 'BIDX','Q220A']]
target.CASEID.nunique(), target[target['Q220A']!=" "].CASEID.nunique()

(24627, 18335)

In [4]:
# # de meses de nascimento
target.Q220A.value_counts()

Q220A
     39575
9    16932
8     3467
7      580
6      122
5       17
Name: count, dtype: int64

In [5]:
target=target[target['Q220A']!= " " ]
target['Q220A'] = pd.to_numeric(target['Q220A'])
target.Q220A.value_counts()

Q220A
9    16932
8     3467
7      580
6      122
5       17
Name: count, dtype: int64

In [6]:
target.CASEID.nunique(), target.shape

(18335, (21118, 3))

In [7]:
# Keep row with max BIDX per CASEID
target = target.loc[target.groupby("CASEID")["BIDX"].idxmax()]

# Reset index (optional, just for clean display)
target = target.reset_index(drop=True)

#Create flag 
target['premature'] =  np.where(target['Q220A'] <= 8, 1, 0)
target_final = target.copy()

#target_final = target.groupby('CASEID', as_index=False)['premature'].sum()
target_final['premature_flag'] = np.where(target_final['premature'] >= 1, 1, 0)
target_final.premature_flag.value_counts()

premature_flag
0    14801
1     3534
Name: count, dtype: int64

In [8]:
target_final.premature_flag.value_counts(1)

premature_flag
0    0.807254
1    0.192746
Name: proportion, dtype: float64

In [9]:
target_final.shape , target_final.CASEID.nunique()

((18335, 5), 18335)

In [10]:
output_file = "target_final.csv"

# Go one level up from the current working directory
base_dir = os.path.dirname(os.getcwd())   # gives "c:\\Users\\linoc\\OneDrive\\Encoder\\03_partos"
output_dir = os.path.join(base_dir, "data\\interim")
print(output_dir)

#Full path
output_path = os.path.join(output_dir, output_file)

# Save DataFrame
target_final.to_csv(output_path, index=False, encoding="utf-8-sig")

c:\Users\linoc\OneDrive\Encoder\03_partos\02_scripts\Premature_model\data\interim

# 2 join other tables

In [11]:
Modulo1631_REC91_2024 = pd.read_csv("C:/Users/linoc/OneDrive/Encoder/03_partos/01_raws/2024/968-Modulo1631/968-Modulo1631/REC91_2024.csv", low_memory=False)
Modulo1632_RE223132_2024 = pd.read_csv("C:/Users/linoc/OneDrive/Encoder/03_partos/01_raws/2024/968-Modulo1632/968-Modulo1632/RE223132_2024.csv", low_memory=False)
Modulo1633_REC41_2024 = pd.read_csv("C:/Users/linoc/OneDrive/Encoder/03_partos/01_raws/2024/968-Modulo1633/968-Modulo1633/REC41_2024.csv", low_memory=False)
Modulo1633_REC94_2024 = pd.read_csv("C:/Users/linoc/OneDrive/Encoder/03_partos/01_raws/2024/968-Modulo1633/968-Modulo1633/REC94_2024.csv", low_memory=False)
Modulo1635_RE516171_2024 = pd.read_csv("C:/Users/linoc/OneDrive/Encoder/03_partos/01_raws/2024/968-Modulo1635/968-Modulo1635/RE516171_2024.csv", low_memory=False)
Modulo1640_CSALUD01_2024 = pd.read_csv("C:/Users/linoc/OneDrive/Encoder/03_partos/01_raws/2024/968-Modulo1640/968-Modulo1640/CSALUD01_2024.csv", low_memory=False)

Modulo1640_CSALUD01_2024 = pd.read_csv("C:/Users/linoc/OneDrive/Encoder/03_partos/01_raws/2024/968-Modulo1640/968-Modulo1640/CSALUD01_2024.csv", low_memory=False)
Modulo1640_CSALUD08_2024 = pd.read_csv("C:/Users/linoc/OneDrive/Encoder/03_partos/01_raws/2024/968-Modulo1640/968-Modulo1640/CSALUD08_2024.csv", low_memory=False)


print(f"size file: {get_variable_name(Modulo1631_REC91_2024)}: {Modulo1631_REC91_2024.shape}")
print(f"size file: {get_variable_name(Modulo1632_RE223132_2024)}: {Modulo1632_RE223132_2024.shape}")
print(f"size file: {get_variable_name(Modulo1633_REC41_2024)}: {Modulo1633_REC41_2024.shape}")
print(f"size file: {get_variable_name(Modulo1633_REC94_2024)}: {Modulo1633_REC94_2024.shape}")
print(f"size file: {get_variable_name(Modulo1635_RE516171_2024)}: {Modulo1635_RE516171_2024.shape}")

print(f"size file: {get_variable_name(Modulo1640_CSALUD01_2024)}: {Modulo1640_CSALUD01_2024.shape}")
print(f"size file: {get_variable_name(Modulo1640_CSALUD08_2024)}: {Modulo1640_CSALUD08_2024.shape}")

size file: None: (37117, 343)
size file: None: (34252, 149)
size file: None: (19751, 147)
size file: None: (19751, 61)
size file: None: (34252, 84)
size file: None: (34018, 258)
size file: None: (41309, 53)

## 2.1 match with CASEID level

In [12]:
Modulo1631_REC91_2024 = Modulo1631_REC91_2024.drop_duplicates()
Modulo1632_RE223132_2024 = Modulo1632_RE223132_2024.drop_duplicates()
Modulo1635_RE516171_2024 = Modulo1635_RE516171_2024.drop_duplicates()

In [13]:
Modulo1631_REC91_2024.shape,Modulo1632_RE223132_2024.shape, Modulo1635_RE516171_2024.shape

((37117, 343), (34252, 149), (34252, 84))

In [14]:
analyze_matches(target_final, Modulo1631_REC91_2024, 'Modulo1631_REC91_2024')
analyze_matches(target_final, Modulo1632_RE223132_2024, 'Modulo1632_RE223132_2024')
analyze_matches(target_final, Modulo1635_RE516171_2024, 'Modulo1635_RE516171_2024')

🔎 Modulo1631_REC91_2024
 - Rows in target_final: 18335
 - Rows in right dataframe (Modulo1631_REC91_2024): 37117
 - Rows after merge: 18335
 ✅ Matches on CASEID: 18335 (100.00%)

🔎 Modulo1632_RE223132_2024
 - Rows in target_final: 18335
 - Rows in right dataframe (Modulo1632_RE223132_2024): 34252
 - Rows after merge: 18335
 ✅ Matches on CASEID: 18335 (100.00%)

🔎 Modulo1635_RE516171_2024
 - Rows in target_final: 18335
 - Rows in right dataframe (Modulo1635_RE516171_2024): 34252
 - Rows after merge: 18335
 ✅ Matches on CASEID: 18335 (100.00%)

In [15]:
print(Modulo1631_REC91_2024.shape[0]), print(Modulo1631_REC91_2024.CASEID.nunique())
print(Modulo1632_RE223132_2024.shape[0]), print(Modulo1632_RE223132_2024.CASEID.nunique())
print(Modulo1635_RE516171_2024.shape[0]), print(Modulo1635_RE516171_2024.CASEID.nunique())

37117
37117
34252
34252
34252
34252

(None, None)

In [16]:
Modulo1631_REC91_2024 = add_prefix_except_caseid(Modulo1631_REC91_2024, 'REC91')
Modulo1632_RE223132_2024 = add_prefix_except_caseid(Modulo1631_REC91_2024, 'RE223132')
Modulo1635_RE516171_2024 = add_prefix_except_caseid(Modulo1635_RE516171_2024, 'RE516171')

# Perform left merges one by one
target_merged = target_final.merge(Modulo1631_REC91_2024, on='CASEID', how='left') \
                            .merge(Modulo1632_RE223132_2024, on='CASEID', how='left') \
                            .merge(Modulo1635_RE516171_2024, on='CASEID', how='left')
target_merged.info(verbose  = True, show_counts = True)

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 18335 entries, 0 to 18334
Data columns (total 772 columns):
 #    Column                   Non-Null Count  Dtype
---   ------                   --------------  -----
 0    CASEID                   18335 non-null  object
 1    BIDX                     18335 non-null  int64
 2    Q220A                    18335 non-null  int64
 3    premature                18335 non-null  int32
 4    premature_flag           18335 non-null  int32
 5    REC91_ID1                18335 non-null  int64
 6    REC91_SVER               18335 non-null  int64
 7    REC91_SREGION            18335 non-null  int64
 8    REC91_SSEMES             18335 non-null  int64
 9    REC91_SPROVIN            18335 non-null  int64
 10   REC91_SDISTRI            18335 non-null  int64
 11   REC91_S108N              18335 non-null  object
 12   REC91_S108Y              18335 non-null  object
 13   REC91_S108G              18335 non-null  object
 14   REC91_S111               18335 non-null  object
 15   REC91_S112               18335 non-null  object
 16   REC91_S119               18335 non-null  object
 17   REC91_S119NA             18335 non-null  object
 18   REC91_S119NB             18335 non-null  object
 19   REC91_S119D              18335 non-null  object
 20   REC91_S229A              18335 non-null  object
 21   REC91_S229B              18335 non-null  object
 22   REC91_S229C              18335 non-null  object
 23   REC91_S229D              18335 non-null  object
 24   REC91_S229E              18335 non-null  object
 25   REC91_S229F              18335 non-null  object
 26   REC91_S229G              18335 non-null  object
 27   REC91_S229H              18335 non-null  object
 28   REC91_S229I              18335 non-null  object
 29   REC91_S229J              18335 non-null  object
 30   REC91_S229K              18335 non-null  object
 31   REC91_S229L              18335 non-null  object
 32   REC91_S229X              18335 non-null  object
 33   REC91_S229Y              18335 non-null  object
 34   REC91_S229A1             18335 non-null  object
 35   REC91_S229B1             18335 non-null  object
 36   REC91_S229CDAY           18335 non-null  object
 37   REC91_S229CM             18335 non-null  object
 38   REC91_S229CY             18335 non-null  object
 39   REC91_S229DA             18335 non-null  object
 40   REC91_S229DB             18335 non-null  object
 41   REC91_S229DC             18335 non-null  object
 42   REC91_S229DD             18335 non-null  object
 43   REC91_S229DE             18335 non-null  object
 44   REC91_S229DF             18335 non-null  object
 45   REC91_S229DX             18335 non-null  object
 46   REC91_S239A              18335 non-null  object
 47   REC91_S239B              18335 non-null  object
 48   REC91_S239C              18335 non-null  object
 49   REC91_S239D              18335 non-null  object
 50   REC91_S239E              18335 non-null  object
 51   REC91_S239F              18335 non-null  object
 52   REC91_S239X              18335 non-null  object
 53   REC91_S314               18335 non-null  object
 54   REC91_S315B              18335 non-null  object
 55   REC91_S317AC             18335 non-null  object
 56   REC91_S317AD             18335 non-null  object
 57   REC91_S317C              18335 non-null  object
 58   REC91_S321A              18335 non-null  object
 59   REC91_S325A              18335 non-null  object
 60   REC91_S325B              18335 non-null  object
 61   REC91_S325CA             18335 non-null  object
 62   REC91_S325CB             18335 non-null  object
 63   REC91_S325CX             18335 non-null  object
 64   REC91_S325D              18335 non-null  object
 65   REC91_S325E              18335 non-null  object
 66   REC91_S325GA             18335 non-null  object
 67   REC91_S325GB             18335 non-null  object
 68   REC91_S325GC             18335 non-null  object
 69   REC91_S325GD             18335 non-null  object
 70   REC91_S325GE             18335 non-null  object
 71   REC91_S325GF             18335 non-null  object
 72   REC91_S325GG             18335 non-null  object
 73   REC91_S325GH             18335 non-null  object
 74   REC91_S325GI             18335 non-null  object
 75   REC91_S325GJ             18335 non-null  object
 76   REC91_S325GK             18335 non-null  object
 77   REC91_S327B              18335 non-null  object
 78   REC91_S327C              18335 non-null  object
 79   REC91_S481AA             18335 non-null  object
 80   REC91_S481AB             18335 non-null  object
 81   REC91_S481AC             18335 non-null  object
 82   REC91_S481AD             18335 non-null  object
 83   REC91_S481AE             18335 non-null  object
 84   REC91_S481AF             18335 non-null  object
 85   REC91_S481AG             18335 non-null  object
 86   REC91_S481AX             18335 non-null  object
 87   REC91_S481AZ             18335 non-null  object
 88   REC91_S484               18335 non-null  object
 89   REC91_S484D              18335 non-null  object
 90   REC91_S484M              18335 non-null  object
 91   REC91_S484Y              18335 non-null  object
 92   REC91_S485               18335 non-null  object
 93   REC91_S485A              18335 non-null  object
 94   REC91_S486               18335 non-null  object
 95   REC91_S486A              18335 non-null  object
 96   REC91_S486B              18335 non-null  object
 97   REC91_S489C              18335 non-null  object
 98   REC91_S489D              18335 non-null  object
 99   REC91_S490               18335 non-null  object
 100  REC91_S490AA             18335 non-null  object
 101  REC91_S490AB             18335 non-null  object
 102  REC91_S490AC             18335 non-null  object
 103  REC91_S490AD             18335 non-null  object
 104  REC91_S490AE             18335 non-null  object
 105  REC91_S490AF             18335 non-null  object
 106  REC91_S490AG             18335 non-null  object
 107  REC91_S490AX             18335 non-null  object
 108  REC91_S490BA             18335 non-null  object
 109  REC91_S490BB             18335 non-null  object
 110  REC91_S490BC             18335 non-null  object
 111  REC91_S490BD             18335 non-null  object
 112  REC91_S490BX             18335 non-null  object
 113  REC91_S492A              18335 non-null  object
 114  REC91_S492B              18335 non-null  object
 115  REC91_S492C              18335 non-null  object
 116  REC91_S492D              18335 non-null  object
 117  REC91_S492E              18335 non-null  object
 118  REC91_S492F              18335 non-null  object
 119  REC91_S492G              18335 non-null  object
 120  REC91_S493A              18335 non-null  object
 121  REC91_S493B              18335 non-null  object
 122  REC91_S493C              18335 non-null  object
 123  REC91_S493D              18335 non-null  object
 124  REC91_S493E              18335 non-null  object
 125  REC91_S493F              18335 non-null  object
 126  REC91_S493G              18335 non-null  object
 127  REC91_S493H              18335 non-null  object
 128  REC91_S493I              18335 non-null  object
 129  REC91_S493J              18335 non-null  object
 130  REC91_S493K              18335 non-null  object
 131  REC91_S493L              18335 non-null  object
 132  REC91_S493M              18335 non-null  object
 133  REC91_S493N              18335 non-null  object
 134  REC91_S493O              18335 non-null  object
 135  REC91_S493P              18335 non-null  object
 136  REC91_S494               18335 non-null  object
 137  REC91_S494A              18335 non-null  object
 138  REC91_S494B              18335 non-null  object
 139  REC91_S495A              18335 non-null  object
 140  REC91_S496               18335 non-null  object
 141  REC91_S500A              18335 non-null  object
 142  REC91_S500B              18335 non-null  object
 143  REC91_S500C              18335 non-null  object
 144  REC91_S500D              18335 non-null  object
 145  REC91_S508A              18335 non-null  object
 146  REC91_S512C              18335 non-null  object
 147  REC91_S616               18335 non-null  object
 148  REC91_S618A              18335 non-null  object
 149  REC91_S618B              18335 non-null  object
 150  REC91_S618C              18335 non-null  object
 151  REC91_S618D              18335 non-null  object
 152  REC91_S618E              18335 non-null  object
 153  REC91_S618F              18335 non-null  object
 154  REC91_S618G              18335 non-null  object
 155  REC91_S618H              18335 non-null  object
 156  REC91_S618I              18335 non-null  object
 157  REC91_S618J              18335 non-null  object
 158  REC91_S618K              18335 non-null  object
 159  REC91_S618L              18335 non-null  object
 160  REC91_S618M              18335 non-null  object
 161  REC91_S618X              18335 non-null  object
 162  REC91_S621               18335 non-null  object
 163  REC91_S621A              18335 non-null  object
 164  REC91_S704N              18335 non-null  object
 165  REC91_S704Y              18335 non-null  object
 166  REC91_S704G              18335 non-null  object
 167  REC91_S718               18335 non-null  object
 168  REC91_S720A              18335 non-null  object
 169  REC91_S802               18335 non-null  object
 170  REC91_S802D              18335 non-null  object
 171  REC91_S802E              18335 non-null  object
 172  REC91_S802F              18335 non-null  object
 173  REC91_S802H              18335 non-null  object
 174  REC91_S802I              18335 non-null  object
 175  REC91_S803AF             18335 non-null  object
 176  REC91_S803AG             18335 non-null  object
 177  REC91_S803AM             18335 non-null  object
 178  REC91_S804A              18335 non-null  object
 179  REC91_S804C              18335 non-null  object
 180  REC91_S806AX             18335 non-null  object
 181  REC91_S806AZ             18335 non-null  object
 182  REC91_S807               18335 non-null  object
 183  REC91_S809               18335 non-null  object
 184  REC91_S810               18335 non-null  object
 185  REC91_S811               18335 non-null  object
 186  REC91_S815AA             18335 non-null  object
 187  REC91_S815AB             18335 non-null  object
 188  REC91_S815AC             18335 non-null  object
 189  REC91_S815AD             18335 non-null  object
 190  REC91_S815AE             18335 non-null  object
 191  REC91_S815AX             18335 non-null  object
 192  REC91_S815AZ             18335 non-null  object
 193  REC91_S816A              18335 non-null  object
 194  REC91_S816B              18335 non-null  object
 195  REC91_S816C              18335 non-null  object
 196  REC91_S816D              18335 non-null  object
 197  REC91_S816E              18335 non-null  object
 198  REC91_S816F              18335 non-null  object
 199  REC91_S816G              18335 non-null  object
 200  REC91_S816H              18335 non-null  object
 201  REC91_S816I              18335 non-null  object
 202  REC91_S816J              18335 non-null  object
 203  REC91_S816K              18335 non-null  object
 204  REC91_S816L              18335 non-null  object
 205  REC91_S816M              18335 non-null  object
 206  REC91_S816W              18335 non-null  object
 207  REC91_S816Z              18335 non-null  object
 208  REC91_S816AA             18335 non-null  object
 209  REC91_S816AB             18335 non-null  object
 210  REC91_S816AC             18335 non-null  object
 211  REC91_S816AD             18335 non-null  object
 212  REC91_S816AE             18335 non-null  object
 213  REC91_S816AF             18335 non-null  object
 214  REC91_S816AG             18335 non-null  object
 215  REC91_S816AH             18335 non-null  object
 216  REC91_S816AI             18335 non-null  object
 217  REC91_S816AJ             18335 non-null  object
 218  REC91_S816AK             18335 non-null  object
 219  REC91_S816AL             18335 non-null  object
 220  REC91_S816AW             18335 non-null  object
 221  REC91_S816AZ             18335 non-null  object
 222  REC91_S817               18335 non-null  object
 223  REC91_S817GF             18335 non-null  object
 224  REC91_S817GG             18335 non-null  object
 225  REC91_S817GM             18335 non-null  object
 226  REC91_S818               18335 non-null  object
 227  REC91_S1002A             18335 non-null  object
 228  REC91_S1002B             18335 non-null  object
 229  REC91_S1002C             18335 non-null  object
 230  REC91_S1002D             18335 non-null  object
 231  REC91_S1002E             18335 non-null  object
 232  REC91_S1008AN            18335 non-null  object
 233  REC91_S1008BN            18335 non-null  object
 234  REC91_S1008CN            18335 non-null  object
 235  REC91_S1008DN            18335 non-null  object
 236  REC91_S1012B             18335 non-null  object
 237  REC91_S1012BN            18335 non-null  object
 238  REC91_S1017              18335 non-null  object
 239  REC91_S1023AA            18335 non-null  object
 240  REC91_S1023AB            18335 non-null  object
 241  REC91_S1023AC            18335 non-null  object
 242  REC91_S1023AD            18335 non-null  object
 243  REC91_S1023AE            18335 non-null  object
 244  REC91_S1023AF            18335 non-null  object
 245  REC91_S1023AG            18335 non-null  object
 246  REC91_S1023AH            18335 non-null  object
 247  REC91_S1023AX            18335 non-null  object
 248  REC91_S1023AZ            18335 non-null  object
 249  REC91_S1026              18335 non-null  object
 250  REC91_S1030AA            18335 non-null  object
 251  REC91_S1030AB            18335 non-null  object
 252  REC91_S1030AC            18335 non-null  object
 253  REC91_S1030AD            18335 non-null  object
 254  REC91_S1030AE            18335 non-null  object
 255  REC91_S1030AF            18335 non-null  object
 256  REC91_S1030AG            18335 non-null  object
 257  REC91_S1030AH            18335 non-null  object
 258  REC91_S1030AI            18335 non-null  object
 259  REC91_S1030AJ            18335 non-null  object
 260  REC91_S1030AK            18335 non-null  object
 261  REC91_S1030AL            18335 non-null  object
 262  REC91_S1030AM            18335 non-null  object
 263  REC91_S1030AX            18335 non-null  object
 264  REC91_S1030BA            18335 non-null  object
 265  REC91_S1030BB            18335 non-null  object
 266  REC91_S1030BC            18335 non-null  object
 267  REC91_S1030BD            18335 non-null  object
 268  REC91_S1030BE            18335 non-null  object
 269  REC91_S1030BF            18335 non-null  object
 270  REC91_S1030BG            18335 non-null  object
 271  REC91_S1030BH            18335 non-null  object
 272  REC91_S1030BI            18335 non-null  object
 273  REC91_S1030BJ            18335 non-null  object
 274  REC91_S1030BK            18335 non-null  object
 275  REC91_S1030BL            18335 non-null  object
 276  REC91_S1030BM            18335 non-null  object
 277  REC91_S1030BX            18335 non-null  object
 278  REC91_S1030CA            18335 non-null  object
 279  REC91_S1030CB            18335 non-null  object
 280  REC91_S1030CC            18335 non-null  object
 281  REC91_S1030CD            18335 non-null  object
 282  REC91_S1030CE            18335 non-null  object
 283  REC91_S1030CF            18335 non-null  object
 284  REC91_S1030CG            18335 non-null  object
 285  REC91_S1030CH            18335 non-null  object
 286  REC91_S1030CI            18335 non-null  object
 287  REC91_S1030CJ            18335 non-null  object
 288  REC91_S1030CK            18335 non-null  object
 289  REC91_S1030CL            18335 non-null  object
 290  REC91_S1030CM            18335 non-null  object
 291  REC91_S1030CX            18335 non-null  object
 292  REC91_S1031              18335 non-null  object
 293  REC91_S1032A             18335 non-null  object
 294  REC91_S1032B             18335 non-null  object
 295  REC91_S1032C             18335 non-null  object
 296  REC91_S1032D             18335 non-null  object
 297  REC91_S1032E             18335 non-null  object
 298  REC91_S1032F             18335 non-null  object
 299  REC91_S1032G             18335 non-null  object
 300  REC91_S1032H             18335 non-null  object
 301  REC91_S1032I             18335 non-null  object
 302  REC91_S1032J             18335 non-null  object
 303  REC91_S1032K             18335 non-null  object
 304  REC91_S1032L             18335 non-null  object
 305  REC91_S1032M             18335 non-null  object
 306  REC91_S1032N             18335 non-null  object
 307  REC91_S1032X             18335 non-null  object
 308  REC91_S1032Y             18335 non-null  object
 309  REC91_S1033              18335 non-null  object
 310  REC91_S1034A             18335 non-null  object
 311  REC91_S1034B             18335 non-null  object
 312  REC91_QI479E_A           18335 non-null  object
 313  REC91_QI479E_B           18335 non-null  object
 314  REC91_QI479E_C           18335 non-null  object
 315  REC91_QI479E_D           18335 non-null  object
 316  REC91_QI479E_E           18335 non-null  object
 317  REC91_QI479E_F           18335 non-null  object
 318  REC91_QI479E_G           18335 non-null  object
 319  REC91_QI479E_H           18335 non-null  object
 320  REC91_QI479E_I           18335 non-null  object
 321  REC91_QI479E_J           18335 non-null  object
 322  REC91_QI479E_X           18335 non-null  object
 323  REC91_QI479E_Y           18335 non-null  object
 324  REC91_QI479F_A           18335 non-null  object
 325  REC91_QI479F_B           18335 non-null  object
 326  REC91_QI479F_C           18335 non-null  object
 327  REC91_QI479F_D           18335 non-null  object
 328  REC91_QI479F_E           18335 non-null  object
 329  REC91_QI479F_F           18335 non-null  object
 330  REC91_QI479F_G           18335 non-null  object
 331  REC91_QI479F_H           18335 non-null  object
 332  REC91_QI479F_I           18335 non-null  object
 333  REC91_QI479F_J           18335 non-null  object
 334  REC91_QI479F_K           18335 non-null  object
 335  REC91_QI479F_L           18335 non-null  object
 336  REC91_QI479F_M           18335 non-null  object
 337  REC91_QI479F_X           18335 non-null  object
 338  REC91_QI479F_Y           18335 non-null  object
 339  REC91_Q479A              18335 non-null  object
 340  REC91_Q479B              18335 non-null  object
 341  REC91_Q479C              18335 non-null  object
 342  REC91_Q479D              18335 non-null  object
 343  REC91_S1028A             18335 non-null  object
 344  REC91_S1028B             18335 non-null  object
 345  REC91_S1028X             18335 non-null  object
 346  REC91_S1028Y             18335 non-null  object
 347  RE223132_REC91_ID1       18335 non-null  int64
 348  RE223132_REC91_SVER      18335 non-null  int64
 349  RE223132_REC91_SREGION   18335 non-null  int64
 350  RE223132_REC91_SSEMES    18335 non-null  int64
 351  RE223132_REC91_SPROVIN   18335 non-null  int64
 352  RE223132_REC91_SDISTRI   18335 non-null  int64
 353  RE223132_REC91_S108N     18335 non-null  object
 354  RE223132_REC91_S108Y     18335 non-null  object
 355  RE223132_REC91_S108G     18335 non-null  object
 356  RE223132_REC91_S111      18335 non-null  object
 357  RE223132_REC91_S112      18335 non-null  object
 358  RE223132_REC91_S119      18335 non-null  object
 359  RE223132_REC91_S119NA    18335 non-null  object
 360  RE223132_REC91_S119NB    18335 non-null  object
 361  RE223132_REC91_S119D     18335 non-null  object
 362  RE223132_REC91_S229A     18335 non-null  object
 363  RE223132_REC91_S229B     18335 non-null  object
 364  RE223132_REC91_S229C     18335 non-null  object
 365  RE223132_REC91_S229D     18335 non-null  object

## 2.2 match with CASEID and BIRD

In [17]:
target = target.drop_duplicates()
target.shape

(18335, 4)

In [18]:
Modulo1633_REC41_2024.shape, Modulo1633_REC94_2024.shape

((19751, 147), (19751, 61))

In [19]:
#Modulo1632_REC21_2024 = Modulo1632_REC21_2024.drop_duplicates()
Modulo1633_REC41_2024 = Modulo1633_REC41_2024.drop_duplicates()
Modulo1633_REC94_2024  = Modulo1633_REC94_2024.drop_duplicates()

In [20]:
Modulo1633_REC41_2024.shape, Modulo1633_REC94_2024.shape

((19751, 147), (19751, 61))

In [21]:
#analyze_matches_explicit_keys(target, Modulo1632_REC21_2024, 'Modulo1632_REC21_2024', 'BIDX')
analyze_matches_explicit_keys(target, Modulo1633_REC41_2024, 'Modulo1633_REC41_2024', 'MIDX')
analyze_matches_explicit_keys(target, Modulo1633_REC94_2024, 'Modulo1633_REC94_2024', 'IDX94')

🔎 Modulo1633_REC41_2024
 - Rows in target_final: 18335
 - Rows in right dataframe: 19751
 - Matches on CASEID + MIDX: 16983 (92.63%)

🔎 Modulo1633_REC94_2024
 - Rows in target_final: 18335
 - Rows in right dataframe: 19751
 - Matches on CASEID + IDX94: 16983 (92.63%)

### 2.2.1 Modulo1633_REC41_2024

In [22]:
Modulo1633_REC41_2024_M = convert_objects_to_int64_safe(Modulo1633_REC41_2024)
Modulo1633_REC41_2024_M.info(verbose = True, show_counts = True)

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 19751 entries, 0 to 19750
Data columns (total 147 columns):
 #    Column  Non-Null Count  Dtype
---   ------  --------------  -----
 0    ID1     19751 non-null  int64
 1    CASEID  19751 non-null  object
 2    MIDX    19751 non-null  int64
 3    M1      17608 non-null  Int64
 4    M1A     8385 non-null   Int64
 5    M1B     6079 non-null   Int64
 6    M1C     6079 non-null   Int64
 7    M1D     534 non-null    Int64
 8    M1E     6079 non-null   Int64
 9    M2A     17608 non-null  Int64
 10   M2B     17608 non-null  Int64
 11   M2C     17608 non-null  Int64
 12   M2D     17608 non-null  Int64
 13   M2E     17608 non-null  Int64
 14   M2F     0 non-null      Int64
 15   M2G     17608 non-null  Int64
 16   M2H     0 non-null      Int64
 17   M2I     0 non-null      Int64
 18   M2J     0 non-null      Int64
 19   M2K     17608 non-null  Int64
 20   M2L     0 non-null      Int64
 21   M2M     0 non-null      Int64
 22   M2N     17608 non-null  Int64
 23   M3A     19751 non-null  int64
 24   M3B     19751 non-null  int64
 25   M3C     19751 non-null  int64
 26   M3D     19751 non-null  int64
 27   M3E     19751 non-null  int64
 28   M3F     0 non-null      Int64
 29   M3G     19751 non-null  int64
 30   M3H     19751 non-null  int64
 31   M3I     0 non-null      Int64
 32   M3J     0 non-null      Int64
 33   M3K     19751 non-null  int64
 34   M3L     0 non-null      Int64
 35   M3M     0 non-null      Int64
 36   M3N     19751 non-null  int64
 37   M4      19751 non-null  int64
 38   M5      19751 non-null  int64
 39   M6      19751 non-null  int64
 40   M7      19751 non-null  int64
 41   M8      19751 non-null  int64
 42   M9      19751 non-null  int64
 43   M10     19751 non-null  int64
 44   M11     6006 non-null   Int64
 45   M13     17426 non-null  Int64
 46   M14     17608 non-null  Int64
 47   M15     19751 non-null  int64
 48   M17     19751 non-null  int64
 49   M18     19751 non-null  int64
 50   M19     19751 non-null  int64
 51   M19A    19543 non-null  Int64
 52   M27     19751 non-null  int64
 53   M28     19751 non-null  int64
 54   M29     19751 non-null  int64
 55   M34     19561 non-null  Int64
 56   M35     7589 non-null   Int64
 57   M36     7589 non-null   Int64
 58   M38     19582 non-null  Int64
 59   M39     19582 non-null  Int64
 60   M42A    17426 non-null  Int64
 61   M42B    0 non-null      Int64
 62   M42C    17426 non-null  Int64
 63   M42D    17426 non-null  Int64
 64   M42E    17426 non-null  Int64
 65   M43     17426 non-null  Int64
 66   M44     16736 non-null  Int64
 67   M45     17608 non-null  Int64
 68   M46     16727 non-null  Int64
 69   M47     17608 non-null  Int64
 70   M48     17608 non-null  Int64
 71   M49A    0 non-null      Int64
 72   M49B    0 non-null      Int64
 73   M49C    0 non-null      Int64
 74   M49D    0 non-null      Int64
 75   M49E    0 non-null      Int64
 76   M49F    0 non-null      Int64
 77   M49G    0 non-null      Int64
 78   M49X    0 non-null      Int64
 79   M49Z    0 non-null      Int64
 80   M51A    0 non-null      Int64
 81   M54     17608 non-null  Int64
 82   M55A    19751 non-null  int64
 83   M55B    19751 non-null  int64
 84   M55C    19751 non-null  int64
 85   M55D    0 non-null      Int64
 86   M55E    19751 non-null  int64
 87   M55F    19751 non-null  int64
 88   M55G    19751 non-null  int64
 89   M55H    19751 non-null  int64
 90   M55I    19751 non-null  int64
 91   M55J    0 non-null      Int64
 92   M55K    0 non-null      Int64
 93   M55L    0 non-null      Int64
 94   M55M    0 non-null      Int64
 95   M55N    0 non-null      Int64
 96   M55X    19751 non-null  int64
 97   M55Z    19751 non-null  int64
 98   M57A    0 non-null      Int64
 99   M57B    0 non-null      Int64
 100  M57C    0 non-null      Int64
 101  M57D    0 non-null      Int64
 102  M57E    17426 non-null  Int64
 103  M57F    17426 non-null  Int64
 104  M57G    17426 non-null  Int64
 105  M57H    0 non-null      Int64
 106  M57I    17426 non-null  Int64
 107  M57J    17426 non-null  Int64
 108  M57K    17426 non-null  Int64
 109  M57L    17426 non-null  Int64
 110  M57M    17426 non-null  Int64
 111  M57N    0 non-null      Int64
 112  M57O    17426 non-null  Int64
 113  M57P    17426 non-null  Int64
 114  M57Q    17426 non-null  Int64
 115  M57R    0 non-null      Int64
 116  M57S    17426 non-null  Int64
 117  M57T    0 non-null      Int64
 118  M57U    0 non-null      Int64
 119  M57V    0 non-null      Int64
 120  M57X    17426 non-null  Int64
 121  M60     17608 non-null  Int64
 122  M61     0 non-null      Int64
 123  M62     0 non-null      Int64
 124  M63     0 non-null      Int64
 125  M64     0 non-null      Int64
 126  M65A    0 non-null      Int64
 127  M65B    0 non-null      Int64
 128  M65C    0 non-null      Int64
 129  M65D    0 non-null      Int64
 130  M65E    0 non-null      Int64
 131  M65F    0 non-null      Int64
 132  M65G    0 non-null      Int64
 133  M65H    0 non-null      Int64
 134  M65I    0 non-null      Int64
 135  M65J    0 non-null      Int64
 136  M65K    0 non-null      Int64
 137  M65L    0 non-null      Int64
 138  M65X    0 non-null      Int64
 139  M66     19751 non-null  int64
 140  M67     17217 non-null  Int64
 141  M68     17288 non-null  Int64
 142  M69     17288 non-null  Int64
 143  M70     17608 non-null  Int64
 144  M71     17422 non-null  Int64
 145  M72     17422 non-null  Int64
 146  M73     17422 non-null  Int64
dtypes: Int64(110), int64(36), object(1)
memory usage: 24.2+ MB

In [23]:
Modulo1633_REC41_2024_M = target_final.merge(Modulo1633_REC41_2024_M, 
                                               how='left', left_on=['CASEID', 'BIDX'],
                                                 right_on=['CASEID','MIDX'])

Modulo1633_REC41_2024_M = Modulo1633_REC41_2024_M.drop(['Q220A', 'premature'], axis = 1)

Modulo1633_REC41_2024_M.info(verbose = True, show_counts = True)

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 18335 entries, 0 to 18334
Data columns (total 149 columns):
 #    Column          Non-Null Count  Dtype
---   ------          --------------  -----
 0    CASEID          18335 non-null  object
 1    BIDX            18335 non-null  int64
 2    premature_flag  18335 non-null  int32
 3    ID1             16983 non-null  float64
 4    MIDX            16983 non-null  float64
 5    M1              14982 non-null  Int64
 6    M1A             6980 non-null   Int64
 7    M1B             4977 non-null   Int64
 8    M1C             4977 non-null   Int64
 9    M1D             481 non-null    Int64
 10   M1E             4977 non-null   Int64
 11   M2A             14982 non-null  Int64
 12   M2B             14982 non-null  Int64
 13   M2C             14982 non-null  Int64
 14   M2D             14982 non-null  Int64
 15   M2E             14982 non-null  Int64
 16   M2F             0 non-null      Int64
 17   M2G             14982 non-null  Int64
 18   M2H             0 non-null      Int64
 19   M2I             0 non-null      Int64
 20   M2J             0 non-null      Int64
 21   M2K             14982 non-null  Int64
 22   M2L             0 non-null      Int64
 23   M2M             0 non-null      Int64
 24   M2N             14982 non-null  Int64
 25   M3A             16983 non-null  float64
 26   M3B             16983 non-null  float64
 27   M3C             16983 non-null  float64
 28   M3D             16983 non-null  float64
 29   M3E             16983 non-null  float64
 30   M3F             0 non-null      Int64
 31   M3G             16983 non-null  float64
 32   M3H             16983 non-null  float64
 33   M3I             0 non-null      Int64
 34   M3J             0 non-null      Int64
 35   M3K             16983 non-null  float64
 36   M3L             0 non-null      Int64
 37   M3M             0 non-null      Int64
 38   M3N             16983 non-null  float64
 39   M4              16983 non-null  float64
 40   M5              16983 non-null  float64
 41   M6              16983 non-null  float64
 42   M7              16983 non-null  float64
 43   M8              16983 non-null  float64
 44   M9              16983 non-null  float64
 45   M10             16983 non-null  float64
 46   M11             5037 non-null   Int64
 47   M13             14858 non-null  Int64
 48   M14             14982 non-null  Int64
 49   M15             16983 non-null  float64
 50   M17             16983 non-null  float64
 51   M18             16983 non-null  float64
 52   M19             16983 non-null  float64
 53   M19A            16803 non-null  Int64
 54   M27             16983 non-null  float64
 55   M28             16983 non-null  float64
 56   M29             16983 non-null  float64
 57   M34             16835 non-null  Int64
 58   M35             5943 non-null   Int64
 59   M36             5943 non-null   Int64
 60   M38             16867 non-null  Int64
 61   M39             16867 non-null  Int64
 62   M42A            14858 non-null  Int64
 63   M42B            0 non-null      Int64
 64   M42C            14858 non-null  Int64
 65   M42D            14858 non-null  Int64
 66   M42E            14858 non-null  Int64
 67   M43             14858 non-null  Int64
 68   M44             14265 non-null  Int64
 69   M45             14982 non-null  Int64
 70   M46             14283 non-null  Int64
 71   M47             14982 non-null  Int64
 72   M48             14982 non-null  Int64
 73   M49A            0 non-null      Int64
 74   M49B            0 non-null      Int64
 75   M49C            0 non-null      Int64
 76   M49D            0 non-null      Int64
 77   M49E            0 non-null      Int64
 78   M49F            0 non-null      Int64
 79   M49G            0 non-null      Int64
 80   M49X            0 non-null      Int64
 81   M49Z            0 non-null      Int64
 82   M51A            0 non-null      Int64
 83   M54             14982 non-null  Int64
 84   M55A            16983 non-null  float64
 85   M55B            16983 non-null  float64
 86   M55C            16983 non-null  float64
 87   M55D            0 non-null      Int64
 88   M55E            16983 non-null  float64
 89   M55F            16983 non-null  float64
 90   M55G            16983 non-null  float64
 91   M55H            16983 non-null  float64
 92   M55I            16983 non-null  float64
 93   M55J            0 non-null      Int64
 94   M55K            0 non-null      Int64
 95   M55L            0 non-null      Int64
 96   M55M            0 non-null      Int64
 97   M55N            0 non-null      Int64
 98   M55X            16983 non-null  float64
 99   M55Z            16983 non-null  float64
 100  M57A            0 non-null      Int64
 101  M57B            0 non-null      Int64
 102  M57C            0 non-null      Int64
 103  M57D            0 non-null      Int64
 104  M57E            14858 non-null  Int64
 105  M57F            14858 non-null  Int64
 106  M57G            14858 non-null  Int64
 107  M57H            0 non-null      Int64
 108  M57I            14858 non-null  Int64
 109  M57J            14858 non-null  Int64
 110  M57K            14858 non-null  Int64
 111  M57L            14858 non-null  Int64
 112  M57M            14858 non-null  Int64
 113  M57N            0 non-null      Int64
 114  M57O            14858 non-null  Int64
 115  M57P            14858 non-null  Int64
 116  M57Q            14858 non-null  Int64
 117  M57R            0 non-null      Int64
 118  M57S            14858 non-null  Int64
 119  M57T            0 non-null      Int64
 120  M57U            0 non-null      Int64
 121  M57V            0 non-null      Int64
 122  M57X            14858 non-null  Int64
 123  M60             14982 non-null  Int64
 124  M61             0 non-null      Int64
 125  M62             0 non-null      Int64
 126  M63             0 non-null      Int64
 127  M64             0 non-null      Int64
 128  M65A            0 non-null      Int64
 129  M65B            0 non-null      Int64
 130  M65C            0 non-null      Int64
 131  M65D            0 non-null      Int64
 132  M65E            0 non-null      Int64
 133  M65F            0 non-null      Int64
 134  M65G            0 non-null      Int64
 135  M65H            0 non-null      Int64
 136  M65I            0 non-null      Int64
 137  M65J            0 non-null      Int64
 138  M65K            0 non-null      Int64
 139  M65L            0 non-null      Int64
 140  M65X            0 non-null      Int64
 141  M66             16983 non-null  float64
 142  M67             14723 non-null  Int64
 143  M68             14788 non-null  Int64
 144  M69             14788 non-null  Int64
 145  M70             14982 non-null  Int64
 146  M71             14875 non-null  Int64
 147  M72             14875 non-null  Int64
 148  M73             14875 non-null  Int64
dtypes: Int64(110), float64(36), int32(1), int64(1), object(1)
memory usage: 22.7+ MB

In [24]:
dummy_variables  = get_dummy_variables(Modulo1633_REC41_2024_M)
Modulo1633_REC41_2024_M[dummy_variables].describe().T

                  count      mean       std  min  25%  50%  75%  max
premature_flag  18335.0  0.192746  0.394466  0.0  0.0  0.0  0.0  1.0
M2A             14982.0  0.260045  0.438674  0.0  0.0  0.0  1.0  1.0
M2B             14982.0  0.073421  0.260836  0.0  0.0  0.0  0.0  1.0
M2C             14982.0  0.892538   0.30971  0.0  1.0  1.0  1.0  1.0
M2D             14982.0  0.017421  0.130838  0.0  0.0  0.0  0.0  1.0
M2E             14982.0  0.000067   0.00817  0.0  0.0  0.0  0.0  1.0
M2G             14982.0  0.000133  0.011554  0.0  0.0  0.0  0.0  1.0
M2K             14982.0  0.000467  0.021611  0.0  0.0  0.0  0.0  1.0
M2N             14982.0  0.008277  0.090602  0.0  0.0  0.0  0.0  1.0
M3A             16983.0  0.672555  0.469295  0.0  0.0  1.0  1.0  1.0
M3B             16983.0  0.781841  0.413008  0.0  1.0  1.0  1.0  1.0
M3C             16983.0  0.746747  0.434888  0.0  0.0  1.0  1.0  1.0
M3D             16983.0  0.188306  0.390968  0.0  0.0  0.0  0.0  1.0
M3E             16983.0  0.000471  0.021699  0.0  0.0  0.0  0.0  1.0
M3G             16983.0  0.021198  0.144047  0.0  0.0  0.0  0.0  1.0
M3H             16983.0  0.026733  0.161306  0.0  0.0  0.0  0.0  1.0
M3K             16983.0  0.008773  0.093258  0.0  0.0  0.0  0.0  1.0
M3N             16983.0  0.001354  0.036777  0.0  0.0  0.0  0.0  1.0
M17             16983.0  0.358064  0.479445  0.0  0.0  0.0  1.0  1.0
M54             14982.0  0.141436  0.348483  0.0  0.0  0.0  0.0  1.0
M57E            14858.0   0.10385  0.305076  0.0  0.0  0.0  0.0  1.0
M57F            14858.0  0.443196  0.496779  0.0  0.0  0.0  1.0  1.0
M57G            14858.0  0.302194  0.459224  0.0  0.0  0.0  1.0  1.0
M57I            14858.0  0.113407    0.3171  0.0  0.0  0.0  0.0  1.0
M57J            14858.0  0.003904  0.062359  0.0  0.0  0.0  0.0  1.0
M57K            14858.0  0.057074  0.231991  0.0  0.0  0.0  0.0  1.0
M57L            14858.0  0.001481  0.038452  0.0  0.0  0.0  0.0  1.0
M57M            14858.0  0.110311  0.313287  0.0  0.0  0.0  0.0  1.0
M57O            14858.0   0.03944  0.194646  0.0  0.0  0.0  0.0  1.0
M57P            14858.0  0.000606  0.024605  0.0  0.0  0.0  0.0  1.0
M57Q            14858.0  0.002894   0.05372  0.0  0.0  0.0  0.0  1.0
M57S            14858.0  0.000135  0.011602  0.0  0.0  0.0  0.0  1.0
M57X            14858.0  0.006259   0.07887  0.0  0.0  0.0  0.0  1.0
M66             16983.0  0.982983  0.129338  0.0  1.0  1.0  1.0  1.0

In [25]:
no_dummy = drop_null_and_list(Modulo1633_REC41_2024_M, dummy_variables)
no_dummy_list =no_dummy.columns.to_list()
no_dummy_list

remove_items = {"M1C", "M1E", "M4","M46","M34", "M19","M6","M7","M8","M9","M11","M13","M14"}
no_dummy_list = [col for col in no_dummy_list if col not in remove_items]

In [26]:
#df_dummy_variables = aggregate_sum_by_caseid(Modulo1633_REC41_2024_M[dummy_variables + ['CASEID']])

df_dummy_variables = Modulo1633_REC41_2024_M[dummy_variables + ['CASEID','BIDX']]
df_dummy_variables.info(verbose = True, show_counts=True)

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 18335 entries, 0 to 18334
Data columns (total 36 columns):
 #   Column          Non-Null Count  Dtype
---  ------          --------------  -----
 0   premature_flag  18335 non-null  int32
 1   M2A             14982 non-null  Int64
 2   M2B             14982 non-null  Int64
 3   M2C             14982 non-null  Int64
 4   M2D             14982 non-null  Int64
 5   M2E             14982 non-null  Int64
 6   M2G             14982 non-null  Int64
 7   M2K             14982 non-null  Int64
 8   M2N             14982 non-null  Int64
 9   M3A             16983 non-null  float64
 10  M3B             16983 non-null  float64
 11  M3C             16983 non-null  float64
 12  M3D             16983 non-null  float64
 13  M3E             16983 non-null  float64
 14  M3G             16983 non-null  float64
 15  M3H             16983 non-null  float64
 16  M3K             16983 non-null  float64
 17  M3N             16983 non-null  float64
 18  M17             16983 non-null  float64
 19  M54             14982 non-null  Int64
 20  M57E            14858 non-null  Int64
 21  M57F            14858 non-null  Int64
 22  M57G            14858 non-null  Int64
 23  M57I            14858 non-null  Int64
 24  M57J            14858 non-null  Int64
 25  M57K            14858 non-null  Int64
 26  M57L            14858 non-null  Int64
 27  M57M            14858 non-null  Int64
 28  M57O            14858 non-null  Int64
 29  M57P            14858 non-null  Int64
 30  M57Q            14858 non-null  Int64
 31  M57S            14858 non-null  Int64
 32  M57X            14858 non-null  Int64
 33  M66             16983 non-null  float64
 34  CASEID          18335 non-null  object
 35  BIDX            18335 non-null  int64
dtypes: Int64(22), float64(11), int32(1), int64(1), object(1)
memory usage: 5.4+ MB

In [27]:
Modulo1633_REC41_2024_M [no_dummy_list].describe().T

# categoricas, M10, M15,M42A,M42C, M42D, M42E, M43, M44,M45, M47, M48, M60, M69

        count        mean         std     min     25%     50%     75%     max
BIDX  18335.0    1.151786    0.380799     1.0     1.0     1.0     1.0     4.0
ID1   16983.0      2024.0         0.0  2024.0  2024.0  2024.0  2024.0  2024.0
MIDX  16983.0    1.123182    0.345087     1.0     1.0     1.0     1.0     4.0
M1    14982.0    1.529836    1.279564     0.0     1.0     2.0     2.0     8.0
M1A    6980.0    2.048424     2.21775     0.0     1.0     2.0     2.0     8.0
M1B    4977.0   61.164758    44.97024     1.0     7.0    98.0    98.0    98.0
M1D     481.0   54.590437   44.645649     1.0     8.0    98.0    98.0    98.0
M5    16983.0   17.994701   11.892185     0.0    11.0    17.0    24.0    98.0
M10   16983.0    1.688041    0.778541     1.0     1.0     1.0     2.0     3.0
M15   16983.0   23.007949    8.370836    11.0    21.0    21.0    24.0    96.0
M18   16983.0    2.992934    0.824528     1.0     2.0     3.0     3.0     8.0
M19A  16803.0    1.415581    0.535992     0.0     1.0     1.0     2.0     8.0
M27   16983.0    0.000353    0.032555     0.0     0.0     0.0     0.0     3.0
M28   16983.0    0.003827    0.118571     0.0     0.0     0.0     0.0     4.0
M29   16983.0    0.001649    0.077483     0.0     0.0     0.0     0.0     4.0
M35    5943.0    3.696281    2.120995     0.0     2.0     3.0     5.0    20.0
M36    5943.0    5.008077    3.082278     0.0     3.0     5.0     6.0    24.0
M38   16867.0    0.306634    0.564687     0.0     0.0     0.0     1.0     8.0
M39   16867.0     4.23626    1.445018     0.0     4.0     5.0     5.0     8.0
M42A  14858.0    0.999394    0.090244     0.0     1.0     1.0     1.0     8.0
M42C  14858.0    0.999529     0.10853     0.0     1.0     1.0     1.0     8.0
M42D  14858.0    0.987145    0.263115     0.0     1.0     1.0     1.0     8.0
M42E  14858.0    0.991183    0.232316     0.0     1.0     1.0     1.0     8.0
M43   14858.0    0.962781    0.233843     0.0     1.0     1.0     1.0     8.0
M44   14265.0    0.992639    0.105986     0.0     1.0     1.0     1.0     8.0
M45   14982.0     0.95548    0.239777     0.0     1.0     1.0     1.0     8.0
M47   14982.0    0.062275    0.256664     0.0     0.0     0.0     0.0     8.0
M48   14982.0     0.03344    0.208658     0.0     0.0     0.0     0.0     8.0
M55A  16983.0    0.082965    0.795853     0.0     0.0     0.0     0.0     8.0
M55B  16983.0    0.080787    0.794708     0.0     0.0     0.0     0.0     8.0
M55C  16983.0    0.081493     0.79508     0.0     0.0     0.0     0.0     8.0
M55E  16983.0     0.08008    0.794335     0.0     0.0     0.0     0.0     8.0
M55F  16983.0    0.079962    0.794272     0.0     0.0     0.0     0.0     8.0
M55G  16983.0    0.481894    0.898322     0.0     0.0     0.0     1.0     8.0
M55H  16983.0    0.082318    0.795514     0.0     0.0     0.0     0.0     8.0
M55I  16983.0    0.080139    0.794366     0.0     0.0     0.0     0.0     8.0
M55X  16983.0    0.082023    0.795359     0.0     0.0     0.0     0.0     8.0
M55Z  16983.0    0.657422    0.884606     0.0     0.0     1.0     1.0     8.0
M60   14982.0    0.084301    0.531783     0.0     0.0     0.0     0.0     8.0
M67   14723.0  103.188549    13.51582   100.0   100.0   101.0   103.0   304.0
M68   14788.0    12.26224    4.490901    11.0    11.0    12.0    13.0    96.0
M69   14788.0   23.054639    6.935207    11.0    21.0    21.0    24.0    96.0
M70   14982.0    0.998732    0.205877     0.0     1.0     1.0     1.0     8.0
M71   14875.0   121.60679  126.750416   100.0   100.0   101.0   102.0   999.0
M72   14875.0   12.295933    4.938055    11.0    11.0    12.0    13.0    96.0
M73   14875.0   23.063328    6.817461    11.0    21.0    21.0    24.0    96.0

In [28]:
# df_no_dummy_list = aggregate_with_value_suffix(Modulo1633_REC41_2024_M[no_dummy_list], 
#                                                caseid_col="CASEID",
#                                                exclude_cols=['MIDX'])

# df_no_dummy_list.info(verbose=True, show_counts=True)

In [29]:
continue_var_REC41 = ["M6","M7","M8","M9","M11","M13","M14"]

#df_continue_var_REC41 = aggregate_by_caseid_mean(Modulo1633_REC41_2024_M[continue_var_REC41 + ['CASEID']], caseid_col="CASEID")
df_continue_var_REC41 = Modulo1633_REC41_2024_M[continue_var_REC41 + ['CASEID','BIDX']]
df_continue_var_REC41.head()

     M6    M7   M8   M9   M11  M13  M14              CASEID  BIDX
0  12.0  12.0  8.0  8.0  <NA>    1    6        325503101  2     1
1   4.0   4.0  4.0  4.0  <NA>    4    8        325504701  2     1
2   3.0   3.0  3.0  3.0  <NA>    1   11        325505001  1     1
3   6.0   6.0  4.0  4.0  <NA>    1   12        325508901  2     1
4  96.0  18.0  1.0  1.0  <NA>    2   10        325509701  2     1

In [30]:
Modulo1633_REC41_2024_fil = df_dummy_variables.merge(Modulo1633_REC41_2024_M[no_dummy_list], how='left', on='CASEID')
Modulo1633_REC41_2024_fil =Modulo1633_REC41_2024_fil.merge(df_continue_var_REC41, how = 'left', on = 'CASEID')
Modulo1633_REC41_2024_fil.info(verbose = True, show_counts = True)

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 18335 entries, 0 to 18334
Data columns (total 90 columns):
 #   Column          Non-Null Count  Dtype
---  ------          --------------  -----
 0   premature_flag  18335 non-null  int32
 1   M2A             14982 non-null  Int64
 2   M2B             14982 non-null  Int64
 3   M2C             14982 non-null  Int64
 4   M2D             14982 non-null  Int64
 5   M2E             14982 non-null  Int64
 6   M2G             14982 non-null  Int64
 7   M2K             14982 non-null  Int64
 8   M2N             14982 non-null  Int64
 9   M3A             16983 non-null  float64
 10  M3B             16983 non-null  float64
 11  M3C             16983 non-null  float64
 12  M3D             16983 non-null  float64
 13  M3E             16983 non-null  float64
 14  M3G             16983 non-null  float64
 15  M3H             16983 non-null  float64
 16  M3K             16983 non-null  float64
 17  M3N             16983 non-null  float64
 18  M17             16983 non-null  float64
 19  M54             14982 non-null  Int64
 20  M57E            14858 non-null  Int64
 21  M57F            14858 non-null  Int64
 22  M57G            14858 non-null  Int64
 23  M57I            14858 non-null  Int64
 24  M57J            14858 non-null  Int64
 25  M57K            14858 non-null  Int64
 26  M57L            14858 non-null  Int64
 27  M57M            14858 non-null  Int64
 28  M57O            14858 non-null  Int64
 29  M57P            14858 non-null  Int64
 30  M57Q            14858 non-null  Int64
 31  M57S            14858 non-null  Int64
 32  M57X            14858 non-null  Int64
 33  M66             16983 non-null  float64
 34  CASEID          18335 non-null  object
 35  BIDX_x          18335 non-null  int64
 36  BIDX_y          18335 non-null  int64
 37  ID1             16983 non-null  float64
 38  MIDX            16983 non-null  float64
 39  M1              14982 non-null  Int64
 40  M1A             6980 non-null   Int64
 41  M1B             4977 non-null   Int64
 42  M1D             481 non-null    Int64
 43  M5              16983 non-null  float64
 44  M10             16983 non-null  float64
 45  M15             16983 non-null  float64
 46  M18             16983 non-null  float64
 47  M19A            16803 non-null  Int64
 48  M27             16983 non-null  float64
 49  M28             16983 non-null  float64
 50  M29             16983 non-null  float64
 51  M35             5943 non-null   Int64
 52  M36             5943 non-null   Int64
 53  M38             16867 non-null  Int64
 54  M39             16867 non-null  Int64
 55  M42A            14858 non-null  Int64
 56  M42C            14858 non-null  Int64
 57  M42D            14858 non-null  Int64
 58  M42E            14858 non-null  Int64
 59  M43             14858 non-null  Int64
 60  M44             14265 non-null  Int64
 61  M45             14982 non-null  Int64
 62  M47             14982 non-null  Int64
 63  M48             14982 non-null  Int64
 64  M55A            16983 non-null  float64
 65  M55B            16983 non-null  float64
 66  M55C            16983 non-null  float64
 67  M55E            16983 non-null  float64
 68  M55F            16983 non-null  float64
 69  M55G            16983 non-null  float64
 70  M55H            16983 non-null  float64
 71  M55I            16983 non-null  float64
 72  M55X            16983 non-null  float64
 73  M55Z            16983 non-null  float64
 74  M60             14982 non-null  Int64
 75  M67             14723 non-null  Int64
 76  M68             14788 non-null  Int64
 77  M69             14788 non-null  Int64
 78  M70             14982 non-null  Int64
 79  M71             14875 non-null  Int64
 80  M72             14875 non-null  Int64
 81  M73             14875 non-null  Int64
 82  M6              16983 non-null  float64
 83  M7              16983 non-null  float64
 84  M8              16983 non-null  float64
 85  M9              16983 non-null  float64
 86  M11             5037 non-null   Int64
 87  M13             14858 non-null  Int64
 88  M14             14982 non-null  Int64
 89  BIDX            18335 non-null  int64
dtypes: Int64(51), float64(34), int32(1), int64(3), object(1)
memory usage: 13.4+ MB

In [31]:
Modulo1633_REC41_2024_fil = Modulo1633_REC41_2024_fil.drop(columns = ['BIDX_y'], axis=1)

In [32]:
# File name only
output_file = "Modulo1633_REC41_2024_fil_v3.csv"

# Go one level up from the current working directory
base_dir = os.path.dirname(os.getcwd())   # gives "c:\\Users\\linoc\\OneDrive\\Encoder\\03_partos"
output_dir = os.path.join(base_dir, "data\\interim")

#Full path
output_path = os.path.join(output_dir, output_file)

# Save DataFrame
Modulo1633_REC41_2024_fil.to_csv(output_path, index=False, encoding="utf-8-sig")

### 2.2.1 Modulo1633_REC94_2024

In [33]:
Modulo1633_REC94_2024_M = convert_objects_to_int64_safe(Modulo1633_REC94_2024)
Modulo1633_REC94_2024_M.info(verbose = True, show_counts = True)

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 19751 entries, 0 to 19750
Data columns (total 61 columns):
 #   Column    Non-Null Count  Dtype
---  ------    --------------  -----
 0   ID1       19751 non-null  int64
 1   CASEID    19751 non-null  object
 2   IDX94     19751 non-null  int64
 3   S410B     17334 non-null  Int64
 4   S411B     17426 non-null  Int64
 5   S411F     17426 non-null  Int64
 6   S411G     17426 non-null  Int64
 7   S411H     17426 non-null  Int64
 8   S411I     17426 non-null  Int64
 9   S411J     17426 non-null  Int64
 10  S411K     17426 non-null  Int64
 11  S411L     17426 non-null  Int64
 12  S411BA    17054 non-null  Int64
 13  S411CA    17141 non-null  Int64
 14  S411DA    15366 non-null  Int64
 15  S411EA    16355 non-null  Int64
 16  S413      17608 non-null  Int64
 17  S422I     16727 non-null  Int64
 18  S426B     5993 non-null   Int64
 19  S426E     6957 non-null   Int64
 20  S426FA    0 non-null      Int64
 21  S426FB    15273 non-null  Int64
 22  S426GA    17608 non-null  Int64
 23  S426GB    17608 non-null  Int64
 24  S426GC    17608 non-null  Int64
 25  S426GD    17608 non-null  Int64
 26  S426GE    17608 non-null  Int64
 27  S430C     19751 non-null  int64
 28  S430D     17431 non-null  Int64
 29  S431A     16586 non-null  Int64
 30  S425A     0 non-null      Int64
 31  S432      19751 non-null  int64
 32  S432AD    0 non-null      Int64
 33  S432AM    0 non-null      Int64
 34  S432AY    0 non-null      Int64
 35  S427DA    17608 non-null  Int64
 36  S427DB    17608 non-null  Int64
 37  S427DC    17608 non-null  Int64
 38  S427DD    17608 non-null  Int64
 39  S427DE    17608 non-null  Int64
 40  S427DF    17608 non-null  Int64
 41  S427DG    17608 non-null  Int64
 42  S427F     5569 non-null   Int64
 43  S435      190 non-null    Int64
 44  S436C     19561 non-null  Int64
 45  S440      11894 non-null  Int64
 46  S441      19751 non-null  int64
 47  S442      14237 non-null  Int64
 48  S446AA    0 non-null      Int64
 49  S446AB    0 non-null      Int64
 50  S446A     0 non-null      Int64
 51  S447      19582 non-null  Int64
 52  S448A     0 non-null      Int64
 53  S448B     0 non-null      Int64
 54  QI411_M   17426 non-null  Int64
 55  QI411F    14576 non-null  Int64
 56  QI422A_A  17608 non-null  Int64
 57  QI422A_B  16949 non-null  Int64
 58  QI422A_C  4900 non-null   Int64
 59  QI422A_D  4741 non-null   Int64
 60  QI440B    10483 non-null  Int64
dtypes: Int64(55), int64(5), object(1)
memory usage: 10.2+ MB

In [34]:
Modulo1633_REC94_2024_M.QI422A_A.value_counts()

QI422A_A
1    16949
2      615
8       44
Name: count, dtype: Int64

In [35]:
Modulo1633_REC94_2024_M = target_final.merge(Modulo1633_REC94_2024_M, 
                                               how='left', left_on=['CASEID', 'BIDX'],
                                                 right_on=['CASEID','IDX94'])

Modulo1633_REC94_2024_M = Modulo1633_REC94_2024_M.drop(['Q220A', 'premature'], axis = 1)

Modulo1633_REC94_2024_M.info(verbose = True, show_counts = True)

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 18335 entries, 0 to 18334
Data columns (total 63 columns):
 #   Column          Non-Null Count  Dtype
---  ------          --------------  -----
 0   CASEID          18335 non-null  object
 1   BIDX            18335 non-null  int64
 2   premature_flag  18335 non-null  int32
 3   ID1             16983 non-null  float64
 4   IDX94           16983 non-null  float64
 5   S410B           14790 non-null  Int64
 6   S411B           14858 non-null  Int64
 7   S411F           14858 non-null  Int64
 8   S411G           14858 non-null  Int64
 9   S411H           14858 non-null  Int64
 10  S411I           14858 non-null  Int64
 11  S411J           14858 non-null  Int64
 12  S411K           14858 non-null  Int64
 13  S411L           14858 non-null  Int64
 14  S411BA          14547 non-null  Int64
 15  S411CA          14631 non-null  Int64
 16  S411DA          13108 non-null  Int64
 17  S411EA          13938 non-null  Int64
 18  S413            14982 non-null  Int64
 19  S422I           14283 non-null  Int64
 20  S426B           5135 non-null   Int64
 21  S426E           6081 non-null   Int64
 22  S426FA          0 non-null      Int64
 23  S426FB          13350 non-null  Int64
 24  S426GA          14982 non-null  Int64
 25  S426GB          14982 non-null  Int64
 26  S426GC          14982 non-null  Int64
 27  S426GD          14982 non-null  Int64
 28  S426GE          14982 non-null  Int64
 29  S430C           16983 non-null  float64
 30  S430D           15095 non-null  Int64
 31  S431A           14265 non-null  Int64
 32  S425A           0 non-null      Int64
 33  S432            16983 non-null  float64
 34  S432AD          0 non-null      Int64
 35  S432AM          0 non-null      Int64
 36  S432AY          0 non-null      Int64
 37  S427DA          14982 non-null  Int64
 38  S427DB          14982 non-null  Int64
 39  S427DC          14982 non-null  Int64
 40  S427DD          14982 non-null  Int64
 41  S427DE          14982 non-null  Int64
 42  S427DF          14982 non-null  Int64
 43  S427DG          14982 non-null  Int64
 44  S427F           4837 non-null   Int64
 45  S435            148 non-null    Int64
 46  S436C           16835 non-null  Int64
 47  S440            10831 non-null  Int64
 48  S441            16983 non-null  float64
 49  S442            12351 non-null  Int64
 50  S446AA          0 non-null      Int64
 51  S446AB          0 non-null      Int64
 52  S446A           0 non-null      Int64
 53  S447            16867 non-null  Int64
 54  S448A           0 non-null      Int64
 55  S448B           0 non-null      Int64
 56  QI411_M         14858 non-null  Int64
 57  QI411F          12428 non-null  Int64
 58  QI422A_A        14982 non-null  Int64
 59  QI422A_B        14460 non-null  Int64
 60  QI422A_C        4060 non-null   Int64
 61  QI422A_D        3934 non-null   Int64
 62  QI440B          9022 non-null   Int64
dtypes: Int64(55), float64(5), int32(1), int64(1), object(1)
memory usage: 9.7+ MB

In [36]:
Modulo1633_REC94_2024_M.shape, Modulo1633_REC94_2024_M.CASEID.nunique()

((18335, 63), 18335)

In [37]:
dummy_variables_REC94  = get_dummy_variables(Modulo1633_REC94_2024_M)
Modulo1633_REC94_2024_M[dummy_variables_REC94].describe().T

                  count      mean       std  min  25%  50%  75%  max
premature_flag  18335.0  0.192746  0.394466  0.0  0.0  0.0  0.0  1.0
S413            14982.0  0.803297  0.397519  0.0  1.0  1.0  1.0  1.0
S426E            6081.0  0.408979  0.491686  0.0  0.0  0.0  1.0  1.0
S426GA          14982.0  0.107796  0.310133  0.0  0.0  0.0  0.0  1.0
S426GB          14982.0  0.089507  0.285484  0.0  0.0  0.0  0.0  1.0
S426GC          14982.0  0.018422  0.134477  0.0  0.0  0.0  0.0  1.0
S426GD          14982.0  0.009278  0.095877  0.0  0.0  0.0  0.0  1.0
S426GE          14982.0  0.050127  0.218214  0.0  0.0  0.0  0.0  1.0
S430D           15095.0  0.998874  0.033541  0.0  1.0  1.0  1.0  1.0
S427DA          14982.0  0.045188  0.207722  0.0  0.0  0.0  0.0  1.0
S427DB          14982.0  0.020625  0.142129  0.0  0.0  0.0  0.0  1.0
S427DC          14982.0  0.129622  0.335899  0.0  0.0  0.0  0.0  1.0
S427DD          14982.0  0.118075  0.322708  0.0  0.0  0.0  0.0  1.0
S427DE          14982.0  0.140902  0.347932  0.0  0.0  0.0  0.0  1.0
S427DF          14982.0  0.054732  0.227465  0.0  0.0  0.0  0.0  1.0
S427DG          14982.0  0.063076  0.243107  0.0  0.0  0.0  0.0  1.0
S427F            4837.0  0.559851  0.496456  0.0  0.0  1.0  1.0  1.0
S436C           16835.0  0.566083  0.495629  0.0  0.0  1.0  1.0  1.0
S441            16983.0  0.727257  0.445383  0.0  0.0  1.0  1.0  1.0

In [38]:
#df_dummy_variables_REC94 = aggregate_sum_by_caseid(Modulo1633_REC94_2024_M[dummy_variables_REC94 + ['CASEID']])
df_dummy_variables_REC94 =Modulo1633_REC94_2024_M[dummy_variables_REC94 + ['CASEID', 'IDX94']]
df_dummy_variables_REC94.describe().T

                  count      mean       std  min  25%  50%  75%  max
premature_flag  18335.0  0.192746  0.394466  0.0  0.0  0.0  0.0  1.0
S413            14982.0  0.803297  0.397519  0.0  1.0  1.0  1.0  1.0
S426E            6081.0  0.408979  0.491686  0.0  0.0  0.0  1.0  1.0
S426GA          14982.0  0.107796  0.310133  0.0  0.0  0.0  0.0  1.0
S426GB          14982.0  0.089507  0.285484  0.0  0.0  0.0  0.0  1.0
S426GC          14982.0  0.018422  0.134477  0.0  0.0  0.0  0.0  1.0
S426GD          14982.0  0.009278  0.095877  0.0  0.0  0.0  0.0  1.0
S426GE          14982.0  0.050127  0.218214  0.0  0.0  0.0  0.0  1.0
S430D           15095.0  0.998874  0.033541  0.0  1.0  1.0  1.0  1.0
S427DA          14982.0  0.045188  0.207722  0.0  0.0  0.0  0.0  1.0
S427DB          14982.0  0.020625  0.142129  0.0  0.0  0.0  0.0  1.0
S427DC          14982.0  0.129622  0.335899  0.0  0.0  0.0  0.0  1.0
S427DD          14982.0  0.118075  0.322708  0.0  0.0  0.0  0.0  1.0
S427DE          14982.0  0.140902  0.347932  0.0  0.0  0.0  0.0  1.0
S427DF          14982.0  0.054732  0.227465  0.0  0.0  0.0  0.0  1.0
S427DG          14982.0  0.063076  0.243107  0.0  0.0  0.0  0.0  1.0
S427F            4837.0  0.559851  0.496456  0.0  0.0  1.0  1.0  1.0
S436C           16835.0  0.566083  0.495629  0.0  0.0  1.0  1.0  1.0
S441            16983.0  0.727257  0.445383  0.0  0.0  1.0  1.0  1.0
IDX94           16983.0  1.123182  0.345087  1.0  1.0  1.0  1.0  4.0

In [39]:
dummy_variables_REC94

['premature_flag',
 'S413',
 'S426E',
 'S426GA',
 'S426GB',
 'S426GC',
 'S426GD',
 'S426GE',
 'S430D',
 'S427DA',
 'S427DB',
 'S427DC',
 'S427DD',
 'S427DE',
 'S427DF',
 'S427DG',
 'S427F',
 'S436C',
 'S441']

In [40]:
no_dummy_REC94 = drop_null_and_list(Modulo1633_REC94_2024_M, dummy_variables_REC94)
no_dummy_list_REC94 =no_dummy_REC94.columns.to_list()
remove_items = {"S411BA","S411CA","S411DA","S411EA","S422I"}
no_dummy_list = [col for col in no_dummy_list_REC94 if col not in remove_items]

In [41]:
no_dummy_list

['CASEID',
 'BIDX',
 'ID1',
 'IDX94',
 'S410B',
 'S411B',
 'S411F',
 'S411G',
 'S411H',
 'S411I',
 'S411J',
 'S411K',
 'S411L',
 'S426B',
 'S426FB',
 'S430C',
 'S431A',
 'S432',
 'S435',
 'S440',
 'S442',
 'S447',
 'QI411_M',
 'QI411F',
 'QI422A_A',
 'QI422A_B',
 'QI422A_C',
 'QI422A_D',
 'QI440B']

In [42]:
# df_no_dummy_list_REC94 = aggregate_with_value_suffix(Modulo1633_REC94_2024_M[no_dummy_list_REC94], caseid_col="CASEID")
# df_no_dummy_list_REC94.describe().T

In [43]:
continue_var = list(remove_items)
#df_continue_var = aggregate_by_caseid_mean(Modulo1633_REC94_2024_M[continue_var + ['CASEID']], caseid_col="CASEID")
df_continue_var = Modulo1633_REC94_2024_M[continue_var + ['CASEID', 'IDX94']]

df_continue_var.head()

   S411BA  S411DA  S411CA  S411EA  S422I              CASEID  IDX94
0       2       2       2       2      0        325503101  2    1.0
1       4       4       4       4      0        325504701  2    1.0
2       2       2       2       2      0        325505001  1    1.0
3       1       1       1       1      0        325508901  2    1.0
4       3       3       3       3      0        325509701  2    1.0

In [44]:
no_dummy_list_REC94

['CASEID',
 'BIDX',
 'ID1',
 'IDX94',
 'S410B',
 'S411B',
 'S411F',
 'S411G',
 'S411H',
 'S411I',
 'S411J',
 'S411K',
 'S411L',
 'S411BA',
 'S411CA',
 'S411DA',
 'S411EA',
 'S422I',
 'S426B',
 'S426FB',
 'S430C',
 'S431A',
 'S432',
 'S435',
 'S440',
 'S442',
 'S447',
 'QI411_M',
 'QI411F',
 'QI422A_A',
 'QI422A_B',
 'QI422A_C',
 'QI422A_D',
 'QI440B']

In [45]:
Modulo1633_REC94_2024_fil = df_dummy_variables_REC94.merge(Modulo1633_REC94_2024_M[no_dummy_list], how='left', on='CASEID')
Modulo1633_REC94_2024_fil= Modulo1633_REC94_2024_fil.merge(df_continue_var, how ='left', on ='CASEID')
Modulo1633_REC94_2024_fil.info(verbose = True, show_counts = True)

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 18335 entries, 0 to 18334
Data columns (total 55 columns):
 #   Column          Non-Null Count  Dtype
---  ------          --------------  -----
 0   premature_flag  18335 non-null  int32
 1   S413            14982 non-null  Int64
 2   S426E           6081 non-null   Int64
 3   S426GA          14982 non-null  Int64
 4   S426GB          14982 non-null  Int64
 5   S426GC          14982 non-null  Int64
 6   S426GD          14982 non-null  Int64
 7   S426GE          14982 non-null  Int64
 8   S430D           15095 non-null  Int64
 9   S427DA          14982 non-null  Int64
 10  S427DB          14982 non-null  Int64
 11  S427DC          14982 non-null  Int64
 12  S427DD          14982 non-null  Int64
 13  S427DE          14982 non-null  Int64
 14  S427DF          14982 non-null  Int64
 15  S427DG          14982 non-null  Int64
 16  S427F           4837 non-null   Int64
 17  S436C           16835 non-null  Int64
 18  S441            16983 non-null  float64
 19  CASEID          18335 non-null  object
 20  IDX94_x         16983 non-null  float64
 21  BIDX            18335 non-null  int64
 22  ID1             16983 non-null  float64
 23  IDX94_y         16983 non-null  float64
 24  S410B           14790 non-null  Int64
 25  S411B           14858 non-null  Int64
 26  S411F           14858 non-null  Int64
 27  S411G           14858 non-null  Int64
 28  S411H           14858 non-null  Int64
 29  S411I           14858 non-null  Int64
 30  S411J           14858 non-null  Int64
 31  S411K           14858 non-null  Int64
 32  S411L           14858 non-null  Int64
 33  S426B           5135 non-null   Int64
 34  S426FB          13350 non-null  Int64
 35  S430C           16983 non-null  float64
 36  S431A           14265 non-null  Int64
 37  S432            16983 non-null  float64
 38  S435            148 non-null    Int64
 39  S440            10831 non-null  Int64
 40  S442            12351 non-null  Int64
 41  S447            16867 non-null  Int64
 42  QI411_M         14858 non-null  Int64
 43  QI411F          12428 non-null  Int64
 44  QI422A_A        14982 non-null  Int64
 45  QI422A_B        14460 non-null  Int64
 46  QI422A_C        4060 non-null   Int64
 47  QI422A_D        3934 non-null   Int64
 48  QI440B          9022 non-null   Int64
 49  S411BA          14547 non-null  Int64
 50  S411DA          13108 non-null  Int64
 51  S411CA          14631 non-null  Int64
 52  S411EA          13938 non-null  Int64
 53  S422I           14283 non-null  Int64
 54  IDX94           16983 non-null  float64
dtypes: Int64(45), float64(7), int32(1), int64(1), object(1)
memory usage: 8.4+ MB

In [46]:
Modulo1633_REC94_2024_fil.drop(columns = ['IDX94_y'], axis=1, inplace=True)

In [47]:
# File name only
output_file = "Modulo1633_REC94_2024_fil_v3.csv"

# Go one level up from the current working directory
base_dir = os.path.dirname(os.getcwd())   # gives "c:\\Users\\linoc\\OneDrive\\Encoder\\03_partos"
output_dir = os.path.join(base_dir, "data\\interim")   

#Full path
output_path = os.path.join(output_dir, output_file)

# Save DataFrame
Modulo1633_REC94_2024_fil.to_csv(output_path, index=False, encoding="utf-8-sig")