In [2]:
# This is timport datarobot as dr
import pandas as pd
import numpy as np
from datetime import datetime
from scipy.stats import mode
import seaborn as sns
import matplotlib.pyplot as plt
import numpy as np
from sklearn.preprocessing import MinMaxScaler
import sys, os
from pathlib import Path



# Go up one directory from "notebooks" to project root
project_root = os.path.abspath(os.path.join(os.getcwd(), ".."))
sys.path.append(project_root)

from scripts.utils import (get_variable_name,
                           count_repetitive_caseids,
                            add_prefix_except_caseid, 
                            get_dummy_variables, 
                            convert_objects_to_int64_safe,
                            drop_null_and_list,
                            aggregate_sum_by_caseid,
                            analyze_matches,
                            analyze_matches_explicit_keys, 
                            aggregate_with_value_suffix, 
                            drop_high_null_columns,
                            save_file,
                            add_value_suffix,
                            save_txt
                            ) 


# Now import works
from scripts.Wrangling import (
    categorize_columns,
    fill_missing_with_mode,
    target_encode, 
    fill_missing_with_median_coding,
    #target_encode_dataframe,
    target_encode_dataframe_map,
    #sklearn_target_encode
)

In [3]:
# import sys
# print(sys.executable)

# !{sys.executable} -m pip install category_encoders

In [4]:
key_variables =['CASEID']

# 1 - Ingest Data

In [5]:
# Modulo1632_REC21_2023 = pd.read_csv("C:/Users/linoc/OneDrive/Encoder/03_partos/01_raws/2024/968-Modulo1632/968-Modulo1632/REC21_2024.csv", low_memory=False)
# Modulo1632_REC21_2023.info(verbose = True, show_counts = True)


# Build base directory (go up one level from current /02_scripts)
base_dir = os.path.dirname(os.getcwd())   # → c:\Users\linoc\OneDrive\Encoder\03_partos
base_dir_raw =  Path(base_dir)
base_dir_raw= str(base_dir_raw.parents[1])

# Build the path to the target CSV
csv_path_Modulo1633_REC41_2024_fil = os.path.join(base_dir,"data\\interim", "Modulo1633_REC41_2024_fil_v3.csv")
csv_path_Modulo1633_REC94_2024_fil = os.path.join(base_dir,"data\\interim", "Modulo1633_REC94_2024_fil_v3.csv")

# Build the path to the target CSV
csv_path_Modulo1631_REC91_2024 = os.path.join(base_dir_raw,"01_raws", "2024", "968-Modulo1631", "968-Modulo1631", "REC91_2024.csv")
csv_path_Modulo1632_RE223132_2024= os.path.join(base_dir_raw,"01_raws", "2024", "968-Modulo1632", "968-Modulo1632", "RE223132_2024.csv")
csv_path_Modulo1635_RE516171_2024 = os.path.join(base_dir_raw,"01_raws", "2024", "968-Modulo1635", "968-Modulo1635", "RE516171_2024.csv")

# Load the dataset
Modulo1633_REC41_2024_fil = pd.read_csv(csv_path_Modulo1633_REC41_2024_fil, low_memory=False)
Modulo1633_REC94_2024_fil = pd.read_csv(csv_path_Modulo1633_REC94_2024_fil, low_memory=False)
Modulo1631_REC91_2024 = pd.read_csv(csv_path_Modulo1631_REC91_2024, low_memory=False)
Modulo1632_RE223132_2024 = pd.read_csv(csv_path_Modulo1632_RE223132_2024, low_memory=False)
Modulo1635_RE516171_2024 = pd.read_csv(csv_path_Modulo1635_RE516171_2024, low_memory=False)

Modulo1633_REC41_2024_fil.shape, Modulo1633_REC94_2024_fil.shape, Modulo1631_REC91_2024.shape, Modulo1632_RE223132_2024.shape, Modulo1635_RE516171_2024.shape

((18335, 89), (18335, 54), (37117, 343), (34252, 149), (34252, 84))

In [6]:
Modulo1635_RE516171_2024.V717.value_counts(dropna=False)

V717
0     11831
3      6727
4      5026
1      3614
6      2675
8      1695
7      1303
2      1131
9       235
98       15
Name: count, dtype: int64

In [25]:
Modulo1640_CSALUD01_2024.QS25AA.value_counts(dropna=False)

QS25AA
10    23464
1      6399
       2534
2       864
4       217
3       178
5       113
9        95
6        48
11       46
7        36
8        16
12        8
Name: count, dtype: int64

In [27]:
Modulo1632_RE223132_2024.V217.value_counts(dropna=False)

V217
3    9952
8    7339
6    6854
2    6221
1    1445
4    1327
5    1114
Name: count, dtype: int64

In [26]:
Modulo1633_REC41_2024_fil.M45.value_counts(dropna=False)

M45
1.0    14283
NaN     3353
0.0      695
8.0        4
Name: count, dtype: int64

In [7]:
Modulo1633_REC94_2024_fil.S413.value_counts(dropna=False)

S413
1.0    12035
NaN     3353
0.0     2947
Name: count, dtype: int64

In [22]:
Modulo1635_RE516171_2024.V228.value_counts(dropna=False)

AttributeError: 'DataFrame' object has no attribute 'V228'

In [5]:
csv_path_target_final = os.path.join(base_dir,"data\\interim", "target_final.csv")

# Load the dataset
target_final = pd.read_csv(csv_path_target_final,usecols = ['CASEID','premature_flag'], low_memory=False)
target_final.shape

(18335, 2)

In [6]:
Modulo1632_RE223132_2024.CASEID.nunique()
key_variables =['CASEID']

# 2 Data Wrangling

## 2.1 csv_path_Modulo1633_REC41_2024_fil

In [1]:
Modulo1633_REC41_2024_fil.M13.value_counts()

NameError: name 'Modulo1633_REC41_2024_fil' is not defined

In [7]:
Modulo1633_REC41_2024_fil.info(verbose = True)

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 18335 entries, 0 to 18334
Data columns (total 89 columns):
 #   Column          Non-Null Count  Dtype
---  ------          --------------  -----
 0   premature_flag  18335 non-null  int64
 1   M2A             14982 non-null  float64
 2   M2B             14982 non-null  float64
 3   M2C             14982 non-null  float64
 4   M2D             14982 non-null  float64
 5   M2E             14982 non-null  float64
 6   M2G             14982 non-null  float64
 7   M2K             14982 non-null  float64
 8   M2N             14982 non-null  float64
 9   M3A             16983 non-null  float64
 10  M3B             16983 non-null  float64
 11  M3C             16983 non-null  float64
 12  M3D             16983 non-null  float64
 13  M3E             16983 non-null  float64
 14  M3G             16983 non-null  float64
 15  M3H             16983 non-null  float64
 16  M3K             16983 non-null  float64
 17  M3N             16983 non-null  float64
 18  M17             16983 non-null  float64
 19  M54             14982 non-null  float64
 20  M57E            14858 non-null  float64
 21  M57F            14858 non-null  float64
 22  M57G            14858 non-null  float64
 23  M57I            14858 non-null  float64
 24  M57J            14858 non-null  float64
 25  M57K            14858 non-null  float64
 26  M57L            14858 non-null  float64
 27  M57M            14858 non-null  float64
 28  M57O            14858 non-null  float64
 29  M57P            14858 non-null  float64
 30  M57Q            14858 non-null  float64
 31  M57S            14858 non-null  float64
 32  M57X            14858 non-null  float64
 33  M66             16983 non-null  float64
 34  CASEID          18335 non-null  object
 35  BIDX_x          18335 non-null  int64
 36  ID1             16983 non-null  float64
 37  MIDX            16983 non-null  float64
 38  M1              14982 non-null  float64
 39  M1A             6980 non-null   float64
 40  M1B             4977 non-null   float64
 41  M1D             481 non-null    float64
 42  M5              16983 non-null  float64
 43  M10             16983 non-null  float64
 44  M15             16983 non-null  float64
 45  M18             16983 non-null  float64
 46  M19A            16803 non-null  float64
 47  M27             16983 non-null  float64
 48  M28             16983 non-null  float64
 49  M29             16983 non-null  float64
 50  M35             5943 non-null   float64
 51  M36             5943 non-null   float64
 52  M38             16867 non-null  float64
 53  M39             16867 non-null  float64
 54  M42A            14858 non-null  float64
 55  M42C            14858 non-null  float64
 56  M42D            14858 non-null  float64
 57  M42E            14858 non-null  float64
 58  M43             14858 non-null  float64
 59  M44             14265 non-null  float64
 60  M45             14982 non-null  float64
 61  M47             14982 non-null  float64
 62  M48             14982 non-null  float64
 63  M55A            16983 non-null  float64
 64  M55B            16983 non-null  float64
 65  M55C            16983 non-null  float64
 66  M55E            16983 non-null  float64
 67  M55F            16983 non-null  float64
 68  M55G            16983 non-null  float64
 69  M55H            16983 non-null  float64
 70  M55I            16983 non-null  float64
 71  M55X            16983 non-null  float64
 72  M55Z            16983 non-null  float64
 73  M60             14982 non-null  float64
 74  M67             14723 non-null  float64
 75  M68             14788 non-null  float64
 76  M69             14788 non-null  float64
 77  M70             14982 non-null  float64
 78  M71             14875 non-null  float64
 79  M72             14875 non-null  float64
 80  M73             14875 non-null  float64
 81  M6              16983 non-null  float64
 82  M7              16983 non-null  float64
 83  M8              16983 non-null  float64
 84  M9              16983 non-null  float64
 85  M11             5037 non-null   float64
 86  M13             14858 non-null  float64
 87  M14             14982 non-null  float64
 88  BIDX            18335 non-null  int64
dtypes: float64(85), int64(3), object(1)
memory usage: 12.4+ MB

In [8]:
# categoricas, M10, M15,M42A,M42C, M42D, M42E, M43, M44,M45, M47, M48, M60, M69

categorical_cols = ['M15', 
                    'M19A',
                     'M27',
                     'M28',
                     'M29', 
                     #'M34',
                     'M10', 
                     #'M15',
                     'M42A',
                     'M42C', 
                     'M42D', 
                     'M42E', 
                     'M43', 
                     'M44',
                     'M45', 
                     'M47', 
                     'M48', 
                     'M60', 
                     'M69',
                     ]


Modulo1633_REC41_2024_fil[categorical_cols].head()

,M15,M19A,M27,M28,M29,M10,M42A,M42C,M42D,M42E,M43,M44,M45,M47,M48,M60,M69
0,21.0,1.0,0.0,0.0,0.0,1.0,1.0,1.0,1.0,1.0,1.0,1.0,1.0,0.0,0.0,0.0,21.0
1,21.0,1.0,0.0,0.0,0.0,3.0,1.0,1.0,1.0,1.0,1.0,1.0,1.0,0.0,0.0,0.0,21.0
2,21.0,1.0,0.0,0.0,0.0,1.0,1.0,1.0,1.0,1.0,1.0,1.0,1.0,0.0,0.0,1.0,21.0
3,21.0,1.0,0.0,0.0,0.0,1.0,1.0,1.0,1.0,1.0,1.0,1.0,1.0,0.0,0.0,0.0,21.0
4,21.0,1.0,0.0,0.0,0.0,1.0,1.0,1.0,1.0,1.0,1.0,1.0,1.0,0.0,0.0,0.0,21.0

In [9]:
key_variables =['CASEID']
numeric_cols, categorical_cols, dummy_cols = categorize_columns (Modulo1633_REC41_2024_fil, key_variables, categorical_cols)

🔹 Numeric columns: 37
🔹 Categorical columns: 17
🔹 Dummy columns: 34

In [10]:
categorical_cols.append('CASEID')
df_categorical = Modulo1633_REC41_2024_fil[categorical_cols].merge(target_final, how= 'left', on ='CASEID')

df_categorical_cod, encoding_map, encoder = target_encode_dataframe_map(df_categorical,
                                                               target_col='premature_flag', id_col='CASEID')

✅ Encoded 17 categorical columns.

In [11]:
df_categorical_cod.head()

,CASEID,M27,M10,M42C,M44,M45,M60,M42D,M15,M42A,M47,M29,M42E,M69,M19A,M43,M48,M28,premature_flag
0,325503101 2,0.194256,0.202711,0.193222,0.191153,0.193667,0.192802,0.192654,0.212246,0.193124,0.190103,0.194416,0.192830,0.207502,0.190584,0.191223,0.190727,0.194176,1
1,325504701 2,0.193653,0.194756,0.191335,0.189192,0.191601,0.191533,0.190574,0.214105,0.191387,0.189233,0.193798,0.190915,0.207762,0.189582,0.189348,0.189684,0.193824,0
2,325505001 1,0.194258,0.201619,0.192934,0.190476,0.193464,0.202129,0.192000,0.213112,0.192869,0.191204,0.194418,0.192459,0.208136,0.193043,0.190539,0.192188,0.194252,0
3,325508901 2,0.194256,0.202711,0.193222,0.191153,0.193667,0.192802,0.192654,0.212246,0.193124,0.190103,0.194416,0.192830,0.207502,0.190584,0.191223,0.190727,0.194176,0
4,325509701 2,0.194258,0.201619,0.192934,0.190476,0.193464,0.193568,0.192000,0.213112,0.192869,0.191204,0.194418,0.192459,0.208136,0.193043,0.190539,0.192188,0.194252,0

In [12]:
df_categorical_cod = fill_missing_with_mode(df_categorical_cod)

In [13]:
df_numeric_cols = fill_missing_with_median_coding(Modulo1633_REC41_2024_fil[numeric_cols])

Shape after transformation: (18335, 37)

In [14]:
df_load_dummy_cols =  fill_missing_with_mode(Modulo1633_REC41_2024_fil[dummy_cols])

In [15]:
df_categorical_cod.shape, df_numeric_cols.shape, df_load_dummy_cols.shape

((18335, 19), (18335, 37), (18335, 34))

In [16]:
df_categorical_cod.info(verbose = True, show_counts = True)

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 18335 entries, 0 to 18334
Data columns (total 19 columns):
 #   Column          Non-Null Count  Dtype
---  ------          --------------  -----
 0   CASEID          18335 non-null  object
 1   M27             18335 non-null  float64
 2   M10             18335 non-null  float64
 3   M42C            18335 non-null  float64
 4   M44             18335 non-null  float64
 5   M45             18335 non-null  float64
 6   M60             18335 non-null  float64
 7   M42D            18335 non-null  float64
 8   M15             18335 non-null  float64
 9   M42A            18335 non-null  float64
 10  M47             18335 non-null  float64
 11  M29             18335 non-null  float64
 12  M42E            18335 non-null  float64
 13  M69             18335 non-null  float64
 14  M19A            18335 non-null  float64
 15  M43             18335 non-null  float64
 16  M48             18335 non-null  float64
 17  M28             18335 non-null  float64
 18  premature_flag  18335 non-null  int64
dtypes: float64(17), int64(1), object(1)
memory usage: 2.7+ MB

In [17]:
Modulo1633_REC41_2024_fil_clear = pd.concat([df_numeric_cols,
                                              df_load_dummy_cols, 
                                              df_categorical_cod], axis=1)
Modulo1633_REC41_2024_fil_clear.info(verbose = True, show_counts = True)

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 18335 entries, 0 to 18334
Data columns (total 90 columns):
 #   Column          Non-Null Count  Dtype
---  ------          --------------  -----
 0   BIDX_x          18335 non-null  float64
 1   ID1             18335 non-null  float64
 2   MIDX            18335 non-null  float64
 3   M1              18335 non-null  float64
 4   M1A             18335 non-null  float64
 5   M1B             18335 non-null  float64
 6   M1D             18335 non-null  float64
 7   M5              18335 non-null  float64
 8   M18             18335 non-null  float64
 9   M35             18335 non-null  float64
 10  M36             18335 non-null  float64
 11  M38             18335 non-null  float64
 12  M39             18335 non-null  float64
 13  M55A            18335 non-null  float64
 14  M55B            18335 non-null  float64
 15  M55C            18335 non-null  float64
 16  M55E            18335 non-null  float64
 17  M55F            18335 non-null  float64
 18  M55G            18335 non-null  float64
 19  M55H            18335 non-null  float64
 20  M55I            18335 non-null  float64
 21  M55X            18335 non-null  float64
 22  M55Z            18335 non-null  float64
 23  M67             18335 non-null  float64
 24  M68             18335 non-null  float64
 25  M70             18335 non-null  float64
 26  M71             18335 non-null  float64
 27  M72             18335 non-null  float64
 28  M73             18335 non-null  float64
 29  M6              18335 non-null  float64
 30  M7              18335 non-null  float64
 31  M8              18335 non-null  float64
 32  M9              18335 non-null  float64
 33  M11             18335 non-null  float64
 34  M13             18335 non-null  float64
 35  M14             18335 non-null  float64
 36  BIDX            18335 non-null  float64
 37  premature_flag  18335 non-null  int64
 38  M2A             18335 non-null  float64
 39  M2B             18335 non-null  float64
 40  M2C             18335 non-null  float64
 41  M2D             18335 non-null  float64
 42  M2E             18335 non-null  float64
 43  M2G             18335 non-null  float64
 44  M2K             18335 non-null  float64
 45  M2N             18335 non-null  float64
 46  M3A             18335 non-null  float64
 47  M3B             18335 non-null  float64
 48  M3C             18335 non-null  float64
 49  M3D             18335 non-null  float64
 50  M3E             18335 non-null  float64
 51  M3G             18335 non-null  float64
 52  M3H             18335 non-null  float64
 53  M3K             18335 non-null  float64
 54  M3N             18335 non-null  float64
 55  M17             18335 non-null  float64
 56  M54             18335 non-null  float64
 57  M57E            18335 non-null  float64
 58  M57F            18335 non-null  float64
 59  M57G            18335 non-null  float64
 60  M57I            18335 non-null  float64
 61  M57J            18335 non-null  float64
 62  M57K            18335 non-null  float64
 63  M57L            18335 non-null  float64
 64  M57M            18335 non-null  float64
 65  M57O            18335 non-null  float64
 66  M57P            18335 non-null  float64
 67  M57Q            18335 non-null  float64
 68  M57S            18335 non-null  float64
 69  M57X            18335 non-null  float64
 70  M66             18335 non-null  float64
 71  CASEID          18335 non-null  object
 72  M27             18335 non-null  float64
 73  M10             18335 non-null  float64
 74  M42C            18335 non-null  float64
 75  M44             18335 non-null  float64
 76  M45             18335 non-null  float64
 77  M60             18335 non-null  float64
 78  M42D            18335 non-null  float64
 79  M15             18335 non-null  float64
 80  M42A            18335 non-null  float64
 81  M47             18335 non-null  float64
 82  M29             18335 non-null  float64
 83  M42E            18335 non-null  float64
 84  M69             18335 non-null  float64
 85  M19A            18335 non-null  float64
 86  M43             18335 non-null  float64
 87  M48             18335 non-null  float64
 88  M28             18335 non-null  float64
 89  premature_flag  18335 non-null  int64
dtypes: float64(87), int64(2), object(1)
memory usage: 12.6+ MB

In [18]:
save_file(Modulo1633_REC41_2024_fil_clear, output_file = "Modulo1633_REC41_2024_fil_clear_v3.csv")
save_txt(encoding_map, dir="data\\interim",output_file="encoding_map_REC41.txt")

✅ File saved successfully at: c:\Users\linoc\OneDrive\Encoder\03_partos\02_scripts\Premature_model\data\interim\encoding_map_REC41.txt

## 3.2 Modulo1633_REC94_2024_fil

In [19]:
Modulo1633_REC94_2024_fil.info(verbose = True, show_counts=True)

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 18335 entries, 0 to 18334
Data columns (total 54 columns):
 #   Column          Non-Null Count  Dtype
---  ------          --------------  -----
 0   premature_flag  18335 non-null  int64
 1   S413            14982 non-null  float64
 2   S426E           6081 non-null   float64
 3   S426GA          14982 non-null  float64
 4   S426GB          14982 non-null  float64
 5   S426GC          14982 non-null  float64
 6   S426GD          14982 non-null  float64
 7   S426GE          14982 non-null  float64
 8   S430D           15095 non-null  float64
 9   S427DA          14982 non-null  float64
 10  S427DB          14982 non-null  float64
 11  S427DC          14982 non-null  float64
 12  S427DD          14982 non-null  float64
 13  S427DE          14982 non-null  float64
 14  S427DF          14982 non-null  float64
 15  S427DG          14982 non-null  float64
 16  S427F           4837 non-null   float64
 17  S436C           16835 non-null  float64
 18  S441            16983 non-null  float64
 19  CASEID          18335 non-null  object
 20  IDX94_x         16983 non-null  float64
 21  BIDX            18335 non-null  int64
 22  ID1             16983 non-null  float64
 23  S410B           14790 non-null  float64
 24  S411B           14858 non-null  float64
 25  S411F           14858 non-null  float64
 26  S411G           14858 non-null  float64
 27  S411H           14858 non-null  float64
 28  S411I           14858 non-null  float64
 29  S411J           14858 non-null  float64
 30  S411K           14858 non-null  float64
 31  S411L           14858 non-null  float64
 32  S426B           5135 non-null   float64
 33  S426FB          13350 non-null  float64
 34  S430C           16983 non-null  float64
 35  S431A           14265 non-null  float64
 36  S432            16983 non-null  float64
 37  S435            148 non-null    float64
 38  S440            10831 non-null  float64
 39  S442            12351 non-null  float64
 40  S447            16867 non-null  float64
 41  QI411_M         14858 non-null  float64
 42  QI411F          12428 non-null  float64
 43  QI422A_A        14982 non-null  float64
 44  QI422A_B        14460 non-null  float64
 45  QI422A_C        4060 non-null   float64
 46  QI422A_D        3934 non-null   float64
 47  QI440B          9022 non-null   float64
 48  S411BA          14547 non-null  float64
 49  S411DA          13108 non-null  float64
 50  S411CA          14631 non-null  float64
 51  S411EA          13938 non-null  float64
 52  S422I           14283 non-null  float64
 53  IDX94           16983 non-null  float64
dtypes: float64(51), int64(2), object(1)
memory usage: 7.6+ MB

In [20]:
categorical_cols_REC94 = ['S411B',
                    'S411F',
                    'S411G',
                    'S411H',
                    'S411I',
                    'S411J',
                    'S411K',
                    'S411L',
                    'S426B',
                    #'S426FA',
                    'S426FB',
                    'QI411_M',
                    'QI422A_A',
                    'QI422A_B', 
                    'QI422A_C', 
                    'QI422A_D'
                    ]

In [21]:
numeric_cols_REC94, categorical_cols_REC94, dummy_cols_REC94 = categorize_columns (Modulo1633_REC94_2024_fil, key_variables,categorical_cols_REC94)
dummy_cols_REC94.remove('premature_flag')

🔹 Numeric columns: 19
🔹 Categorical columns: 15
🔹 Dummy columns: 19

In [22]:
Modulo1633_REC94_2024_fil[categorical_cols_REC94].head()

,S411L,QI422A_C,QI422A_A,S426FB,QI422A_D,S411I,S411K,S411H,S411F,QI422A_B,QI411_M,S411J,S411G,S411B,S426B
0,1.0,NaN,1.0,100.0,NaN,1.0,1.0,1.0,1.0,2.0,1.0,1.0,1.0,1.0,NaN
1,1.0,NaN,1.0,100.0,NaN,1.0,1.0,1.0,1.0,2.0,1.0,1.0,1.0,1.0,NaN
2,1.0,NaN,1.0,100.0,NaN,1.0,0.0,1.0,1.0,2.0,1.0,1.0,1.0,1.0,NaN
3,1.0,NaN,1.0,100.0,NaN,1.0,1.0,1.0,1.0,2.0,1.0,1.0,1.0,1.0,NaN
4,1.0,NaN,1.0,101.0,NaN,1.0,1.0,1.0,1.0,2.0,1.0,1.0,1.0,1.0,NaN

In [23]:
categorical_cols_REC94.append('CASEID')

df_categorical_rec94 = Modulo1633_REC94_2024_fil[categorical_cols_REC94].merge(target_final, how= 'left', on ='CASEID')

df_categorical_cod_rec94, encoding_map_rec94, encoder_rec94 = target_encode_dataframe_map(df_categorical_rec94,
                                                               target_col='premature_flag', id_col='CASEID')

df_categorical_cod_rec94.head()

✅ Encoded 15 categorical columns.

,CASEID,S411L,QI422A_C,QI422A_A,S426FB,QI422A_D,S411I,S411K,S411H,S411F,QI422A_B,QI411_M,S411J,S411G,S411B,S426B,premature_flag
0,325503101 2,0.179648,0.190885,0.192052,0.180430,0.191104,0.191480,0.180320,0.193857,0.192963,0.189430,0.190821,0.189523,0.193312,0.192650,0.182181,1
1,325504701 2,0.176358,0.189942,0.190390,0.180148,0.190191,0.189877,0.178021,0.191249,0.191272,0.185641,0.189266,0.186616,0.190622,0.191057,0.183914,0
2,325505001 1,0.180461,0.190426,0.191403,0.180828,0.190980,0.191627,0.222075,0.193476,0.193077,0.187741,0.190112,0.189115,0.191802,0.192679,0.182866,0
3,325508901 2,0.179648,0.190885,0.192052,0.180430,0.191104,0.191480,0.180320,0.193857,0.192963,0.189430,0.190821,0.189523,0.193312,0.192650,0.182181,0
4,325509701 2,0.180461,0.190426,0.191403,0.203308,0.190980,0.191627,0.182156,0.193476,0.193077,0.187741,0.190112,0.189115,0.191802,0.192679,0.182866,0

In [24]:
df_numeric_cols_REC94 = fill_missing_with_median_coding(Modulo1633_REC94_2024_fil[numeric_cols_REC94])
df_numeric_cols_REC94.info(verbose = True, show_counts = True)

Shape after transformation: (18335, 19)
<class 'pandas.core.frame.DataFrame'>
RangeIndex: 18335 entries, 0 to 18334
Data columns (total 19 columns):
 #   Column   Non-Null Count  Dtype
---  ------   --------------  -----
 0   IDX94_x  18335 non-null  float64
 1   BIDX     18335 non-null  float64
 2   ID1      18335 non-null  float64
 3   S410B    18335 non-null  float64
 4   S430C    18335 non-null  float64
 5   S431A    18335 non-null  float64
 6   S432     18335 non-null  float64
 7   S435     18335 non-null  float64
 8   S440     18335 non-null  float64
 9   S442     18335 non-null  float64
 10  S447     18335 non-null  float64
 11  QI411F   18335 non-null  float64
 12  QI440B   18335 non-null  float64
 13  S411BA   18335 non-null  float64
 14  S411DA   18335 non-null  float64
 15  S411CA   18335 non-null  float64
 16  S411EA   18335 non-null  float64
 17  S422I    18335 non-null  float64
 18  IDX94    18335 non-null  float64
dtypes: float64(19)
memory usage: 2.7 MB

In [25]:
df_load_dummy_cols_REC94 =  fill_missing_with_mode(Modulo1633_REC94_2024_fil[dummy_cols_REC94])
df_load_dummy_cols_REC94.info(verbose = True, show_counts= True)

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 18335 entries, 0 to 18334
Data columns (total 18 columns):
 #   Column  Non-Null Count  Dtype
---  ------  --------------  -----
 0   S413    18335 non-null  float64
 1   S426E   18335 non-null  float64
 2   S426GA  18335 non-null  float64
 3   S426GB  18335 non-null  float64
 4   S426GC  18335 non-null  float64
 5   S426GD  18335 non-null  float64
 6   S426GE  18335 non-null  float64
 7   S430D   18335 non-null  float64
 8   S427DA  18335 non-null  float64
 9   S427DB  18335 non-null  float64
 10  S427DC  18335 non-null  float64
 11  S427DD  18335 non-null  float64
 12  S427DE  18335 non-null  float64
 13  S427DF  18335 non-null  float64
 14  S427DG  18335 non-null  float64
 15  S427F   18335 non-null  float64
 16  S436C   18335 non-null  float64
 17  S441    18335 non-null  float64
dtypes: float64(18)
memory usage: 2.5 MB

In [26]:
df_categorical_cod_rec94.shape,  df_numeric_cols_REC94.shape, df_load_dummy_cols_REC94.shape

((18335, 17), (18335, 19), (18335, 18))

In [27]:
Modulo1633_REC94_2024_fil_clear = pd.concat([df_numeric_cols_REC94, 
                                             df_load_dummy_cols_REC94,
                                              df_categorical_cod_rec94], axis=1)

Modulo1633_REC94_2024_fil_clear.info(verbose = True, show_counts = True)

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 18335 entries, 0 to 18334
Data columns (total 54 columns):
 #   Column          Non-Null Count  Dtype
---  ------          --------------  -----
 0   IDX94_x         18335 non-null  float64
 1   BIDX            18335 non-null  float64
 2   ID1             18335 non-null  float64
 3   S410B           18335 non-null  float64
 4   S430C           18335 non-null  float64
 5   S431A           18335 non-null  float64
 6   S432            18335 non-null  float64
 7   S435            18335 non-null  float64
 8   S440            18335 non-null  float64
 9   S442            18335 non-null  float64
 10  S447            18335 non-null  float64
 11  QI411F          18335 non-null  float64
 12  QI440B          18335 non-null  float64
 13  S411BA          18335 non-null  float64
 14  S411DA          18335 non-null  float64
 15  S411CA          18335 non-null  float64
 16  S411EA          18335 non-null  float64
 17  S422I           18335 non-null  float64
 18  IDX94           18335 non-null  float64
 19  S413            18335 non-null  float64
 20  S426E           18335 non-null  float64
 21  S426GA          18335 non-null  float64
 22  S426GB          18335 non-null  float64
 23  S426GC          18335 non-null  float64
 24  S426GD          18335 non-null  float64
 25  S426GE          18335 non-null  float64
 26  S430D           18335 non-null  float64
 27  S427DA          18335 non-null  float64
 28  S427DB          18335 non-null  float64
 29  S427DC          18335 non-null  float64
 30  S427DD          18335 non-null  float64
 31  S427DE          18335 non-null  float64
 32  S427DF          18335 non-null  float64
 33  S427DG          18335 non-null  float64
 34  S427F           18335 non-null  float64
 35  S436C           18335 non-null  float64
 36  S441            18335 non-null  float64
 37  CASEID          18335 non-null  object
 38  S411L           18335 non-null  float64
 39  QI422A_C        18335 non-null  float64
 40  QI422A_A        18335 non-null  float64
 41  S426FB          18335 non-null  float64
 42  QI422A_D        18335 non-null  float64
 43  S411I           18335 non-null  float64
 44  S411K           18335 non-null  float64
 45  S411H           18335 non-null  float64
 46  S411F           18335 non-null  float64
 47  QI422A_B        18335 non-null  float64
 48  QI411_M         18335 non-null  float64
 49  S411J           18335 non-null  float64
 50  S411G           18335 non-null  float64
 51  S411B           18335 non-null  float64
 52  S426B           18335 non-null  float64
 53  premature_flag  18335 non-null  int64
dtypes: float64(52), int64(1), object(1)
memory usage: 7.6+ MB

In [28]:
encoding_map_rec94

{'S411L': {'0.0': 0.2307582932620273,
  '1.0': 0.17827090632940568,
  '8.0': 0.351137384963986,
  'nan': 0.1944199928335902},
 'QI422A_C': {'1.0': 0.20055718123285565,
  '2.0': 0.2255095870447312,
  '8.0': 0.0,
  'nan': 0.1903329169951406},
 'QI422A_A': {'1.0': 0.19107895270772216,
  '2.0': 0.24261635765951195,
  '8.0': 0.15085811217129316,
  'nan': 0.19325961391567134},
 'S426FB': {'100.0': 0.18011182195357203,
  '101.0': 0.19999373713789612,
  '102.0': 0.2321171655030382,
  '103.0': 0.2237231504522903,
  '104.0': 0.14377474070789084,
  '105.0': 0.30194247964351323,
  '106.0': 0.0,
  '107.0': 0.0,
  '108.0': 0.08763371612481448,
  '110.0': 0.351137384963986,
  '113.0': 1.0,
  '115.0': 0.0,
  '116.0': 1.0,
  '120.0': 0.3631239723743611,
  '201.0': 0.0,
  '202.0': 0.0,
  '203.0': 1.0,
  '304.0': 1.0,
  '998.0': 0.3723038397927811,
  'nan': 0.21584250262532076},
 'QI422A_D': {'1.0': 0.2218307061642145,
  '2.0': 0.1769516264894459,
  'nan': 0.19061191001676256},
 'S411I': {'0.0': 0.23943979749526043,
  '1.0': 0.19061925796941065,
  '8.0': 0.19876263071487615,
  'nan': 0.1944199928335902},
 'S411K': {'0.0': 0.2269354834251489,
  '1.0': 0.17941727752317377,
  '8.0': 0.26442103024491526,
  'nan': 0.1944199928335902},
 'S411H': {'0.0': 0.20440853439084816,
  '1.0': 0.1924953544634142,
  '8.0': 0.16523836902803687,
  'nan': 0.1944199928335902},
 'S411F': {'0.0': 0.2540690771492045,
  '1.0': 0.1921804689297172,
  '8.0': 0.17004408699980744,
  'nan': 0.1944199928335902},
 'QI422A_B': {'1.0': 0.20122936856588078,
  '2.0': 0.18718742153602874,
  '8.0': 0.15168244979533013,
  'nan': 0.19896609773623772},
 'QI411_M': {'1.0': 0.18973310081918432,
  '2.0': 0.2147846174316331,
  '8.0': 0.19047867888462047,
  'nan': 0.1944199928335902},
 'S411J': {'0.0': 0.21529530448512416,
  '1.0': 0.18828486477211587,
  '8.0': 0.2683466839607115,
  'nan': 0.1944199928335902},
 'S411G': {'0.0': 0.21346031315512892,
  '1.0': 0.191715061553752,
  '8.0': 0.17641407166540363,
  'nan': 0.1944199928335902},
 'S411B': {'0.0': 0.24403279667261527,
  '1.0': 0.1919637335655019,
  '8.0': 0.30630287261144784,
  'nan': 0.1944199928335902},
 'S426B': {'11.0': 0.0,
  '12.0': 0.09689633325278482,
  '13.0': 0.10371819536925576,
  '14.0': 0.24763311952822792,
  '15.0': 0.23134659788926962,
  '16.0': 0.06205516477849862,
  '17.0': 0.2459281991539135,
  '18.0': 0.054753346215898266,
  '19.0': 0.2967404827843628,
  '20.0': 0.2364294004854623,
  '21.0': 0.22050890470297363,
  '22.0': 0.23542400891565912,
  '23.0': 0.13613616219345318,
  '24.0': 0.16684184049198472,
  '25.0': 0.14948108881836877,
  '96.0': 0.1700029856217634,
  'nan': 0.18325826718246602}}

In [29]:
save_file(Modulo1633_REC94_2024_fil_clear, output_file = "Modulo1633_REC94_2024_fil_clear_v3.csv")
save_txt(encoding_map_rec94, dir="data\\interim",output_file="encoding_map_rec94.txt")

✅ File saved successfully at: c:\Users\linoc\OneDrive\Encoder\03_partos\02_scripts\Premature_model\data\interim\encoding_map_rec94.txt

## Modulo1631_REC91_2024

In [30]:
Modulo1631_REC91_2024.info(verbose= True, show_counts = True)

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 37117 entries, 0 to 37116
Data columns (total 343 columns):
 #    Column    Non-Null Count  Dtype
---   ------    --------------  -----
 0    ID1       37117 non-null  int64
 1    CASEID    37117 non-null  object
 2    SVER      37117 non-null  int64
 3    SREGION   37117 non-null  int64
 4    SSEMES    37117 non-null  int64
 5    SPROVIN   37117 non-null  int64
 6    SDISTRI   37117 non-null  int64
 7    S108N     37117 non-null  object
 8    S108Y     37117 non-null  object
 9    S108G     37117 non-null  object
 10   S111      37117 non-null  object
 11   S112      37117 non-null  object
 12   S119      37117 non-null  object
 13   S119NA    37117 non-null  object
 14   S119NB    37117 non-null  object
 15   S119D     37117 non-null  object
 16   S229A     37117 non-null  object
 17   S229B     37117 non-null  object
 18   S229C     37117 non-null  object
 19   S229D     37117 non-null  object
 20   S229E     37117 non-null  object
 21   S229F     37117 non-null  object
 22   S229G     37117 non-null  object
 23   S229H     37117 non-null  object
 24   S229I     37117 non-null  object
 25   S229J     37117 non-null  object
 26   S229K     37117 non-null  object
 27   S229L     37117 non-null  object
 28   S229X     37117 non-null  object
 29   S229Y     37117 non-null  object
 30   S229A1    37117 non-null  object
 31   S229B1    37117 non-null  object
 32   S229CDAY  37117 non-null  object
 33   S229CM    37117 non-null  object
 34   S229CY    37117 non-null  object
 35   S229DA    37117 non-null  object
 36   S229DB    37117 non-null  object
 37   S229DC    37117 non-null  object
 38   S229DD    37117 non-null  object
 39   S229DE    37117 non-null  object
 40   S229DF    37117 non-null  object
 41   S229DX    37117 non-null  object
 42   S239A     37117 non-null  object
 43   S239B     37117 non-null  object
 44   S239C     37117 non-null  object
 45   S239D     37117 non-null  object
 46   S239E     37117 non-null  object
 47   S239F     37117 non-null  object
 48   S239X     37117 non-null  object
 49   S314      37117 non-null  object
 50   S315B     37117 non-null  object
 51   S317AC    37117 non-null  object
 52   S317AD    37117 non-null  object
 53   S317C     37117 non-null  object
 54   S321A     37117 non-null  object
 55   S325A     37117 non-null  object
 56   S325B     37117 non-null  object
 57   S325CA    37117 non-null  object
 58   S325CB    37117 non-null  object
 59   S325CX    37117 non-null  object
 60   S325D     37117 non-null  object
 61   S325E     37117 non-null  object
 62   S325GA    37117 non-null  object
 63   S325GB    37117 non-null  object
 64   S325GC    37117 non-null  object
 65   S325GD    37117 non-null  object
 66   S325GE    37117 non-null  object
 67   S325GF    37117 non-null  object
 68   S325GG    37117 non-null  object
 69   S325GH    37117 non-null  object
 70   S325GI    37117 non-null  object
 71   S325GJ    37117 non-null  object
 72   S325GK    37117 non-null  object
 73   S327B     37117 non-null  object
 74   S327C     37117 non-null  object
 75   S481AA    37117 non-null  object
 76   S481AB    37117 non-null  object
 77   S481AC    37117 non-null  object
 78   S481AD    37117 non-null  object
 79   S481AE    37117 non-null  object
 80   S481AF    37117 non-null  object
 81   S481AG    37117 non-null  object
 82   S481AX    37117 non-null  object
 83   S481AZ    37117 non-null  object
 84   S484      37117 non-null  object
 85   S484D     37117 non-null  object
 86   S484M     37117 non-null  object
 87   S484Y     37117 non-null  object
 88   S485      37117 non-null  object
 89   S485A     37117 non-null  object
 90   S486      37117 non-null  object
 91   S486A     37117 non-null  object
 92   S486B     37117 non-null  object
 93   S489C     37117 non-null  object
 94   S489D     37117 non-null  object
 95   S490      37117 non-null  object
 96   S490AA    37117 non-null  object
 97   S490AB    37117 non-null  object
 98   S490AC    37117 non-null  object
 99   S490AD    37117 non-null  object
 100  S490AE    37117 non-null  object
 101  S490AF    37117 non-null  object
 102  S490AG    37117 non-null  object
 103  S490AX    37117 non-null  object
 104  S490BA    37117 non-null  object
 105  S490BB    37117 non-null  object
 106  S490BC    37117 non-null  object
 107  S490BD    37117 non-null  object
 108  S490BX    37117 non-null  object
 109  S492A     37117 non-null  object
 110  S492B     37117 non-null  object
 111  S492C     37117 non-null  object
 112  S492D     37117 non-null  object
 113  S492E     37117 non-null  object
 114  S492F     37117 non-null  object
 115  S492G     37117 non-null  object
 116  S493A     37117 non-null  object
 117  S493B     37117 non-null  object
 118  S493C     37117 non-null  object
 119  S493D     37117 non-null  object
 120  S493E     37117 non-null  object
 121  S493F     37117 non-null  object
 122  S493G     37117 non-null  object
 123  S493H     37117 non-null  object
 124  S493I     37117 non-null  object
 125  S493J     37117 non-null  object
 126  S493K     37117 non-null  object
 127  S493L     37117 non-null  object
 128  S493M     37117 non-null  object
 129  S493N     37117 non-null  object
 130  S493O     37117 non-null  object
 131  S493P     37117 non-null  object
 132  S494      37117 non-null  object
 133  S494A     37117 non-null  object
 134  S494B     37117 non-null  object
 135  S495A     37117 non-null  object
 136  S496      37117 non-null  object
 137  S500A     37117 non-null  object
 138  S500B     37117 non-null  object
 139  S500C     37117 non-null  object
 140  S500D     37117 non-null  object
 141  S508A     37117 non-null  object
 142  S512C     37117 non-null  object
 143  S616      37117 non-null  object
 144  S618A     37117 non-null  object
 145  S618B     37117 non-null  object
 146  S618C     37117 non-null  object
 147  S618D     37117 non-null  object
 148  S618E     37117 non-null  object
 149  S618F     37117 non-null  object
 150  S618G     37117 non-null  object
 151  S618H     37117 non-null  object
 152  S618I     37117 non-null  object
 153  S618J     37117 non-null  object
 154  S618K     37117 non-null  object
 155  S618L     37117 non-null  object
 156  S618M     37117 non-null  object
 157  S618X     37117 non-null  object
 158  S621      37117 non-null  object
 159  S621A     37117 non-null  object
 160  S704N     37117 non-null  object
 161  S704Y     37117 non-null  object
 162  S704G     37117 non-null  object
 163  S718      37117 non-null  object
 164  S720A     37117 non-null  object
 165  S802      37117 non-null  object
 166  S802D     37117 non-null  object
 167  S802E     37117 non-null  object
 168  S802F     37117 non-null  object
 169  S802H     37117 non-null  object
 170  S802I     37117 non-null  object
 171  S803AF    37117 non-null  object
 172  S803AG    37117 non-null  object
 173  S803AM    37117 non-null  object
 174  S804A     37117 non-null  object
 175  S804C     37117 non-null  object
 176  S806AX    37117 non-null  object
 177  S806AZ    37117 non-null  object
 178  S807      37117 non-null  object
 179  S809      37117 non-null  object
 180  S810      37117 non-null  object
 181  S811      37117 non-null  object
 182  S815AA    37117 non-null  object
 183  S815AB    37117 non-null  object
 184  S815AC    37117 non-null  object
 185  S815AD    37117 non-null  object
 186  S815AE    37117 non-null  object
 187  S815AX    37117 non-null  object
 188  S815AZ    37117 non-null  object
 189  S816A     37117 non-null  object
 190  S816B     37117 non-null  object
 191  S816C     37117 non-null  object
 192  S816D     37117 non-null  object
 193  S816E     37117 non-null  object
 194  S816F     37117 non-null  object
 195  S816G     37117 non-null  object
 196  S816H     37117 non-null  object
 197  S816I     37117 non-null  object
 198  S816J     37117 non-null  object
 199  S816K     37117 non-null  object
 200  S816L     37117 non-null  object
 201  S816M     37117 non-null  object
 202  S816W     37117 non-null  object
 203  S816Z     37117 non-null  object
 204  S816AA    37117 non-null  object
 205  S816AB    37117 non-null  object
 206  S816AC    37117 non-null  object
 207  S816AD    37117 non-null  object
 208  S816AE    37117 non-null  object
 209  S816AF    37117 non-null  object
 210  S816AG    37117 non-null  object
 211  S816AH    37117 non-null  object
 212  S816AI    37117 non-null  object
 213  S816AJ    37117 non-null  object
 214  S816AK    37117 non-null  object
 215  S816AL    37117 non-null  object
 216  S816AW    37117 non-null  object
 217  S816AZ    37117 non-null  object
 218  S817      37117 non-null  object
 219  S817GF    37117 non-null  object
 220  S817GG    37117 non-null  object
 221  S817GM    37117 non-null  object
 222  S818      37117 non-null  object
 223  S1002A    37117 non-null  object
 224  S1002B    37117 non-null  object
 225  S1002C    37117 non-null  object
 226  S1002D    37117 non-null  object
 227  S1002E    37117 non-null  object
 228  S1008AN   37117 non-null  object
 229  S1008BN   37117 non-null  object
 230  S1008CN   37117 non-null  object
 231  S1008DN   37117 non-null  object
 232  S1012B    37117 non-null  object
 233  S1012BN   37117 non-null  object
 234  S1017     37117 non-null  object
 235  S1023AA   37117 non-null  object
 236  S1023AB   37117 non-null  object
 237  S1023AC   37117 non-null  object
 238  S1023AD   37117 non-null  object
 239  S1023AE   37117 non-null  object
 240  S1023AF   37117 non-null  object
 241  S1023AG   37117 non-null  object
 242  S1023AH   37117 non-null  object
 243  S1023AX   37117 non-null  object
 244  S1023AZ   37117 non-null  object
 245  S1026     37117 non-null  object
 246  S1030AA   37117 non-null  object
 247  S1030AB   37117 non-null  object
 248  S1030AC   37117 non-null  object
 249  S1030AD   37117 non-null  object
 250  S1030AE   37117 non-null  object
 251  S1030AF   37117 non-null  object
 252  S1030AG   37117 non-null  object
 253  S1030AH   37117 non-null  object
 254  S1030AI   37117 non-null  object
 255  S1030AJ   37117 non-null  object
 256  S1030AK   37117 non-null  object
 257  S1030AL   37117 non-null  object
 258  S1030AM   37117 non-null  object
 259  S1030AX   37117 non-null  object
 260  S1030BA   37117 non-null  object
 261  S1030BB   37117 non-null  object
 262  S1030BC   37117 non-null  object
 263  S1030BD   37117 non-null  object
 264  S1030BE   37117 non-null  object
 265  S1030BF   37117 non-null  object
 266  S1030BG   37117 non-null  object
 267  S1030BH   37117 non-null  object
 268  S1030BI   37117 non-null  object
 269  S1030BJ   37117 non-null  object
 270  S1030BK   37117 non-null  object
 271  S1030BL   37117 non-null  object
 272  S1030BM   37117 non-null  object
 273  S1030BX   37117 non-null  object
 274  S1030CA   37117 non-null  object
 275  S1030CB   37117 non-null  object
 276  S1030CC   37117 non-null  object
 277  S1030CD   37117 non-null  object
 278  S1030CE   37117 non-null  object
 279  S1030CF   37117 non-null  object
 280  S1030CG   37117 non-null  object
 281  S1030CH   37117 non-null  object
 282  S1030CI   37117 non-null  object
 283  S1030CJ   37117 non-null  object
 284  S1030CK   37117 non-null  object
 285  S1030CL   37117 non-null  object
 286  S1030CM   37117 non-null  object
 287  S1030CX   37117 non-null  object
 288  S1031     37117 non-null  object
 289  S1032A    37117 non-null  object
 290  S1032B    37117 non-null  object
 291  S1032C    37117 non-null  object
 292  S1032D    37117 non-null  object
 293  S1032E    37117 non-null  object
 294  S1032F    37117 non-null  object
 295  S1032G    37117 non-null  object
 296  S1032H    37117 non-null  object
 297  S1032I    37117 non-null  object
 298  S1032J    37117 non-null  object
 299  S1032K    37117 non-null  object
 300  S1032L    37117 non-null  object
 301  S1032M    37117 non-null  object
 302  S1032N    37117 non-null  object
 303  S1032X    37117 non-null  object
 304  S1032Y    37117 non-null  object
 305  S1033     37117 non-null  object
 306  S1034A    37117 non-null  object
 307  S1034B    37117 non-null  object
 308  QI479E_A  37117 non-null  object
 309  QI479E_B  37117 non-null  object
 310  QI479E_C  37117 non-null  object
 311  QI479E_D  37117 non-null  object
 312  QI479E_E  37117 non-null  object
 313  QI479E_F  37117 non-null  object
 314  QI479E_G  37117 non-null  object
 315  QI479E_H  37117 non-null  object
 316  QI479E_I  37117 non-null  object
 317  QI479E_J  37117 non-null  object
 318  QI479E_X  37117 non-null  object
 319  QI479E_Y  37117 non-null  object
 320  QI479F_A  37117 non-null  object
 321  QI479F_B  37117 non-null  object
 322  QI479F_C  37117 non-null  object
 323  QI479F_D  37117 non-null  object
 324  QI479F_E  37117 non-null  object
 325  QI479F_F  37117 non-null  object
 326  QI479F_G  37117 non-null  object
 327  QI479F_H  37117 non-null  object
 328  QI479F_I  37117 non-null  object
 329  QI479F_J  37117 non-null  object
 330  QI479F_K  37117 non-null  object
 331  QI479F_L  37117 non-null  object
 332  QI479F_M  37117 non-null  object
 333  QI479F_X  37117 non-null  object
 334  QI479F_Y  37117 non-null  object
 335  Q479A     37117 non-null  object
 336  Q479B     37117 non-null  object
 337  Q479C     37117 non-null  object
 338  Q479D     37117 non-null  object
 339  S1028A    37117 non-null  object
 340  S1028B    37117 non-null  object
 341  S1028X    37117 non-null  object
 342  S1028Y    37117 non-null  object
dtypes: int64(6), object(337)
memory usage: 97.1+ MB

In [31]:
Modulo1631_REC91_2024_M = convert_objects_to_int64_safe(Modulo1631_REC91_2024)
Modulo1631_REC91_2024_M = Modulo1631_REC91_2024_M.dropna(axis=1, how="all")
Modulo1631_REC91_2024_M.info(verbose = True, show_counts = True)

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 37117 entries, 0 to 37116
Data columns (total 299 columns):
 #    Column    Non-Null Count  Dtype
---   ------    --------------  -----
 0    ID1       37117 non-null  int64
 1    CASEID    37117 non-null  object
 2    SVER      37117 non-null  int64
 3    SREGION   37117 non-null  int64
 4    SSEMES    37117 non-null  int64
 5    SPROVIN   37117 non-null  int64
 6    SDISTRI   37117 non-null  int64
 7    S108N     34252 non-null  Int64
 8    S108Y     33910 non-null  Int64
 9    S108G     6326 non-null   Int64
 10   S111      12058 non-null  Int64
 11   S112      4623 non-null   Int64
 12   S119      34252 non-null  Int64
 13   S119NA    27810 non-null  Int64
 14   S119NB    27810 non-null  Int64
 15   S119D     34252 non-null  Int64
 16   S229A     723 non-null    Int64
 17   S229B     723 non-null    Int64
 18   S229C     723 non-null    Int64
 19   S229D     723 non-null    Int64
 20   S229E     723 non-null    Int64
 21   S229F     723 non-null    Int64
 22   S229G     723 non-null    Int64
 23   S229H     723 non-null    Int64
 24   S229I     723 non-null    Int64
 25   S229J     723 non-null    Int64
 26   S229K     723 non-null    Int64
 27   S229L     723 non-null    Int64
 28   S229X     723 non-null    Int64
 29   S229Y     723 non-null    Int64
 30   S229A1    629 non-null    Int64
 31   S239A     34252 non-null  Int64
 32   S239B     34252 non-null  Int64
 33   S239C     34252 non-null  Int64
 34   S239D     34252 non-null  Int64
 35   S239E     34252 non-null  Int64
 36   S239F     34252 non-null  Int64
 37   S239X     34252 non-null  Int64
 38   S321A     9388 non-null   Int64
 39   S325A     11284 non-null  Int64
 40   S325B     254 non-null    Int64
 41   S325CA    254 non-null    Int64
 42   S325CB    254 non-null    Int64
 43   S325CX    254 non-null    Int64
 44   S325D     335 non-null    Int64
 45   S325E     335 non-null    Int64
 46   S327B     2659 non-null   Int64
 47   S327C     1282 non-null   Int64
 48   S481AA    17496 non-null  Int64
 49   S481AB    17496 non-null  Int64
 50   S481AC    17496 non-null  Int64
 51   S481AD    17496 non-null  Int64
 52   S481AE    17496 non-null  Int64
 53   S481AF    17496 non-null  Int64
 54   S481AG    17496 non-null  Int64
 55   S481AX    17496 non-null  Int64
 56   S481AZ    17496 non-null  Int64
 57   S489C     30623 non-null  Int64
 58   S489D     30623 non-null  Int64
 59   S490      34252 non-null  Int64
 60   S490AA    34245 non-null  Int64
 61   S490AB    34245 non-null  Int64
 62   S490AC    34245 non-null  Int64
 63   S490AD    34245 non-null  Int64
 64   S490AE    34245 non-null  Int64
 65   S490AF    34245 non-null  Int64
 66   S490AG    34245 non-null  Int64
 67   S490AX    34245 non-null  Int64
 68   S490BA    34245 non-null  Int64
 69   S490BB    34245 non-null  Int64
 70   S490BC    34245 non-null  Int64
 71   S490BD    34245 non-null  Int64
 72   S490BX    34245 non-null  Int64
 73   S492A     11138 non-null  Int64
 74   S492B     11138 non-null  Int64
 75   S492C     11138 non-null  Int64
 76   S492D     11138 non-null  Int64
 77   S492E     11138 non-null  Int64
 78   S492F     11138 non-null  Int64
 79   S492G     11138 non-null  Int64
 80   S493A     11138 non-null  Int64
 81   S493B     11138 non-null  Int64
 82   S493C     11138 non-null  Int64
 83   S493D     11138 non-null  Int64
 84   S493E     11138 non-null  Int64
 85   S493F     11138 non-null  Int64
 86   S493G     11138 non-null  Int64
 87   S493H     11138 non-null  Int64
 88   S493I     11138 non-null  Int64
 89   S493J     11138 non-null  Int64
 90   S493K     11138 non-null  Int64
 91   S493L     11138 non-null  Int64
 92   S493M     11138 non-null  Int64
 93   S493N     11138 non-null  Int64
 94   S493O     11138 non-null  Int64
 95   S493P     11138 non-null  Int64
 96   S495A     1057 non-null   Int64
 97   S496      10089 non-null  Int64
 98   S500A     34252 non-null  Int64
 99   S500B     34252 non-null  Int64
 100  S500C     34252 non-null  Int64
 101  S500D     34252 non-null  Int64
 102  S508A     4414 non-null   Int64
 103  S512C     5778 non-null   Int64
 104  S618A     34252 non-null  Int64
 105  S618B     34252 non-null  Int64
 106  S618C     34252 non-null  Int64
 107  S618D     34252 non-null  Int64
 108  S618E     34252 non-null  Int64
 109  S618F     34252 non-null  Int64
 110  S618G     34252 non-null  Int64
 111  S618H     34252 non-null  Int64
 112  S618I     34252 non-null  Int64
 113  S618J     34252 non-null  Int64
 114  S618K     34252 non-null  Int64
 115  S618L     34252 non-null  Int64
 116  S618M     34252 non-null  Int64
 117  S618X     34252 non-null  Int64
 118  S621      19779 non-null  Int64
 119  S621A     19779 non-null  Int64
 120  S704N     24189 non-null  Int64
 121  S704Y     23975 non-null  Int64
 122  S704G     3310 non-null   Int64
 123  S720A     18579 non-null  Int64
 124  S802      33206 non-null  Int64
 125  S802D     33206 non-null  Int64
 126  S802E     33206 non-null  Int64
 127  S802F     33206 non-null  Int64
 128  S802I     33206 non-null  Int64
 129  S803AF    33206 non-null  Int64
 130  S803AG    33206 non-null  Int64
 131  S803AM    33206 non-null  Int64
 132  S804A     24196 non-null  Int64
 133  S804C     23108 non-null  Int64
 134  S806AX    33206 non-null  Int64
 135  S806AZ    33206 non-null  Int64
 136  S807      33206 non-null  Int64
 137  S809      33206 non-null  Int64
 138  S810      33206 non-null  Int64
 139  S811      33206 non-null  Int64
 140  S815AA    34252 non-null  Int64
 141  S815AB    34252 non-null  Int64
 142  S815AC    34252 non-null  Int64
 143  S815AD    34252 non-null  Int64
 144  S815AE    34252 non-null  Int64
 145  S815AX    34252 non-null  Int64
 146  S815AZ    34252 non-null  Int64
 147  S816A     33264 non-null  Int64
 148  S816B     33264 non-null  Int64
 149  S816C     33264 non-null  Int64
 150  S816D     33264 non-null  Int64
 151  S816E     33264 non-null  Int64
 152  S816F     33264 non-null  Int64
 153  S816G     33264 non-null  Int64
 154  S816H     33264 non-null  Int64
 155  S816I     33264 non-null  Int64
 156  S816J     33264 non-null  Int64
 157  S816K     33264 non-null  Int64
 158  S816L     33264 non-null  Int64
 159  S816M     33264 non-null  Int64
 160  S816W     33264 non-null  Int64
 161  S816Z     33264 non-null  Int64
 162  S816AA    33264 non-null  Int64
 163  S816AB    33264 non-null  Int64
 164  S816AC    33264 non-null  Int64
 165  S816AD    33264 non-null  Int64
 166  S816AE    33264 non-null  Int64
 167  S816AF    33264 non-null  Int64
 168  S816AG    33264 non-null  Int64
 169  S816AH    33264 non-null  Int64
 170  S816AI    33264 non-null  Int64
 171  S816AJ    33264 non-null  Int64
 172  S816AK    33264 non-null  Int64
 173  S816AL    33264 non-null  Int64
 174  S816AW    33264 non-null  Int64
 175  S816AZ    33264 non-null  Int64
 176  S817      20033 non-null  Int64
 177  S817GF    2611 non-null   Int64
 178  S817GG    2611 non-null   Int64
 179  S817GM    2611 non-null   Int64
 180  S1002A    23457 non-null  Int64
 181  S1002B    23457 non-null  Int64
 182  S1002C    23457 non-null  Int64
 183  S1002D    23457 non-null  Int64
 184  S1002E    23457 non-null  Int64
 185  S1008AN   3206 non-null   Int64
 186  S1008BN   538 non-null    Int64
 187  S1008CN   570 non-null    Int64
 188  S1008DN   114 non-null    Int64
 189  S1012B    4581 non-null   Int64
 190  S1012BN   2234 non-null   Int64
 191  S1017     113 non-null    Int64
 192  S1023AA   7778 non-null   Int64
 193  S1023AB   7778 non-null   Int64
 194  S1023AC   7778 non-null   Int64
 195  S1023AD   7778 non-null   Int64
 196  S1023AE   7778 non-null   Int64
 197  S1023AF   7778 non-null   Int64
 198  S1023AG   7778 non-null   Int64
 199  S1023AH   7778 non-null   Int64
 200  S1023AX   7778 non-null   Int64
 201  S1023AZ   7778 non-null   Int64
 202  S1026     24294 non-null  Int64
 203  S1030AA   11591 non-null  Int64
 204  S1030AB   11591 non-null  Int64
 205  S1030AC   11591 non-null  Int64
 206  S1030AD   11591 non-null  Int64
 207  S1030AE   11591 non-null  Int64
 208  S1030AF   11591 non-null  Int64
 209  S1030AG   11591 non-null  Int64
 210  S1030AH   11591 non-null  Int64
 211  S1030AI   11591 non-null  Int64
 212  S1030AJ   11591 non-null  Int64
 213  S1030AK   11591 non-null  Int64
 214  S1030AL   11591 non-null  Int64
 215  S1030AM   11591 non-null  Int64
 216  S1030AX   11591 non-null  Int64
 217  S1030BA   18232 non-null  Int64
 218  S1030BB   18232 non-null  Int64
 219  S1030BC   18232 non-null  Int64
 220  S1030BD   18232 non-null  Int64
 221  S1030BE   18232 non-null  Int64
 222  S1030BF   18232 non-null  Int64
 223  S1030BG   18232 non-null  Int64
 224  S1030BH   18232 non-null  Int64
 225  S1030BI   18232 non-null  Int64
 226  S1030BJ   18232 non-null  Int64
 227  S1030BK   18232 non-null  Int64
 228  S1030BL   18232 non-null  Int64
 229  S1030BM   18232 non-null  Int64
 230  S1030BX   18232 non-null  Int64
 231  S1030CA   926 non-null    Int64
 232  S1030CB   926 non-null    Int64
 233  S1030CC   926 non-null    Int64
 234  S1030CD   926 non-null    Int64
 235  S1030CE   926 non-null    Int64
 236  S1030CF   926 non-null    Int64
 237  S1030CG   926 non-null    Int64
 238  S1030CH   926 non-null    Int64
 239  S1030CI   926 non-null    Int64
 240  S1030CJ   926 non-null    Int64
 241  S1030CK   926 non-null    Int64
 242  S1030CL   926 non-null    Int64
 243  S1030CM   926 non-null    Int64
 244  S1030CX   926 non-null    Int64
 245  S1031     18523 non-null  Int64
 246  S1032A    24294 non-null  Int64
 247  S1032B    24294 non-null  Int64
 248  S1032C    24294 non-null  Int64
 249  S1032D    24294 non-null  Int64
 250  S1032E    24294 non-null  Int64
 251  S1032F    24294 non-null  Int64
 252  S1032G    24294 non-null  Int64
 253  S1032H    24294 non-null  Int64
 254  S1032I    24294 non-null  Int64
 255  S1032J    24294 non-null  Int64
 256  S1032K    24294 non-null  Int64
 257  S1032L    24294 non-null  Int64
 258  S1032M    24294 non-null  Int64
 259  S1032N    24294 non-null  Int64
 260  S1032X    24294 non-null  Int64
 261  S1033     24294 non-null  Int64
 262  S1034A    24287 non-null  Int64
 263  S1034B    24287 non-null  Int64
 264  QI479E_A  11170 non-null  Int64
 265  QI479E_B  11170 non-null  Int64
 266  QI479E_C  11170 non-null  Int64
 267  QI479E_D  11170 non-null  Int64
 268  QI479E_E  11170 non-null  Int64
 269  QI479E_F  11170 non-null  Int64
 270  QI479E_G  11170 non-null  Int64
 271  QI479E_H  11170 non-null  Int64
 272  QI479E_I  11170 non-null  Int64
 273  QI479E_J  11170 non-null  Int64
 274  QI479E_X  11170 non-null  Int64
 275  QI479E_Y  11170 non-null  Int64
 276  QI479F_A  11170 non-null  Int64
 277  QI479F_B  11170 non-null  Int64
 278  QI479F_C  11170 non-null  Int64
 279  QI479F_D  11170 non-null  Int64
 280  QI479F_E  11170 non-null  Int64
 281  QI479F_F  11170 non-null  Int64
 282  QI479F_G  11170 non-null  Int64
 283  QI479F_H  11170 non-null  Int64
 284  QI479F_I  11170 non-null  Int64
 285  QI479F_J  11170 non-null  Int64
 286  QI479F_K  11170 non-null  Int64
 287  QI479F_L  11170 non-null  Int64
 288  QI479F_M  11170 non-null  Int64
 289  QI479F_X  11170 non-null  Int64
 290  QI479F_Y  11170 non-null  Int64
 291  Q479A     11168 non-null  Int64
 292  Q479B     1589 non-null   Int64
 293  Q479C     11168 non-null  Int64
 294  Q479D     1514 non-null   Int64
 295  S1028A    20235 non-null  Int64
 296  S1028B    20235 non-null  Int64
 297  S1028X    20235 non-null  Int64
 298  S1028Y    20235 non-null  Int64
dtypes: Int64(292), int64(6), object(1)
memory usage: 95.0+ MB

In [32]:
Modulo1631_REC91_2024_M = drop_high_null_columns(Modulo1631_REC91_2024_M , threshold=0.45)
Modulo1631_REC91_2024_M.info(verbose = True, show_counts = True)

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 37117 entries, 0 to 37116
Data columns (total 132 columns):
 #    Column   Non-Null Count  Dtype
---   ------   --------------  -----
 0    ID1      37117 non-null  int64
 1    CASEID   37117 non-null  object
 2    SVER     37117 non-null  int64
 3    SREGION  37117 non-null  int64
 4    SSEMES   37117 non-null  int64
 5    SPROVIN  37117 non-null  int64
 6    SDISTRI  37117 non-null  int64
 7    S108N    34252 non-null  Int64
 8    S108Y    33910 non-null  Int64
 9    S119     34252 non-null  Int64
 10   S119NA   27810 non-null  Int64
 11   S119NB   27810 non-null  Int64
 12   S119D    34252 non-null  Int64
 13   S239A    34252 non-null  Int64
 14   S239B    34252 non-null  Int64
 15   S239C    34252 non-null  Int64
 16   S239D    34252 non-null  Int64
 17   S239E    34252 non-null  Int64
 18   S239F    34252 non-null  Int64
 19   S239X    34252 non-null  Int64
 20   S489C    30623 non-null  Int64
 21   S489D    30623 non-null  Int64
 22   S490     34252 non-null  Int64
 23   S490AA   34245 non-null  Int64
 24   S490AB   34245 non-null  Int64
 25   S490AC   34245 non-null  Int64
 26   S490AD   34245 non-null  Int64
 27   S490AE   34245 non-null  Int64
 28   S490AF   34245 non-null  Int64
 29   S490AG   34245 non-null  Int64
 30   S490AX   34245 non-null  Int64
 31   S490BA   34245 non-null  Int64
 32   S490BB   34245 non-null  Int64
 33   S490BC   34245 non-null  Int64
 34   S490BD   34245 non-null  Int64
 35   S490BX   34245 non-null  Int64
 36   S500A    34252 non-null  Int64
 37   S500B    34252 non-null  Int64
 38   S500C    34252 non-null  Int64
 39   S500D    34252 non-null  Int64
 40   S618A    34252 non-null  Int64
 41   S618B    34252 non-null  Int64
 42   S618C    34252 non-null  Int64
 43   S618D    34252 non-null  Int64
 44   S618E    34252 non-null  Int64
 45   S618F    34252 non-null  Int64
 46   S618G    34252 non-null  Int64
 47   S618H    34252 non-null  Int64
 48   S618I    34252 non-null  Int64
 49   S618J    34252 non-null  Int64
 50   S618K    34252 non-null  Int64
 51   S618L    34252 non-null  Int64
 52   S618M    34252 non-null  Int64
 53   S618X    34252 non-null  Int64
 54   S704N    24189 non-null  Int64
 55   S704Y    23975 non-null  Int64
 56   S802     33206 non-null  Int64
 57   S802D    33206 non-null  Int64
 58   S802E    33206 non-null  Int64
 59   S802F    33206 non-null  Int64
 60   S802I    33206 non-null  Int64
 61   S803AF   33206 non-null  Int64
 62   S803AG   33206 non-null  Int64
 63   S803AM   33206 non-null  Int64
 64   S804A    24196 non-null  Int64
 65   S804C    23108 non-null  Int64
 66   S806AX   33206 non-null  Int64
 67   S806AZ   33206 non-null  Int64
 68   S807     33206 non-null  Int64
 69   S809     33206 non-null  Int64
 70   S810     33206 non-null  Int64
 71   S811     33206 non-null  Int64
 72   S815AA   34252 non-null  Int64
 73   S815AB   34252 non-null  Int64
 74   S815AC   34252 non-null  Int64
 75   S815AD   34252 non-null  Int64
 76   S815AE   34252 non-null  Int64
 77   S815AX   34252 non-null  Int64
 78   S815AZ   34252 non-null  Int64
 79   S816A    33264 non-null  Int64
 80   S816B    33264 non-null  Int64
 81   S816C    33264 non-null  Int64
 82   S816D    33264 non-null  Int64
 83   S816E    33264 non-null  Int64
 84   S816F    33264 non-null  Int64
 85   S816G    33264 non-null  Int64
 86   S816H    33264 non-null  Int64
 87   S816I    33264 non-null  Int64
 88   S816J    33264 non-null  Int64
 89   S816K    33264 non-null  Int64
 90   S816L    33264 non-null  Int64
 91   S816M    33264 non-null  Int64
 92   S816W    33264 non-null  Int64
 93   S816Z    33264 non-null  Int64
 94   S816AA   33264 non-null  Int64
 95   S816AB   33264 non-null  Int64
 96   S816AC   33264 non-null  Int64
 97   S816AD   33264 non-null  Int64
 98   S816AE   33264 non-null  Int64
 99   S816AF   33264 non-null  Int64
 100  S816AG   33264 non-null  Int64
 101  S816AH   33264 non-null  Int64
 102  S816AI   33264 non-null  Int64
 103  S816AJ   33264 non-null  Int64
 104  S816AK   33264 non-null  Int64
 105  S816AL   33264 non-null  Int64
 106  S816AW   33264 non-null  Int64
 107  S816AZ   33264 non-null  Int64
 108  S1002A   23457 non-null  Int64
 109  S1002B   23457 non-null  Int64
 110  S1002C   23457 non-null  Int64
 111  S1002D   23457 non-null  Int64
 112  S1002E   23457 non-null  Int64
 113  S1026    24294 non-null  Int64
 114  S1032A   24294 non-null  Int64
 115  S1032B   24294 non-null  Int64
 116  S1032C   24294 non-null  Int64
 117  S1032D   24294 non-null  Int64
 118  S1032E   24294 non-null  Int64
 119  S1032F   24294 non-null  Int64
 120  S1032G   24294 non-null  Int64
 121  S1032H   24294 non-null  Int64
 122  S1032I   24294 non-null  Int64
 123  S1032J   24294 non-null  Int64
 124  S1032K   24294 non-null  Int64
 125  S1032L   24294 non-null  Int64
 126  S1032M   24294 non-null  Int64
 127  S1032N   24294 non-null  Int64
 128  S1032X   24294 non-null  Int64
 129  S1033    24294 non-null  Int64
 130  S1034A   24287 non-null  Int64
 131  S1034B   24287 non-null  Int64
dtypes: Int64(125), int64(6), object(1)
memory usage: 41.8+ MB

In [33]:
categorical_cols_REC91 = ['SREGION',
                          'SPROVIN',
                          'SDISTRI',
                          'S108N',
                          'S112',
                          'S119',
                          'S119NA',
                          'S119NB',
                          'S119D',
                          'S229B1',
                          'S317AC',
                          'S317AD',
                          'S317C',
                          'S321A',
                          'S325A',
                          'S325B',
                          'S325D',
                          'S325E',
                          'S325GA',
                          'S325GB',
                          'S325GC',
                          'S325GD',
                          'S325GE',
                          'S325GF',
                          'S325GG',
                          'S325GH',
                          'S325GI', 
                          'S325GJ',
                          'S325GK',
                          'S621',
                          'S621A',
                          'S704N',
                          'S718',
                          'S720A',
                          'S802',
                          'S802D',
                          'S802E',
                          'S802F',
                          'S802H',
                          'S802I',
                          'S803A',
                          'S806AX',
                        'S806AZ',
                        'S807',
                        'S809',
                        'S8010',
                        'S801',
                        'S1002A',
                        'S1002B',
                        'S1002C',
                        'S1002D',
                        'S1002E',
                        'S1008AN',
                        'S1008BN',
                        'S1008CN',
                        'S1008DN',
                        'S1012BN',
                        'S1026',
                        'S1033',
                        'S1034A',
                        'S1034B',
                        'Q479A',
                        'Q479C'
                    ]

error = ['S112', 'S229B1', 'S317AC', 'S317AD', 'S317C', 'S321A', 'S325A', 'S325B', 'S325D', 'S325E', 'S325GA', 'S325GB', 'S325GC', 'S325GD', 'S325GE', 'S325GF', 'S325GG', 'S325GH', 'S325GI', 'S325GJ', 'S325GK', 'S621', 'S621A', 'S718', 'S720A', 'S802H', 'S803A', 'S8010', 'S801', 'S1008AN', 'S1008BN', 'S1008CN', 'S1008DN', 'S1012BN', 'Q479A', 'Q479C'] 

print(f'number total categor :{len(categorical_cols_REC91)}')
print(f'number Error :{len(error)}')

categorical_cols_REC91 = [col for col in categorical_cols_REC91 if col not in error]

print(f'number total categor after removal:{len(categorical_cols_REC91)}')

for i in Modulo1631_REC91_2024_M[categorical_cols_REC91].columns.to_list():
    print(Modulo1631_REC91_2024_M[i].value_counts())

number total categor :63
number Error :36
number total categor after removal:27
SREGION
3    11743
2    11200
4     9363
1     4811
Name: count, dtype: int64
SPROVIN
1     19006
3      3222
2      3023
6      2176
5      1921
7      1685
4      1422
8      1228
9      1171
11      630
18      484
10      464
12      355
13      141
19       64
17       58
20       27
15       17
16       15
14        8
Name: count, dtype: int64
SDISTRI
1     12479
2      2897
4      2758
5      2618
6      2367
3      2293
7      1790
10     1442
8      1296
9      1106
12      781
11      650
13      631
32      563
14      485
17      326
15      261
43      259
35      213
20      171
18      169
28      165
33      162
25      130
19      124
37      123
42      118
16      116
22       96
29       93
23       82
30       70
40       55
26       49
34       42
41       42
21       28
39       26
31       17
27       12
24       11
36        1
Name: count, dtype: int64
S108N
2    17124
1     6326
3     5452
4     4637
5      371
0      342
Name: count, dtype: Int64
S119
10    27781
1      4972
2       644
4       258
3       201
5       141
9       100
6        63
7        47
11       25
8        16
12        4
Name: count, dtype: Int64
S119NA
10    23322
1      3580
2       604
3        78
11       63
9        62
98       46
5        22
4        11
13        8
6         7
8         3
7         2
12        2
Name: count, dtype: Int64
S119NB
10    23697
1      3048
2       619
98      229
11       82
3        47
9        40
5        14
4         9
12        9
6         7
13        4
8         4
7         1
Name: count, dtype: Int64
S119D
7     13701
1      9518
5      4165
6      2357
98     2164
2      1044
3       758
8       328
4       217
Name: count, dtype: Int64
S704N
2    12442
3     4535
1     3469
4     3191
5      338
0      144
8       70
Name: count, dtype: Int64
S802
1    30458
0     1901
8      847
Name: count, dtype: Int64
S802D
0    23559
1     8915
8      732
Name: count, dtype: Int64
S802E
0    19595
1    12576
8     1035
Name: count, dtype: Int64
S802F
0    18275
1    13654
8     1277
Name: count, dtype: Int64
S802I
0    28028
1     4172
8     1006
Name: count, dtype: Int64
S806AX
0    30527
8     1884
1      795
Name: count, dtype: Int64
S806AZ
0    26816
1     4506
8     1884
Name: count, dtype: Int64
S807
1    22754
0     9812
8      640
Name: count, dtype: Int64
S809
0    25789
1     6760
8      657
Name: count, dtype: Int64
S1002A
1    15380
2     6915
0     1162
Name: count, dtype: Int64
S1002B
1    15080
2     6763
0     1614
Name: count, dtype: Int64
S1002C
1    15249
2     6162
0     2046
Name: count, dtype: Int64
S1002D
1    16850
2     5386
0     1221
Name: count, dtype: Int64
S1002E
1    17761
2     4646
0     1050
Name: count, dtype: Int64
S1026
0    21754
1     2501
8       39
Name: count, dtype: Int64
S1033
0    18090
1     6151
2       53
Name: count, dtype: Int64
S1034A
0    23151
1      735
2      401
Name: count, dtype: Int64
S1034B
0    24092
1      190
2        5
Name: count, dtype: Int64

In [35]:
numeric_cols_REC91, categorical_cols_REC91, dummy_cols_REC91 = categorize_columns (Modulo1631_REC91_2024_M, key_variables,categorical_cols_REC91)

🔹 Numeric columns: 9
🔹 Categorical columns: 27
🔹 Dummy columns: 95

In [36]:
categorical_cols_REC91.append('CASEID')

df_categorical_rec91 = Modulo1631_REC91_2024_M[categorical_cols_REC91].merge(target_final, how= 'left', on ='CASEID')

df_categorical_rec91 = fill_missing_with_mode(df_categorical_rec91)

# df_categorical_cod_rec91= target_encode_dataframe(df_categorical_rec91,target_col='premature_flag', 
#                             smoothing=0.3, min_samples_leaf=20)

df_categorical_cod_rec91, encoding_map_rec91, encoder_rec91 = target_encode_dataframe_map(df_categorical_rec91,
                                                               target_col='premature_flag', id_col='CASEID')

    
df_categorical_cod_rec91.head()

✅ Encoded 27 categorical columns.

,CASEID,S1002C,SPROVIN,S802,S1034B,S806AZ,S1033,SREGION,S1026,S119,...,S1034A,S809,S704N,S119NA,S806AX,S1002A,S119NB,S802F,S802E,premature_flag
0,325503101 2,0.090547,0.096994,0.097220,0.095056,0.097723,0.089674,0.091599,0.091974,0.095737,...,0.094139,0.098114,0.094692,0.095271,0.095539,0.086989,0.095400,0.099240,0.096206,1.0
1,325503101 4,0.091286,0.098470,0.097716,0.095003,0.087319,0.089877,0.089094,0.092348,0.095779,...,0.093862,0.098074,0.072367,0.095067,0.095677,0.086961,0.095464,0.085974,0.093605,0.0
2,325503901 2,0.089886,0.095768,0.077579,0.095012,0.097069,0.089406,0.090514,0.092623,0.095013,...,0.093637,0.084782,0.073294,0.095171,0.095641,0.086755,0.094913,0.099769,0.094825,0.0
3,325504701 2,0.118618,0.095768,0.097138,0.095012,0.078905,0.121753,0.090514,0.092623,0.095013,...,0.093637,0.084782,0.073294,0.095171,0.078905,0.125580,0.094913,0.099769,0.094825,0.0
4,325505001 1,0.091259,0.096855,0.097262,0.094880,0.098351,0.090038,0.093118,0.092579,0.095376,...,0.093958,0.098035,0.093315,0.094788,0.095425,0.087104,0.095143,0.098790,0.095714,0.0

In [37]:
df_numeric_cols_REC91 = fill_missing_with_median_coding(Modulo1631_REC91_2024_M[numeric_cols_REC91])
df_numeric_cols_REC91.info(verbose = True, show_counts = True)

Shape after transformation: (37117, 9)
<class 'pandas.core.frame.DataFrame'>
RangeIndex: 37117 entries, 0 to 37116
Data columns (total 9 columns):
 #   Column  Non-Null Count  Dtype
---  ------  --------------  -----
 0   ID1     37117 non-null  float64
 1   SSEMES  37117 non-null  float64
 2   S108Y   37117 non-null  float64
 3   S489C   37117 non-null  float64
 4   S489D   37117 non-null  float64
 5   S490    37117 non-null  float64
 6   S704Y   37117 non-null  float64
 7   S810    37117 non-null  float64
 8   S811    37117 non-null  float64
dtypes: float64(9)
memory usage: 2.5 MB

In [38]:
df_load_dummy_cols_REC91 =  fill_missing_with_mode(Modulo1631_REC91_2024_M[dummy_cols_REC91])
df_load_dummy_cols_REC91.info(verbose = True, show_counts= True)

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 37117 entries, 0 to 37116
Data columns (total 95 columns):
 #   Column  Non-Null Count  Dtype
---  ------  --------------  -----
 0   SVER    37117 non-null  int64
 1   S239A   37117 non-null  Int64
 2   S239B   37117 non-null  Int64
 3   S239C   37117 non-null  Int64
 4   S239D   37117 non-null  Int64
 5   S239E   37117 non-null  Int64
 6   S239F   37117 non-null  Int64
 7   S239X   37117 non-null  Int64
 8   S490AA  37117 non-null  Int64
 9   S490AB  37117 non-null  Int64
 10  S490AC  37117 non-null  Int64
 11  S490AD  37117 non-null  Int64
 12  S490AE  37117 non-null  Int64
 13  S490AF  37117 non-null  Int64
 14  S490AG  37117 non-null  Int64
 15  S490AX  37117 non-null  Int64
 16  S490BA  37117 non-null  Int64
 17  S490BB  37117 non-null  Int64
 18  S490BC  37117 non-null  Int64
 19  S490BD  37117 non-null  Int64
 20  S490BX  37117 non-null  Int64
 21  S500A   37117 non-null  Int64
 22  S500B   37117 non-null  Int64
 23  S500C   37117 non-null  Int64
 24  S500D   37117 non-null  Int64
 25  S618A   37117 non-null  Int64
 26  S618B   37117 non-null  Int64
 27  S618C   37117 non-null  Int64
 28  S618D   37117 non-null  Int64
 29  S618E   37117 non-null  Int64
 30  S618F   37117 non-null  Int64
 31  S618G   37117 non-null  Int64
 32  S618H   37117 non-null  Int64
 33  S618I   37117 non-null  Int64
 34  S618J   37117 non-null  Int64
 35  S618K   37117 non-null  Int64
 36  S618L   37117 non-null  Int64
 37  S618M   37117 non-null  Int64
 38  S618X   37117 non-null  Int64
 39  S803AF  37117 non-null  Int64
 40  S803AG  37117 non-null  Int64
 41  S803AM  37117 non-null  Int64
 42  S804A   37117 non-null  Int64
 43  S804C   37117 non-null  Int64
 44  S815AA  37117 non-null  Int64
 45  S815AB  37117 non-null  Int64
 46  S815AC  37117 non-null  Int64
 47  S815AD  37117 non-null  Int64
 48  S815AE  37117 non-null  Int64
 49  S815AX  37117 non-null  Int64
 50  S815AZ  37117 non-null  Int64
 51  S816A   37117 non-null  Int64
 52  S816B   37117 non-null  Int64
 53  S816C   37117 non-null  Int64
 54  S816D   37117 non-null  Int64
 55  S816E   37117 non-null  Int64
 56  S816F   37117 non-null  Int64
 57  S816G   37117 non-null  Int64
 58  S816H   37117 non-null  Int64
 59  S816I   37117 non-null  Int64
 60  S816J   37117 non-null  Int64
 61  S816K   37117 non-null  Int64
 62  S816L   37117 non-null  Int64
 63  S816M   37117 non-null  Int64
 64  S816W   37117 non-null  Int64
 65  S816Z   37117 non-null  Int64
 66  S816AA  37117 non-null  Int64
 67  S816AB  37117 non-null  Int64
 68  S816AC  37117 non-null  Int64
 69  S816AD  37117 non-null  Int64
 70  S816AE  37117 non-null  Int64
 71  S816AF  37117 non-null  Int64
 72  S816AG  37117 non-null  Int64
 73  S816AH  37117 non-null  Int64
 74  S816AI  37117 non-null  Int64
 75  S816AJ  37117 non-null  Int64
 76  S816AK  37117 non-null  Int64
 77  S816AL  37117 non-null  Int64
 78  S816AW  37117 non-null  Int64
 79  S816AZ  37117 non-null  Int64
 80  S1032A  37117 non-null  Int64
 81  S1032B  37117 non-null  Int64
 82  S1032C  37117 non-null  Int64
 83  S1032D  37117 non-null  Int64
 84  S1032E  37117 non-null  Int64
 85  S1032F  37117 non-null  Int64
 86  S1032G  37117 non-null  Int64
 87  S1032H  37117 non-null  Int64
 88  S1032I  37117 non-null  Int64
 89  S1032J  37117 non-null  Int64
 90  S1032K  37117 non-null  Int64
 91  S1032L  37117 non-null  Int64
 92  S1032M  37117 non-null  Int64
 93  S1032N  37117 non-null  Int64
 94  S1032X  37117 non-null  Int64
dtypes: Int64(94), int64(1)
memory usage: 30.2 MB

In [39]:
df_categorical_cod_rec91.shape, df_load_dummy_cols_REC91.shape, df_numeric_cols_REC91.shape

((37117, 29), (37117, 95), (37117, 9))

In [41]:
Modulo1631_REC91_2024_M_clear = pd.concat([df_categorical_cod_rec91, 
                                           df_numeric_cols_REC91,
                                             df_load_dummy_cols_REC91], axis=1)
Modulo1631_REC91_2024_M_clear.info(verbose = True, show_counts = True)

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 37117 entries, 0 to 37116
Data columns (total 133 columns):
 #    Column          Non-Null Count  Dtype
---   ------          --------------  -----
 0    CASEID          37117 non-null  object
 1    S1002C          37117 non-null  float64
 2    SPROVIN         37117 non-null  float64
 3    S802            37117 non-null  float64
 4    S1034B          37117 non-null  float64
 5    S806AZ          37117 non-null  float64
 6    S1033           37117 non-null  float64
 7    SREGION         37117 non-null  float64
 8    S1026           37117 non-null  float64
 9    S119            37117 non-null  float64
 10   S119D           37117 non-null  float64
 11   S807            37117 non-null  float64
 12   S802D           37117 non-null  float64
 13   S1002E          37117 non-null  float64
 14   SDISTRI         37117 non-null  float64
 15   S802I           37117 non-null  float64
 16   S108N           37117 non-null  float64
 17   S1002B          37117 non-null  float64
 18   S1002D          37117 non-null  float64
 19   S1034A          37117 non-null  float64
 20   S809            37117 non-null  float64
 21   S704N           37117 non-null  float64
 22   S119NA          37117 non-null  float64
 23   S806AX          37117 non-null  float64
 24   S1002A          37117 non-null  float64
 25   S119NB          37117 non-null  float64
 26   S802F           37117 non-null  float64
 27   S802E           37117 non-null  float64
 28   premature_flag  37117 non-null  float64
 29   ID1             37117 non-null  float64
 30   SSEMES          37117 non-null  float64
 31   S108Y           37117 non-null  float64
 32   S489C           37117 non-null  float64
 33   S489D           37117 non-null  float64
 34   S490            37117 non-null  float64
 35   S704Y           37117 non-null  float64
 36   S810            37117 non-null  float64
 37   S811            37117 non-null  float64
 38   SVER            37117 non-null  int64
 39   S239A           37117 non-null  Int64
 40   S239B           37117 non-null  Int64
 41   S239C           37117 non-null  Int64
 42   S239D           37117 non-null  Int64
 43   S239E           37117 non-null  Int64
 44   S239F           37117 non-null  Int64
 45   S239X           37117 non-null  Int64
 46   S490AA          37117 non-null  Int64
 47   S490AB          37117 non-null  Int64
 48   S490AC          37117 non-null  Int64
 49   S490AD          37117 non-null  Int64
 50   S490AE          37117 non-null  Int64
 51   S490AF          37117 non-null  Int64
 52   S490AG          37117 non-null  Int64
 53   S490AX          37117 non-null  Int64
 54   S490BA          37117 non-null  Int64
 55   S490BB          37117 non-null  Int64
 56   S490BC          37117 non-null  Int64
 57   S490BD          37117 non-null  Int64
 58   S490BX          37117 non-null  Int64
 59   S500A           37117 non-null  Int64
 60   S500B           37117 non-null  Int64
 61   S500C           37117 non-null  Int64
 62   S500D           37117 non-null  Int64
 63   S618A           37117 non-null  Int64
 64   S618B           37117 non-null  Int64
 65   S618C           37117 non-null  Int64
 66   S618D           37117 non-null  Int64
 67   S618E           37117 non-null  Int64
 68   S618F           37117 non-null  Int64
 69   S618G           37117 non-null  Int64
 70   S618H           37117 non-null  Int64
 71   S618I           37117 non-null  Int64
 72   S618J           37117 non-null  Int64
 73   S618K           37117 non-null  Int64
 74   S618L           37117 non-null  Int64
 75   S618M           37117 non-null  Int64
 76   S618X           37117 non-null  Int64
 77   S803AF          37117 non-null  Int64
 78   S803AG          37117 non-null  Int64
 79   S803AM          37117 non-null  Int64
 80   S804A           37117 non-null  Int64
 81   S804C           37117 non-null  Int64
 82   S815AA          37117 non-null  Int64
 83   S815AB          37117 non-null  Int64
 84   S815AC          37117 non-null  Int64
 85   S815AD          37117 non-null  Int64
 86   S815AE          37117 non-null  Int64
 87   S815AX          37117 non-null  Int64
 88   S815AZ          37117 non-null  Int64
 89   S816A           37117 non-null  Int64
 90   S816B           37117 non-null  Int64
 91   S816C           37117 non-null  Int64
 92   S816D           37117 non-null  Int64
 93   S816E           37117 non-null  Int64
 94   S816F           37117 non-null  Int64
 95   S816G           37117 non-null  Int64
 96   S816H           37117 non-null  Int64
 97   S816I           37117 non-null  Int64
 98   S816J           37117 non-null  Int64
 99   S816K           37117 non-null  Int64
 100  S816L           37117 non-null  Int64
 101  S816M           37117 non-null  Int64
 102  S816W           37117 non-null  Int64
 103  S816Z           37117 non-null  Int64
 104  S816AA          37117 non-null  Int64
 105  S816AB          37117 non-null  Int64
 106  S816AC          37117 non-null  Int64
 107  S816AD          37117 non-null  Int64
 108  S816AE          37117 non-null  Int64
 109  S816AF          37117 non-null  Int64
 110  S816AG          37117 non-null  Int64
 111  S816AH          37117 non-null  Int64
 112  S816AI          37117 non-null  Int64
 113  S816AJ          37117 non-null  Int64
 114  S816AK          37117 non-null  Int64
 115  S816AL          37117 non-null  Int64
 116  S816AW          37117 non-null  Int64
 117  S816AZ          37117 non-null  Int64
 118  S1032A          37117 non-null  Int64
 119  S1032B          37117 non-null  Int64
 120  S1032C          37117 non-null  Int64
 121  S1032D          37117 non-null  Int64
 122  S1032E          37117 non-null  Int64
 123  S1032F          37117 non-null  Int64
 124  S1032G          37117 non-null  Int64
 125  S1032H          37117 non-null  Int64
 126  S1032I          37117 non-null  Int64
 127  S1032J          37117 non-null  Int64
 128  S1032K          37117 non-null  Int64
 129  S1032L          37117 non-null  Int64
 130  S1032M          37117 non-null  Int64
 131  S1032N          37117 non-null  Int64
 132  S1032X          37117 non-null  Int64
dtypes: Int64(94), float64(37), int64(1), object(1)
memory usage: 41.0+ MB

In [42]:
save_file(Modulo1631_REC91_2024_M_clear, output_file = "Modulo1631_REC91_2024_M_clear_v3.csv")
save_txt(encoding_map_rec91, dir="data\\interim",output_file="encoding_map_rec91.txt")

✅ File saved successfully at: c:\Users\linoc\OneDrive\Encoder\03_partos\02_scripts\Premature_model\data\interim\encoding_map_rec91.txt

## Modulo1632_RE223132_2024

In [43]:
Modulo1632_RE223132_2024.info(verbose = True, show_counts=True)

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 34252 entries, 0 to 34251
Data columns (total 149 columns):
 #    Column     Non-Null Count  Dtype
---   ------     --------------  -----
 0    ID1        34252 non-null  int64
 1    CASEID     34252 non-null  object
 2    V201       34252 non-null  int64
 3    V202       34252 non-null  int64
 4    V203       34252 non-null  int64
 5    V204       34252 non-null  int64
 6    V205       34252 non-null  int64
 7    V206       34252 non-null  int64
 8    V207       34252 non-null  int64
 9    V208       34252 non-null  int64
 10   V209       34252 non-null  int64
 11   V210       34252 non-null  int64
 12   V211       34252 non-null  object
 13   V212       34252 non-null  object
 14   V213       34252 non-null  int64
 15   V214       34252 non-null  object
 16   V215       34252 non-null  int64
 17   V216       34252 non-null  int64
 18   V217       34252 non-null  int64
 19   V218       34252 non-null  int64
 20   V219       34252 non-null  int64
 21   V220       34252 non-null  int64
 22   V221       34252 non-null  object
 23   V222       34252 non-null  object
 24   V223       34252 non-null  object
 25   V224       34252 non-null  int64
 26   V225       34252 non-null  object
 27   V226       34252 non-null  int64
 28   V227       34252 non-null  int64
 29   V228       34252 non-null  int64
 30   V229       34252 non-null  object
 31   V230       34252 non-null  object
 32   V231       34252 non-null  object
 33   V232       34252 non-null  object
 34   V233       34252 non-null  object
 35   V234       34252 non-null  object
 36   V235       34252 non-null  int64
 37   V237       34252 non-null  object
 38   V238       34252 non-null  int64
 39   V239       34252 non-null  object
 40   V240       34252 non-null  object
 41   V241       34252 non-null  object
 42   V242       34252 non-null  object
 43   V243       34252 non-null  object
 44   V301       34252 non-null  object
 45   V302       34252 non-null  int64
 46   V310       34252 non-null  object
 47   V311       34252 non-null  int64
 48   V312       34252 non-null  int64
 49   V313       34252 non-null  int64
 50   V315       34252 non-null  object
 51   V316       34252 non-null  object
 52   V317       34252 non-null  object
 53   V318       34252 non-null  object
 54   V319       34252 non-null  object
 55   V320       34252 non-null  object
 56   V321       34252 non-null  object
 57   V322       34252 non-null  object
 58   V323       34252 non-null  object
 59   V325A      34252 non-null  object
 60   V326       34252 non-null  object
 61   V327       34252 non-null  object
 62   V337       34252 non-null  object
 63   V359       34252 non-null  object
 64   V360       34252 non-null  object
 65   V361       34252 non-null  int64
 66   V362       34252 non-null  object
 67   V363       34252 non-null  object
 68   V364       34252 non-null  int64
 69   V367       34252 non-null  object
 70   V372       34252 non-null  object
 71   V372A      34252 non-null  object
 72   V375A      34252 non-null  object
 73   V376       34252 non-null  object
 74   V376A      34252 non-null  object
 75   V379       34252 non-null  object
 76   V380       34252 non-null  object
 77   V384A      34252 non-null  int64
 78   V384B      34252 non-null  int64
 79   V384C      34252 non-null  int64
 80   V393       34252 non-null  object
 81   V394       34252 non-null  object
 82   V395       34252 non-null  object
 83   V3A01      34252 non-null  object
 84   V3A02      34252 non-null  object
 85   V3A03      34252 non-null  object
 86   V3A04      34252 non-null  object
 87   V3A05      34252 non-null  object
 88   V3A06      34252 non-null  object
 89   V3A07      34252 non-null  object
 90   V3A08A     34252 non-null  object
 91   V3A08B     34252 non-null  object
 92   V3A08C     34252 non-null  object
 93   V3A08D     34252 non-null  object
 94   V3A08E     34252 non-null  object
 95   V3A08F     34252 non-null  object
 96   V3A08G     34252 non-null  object
 97   V3A08H     34252 non-null  object
 98   V3A08I     34252 non-null  object
 99   V3A08J     34252 non-null  object
 100  V3A08K     34252 non-null  object
 101  V3A08L     34252 non-null  object
 102  V3A08M     34252 non-null  object
 103  V3A08N     34252 non-null  object
 104  V3A08O     34252 non-null  object
 105  V3A08P     34252 non-null  object
 106  V3A08Q     34252 non-null  object
 107  V3A08R     34252 non-null  object
 108  V3A08S     34252 non-null  object
 109  V3A08T     34252 non-null  object
 110  V3A08U     34252 non-null  object
 111  V3A08V     34252 non-null  object
 112  V3A08W     34252 non-null  object
 113  V3A08X     34252 non-null  object
 114  V3A08Z     34252 non-null  object
 115  V3A09A     34252 non-null  object
 116  V3A09B     34252 non-null  object
 117  QI302_05A  34252 non-null  int64
 118  QI302_05B  34252 non-null  int64
 119  V305_01    34252 non-null  int64
 120  V305_02    34252 non-null  int64
 121  V305_03    34252 non-null  int64
 122  V305_05    34252 non-null  int64
 123  V305_06    34252 non-null  int64
 124  V305_07    34252 non-null  int64
 125  V305_08    34252 non-null  int64
 126  V305_09    34252 non-null  int64
 127  V305_10    34252 non-null  int64
 128  V305_11    34252 non-null  int64
 129  V305_13    34252 non-null  int64
 130  V305_14    34252 non-null  int64
 131  V305_15    34252 non-null  int64
 132  V305_16    34252 non-null  int64
 133  V307_01    34252 non-null  object
 134  V307_02    34252 non-null  object
 135  V307_03    34252 non-null  object
 136  V307_04    34252 non-null  object
 137  V307_05    34252 non-null  object
 138  V307_06    34252 non-null  object
 139  V307_07    34252 non-null  object
 140  V307_08    34252 non-null  object
 141  V307_09    34252 non-null  object
 142  V307_10    34252 non-null  object
 143  V307_11    34252 non-null  object
 144  V307_12    34252 non-null  object
 145  V307_13    34252 non-null  object
 146  V307_14    34252 non-null  object
 147  V307_15    34252 non-null  object
 148  V307_16    34252 non-null  object
dtypes: int64(49), object(100)
memory usage: 38.9+ MB

In [44]:
Modulo1632_RE223132_2024_M = convert_objects_to_int64_safe(Modulo1632_RE223132_2024)
Modulo1632_RE223132_2024_M = Modulo1632_RE223132_2024_M.dropna(axis=1, how="all")
Modulo1632_RE223132_2024_M.info(verbose = True, show_counts = True)

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 34252 entries, 0 to 34251
Data columns (total 135 columns):
 #    Column     Non-Null Count  Dtype
---   ------     --------------  -----
 0    ID1        34252 non-null  int64
 1    CASEID     34252 non-null  object
 2    V201       34252 non-null  int64
 3    V202       34252 non-null  int64
 4    V203       34252 non-null  int64
 5    V204       34252 non-null  int64
 6    V205       34252 non-null  int64
 7    V206       34252 non-null  int64
 8    V207       34252 non-null  int64
 9    V208       34252 non-null  int64
 10   V209       34252 non-null  int64
 11   V210       34252 non-null  int64
 12   V211       24627 non-null  Int64
 13   V212       24627 non-null  Int64
 14   V213       34252 non-null  int64
 15   V214       723 non-null    Int64
 16   V215       34252 non-null  int64
 17   V216       34252 non-null  int64
 18   V217       34252 non-null  int64
 19   V218       34252 non-null  int64
 20   V219       34252 non-null  int64
 21   V220       34252 non-null  int64
 22   V221       23451 non-null  Int64
 23   V222       24626 non-null  Int64
 24   V223       723 non-null    Int64
 25   V224       34252 non-null  int64
 26   V225       723 non-null    Int64
 27   V226       34252 non-null  int64
 28   V227       34252 non-null  int64
 29   V228       34252 non-null  int64
 30   V229       5417 non-null   Int64
 31   V230       5417 non-null   Int64
 32   V231       5417 non-null   Int64
 33   V232       5417 non-null   Int64
 34   V233       2060 non-null   Int64
 35   V234       2044 non-null   Int64
 36   V235       34252 non-null  int64
 37   V237       11662 non-null  Int64
 38   V238       34252 non-null  int64
 39   V239       3505 non-null   Int64
 40   V240       3379 non-null   Int64
 41   V241       3379 non-null   Int64
 42   V242       3379 non-null   Int64
 43   V243       3379 non-null   Int64
 44   V302       34252 non-null  int64
 45   V310       27218 non-null  Int64
 46   V311       34252 non-null  int64
 47   V312       34252 non-null  int64
 48   V313       34252 non-null  int64
 49   V315       19600 non-null  Int64
 50   V316       19600 non-null  Int64
 51   V317       19600 non-null  Int64
 52   V318       19600 non-null  Int64
 53   V319       2604 non-null   Int64
 54   V320       2604 non-null   Int64
 55   V321       2604 non-null   Int64
 56   V322       2604 non-null   Int64
 57   V326       15627 non-null  Int64
 58   V327       15620 non-null  Int64
 59   V337       19600 non-null  Int64
 60   V359       20073 non-null  Int64
 61   V360       20073 non-null  Int64
 62   V361       34252 non-null  int64
 63   V362       14650 non-null  Int64
 64   V363       12217 non-null  Int64
 65   V364       34252 non-null  int64
 66   V367       17608 non-null  Int64
 67   V375A      14646 non-null  Int64
 68   V376       2433 non-null   Int64
 69   V384A      34252 non-null  int64
 70   V384B      34252 non-null  int64
 71   V384C      34252 non-null  int64
 72   V393       34248 non-null  Int64
 73   V394       34248 non-null  Int64
 74   V395       15167 non-null  Int64
 75   V3A01      2604 non-null   Int64
 76   V3A02      11284 non-null  Int64
 77   V3A03      3204 non-null   Int64
 78   V3A04      9060 non-null   Int64
 79   V3A05      11284 non-null  Int64
 80   V3A06      2202 non-null   Int64
 81   V3A07      15685 non-null  Int64
 82   V3A08A     12249 non-null  Int64
 83   V3A08B     12249 non-null  Int64
 84   V3A08C     12249 non-null  Int64
 85   V3A08D     12249 non-null  Int64
 86   V3A08E     12249 non-null  Int64
 87   V3A08F     12249 non-null  Int64
 88   V3A08G     12249 non-null  Int64
 89   V3A08H     12249 non-null  Int64
 90   V3A08I     12249 non-null  Int64
 91   V3A08J     12249 non-null  Int64
 92   V3A08K     12249 non-null  Int64
 93   V3A08L     12249 non-null  Int64
 94   V3A08M     12249 non-null  Int64
 95   V3A08N     12249 non-null  Int64
 96   V3A08O     12249 non-null  Int64
 97   V3A08P     12249 non-null  Int64
 98   V3A08Q     12249 non-null  Int64
 99   V3A08R     12249 non-null  Int64
 100  V3A08S     12249 non-null  Int64
 101  V3A08T     12249 non-null  Int64
 102  V3A08U     12249 non-null  Int64
 103  V3A08X     12249 non-null  Int64
 104  V3A08Z     12249 non-null  Int64
 105  QI302_05A  34252 non-null  int64
 106  QI302_05B  34252 non-null  int64
 107  V305_01    34252 non-null  int64
 108  V305_02    34252 non-null  int64
 109  V305_03    34252 non-null  int64
 110  V305_05    34252 non-null  int64
 111  V305_06    34252 non-null  int64
 112  V305_07    34252 non-null  int64
 113  V305_08    34252 non-null  int64
 114  V305_09    34252 non-null  int64
 115  V305_10    34252 non-null  int64
 116  V305_11    34252 non-null  int64
 117  V305_13    34252 non-null  int64
 118  V305_14    34252 non-null  int64
 119  V305_15    34252 non-null  int64
 120  V305_16    34252 non-null  int64
 121  V307_01    10739 non-null  Int64
 122  V307_02    1317 non-null   Int64
 123  V307_03    19230 non-null  Int64
 124  V307_05    17624 non-null  Int64
 125  V307_06    2552 non-null   Int64
 126  V307_07    76 non-null     Int64
 127  V307_08    10787 non-null  Int64
 128  V307_09    16553 non-null  Int64
 129  V307_10    960 non-null    Int64
 130  V307_11    4554 non-null   Int64
 131  V307_13    368 non-null    Int64
 132  V307_14    191 non-null    Int64
 133  V307_15    273 non-null    Int64
 134  V307_16    10656 non-null  Int64
dtypes: Int64(85), int64(49), object(1)
memory usage: 38.1+ MB

In [45]:
Modulo1632_RE223132_2024_M = drop_high_null_columns(Modulo1632_RE223132_2024_M , threshold=0.45)
Modulo1632_RE223132_2024_M.info(verbose = True, show_counts = True)

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 34252 entries, 0 to 34251
Data columns (total 65 columns):
 #   Column     Non-Null Count  Dtype
---  ------     --------------  -----
 0   ID1        34252 non-null  int64
 1   CASEID     34252 non-null  object
 2   V201       34252 non-null  int64
 3   V202       34252 non-null  int64
 4   V203       34252 non-null  int64
 5   V204       34252 non-null  int64
 6   V205       34252 non-null  int64
 7   V206       34252 non-null  int64
 8   V207       34252 non-null  int64
 9   V208       34252 non-null  int64
 10  V209       34252 non-null  int64
 11  V210       34252 non-null  int64
 12  V211       24627 non-null  Int64
 13  V212       24627 non-null  Int64
 14  V213       34252 non-null  int64
 15  V215       34252 non-null  int64
 16  V216       34252 non-null  int64
 17  V217       34252 non-null  int64
 18  V218       34252 non-null  int64
 19  V219       34252 non-null  int64
 20  V220       34252 non-null  int64
 21  V221       23451 non-null  Int64
 22  V222       24626 non-null  Int64
 23  V224       34252 non-null  int64
 24  V226       34252 non-null  int64
 25  V227       34252 non-null  int64
 26  V228       34252 non-null  int64
 27  V235       34252 non-null  int64
 28  V238       34252 non-null  int64
 29  V302       34252 non-null  int64
 30  V310       27218 non-null  Int64
 31  V311       34252 non-null  int64
 32  V312       34252 non-null  int64
 33  V313       34252 non-null  int64
 34  V315       19600 non-null  Int64
 35  V316       19600 non-null  Int64
 36  V317       19600 non-null  Int64
 37  V318       19600 non-null  Int64
 38  V337       19600 non-null  Int64
 39  V359       20073 non-null  Int64
 40  V360       20073 non-null  Int64
 41  V361       34252 non-null  int64
 42  V364       34252 non-null  int64
 43  V384A      34252 non-null  int64
 44  V384B      34252 non-null  int64
 45  V384C      34252 non-null  int64
 46  V393       34248 non-null  Int64
 47  V394       34248 non-null  Int64
 48  QI302_05A  34252 non-null  int64
 49  QI302_05B  34252 non-null  int64
 50  V305_01    34252 non-null  int64
 51  V305_02    34252 non-null  int64
 52  V305_03    34252 non-null  int64
 53  V305_05    34252 non-null  int64
 54  V305_06    34252 non-null  int64
 55  V305_07    34252 non-null  int64
 56  V305_08    34252 non-null  int64
 57  V305_09    34252 non-null  int64
 58  V305_10    34252 non-null  int64
 59  V305_11    34252 non-null  int64
 60  V305_13    34252 non-null  int64
 61  V305_14    34252 non-null  int64
 62  V305_15    34252 non-null  int64
 63  V305_16    34252 non-null  int64
 64  V307_03    19230 non-null  Int64
dtypes: Int64(15), int64(49), object(1)
memory usage: 17.5+ MB

In [46]:

categorical_cols_RE223132 = ['V312',
                          'V313',
                        #   'V326',
                        #   'V327',
                          'V359',
                          'V360',
                          'V361',
                        #   'V362',
                        #   'V363',
                          'V364',
                        #   'V367',
                        #   'V375A',
                        #   'V376',
                        #   'V376A',
                        #   'V379',
                        #   'V380',
                        #   'V3A07'
                    ]

# error = ['S112', 'S229B1', 'S317AC', 'S317AD', 'S317C', 'S321A', 'S325A', 'S325B', 'S325D', 'S325E', 'S325GA', 'S325GB', 'S325GC', 'S325GD', 'S325GE', 'S325GF', 'S325GG', 'S325GH', 'S325GI', 'S325GJ', 'S325GK', 'S621', 'S621A', 'S718', 'S720A', 'S802H', 'S803A', 'S8010', 'S801', 'S1008AN', 'S1008BN', 'S1008CN', 'S1008DN', 'S1012BN', 'Q479A', 'Q479C'] 

# print(f'number total categor :{len(categorical_cols_REC91)}')
# print(f'number Error :{len(error)}')

# categorical_cols_REC91 = [col for col in categorical_cols_REC91 if col not in error]

# print(f'number total categor after removal:{len(categorical_cols_REC91)}')

for i in Modulo1632_RE223132_2024_M[categorical_cols_RE223132].columns.to_list():
    print(Modulo1632_RE223132_2024_M[i].value_counts())

V312
0     14652
3      5941
5      3029
6      2552
11     2546
8      2001
9      1773
1      1274
2       229
10      141
7        52
16       43
13       14
15        5
Name: count, dtype: int64
V313
3    15685
0    14652
2     3774
1      141
Name: count, dtype: int64
V359
3     6199
5     4510
9     2769
8     2613
1     1941
11    1011
16     573
10     252
2      126
13      50
15      16
6        5
14       5
7        3
Name: count, dtype: Int64
V360
1     3903
2     3774
4     3404
13    2229
7     1885
9     1652
8     1040
14     876
6      455
5      272
12     232
3      171
11     154
10      24
98       2
Name: count, dtype: Int64
V361
1    19600
4     7028
2     5135
3     2489
Name: count, dtype: int64
V364
1    15685
3    12217
2     3915
4     2435
Name: count, dtype: int64

In [47]:
numeric_cols_RE223132, categorical_cols_RE223132, dummy_cols_RE223132 = categorize_columns (Modulo1632_RE223132_2024_M, key_variables,categorical_cols_RE223132)

🔹 Numeric columns: 35
🔹 Categorical columns: 6
🔹 Dummy columns: 23

In [48]:
categorical_cols_RE223132.append('CASEID')

df_categorical_RE223132 = Modulo1632_RE223132_2024_M[categorical_cols_RE223132].merge(target_final, how= 'left', on ='CASEID')

df_categorical_RE223132  = fill_missing_with_mode(df_categorical_RE223132)

# df_categorical_RE223132= target_encode_dataframe(df_categorical_RE223132,target_col='premature_flag', 
#                             smoothing=0.3, min_samples_leaf=20)

df_categorical_cod_RE223132, encoding_map_RE223132, encoder_RE223132 = target_encode_dataframe_map(df_categorical_RE223132,
                                                               target_col='premature_flag', id_col='CASEID')
    
df_categorical_RE223132.head()

✅ Encoded 6 categorical columns.

  V313 V364 V359 V360 V312 V361              CASEID  premature_flag
0    2    2    3    1    8    1        325503101  2             1.0
1    0    3    3    1    0    4        325503101  4             0.0
2    0    3    3    1    0    4        325503901  2             0.0
3    2    2    3    1    9    1        325504701  2             0.0
4    3    1    3    4    1    1        325505001  1             0.0

In [49]:
df_categorical_cod_RE223132.head()

,CASEID,V313,V364,V359,V360,V312,V361,premature_flag
0,325503101 2,0.107153,0.107829,0.078865,0.074687,0.104731,0.143155,1.0
1,325503101 4,0.047515,0.047769,0.077752,0.077143,0.047515,0.003588,0.0
2,325503901 2,0.049776,0.051169,0.078865,0.074687,0.049776,0.004937,0.0
3,325504701 2,0.107153,0.107829,0.078865,0.074687,0.109854,0.143155,0.0
4,325505001 1,0.153347,0.153347,0.077752,0.137253,0.112265,0.144517,0.0

In [50]:
df_numeric_cols_RE223132 = fill_missing_with_median_coding(Modulo1632_RE223132_2024_M[numeric_cols_RE223132])
df_numeric_cols_RE223132.info(verbose = True, show_counts = True)

Shape after transformation: (34252, 35)
<class 'pandas.core.frame.DataFrame'>
RangeIndex: 34252 entries, 0 to 34251
Data columns (total 35 columns):
 #   Column     Non-Null Count  Dtype
---  ------     --------------  -----
 0   ID1        34252 non-null  float64
 1   V201       34252 non-null  float64
 2   V202       34252 non-null  float64
 3   V203       34252 non-null  float64
 4   V204       34252 non-null  float64
 5   V205       34252 non-null  float64
 6   V206       34252 non-null  float64
 7   V207       34252 non-null  float64
 8   V208       34252 non-null  float64
 9   V209       34252 non-null  float64
 10  V210       34252 non-null  float64
 11  V211       34252 non-null  float64
 12  V212       34252 non-null  float64
 13  V215       34252 non-null  float64
 14  V217       34252 non-null  float64
 15  V218       34252 non-null  float64
 16  V219       34252 non-null  float64
 17  V220       34252 non-null  float64
 18  V221       34252 non-null  float64
 19  V222       34252 non-null  float64
 20  V224       34252 non-null  float64
 21  V226       34252 non-null  float64
 22  V227       34252 non-null  float64
 23  V235       34252 non-null  float64
 24  V238       34252 non-null  float64
 25  V302       34252 non-null  float64
 26  V310       34252 non-null  float64
 27  V311       34252 non-null  float64
 28  V315       34252 non-null  float64
 29  V316       34252 non-null  float64
 30  V317       34252 non-null  float64
 31  V318       34252 non-null  float64
 32  V337       34252 non-null  float64
 33  QI302_05A  34252 non-null  float64
 34  QI302_05B  34252 non-null  float64
dtypes: float64(35)
memory usage: 9.1 MB

In [51]:
df_load_dummy_cols_RE223132 =  fill_missing_with_mode(Modulo1632_RE223132_2024_M[dummy_cols_RE223132])
df_load_dummy_cols_RE223132.info(verbose = True, show_counts= True)

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 34252 entries, 0 to 34251
Data columns (total 23 columns):
 #   Column   Non-Null Count  Dtype
---  ------   --------------  -----
 0   V213     34252 non-null  int64
 1   V216     34252 non-null  int64
 2   V228     34252 non-null  int64
 3   V384A    34252 non-null  int64
 4   V384B    34252 non-null  int64
 5   V384C    34252 non-null  int64
 6   V393     34252 non-null  Int64
 7   V394     34252 non-null  Int64
 8   V305_01  34252 non-null  int64
 9   V305_02  34252 non-null  int64
 10  V305_03  34252 non-null  int64
 11  V305_05  34252 non-null  int64
 12  V305_06  34252 non-null  int64
 13  V305_07  34252 non-null  int64
 14  V305_08  34252 non-null  int64
 15  V305_09  34252 non-null  int64
 16  V305_10  34252 non-null  int64
 17  V305_11  34252 non-null  int64
 18  V305_13  34252 non-null  int64
 19  V305_14  34252 non-null  int64
 20  V305_15  34252 non-null  int64
 21  V305_16  34252 non-null  int64
 22  V307_03  34252 non-null  Int64
dtypes: Int64(3), int64(20)
memory usage: 6.1 MB

In [52]:
df_numeric_cols_RE223132.shape, df_load_dummy_cols_RE223132.shape,

((34252, 35), (34252, 23))

In [53]:
Modulo1632_RE223132_2024_M_clear = pd.concat([df_numeric_cols_RE223132,
                                               df_load_dummy_cols_RE223132,
                                                 df_categorical_cod_RE223132], axis=1)
Modulo1632_RE223132_2024_M_clear.info(verbose = True, show_counts = True)

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 34252 entries, 0 to 34251
Data columns (total 66 columns):
 #   Column          Non-Null Count  Dtype
---  ------          --------------  -----
 0   ID1             34252 non-null  float64
 1   V201            34252 non-null  float64
 2   V202            34252 non-null  float64
 3   V203            34252 non-null  float64
 4   V204            34252 non-null  float64
 5   V205            34252 non-null  float64
 6   V206            34252 non-null  float64
 7   V207            34252 non-null  float64
 8   V208            34252 non-null  float64
 9   V209            34252 non-null  float64
 10  V210            34252 non-null  float64
 11  V211            34252 non-null  float64
 12  V212            34252 non-null  float64
 13  V215            34252 non-null  float64
 14  V217            34252 non-null  float64
 15  V218            34252 non-null  float64
 16  V219            34252 non-null  float64
 17  V220            34252 non-null  float64
 18  V221            34252 non-null  float64
 19  V222            34252 non-null  float64
 20  V224            34252 non-null  float64
 21  V226            34252 non-null  float64
 22  V227            34252 non-null  float64
 23  V235            34252 non-null  float64
 24  V238            34252 non-null  float64
 25  V302            34252 non-null  float64
 26  V310            34252 non-null  float64
 27  V311            34252 non-null  float64
 28  V315            34252 non-null  float64
 29  V316            34252 non-null  float64
 30  V317            34252 non-null  float64
 31  V318            34252 non-null  float64
 32  V337            34252 non-null  float64
 33  QI302_05A       34252 non-null  float64
 34  QI302_05B       34252 non-null  float64
 35  V213            34252 non-null  int64
 36  V216            34252 non-null  int64
 37  V228            34252 non-null  int64
 38  V384A           34252 non-null  int64
 39  V384B           34252 non-null  int64
 40  V384C           34252 non-null  int64
 41  V393            34252 non-null  Int64
 42  V394            34252 non-null  Int64
 43  V305_01         34252 non-null  int64
 44  V305_02         34252 non-null  int64
 45  V305_03         34252 non-null  int64
 46  V305_05         34252 non-null  int64
 47  V305_06         34252 non-null  int64
 48  V305_07         34252 non-null  int64
 49  V305_08         34252 non-null  int64
 50  V305_09         34252 non-null  int64
 51  V305_10         34252 non-null  int64
 52  V305_11         34252 non-null  int64
 53  V305_13         34252 non-null  int64
 54  V305_14         34252 non-null  int64
 55  V305_15         34252 non-null  int64
 56  V305_16         34252 non-null  int64
 57  V307_03         34252 non-null  Int64
 58  CASEID          34252 non-null  object
 59  V313            34252 non-null  float64
 60  V364            34252 non-null  float64
 61  V359            34252 non-null  float64
 62  V360            34252 non-null  float64
 63  V312            34252 non-null  float64
 64  V361            34252 non-null  float64
 65  premature_flag  34252 non-null  float64
dtypes: Int64(3), float64(42), int64(20), object(1)
memory usage: 17.3+ MB

In [54]:
save_file(Modulo1632_RE223132_2024_M_clear, output_file = "Modulo1632_RE223132_2024_M_clear_v3.csv")
save_txt(encoding_map_RE223132, dir="data\\interim",output_file="encoding_map_RE223132.txt")

✅ File saved successfully at: c:\Users\linoc\OneDrive\Encoder\03_partos\02_scripts\Premature_model\data\interim\encoding_map_RE223132.txt

## Modulo1635_RE516171_2024

In [55]:
Modulo1635_RE516171_2024.info(verbose= True, show_counts = True)

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 34252 entries, 0 to 34251
Data columns (total 84 columns):
 #   Column  Non-Null Count  Dtype
---  ------  --------------  -----
 0   ID1     34252 non-null  int64
 1   CASEID  34252 non-null  object
 2   V501    34252 non-null  int64
 3   V502    34252 non-null  int64
 4   V503    34252 non-null  object
 5   V504    34252 non-null  object
 6   V505    34252 non-null  object
 7   V506    34252 non-null  object
 8   V507    34252 non-null  object
 9   V508    34252 non-null  object
 10  V509    34252 non-null  object
 11  V510    34252 non-null  object
 12  V511    34252 non-null  object
 13  V512    34252 non-null  object
 14  V513    34252 non-null  int64
 15  V525    34252 non-null  int64
 16  V527    34252 non-null  object
 17  V528    34252 non-null  object
 18  V529    34252 non-null  object
 19  V530    34252 non-null  object
 20  V531    34252 non-null  int64
 21  V532    34252 non-null  int64
 22  V535    34252 non-null  object
 23  V536    34252 non-null  int64
 24  V537    34252 non-null  object
 25  V538    34252 non-null  object
 26  V539    34252 non-null  object
 27  V540    34252 non-null  object
 28  V541    34252 non-null  object
 29  V602    34252 non-null  int64
 30  V603    34252 non-null  object
 31  V604    34252 non-null  object
 32  V605    34252 non-null  int64
 33  V613    34252 non-null  int64
 34  V614    34252 non-null  int64
 35  V616    34252 non-null  object
 36  V621    34252 non-null  object
 37  V623    34252 non-null  int64
 38  V624    34252 non-null  int64
 39  V625    34252 non-null  int64
 40  V626    34252 non-null  int64
 41  V627    34252 non-null  int64
 42  V628    34252 non-null  int64
 43  V629    34252 non-null  int64
 44  V631    34252 non-null  object
 45  V632    34252 non-null  object
 46  V633A   34252 non-null  int64
 47  V633B   34252 non-null  int64
 48  V633C   34252 non-null  int64
 49  V633D   34252 non-null  int64
 50  V633E   34252 non-null  object
 51  V633F   34252 non-null  object
 52  V633G   34252 non-null  object
 53  V634    34252 non-null  object
 54  V701    34252 non-null  object
 55  V702    34252 non-null  object
 56  V714    34252 non-null  int64
 57  V714A   34252 non-null  object
 58  V715    34252 non-null  object
 59  V719    34252 non-null  object
 60  V721    34252 non-null  object
 61  V729    34252 non-null  object
 62  V730    34252 non-null  object
 63  V731    34252 non-null  int64
 64  V732    34252 non-null  object
 65  V739    34252 non-null  object
 66  V740    34252 non-null  object
 67  V741    34252 non-null  object
 68  V743A   34252 non-null  object
 69  V743B   34252 non-null  object
 70  V743C   34252 non-null  object
 71  V743D   34252 non-null  object
 72  V743E   34252 non-null  object
 73  V743F   34252 non-null  object
 74  V744A   34252 non-null  int64
 75  V744B   34252 non-null  int64
 76  V744C   34252 non-null  int64
 77  V744D   34252 non-null  int64
 78  V744E   34252 non-null  int64
 79  V746    34252 non-null  object
 80  V704    34252 non-null  object
 81  V716    34252 non-null  object
 82  V705    34252 non-null  object
 83  V717    34252 non-null  int64
dtypes: int64(31), object(53)
memory usage: 22.0+ MB

In [56]:
Modulo1635_RE516171_2024_M = convert_objects_to_int64_safe(Modulo1635_RE516171_2024)
Modulo1635_RE516171_2024_M = Modulo1635_RE516171_2024_M.dropna(axis=1, how="all")
Modulo1635_RE516171_2024_M.info(verbose = True, show_counts = True)

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 34252 entries, 0 to 34251
Data columns (total 76 columns):
 #   Column  Non-Null Count  Dtype
---  ------  --------------  -----
 0   ID1     34252 non-null  int64
 1   CASEID  34252 non-null  object
 2   V501    34252 non-null  int64
 3   V502    34252 non-null  int64
 4   V503    24189 non-null  Int64
 5   V504    19780 non-null  Int64
 6   V507    24189 non-null  Int64
 7   V508    24189 non-null  Int64
 8   V509    24189 non-null  Int64
 9   V510    24189 non-null  Int64
 10  V511    24189 non-null  Int64
 11  V512    24189 non-null  Int64
 12  V513    34252 non-null  int64
 13  V525    34252 non-null  int64
 14  V527    27705 non-null  Int64
 15  V528    27705 non-null  Int64
 16  V529    27705 non-null  Int64
 17  V530    27705 non-null  Int64
 18  V531    34252 non-null  int64
 19  V532    34252 non-null  int64
 20  V535    14472 non-null  Int64
 21  V536    34252 non-null  int64
 22  V537    8581 non-null   Int64
 23  V541    6291 non-null   Int64
 24  V602    34252 non-null  int64
 25  V603    14638 non-null  Int64
 26  V604    14638 non-null  Int64
 27  V605    34252 non-null  int64
 28  V613    34252 non-null  int64
 29  V614    34252 non-null  int64
 30  V616    14672 non-null  Int64
 31  V621    17651 non-null  Int64
 32  V623    34252 non-null  int64
 33  V624    34252 non-null  int64
 34  V625    34252 non-null  int64
 35  V626    34252 non-null  int64
 36  V627    34252 non-null  int64
 37  V628    34252 non-null  int64
 38  V629    34252 non-null  int64
 39  V631    29111 non-null  Int64
 40  V632    16061 non-null  Int64
 41  V633A   34252 non-null  int64
 42  V633B   34252 non-null  int64
 43  V633C   34252 non-null  int64
 44  V633D   34252 non-null  int64
 45  V634    12747 non-null  Int64
 46  V701    24189 non-null  Int64
 47  V702    23975 non-null  Int64
 48  V714    34252 non-null  int64
 49  V714A   15678 non-null  Int64
 50  V715    24189 non-null  Int64
 51  V719    22435 non-null  Int64
 52  V721    22435 non-null  Int64
 53  V729    24189 non-null  Int64
 54  V730    19780 non-null  Int64
 55  V731    34252 non-null  int64
 56  V732    22435 non-null  Int64
 57  V739    10605 non-null  Int64
 58  V740    4709 non-null   Int64
 59  V741    22435 non-null  Int64
 60  V743A   19780 non-null  Int64
 61  V743B   19780 non-null  Int64
 62  V743C   19780 non-null  Int64
 63  V743D   19780 non-null  Int64
 64  V743E   19780 non-null  Int64
 65  V743F   19732 non-null  Int64
 66  V744A   34252 non-null  int64
 67  V744B   34252 non-null  int64
 68  V744C   34252 non-null  int64
 69  V744D   34252 non-null  int64
 70  V744E   34252 non-null  int64
 71  V746    10605 non-null  Int64
 72  V704    24189 non-null  Int64
 73  V716    22435 non-null  Int64
 74  V705    24189 non-null  Int64
 75  V717    34252 non-null  int64
dtypes: Int64(44), int64(31), object(1)
memory usage: 21.3+ MB

In [57]:
Modulo1635_RE516171_2024_M = drop_high_null_columns(Modulo1635_RE516171_2024_M , threshold=0.45)
Modulo1635_RE516171_2024_M.info(verbose = True, show_counts = True)

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 34252 entries, 0 to 34251
Data columns (total 63 columns):
 #   Column  Non-Null Count  Dtype
---  ------  --------------  -----
 0   ID1     34252 non-null  int64
 1   CASEID  34252 non-null  object
 2   V501    34252 non-null  int64
 3   V502    34252 non-null  int64
 4   V503    24189 non-null  Int64
 5   V504    19780 non-null  Int64
 6   V507    24189 non-null  Int64
 7   V508    24189 non-null  Int64
 8   V509    24189 non-null  Int64
 9   V510    24189 non-null  Int64
 10  V511    24189 non-null  Int64
 11  V512    24189 non-null  Int64
 12  V513    34252 non-null  int64
 13  V525    34252 non-null  int64
 14  V527    27705 non-null  Int64
 15  V528    27705 non-null  Int64
 16  V529    27705 non-null  Int64
 17  V530    27705 non-null  Int64
 18  V531    34252 non-null  int64
 19  V532    34252 non-null  int64
 20  V536    34252 non-null  int64
 21  V602    34252 non-null  int64
 22  V605    34252 non-null  int64
 23  V613    34252 non-null  int64
 24  V614    34252 non-null  int64
 25  V623    34252 non-null  int64
 26  V624    34252 non-null  int64
 27  V625    34252 non-null  int64
 28  V626    34252 non-null  int64
 29  V627    34252 non-null  int64
 30  V628    34252 non-null  int64
 31  V629    34252 non-null  int64
 32  V631    29111 non-null  Int64
 33  V633A   34252 non-null  int64
 34  V633B   34252 non-null  int64
 35  V633C   34252 non-null  int64
 36  V633D   34252 non-null  int64
 37  V701    24189 non-null  Int64
 38  V702    23975 non-null  Int64
 39  V714    34252 non-null  int64
 40  V715    24189 non-null  Int64
 41  V719    22435 non-null  Int64
 42  V721    22435 non-null  Int64
 43  V729    24189 non-null  Int64
 44  V730    19780 non-null  Int64
 45  V731    34252 non-null  int64
 46  V732    22435 non-null  Int64
 47  V741    22435 non-null  Int64
 48  V743A   19780 non-null  Int64
 49  V743B   19780 non-null  Int64
 50  V743C   19780 non-null  Int64
 51  V743D   19780 non-null  Int64
 52  V743E   19780 non-null  Int64
 53  V743F   19732 non-null  Int64
 54  V744A   34252 non-null  int64
 55  V744B   34252 non-null  int64
 56  V744C   34252 non-null  int64
 57  V744D   34252 non-null  int64
 58  V744E   34252 non-null  int64
 59  V704    24189 non-null  Int64
 60  V716    22435 non-null  Int64
 61  V705    24189 non-null  Int64
 62  V717    34252 non-null  int64
dtypes: Int64(31), int64(31), object(1)
memory usage: 17.5+ MB

In [58]:
categorical_cols_RE516171 = ['V501','V502','V503',
'V504',
'V510',
# 'V535',
'V536',
# 'V539',
'V602',
'V605',
'V631',
# 'V632',
'V633A',
'V633B', 
'V633C',
'V633D',
# 'V633E',
# 'V633F',
# 'V633G',
# 'V634',
'V701',
'V704',
'V705',
'V716',
'V717',
'V719',
'V729',
'V731',
'V732',
# 'V739',
'V743A','V743B','V743C','V743D','V743E','V743F','V744A','V744B','V744C','V744D','V744E',
# 'V746'
]



# error = ['S112', 'S229B1', 'S317AC', 'S317AD', 'S317C', 'S321A', 'S325A', 'S325B', 'S325D', 'S325E', 'S325GA', 'S325GB', 'S325GC', 'S325GD', 'S325GE', 'S325GF', 'S325GG', 'S325GH', 'S325GI', 'S325GJ', 'S325GK', 'S621', 'S621A', 'S718', 'S720A', 'S802H', 'S803A', 'S8010', 'S801', 'S1008AN', 'S1008BN', 'S1008CN', 'S1008DN', 'S1012BN', 'Q479A', 'Q479C'] 

# print(f'number total categor :{len(categorical_cols_REC91)}')
# print(f'number Error :{len(error)}')

# categorical_cols_REC91 = [col for col in categorical_cols_REC91 if col not in error]

# print(f'number total categor after removal:{len(categorical_cols_REC91)}')

for i in Modulo1635_RE516171_2024_M[categorical_cols_RE516171].columns.to_list():
    print(Modulo1635_RE516171_2024_M[i].value_counts())

V501
2    14819
0    10063
1     4961
5     4251
4       83
3       75
Name: count, dtype: int64
V502
1    19780
0    10063
2     4409
Name: count, dtype: int64
V503
1    19775
2     4414
Name: count, dtype: Int64
V504
1    18088
2     1692
Name: count, dtype: Int64
V510
1    22985
5     1171
6       33
Name: count, dtype: Int64
V536
1    19124
3     6788
0     6547
2     1793
Name: count, dtype: int64
V602
3    16372
1    14638
4     2604
5      470
2      168
Name: count, dtype: int64
V605
5    16372
2    12684
6     2604
1     1579
7      470
3      375
4      168
Name: count, dtype: int64
V631
1    15284
3     8483
2     4904
4      440
Name: count, dtype: Int64
V633A
1    32996
0      858
8      398
Name: count, dtype: int64
V633B
1    33318
0      646
8      288
Name: count, dtype: int64
V633C
1    33272
0      687
8      293
Name: count, dtype: int64
V633D
1    32839
0     1050
8      363
Name: count, dtype: int64
V701
2    12442
3     8064
1     3469
0      144
8       70
Name: count, dtype: Int64
V704
61    6330
88    2773
86    2088
78    1626
98    1461
      ...
82       4
75       2
43       1
12       1
73       1
Name: count, Length: 66, dtype: Int64
V705
4     6781
8     5594
7     4108
1     3225
9     1509
3     1453
2      767
6      688
0       58
98       6
Name: count, dtype: Int64
V716
57    5751
61    4564
94    2616
24    1087
76     877
      ...
11       5
83       4
27       2
71       2
12       2
Name: count, Length: 63, dtype: Int64
V717
0     11831
3      6727
4      5026
1      3614
6      2675
8      1695
7      1303
2      1131
9       235
98       15
Name: count, dtype: int64
V719
2    10580
3     8399
1     3456
Name: count, dtype: Int64
V729
4    9428
5    8064
3    3014
2    1921
1    1548
0     144
8      70
Name: count, dtype: Int64
V731
2    18574
0    11817
1     3522
3      339
Name: count, dtype: int64
V732
1    12255
2     5118
3     5062
Name: count, dtype: Int64
V743A
1    13556
2     4435
4     1718
5       46
3       18
0        7
Name: count, dtype: Int64
V743B
2    11316
1     5541
4     2689
5      146
3       71
0       17
Name: count, dtype: Int64
V743C
1    11213
2     6974
4     1251
3      198
5      140
0        4
Name: count, dtype: Int64
V743D
2    14023
1     4109
4     1365
0      166
5       86
3       31
Name: count, dtype: Int64
V743E
1    14539
2     3759
3      645
5      417
4      400
0       20
Name: count, dtype: Int64
V743F
2    11267
1     4471
4     3957
7       29
5        7
3        1
Name: count, dtype: Int64
V744A
0    34004
1      232
8       16
Name: count, dtype: int64
V744B
0    33844
1      385
8       23
Name: count, dtype: int64
V744C
0    34026
1      205
8       21
Name: count, dtype: int64
V744D
0    34014
1      207
8       31
Name: count, dtype: int64
V744E
0    34014
1      219
8       19
Name: count, dtype: int64

In [62]:
numeric_cols_RE516171, categorical_cols_RE516171, dummy_cols_RE516171 = categorize_columns (Modulo1635_RE516171_2024_M, key_variables,categorical_cols_RE516171)

🔹 Numeric columns: 28
🔹 Categorical columns: 33
🔹 Dummy columns: 1

In [63]:
categorical_cols_RE516171.append('CASEID')

df_categorical_RE516171 = Modulo1635_RE516171_2024_M[categorical_cols_RE516171].merge(target_final, how= 'left', on ='CASEID')

df_categorical_RE516171  = fill_missing_with_mode(df_categorical_RE516171)

# df_categorical_RE516171= target_encode_dataframe(df_categorical_RE516171,target_col='premature_flag', 
#                             smoothing=0.3, min_samples_leaf=20)


df_categorical_cod_RE516171, encoding_map_RE516171, encoder_RE516171 = target_encode_dataframe_map(df_categorical_RE516171,
                                                               target_col='premature_flag', id_col='CASEID')
    
df_categorical_RE516171.head()

✅ Encoded 33 categorical columns.

,V743D,V743E,V510,V602,V744A,V743A,V732,V633C,V536,V633B,...,V705,V744B,V743B,V605,V504,V719,V502,V633D,CASEID,premature_flag
0,2,1,1,3,0,1,1,1,1,1,...,8,0,2,5,1,2,1,1,325503101 2,1.0
1,2,1,1,1,0,1,1,8,0,1,...,4,0,2,2,1,2,0,8,325503101 4,0.0
2,2,1,1,1,0,1,1,1,0,1,...,4,0,2,2,1,2,0,1,325503901 2,0.0
3,2,2,1,3,0,1,1,1,1,1,...,6,0,2,5,1,2,1,1,325504701 2,0.0
4,2,1,1,1,0,2,1,1,1,1,...,8,0,2,2,1,2,1,1,325505001 1,0.0

In [64]:
df_numeric_cols_RE516171 = fill_missing_with_median_coding(Modulo1635_RE516171_2024_M[numeric_cols_RE516171])
df_numeric_cols_RE516171.info(verbose = True, show_counts = True)

Shape after transformation: (34252, 28)
<class 'pandas.core.frame.DataFrame'>
RangeIndex: 34252 entries, 0 to 34251
Data columns (total 28 columns):
 #   Column  Non-Null Count  Dtype
---  ------  --------------  -----
 0   ID1     34252 non-null  float64
 1   V507    34252 non-null  float64
 2   V508    34252 non-null  float64
 3   V509    34252 non-null  float64
 4   V511    34252 non-null  float64
 5   V512    34252 non-null  float64
 6   V513    34252 non-null  float64
 7   V525    34252 non-null  float64
 8   V527    34252 non-null  float64
 9   V528    34252 non-null  float64
 10  V529    34252 non-null  float64
 11  V530    34252 non-null  float64
 12  V531    34252 non-null  float64
 13  V532    34252 non-null  float64
 14  V613    34252 non-null  float64
 15  V614    34252 non-null  float64
 16  V623    34252 non-null  float64
 17  V624    34252 non-null  float64
 18  V625    34252 non-null  float64
 19  V626    34252 non-null  float64
 20  V627    34252 non-null  float64
 21  V628    34252 non-null  float64
 22  V629    34252 non-null  float64
 23  V702    34252 non-null  float64
 24  V715    34252 non-null  float64
 25  V721    34252 non-null  float64
 26  V730    34252 non-null  float64
 27  V741    34252 non-null  float64
dtypes: float64(28)
memory usage: 7.3 MB

In [65]:
df_load_dummy_cols_RE516171 =  fill_missing_with_mode(Modulo1635_RE516171_2024_M[dummy_cols_RE516171])
df_load_dummy_cols_RE516171.info(verbose = True, show_counts= True)

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 34252 entries, 0 to 34251
Data columns (total 1 columns):
 #   Column  Non-Null Count  Dtype
---  ------  --------------  -----
 0   V714    34252 non-null  int64
dtypes: int64(1)
memory usage: 267.7 KB

In [66]:
Modulo1635_RE516171_2024_M_clear = pd.concat([df_numeric_cols_RE516171, 
                                              df_load_dummy_cols_RE516171,
                                                df_categorical_cod_RE516171], axis=1)
Modulo1635_RE516171_2024_M_clear.info(verbose = True, show_counts = True)

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 34252 entries, 0 to 34251
Data columns (total 64 columns):
 #   Column          Non-Null Count  Dtype
---  ------          --------------  -----
 0   ID1             34252 non-null  float64
 1   V507            34252 non-null  float64
 2   V508            34252 non-null  float64
 3   V509            34252 non-null  float64
 4   V511            34252 non-null  float64
 5   V512            34252 non-null  float64
 6   V513            34252 non-null  float64
 7   V525            34252 non-null  float64
 8   V527            34252 non-null  float64
 9   V528            34252 non-null  float64
 10  V529            34252 non-null  float64
 11  V530            34252 non-null  float64
 12  V531            34252 non-null  float64
 13  V532            34252 non-null  float64
 14  V613            34252 non-null  float64
 15  V614            34252 non-null  float64
 16  V623            34252 non-null  float64
 17  V624            34252 non-null  float64
 18  V625            34252 non-null  float64
 19  V626            34252 non-null  float64
 20  V627            34252 non-null  float64
 21  V628            34252 non-null  float64
 22  V629            34252 non-null  float64
 23  V702            34252 non-null  float64
 24  V715            34252 non-null  float64
 25  V721            34252 non-null  float64
 26  V730            34252 non-null  float64
 27  V741            34252 non-null  float64
 28  V714            34252 non-null  int64
 29  CASEID          34252 non-null  object
 30  V743D           34252 non-null  float64
 31  V743E           34252 non-null  float64
 32  V510            34252 non-null  float64
 33  V602            34252 non-null  float64
 34  V744A           34252 non-null  float64
 35  V743A           34252 non-null  float64
 36  V732            34252 non-null  float64
 37  V633C           34252 non-null  float64
 38  V536            34252 non-null  float64
 39  V633B           34252 non-null  float64
 40  V744E           34252 non-null  float64
 41  V743F           34252 non-null  float64
 42  V729            34252 non-null  float64
 43  V503            34252 non-null  float64
 44  V744D           34252 non-null  float64
 45  V716            34252 non-null  float64
 46  V633A           34252 non-null  float64
 47  V704            34252 non-null  float64
 48  V731            34252 non-null  float64
 49  V701            34252 non-null  float64
 50  V744C           34252 non-null  float64
 51  V501            34252 non-null  float64
 52  V631            34252 non-null  float64
 53  V717            34252 non-null  float64
 54  V743C           34252 non-null  float64
 55  V705            34252 non-null  float64
 56  V744B           34252 non-null  float64
 57  V743B           34252 non-null  float64
 58  V605            34252 non-null  float64
 59  V504            34252 non-null  float64
 60  V719            34252 non-null  float64
 61  V502            34252 non-null  float64
 62  V633D           34252 non-null  float64
 63  premature_flag  34252 non-null  float64
dtypes: float64(62), int64(1), object(1)
memory usage: 16.7+ MB

In [67]:
encoding_map_RE516171

{'V743D': {'0': 0.1203633594112511,
  '1': 0.1457636133024487,
  '2': 0.09629782310134083,
  '3': 0.0969635167163105,
  '4': 0.11574073414449072,
  '5': 0.11611203135651278},
 'V743E': {'0': 0.1001473142056087,
  '1': 0.09355102620073219,
  '2': 0.16252000516341472,
  '3': 0.11161388753945603,
  '4': 0.14486037760713413,
  '5': 0.18433560495130968},
 'V510': {'1': 0.10245705382957729,
  '5': 0.121246106711773,
  '6': 0.17816492609978926},
 'V602': {'1': 0.06893180433230499,
  '2': 0.05968044533702935,
  '3': 0.11427973699224073,
  '4': 0.23876098301535453,
  '5': 0.0468662811737324},
 'V744A': {'0': 0.10310551908289024, '1': 0.1206035041484911, '8': 0.0},
 'V743A': {'0': 0.2419802462791059,
  '1': 0.09833040685696708,
  '2': 0.12964322973686435,
  '3': 0.0570099130018505,
  '4': 0.11117081645419798,
  '5': 0.1923549879480032},
 'V732': {'1': 0.09866252651072997,
  '2': 0.114104740380939,
  '3': 0.1135892274315984},
 'V633C': {'0': 0.08590197380766862,
  '1': 0.10417164571792414,
  '8': 0.030796209512580122},
 'V536': {'0': 0.0,
  '1': 0.13475006356416933,
  '2': 0.20180047716002544,
  '3': 0.08765666075599501},
 'V633B': {'0': 0.10216872909154052,
  '1': 0.1036976852284911,
  '8': 0.04523260587803644},
 'V744E': {'0': 0.10307520730174652, '1': 0.12771883330956466, '8': 0.0},
 'V743F': {'1': 0.16303102800894273,
  '2': 0.0881069176215889,
  '3': 0.0,
  '4': 0.13342486748964463,
  '5': 0.13654829995674425,
  '7': 0.1364563460702525},
 'V729': {'0': 0.06960725058611665,
  '1': 0.09690305747143699,
  '2': 0.08590039522119552,
  '3': 0.1171149382285609,
  '4': 0.07675441150131296,
  '5': 0.16677882889387735,
  '8': 0.2114707190458893},
 'V503': {'1': 0.09682304458771084, '2': 0.1461128460793868},
 'V744D': {'0': 0.10316340368823719, '1': 0.12067593210834576, '8': 0.0},
 'V716': {'1': 0.1539618720183686,
  '11': 0.0,
  '12': 0.2719730720921635,
  '13': 0.0,
  '14': 0.2265751681373031,
  '2': 0.22785393535290374,
  '21': 0.10344365820517387,
  '22': 0.14496539063331326,
  '23': 0.1767814618711518,
  '24': 0.13611603534126268,
  '25': 0.140050928288487,
  '26': 0.20739759610555214,
  '27': 1.0,
  '28': 0.21741710748995732,
  '31': 0.10004353182361,
  '32': 0.2675430043311196,
  '33': 0.16081631879991024,
  '34': 0.16943986484241044,
  '35': 0.13982779735087322,
  '36': 0.18607032337697477,
  '37': 0.14466961711347132,
  '38': 0.14429191136335662,
  '39': 0.15617076436341906,
  '41': 0.11898666874066409,
  '42': 0.12318096912344896,
  '43': 0.13654829995674425,
  '44': 0.12219057942999573,
  '45': 0.11526977480846773,
  '46': 0.11178133250954096,
  '5': 0.0,
  '51': 0.08461058556915746,
  '52': 0.10657758608196481,
  '53': 0.1568793523300619,
  '54': 0.13189582644413217,
  '55': 0.21741710748995732,
  '56': 0.12019010778363011,
  '57': 0.09579957341577036,
  '58': 0.12171858567285418,
  '61': 0.08742628830556855,
  '62': 0.07294323613921014,
  '63': 0.04462247678108319,
  '71': 0.0,
  '72': 0.0,
  '74': 0.08344644500903285,
  '76': 0.11742763510123261,
  '77': 0.11081075391014679,
  '78': 0.12904126381318837,
  '79': 0.09768833938763097,
  '81': 0.0,
  '82': 0.2769240062860644,
  '83': 0.0,
  '84': 0.12219057942999573,
  '85': 0.0,
  '86': 0.08242354636803037,
  '87': 0.04462247678108319,
  '88': 0.13367939875947682,
  '91': 0.10393151692099599,
  '93': 0.10445826728151805,
  '94': 0.09862552454425695,
  '95': 0.16782462873814188,
  '96': 0.031977939188433065,
  '98': 0.11814353455218887,
  '998': 0.0},
 'V633A': {'0': 0.11536893994755375,
  '1': 0.10377013587404865,
  '8': 0.02769327388416002},
 'V704': {'1': 0.22542236341301503,
  '11': 0.08461058556915746,
  '12': 1.0,
  '13': 0.21436145275554663,
  '14': 0.12653982438017142,
  '2': 0.15085775938463078,
  '21': 0.1634465901043226,
  '22': 0.2226361995769824,
  '23': 0.17951293061473358,
  '24': 0.15477967916970056,
  '25': 0.19002422371995406,
  '26': 0.19146702141806976,
  '27': 0.1539618720183686,
  '28': 0.24507539001949386,
  '31': 0.18684599452622794,
  '32': 0.04888613600204209,
  '33': 0.20416044979090683,
  '34': 0.17453161337126782,
  '35': 0.10828885784836847,
  '36': 0.18138620135840638,
  '37': 0.26218598155759604,
  '38': 0.11104445939981385,
  '39': 0.1538795570530606,
  '41': 0.17908842541816106,
  '42': 0.15847680664397878,
  '43': 0.0,
  '44': 0.06823316681697436,
  '45': 0.12260856992144328,
  '46': 0.17951741920343162,
  '5': 0.11066693577566691,
  '51': 0.1051570550834244,
  '52': 0.12600364598878896,
  '53': 0.0,
  '54': 0.23298485471464905,
  '55': 0.0,
  '56': 0.1736499437797703,
  '57': 0.1422583662431103,
  '58': 0.13654829995674425,
  '61': 0.04977900905466541,
  '62': 0.12561842732238218,
  '63': 0.12320753836251644,
  '71': 0.10740182656901472,
  '72': 0.0,
  '73': 0.0,
  '74': 0.048886136002042085,
  '75': 0.0,
  '76': 0.1588549479493787,
  '77': 0.15015535352237827,
  '78': 0.16599384371199505,
  '79': 0.13640474432942543,
  '81': 0.10520872254782203,
  '82': 0.0,
  '83': 0.3189083758378702,
  '84': 0.1702717935454207,
  '85': 0.07711537108405837,
  '86': 0.13025232151918378,
  '87': 0.14237198234066373,
  '88': 0.15251751412134576,
  '91': 0.1093244352689116,
  '93': 0.20072090325993222,
  '94': 0.15231251370037485,
  '95': 0.13619000876055232,
  '96': 0.14466961711347132,
  '98': 0.14233287548720694,
  '99': 0.1484407410697921,
  '998': 0.2675430043311196},
 'V731': {'0': 0.08403282764311569,
  '1': 0.10505340513855105,
  '2': 0.11456807964083326,
  '3': 0.12676038760850666},
 'V701': {'0': 0.06960725058611665,
  '1': 0.09080744767397045,
  '2': 0.08216028115484489,
  '3': 0.16677882889387735,
  '8': 0.2114707190458893},
 'V744C': {'0': 0.10315641039331713,
  '1': 0.1121480114489134,
  '8': 0.04888613600204209},
 'V501': {'0': 0.018683965078066432,
  '1': 0.15580028078089597,
  '2': 0.13813044249912082,
  '3': 0.04034764914742743,
  '4': 0.0845248941723454,
  '5': 0.12137826887416875},
 'V631': {'1': 0.09738093049305999,
  '2': 0.10542367650484936,
  '3': 0.11905953037753354,
  '4': 0.0409690398458394},
 'V717': {'0': 0.08393339445223347,
  '1': 0.14884821825675165,
  '2': 0.11758076629505221,
  '3': 0.11817795517255232,
  '4': 0.0859559533163348,
  '6': 0.10018800431227122,
  '7': 0.125842708558033,
  '8': 0.10973043092481712,
  '9': 0.10636902121916186,
  '98': 0.0},
 'V743C': {'0': 0.0,
  '1': 0.09024767263725875,
  '2': 0.14352543658009573,
  '3': 0.1361516712825328,
  '4': 0.12308295516452286,
  '5': 0.24090222609030926},
 'V705': {'0': 0.13717770789276298,
  '1': 0.1757786992527622,
  '2': 0.16025676487233698,
  '3': 0.14105326585085395,
  '4': 0.05177079502952714,
  '6': 0.14671666184378934,
  '7': 0.15601869410139355,
  '8': 0.14300093887130894,
  '9': 0.14244410262792964,
  '98': 0.2675430043311196},
 'V744B': {'0': 0.10326793252725909,
  '1': 0.09871244597120131,
  '8': 0.04462247678108319},
 'V743B': {'0': 0.11675124078002566,
  '1': 0.1582603666553939,
  '2': 0.08938312909368545,
  '3': 0.14016379879788604,
  '4': 0.11565124986450763,
  '5': 0.19751855066866042},
 'V605': {'1': 0.07601052326310143,
  '2': 0.06835572092950536,
  '3': 0.058737392956182494,
  '4': 0.05968044533702935,
  '5': 0.11427973699224073,
  '6': 0.23876098301535453,
  '7': 0.0468662811737324},
 'V504': {'1': 0.10208848519056772, '2': 0.1240989476333886},
 'V719': {'1': 0.08999180222558302,
  '2': 0.09858482876023168,
  '3': 0.12084530453028469},
 'V502': {'0': 0.018683965078066432,
  '1': 0.14256561997406442,
  '2': 0.11929727713425771},
 'V633D': {'0': 0.10666324694187683,
  '1': 0.10344406747389726,
  '8': 0.06893589516483348}}

In [68]:
save_file(Modulo1635_RE516171_2024_M_clear, output_file = "Modulo1635_RE516171_2024_M_clear_v3.csv")

save_txt(encoding_map_RE516171, dir="data\\interim",output_file="encoding_map_RE516171.txt")

✅ File saved successfully at: c:\Users\linoc\OneDrive\Encoder\03_partos\02_scripts\Premature_model\data\interim\encoding_map_RE516171.txt

## Modulo1640_CSALUD01_2024

In [18]:
Modulo1640_CSALUD01_2024 = pd.read_csv("C:/Users/linoc/OneDrive/Encoder/03_partos/01_raws/2024/968-Modulo1640/968-Modulo1640/CSALUD01_2024.csv", low_memory=False)
Modulo1640_CSALUD01_2024.info(verbose= True, show_counts = True)

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 34018 entries, 0 to 34017
Data columns (total 258 columns):
 #    Column       Non-Null Count  Dtype
---   ------       --------------  -----
 0    ID1          34018 non-null  int64
 1    HHID         34018 non-null  int64
 2    QHCLUSTER    34018 non-null  int64
 3    QHNUMBER     34018 non-null  int64
 4    QHHOME       34018 non-null  int64
 5    QSNUMERO     34018 non-null  int64
 6    QSINTM       34018 non-null  int64
 7    QSINTY       34018 non-null  int64
 8    QSTOTVISIT   34018 non-null  int64
 9    QSRESULT     34018 non-null  int64
 10   QSNINOS      34018 non-null  object
 11   QSRESINF     34018 non-null  int64
 12   QS20C        34018 non-null  object
 13   QSSEXO       34018 non-null  object
 14   QSMEF        34018 non-null  object
 15   QSDIA        34018 non-null  object
 16   QS22M        34018 non-null  object
 17   QS22A        34018 non-null  object
 18   QS23         34018 non-null  object
 19   QS24         34018 non-null  object
 20   QS25N        34018 non-null  object
 21   QS25AG       34018 non-null  object
 22   QS25A        34018 non-null  object
 23   QS25G        34018 non-null  object
 24   QS25AA       34018 non-null  object
 25   QS25BB       34018 non-null  object
 26   QS26         34018 non-null  object
 27   QS27         34018 non-null  object
 28   QS28         34018 non-null  object
 29   QS29A        34018 non-null  object
 30   QS29B        34018 non-null  object
 31   QS100        34018 non-null  object
 32   QS101        34018 non-null  object
 33   QS102        34018 non-null  object
 34   QS103U       34018 non-null  object
 35   QS103C       34018 non-null  object
 36   QS104        34018 non-null  object
 37   QS105        34018 non-null  object
 38   QS106        34018 non-null  object
 39   QS107        34018 non-null  object
 40   QS108        34018 non-null  object
 41   QS109        34018 non-null  object
 42   QS110U       34018 non-null  object
 43   QS110C       34018 non-null  object
 44   QS111        34018 non-null  object
 45   QS112        34018 non-null  object
 46   QS113        34018 non-null  object
 47   QS202        34018 non-null  object
 48   QS203U       34018 non-null  object
 49   QS203C       34018 non-null  object
 50   QS204U       34018 non-null  object
 51   QS204C       34018 non-null  object
 52   QS205U       34018 non-null  object
 53   QS205C       34018 non-null  object
 54   QS206        34018 non-null  object
 55   QS207U       34018 non-null  object
 56   QS207C       34018 non-null  object
 57   QS208        34018 non-null  object
 58   QS209        34018 non-null  object
 59   QS210        34018 non-null  object
 60   QS211U       34018 non-null  object
 61   QS211C       34018 non-null  object
 62   QS212T       34018 non-null  object
 63   QS212A       34018 non-null  object
 64   QS212AV      34018 non-null  object
 65   QS212AB      34018 non-null  object
 66   QS212B       34018 non-null  object
 67   QS212BV      34018 non-null  object
 68   QS212BB      34018 non-null  object
 69   QS212C       34018 non-null  object
 70   QS212CV      34018 non-null  object
 71   QS212CB      34018 non-null  object
 72   QS212D       34018 non-null  object
 73   QS212DV      34018 non-null  object
 74   QS212DB      34018 non-null  object
 75   QS212E       34018 non-null  object
 76   QS212EV      34018 non-null  object
 77   QS212EB      34018 non-null  object
 78   QS212F       34018 non-null  object
 79   QS212FV      34018 non-null  object
 80   QS212FB      34018 non-null  object
 81   QS212G       34018 non-null  object
 82   QS212GV      34018 non-null  object
 83   QS212GB      34018 non-null  object
 84   QS212O       34018 non-null  object
 85   QS212XV      34018 non-null  object
 86   QS212XB      34018 non-null  object
 87   QS212Z       34018 non-null  object
 88   QS213U       34018 non-null  object
 89   QS213C       34018 non-null  object
 90   QS214U       34018 non-null  object
 91   QS214C       34018 non-null  object
 92   QS215U       34018 non-null  object
 93   QS215C       34018 non-null  object
 94   QS216U       34018 non-null  object
 95   QS216C       34018 non-null  object
 96   QS217U       34018 non-null  object
 97   QS217C       34018 non-null  object
 98   QS218U       34018 non-null  object
 99   QS218C       34018 non-null  object
 100  QS219U       34018 non-null  object
 101  QS219C       34018 non-null  object
 102  QS220U       34018 non-null  object
 103  QS220CV      34018 non-null  object
 104  QS220CC      34018 non-null  object
 105  QS200        34018 non-null  object
 106  QS201        34018 non-null  object
 107  QS302C       34018 non-null  object
 108  QS303        34018 non-null  object
 109  QS304        34018 non-null  object
 110  QS305U       34018 non-null  object
 111  QS305C       34018 non-null  object
 112  QS306        34018 non-null  object
 113  QS307        34018 non-null  object
 114  QS308        34018 non-null  object
 115  QS309        34018 non-null  object
 116  QS311        34018 non-null  object
 117  QS312U       34018 non-null  object
 118  QS312C       34018 non-null  object
 119  QS313        34018 non-null  object
 120  QS301        34018 non-null  object
 121  QS302U       34018 non-null  object
 122  QS403        34018 non-null  object
 123  QS404        34018 non-null  object
 124  QS406        34018 non-null  object
 125  QS407        34018 non-null  object
 126  QS409        34018 non-null  object
 127  QS410U       34018 non-null  object
 128  QS410C       34018 non-null  object
 129  QS411        34018 non-null  object
 130  QS412U       34018 non-null  object
 131  QS412C       34018 non-null  object
 132  QS413        34018 non-null  object
 133  QS415        34018 non-null  object
 134  QS416U       34018 non-null  object
 135  QS416C       34018 non-null  object
 136  QS401        34018 non-null  object
 137  QS402        34018 non-null  object
 138  QS500        34018 non-null  object
 139  QS501U       34018 non-null  object
 140  QS501C       34018 non-null  object
 141  QS503        34018 non-null  object
 142  QS505A       34018 non-null  object
 143  QS505B       34018 non-null  object
 144  QS505C       34018 non-null  object
 145  QS505D       34018 non-null  object
 146  QS506        34018 non-null  object
 147  QS603        34018 non-null  object
 148  QS604        34018 non-null  object
 149  QS606        34018 non-null  object
 150  QS607        34018 non-null  object
 151  QS608        34018 non-null  object
 152  QS609        34018 non-null  object
 153  QS610        34018 non-null  object
 154  QS611        34018 non-null  object
 155  QS601A       34018 non-null  object
 156  QS601B       34018 non-null  object
 157  QS700A       34018 non-null  object
 158  QS700B       34018 non-null  object
 159  QS700C       34018 non-null  object
 160  QS700D       34018 non-null  object
 161  QS700E       34018 non-null  object
 162  QS700F       34018 non-null  object
 163  QS700G       34018 non-null  object
 164  QS700H       34018 non-null  object
 165  QS700I       34018 non-null  object
 166  QS702        34018 non-null  object
 167  QS703        34018 non-null  object
 168  QS704T       34018 non-null  object
 169  QS704A       34018 non-null  object
 170  QS704B       34018 non-null  object
 171  QS704C       34018 non-null  object
 172  QS704D       34018 non-null  object
 173  QS704E       34018 non-null  object
 174  QS704F       34018 non-null  object
 175  QS704G       34018 non-null  object
 176  QS704H       34018 non-null  object
 177  QS704I       34018 non-null  object
 178  QS706        34018 non-null  object
 179  QS707        34018 non-null  object
 180  QS709        34018 non-null  object
 181  QS710        34018 non-null  object
 182  QS711        34018 non-null  object
 183  QS713        34018 non-null  object
 184  QS714        34018 non-null  object
 185  QS715        34018 non-null  object
 186  QS716        34018 non-null  object
 187  QS717        34018 non-null  object
 188  QS719        34018 non-null  object
 189  QS720        34018 non-null  object
 190  QS721        34018 non-null  object
 191  QS722        34018 non-null  object
 192  QS723        34018 non-null  object
 193  QS724        34018 non-null  object
 194  QS725        34018 non-null  object
 195  QS726        34018 non-null  object
 196  QS727        34018 non-null  object
 197  QS728        34018 non-null  object
 198  QS729        34018 non-null  object
 199  QS730        34018 non-null  object
 200  QFIN         34018 non-null  object
 201  QS8INICIO    34018 non-null  object
 202  QS900        34018 non-null  object
 203  QS901        34018 non-null  object
 204  QS902        34018 non-null  object
 205  QS903S       34018 non-null  object
 206  QS903D       34018 non-null  object
 207  QS905S       34018 non-null  object
 208  QS905D       34018 non-null  object
 209  QS906        34018 non-null  object
 210  QS25C1       34018 non-null  object
 211  QS25C2       34018 non-null  object
 212  QS25C3       34018 non-null  object
 213  QS25C4       34018 non-null  object
 214  QS25C5       34018 non-null  object
 215  QS25C6       34018 non-null  object
 216  QS907        34018 non-null  object
 217  QS908        34018 non-null  object
 218  QS413A       34018 non-null  object
 219  QS413B       34018 non-null  object
 220  QS413B_A     34018 non-null  object
 221  QS413C       34018 non-null  object
 222  QS413D       34018 non-null  object
 223  QS413E       34018 non-null  object
 224  QS413E_A     34018 non-null  object
 225  QS413F       34018 non-null  object
 226  QS506B       34018 non-null  object
 227  QS708_A      34018 non-null  object
 228  QS708_AA     34018 non-null  object
 229  QS708_AB     34018 non-null  object
 230  QS708_B      34018 non-null  object
 231  QS708_C      34018 non-null  object
 232  QS708_D      34018 non-null  object
 233  QS708_E      34018 non-null  object
 234  QS708_EA     34018 non-null  object
 235  QS708_F      34018 non-null  object
 236  QS708_G      34018 non-null  object
 237  QS708_H      34018 non-null  object
 238  QS708_I      34018 non-null  object
 239  QS708_J      34018 non-null  object
 240  QS708_X      34018 non-null  object
 241  QS708_Y      34018 non-null  object
 242  QS731_A      34018 non-null  object
 243  QS731_AA     34018 non-null  object
 244  QS731_AB     34018 non-null  object
 245  QS731_B      34018 non-null  object
 246  QS731_C      34018 non-null  object
 247  QS731_D      34018 non-null  object
 248  QS731_E      34018 non-null  object
 249  QS731_EA     34018 non-null  object
 250  QS731_F      34018 non-null  object
 251  QS731_G      34018 non-null  object
 252  QS731_H      34018 non-null  object
 253  QS731_I      34018 non-null  object
 254  QS731_J      34018 non-null  object
 255  QS731_X      34018 non-null  object
 256  QS731_Y      34018 non-null  object
 257  PESO15_AMAS  34018 non-null  object
dtypes: int64(11), object(247)
memory usage: 67.0+ MB

In [70]:
Modulo1640_CSALUD01_2024.shape, Modulo1640_CSALUD01_2024.HHID.nunique()

((34018, 258), 34018)

In [71]:
Modulo1640_CSALUD01_2024_M = convert_objects_to_int64_safe(Modulo1640_CSALUD01_2024)
Modulo1640_CSALUD01_2024_M = Modulo1640_CSALUD01_2024_M.dropna(axis=1, how="all")
Modulo1640_CSALUD01_2024_M.info(verbose = True, show_counts = True)

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 34018 entries, 0 to 34017
Data columns (total 243 columns):
 #    Column       Non-Null Count  Dtype
---   ------       --------------  -----
 0    ID1          34018 non-null  int64
 1    HHID         34018 non-null  int64
 2    QHCLUSTER    34018 non-null  int64
 3    QHNUMBER     34018 non-null  int64
 4    QHHOME       34018 non-null  int64
 5    QSNUMERO     34018 non-null  int64
 6    QSINTM       34018 non-null  int64
 7    QSINTY       34018 non-null  int64
 8    QSTOTVISIT   34018 non-null  int64
 9    QSRESULT     34018 non-null  int64
 10   QSRESINF     34018 non-null  int64
 11   QS20C        31487 non-null  Int64
 12   QSSEXO       31487 non-null  Int64
 13   QSMEF        31487 non-null  Int64
 14   QSDIA        31484 non-null  Int64
 15   QS22M        31484 non-null  Int64
 16   QS22A        31484 non-null  Int64
 17   QS23         31484 non-null  Int64
 18   QS24         31484 non-null  Int64
 19   QS25N        30374 non-null  Int64
 20   QS25AG       30362 non-null  Int64
 21   QS25A        26370 non-null  Int64
 22   QS25G        3992 non-null   Int64
 23   QS25AA       31484 non-null  Int64
 24   QS25BB       31484 non-null  Int64
 25   QS26         31484 non-null  Int64
 26   QS27         34018 non-null  object
 27   QS28         13770 non-null  Int64
 28   QS29A        13770 non-null  Int64
 29   QS29B        13770 non-null  Int64
 30   QS100        31481 non-null  Int64
 31   QS101        15324 non-null  Int64
 32   QS102        31481 non-null  Int64
 33   QS104        2726 non-null   Int64
 34   QS105        1781 non-null   Int64
 35   QS106        1781 non-null   Int64
 36   QS107        31481 non-null  Int64
 37   QS108        8880 non-null   Int64
 38   QS109        31481 non-null  Int64
 39   QS111        1129 non-null   Int64
 40   QS112        797 non-null    Int64
 41   QS113        797 non-null    Int64
 42   QS202        2896 non-null   Int64
 43   QS203U       357 non-null    Int64
 44   QS203C       356 non-null    Int64
 45   QS204U       1 non-null      Int64
 46   QS205U       357 non-null    Int64
 47   QS205C       356 non-null    Int64
 48   QS206        31467 non-null  Int64
 49   QS207U       28886 non-null  Int64
 50   QS207C       28525 non-null  Int64
 51   QS208        28886 non-null  Int64
 52   QS209        21129 non-null  Int64
 53   QS210        21129 non-null  Int64
 54   QS211U       10319 non-null  Int64
 55   QS211C       10312 non-null  Int64
 56   QS212T       34018 non-null  object
 57   QS212A       10312 non-null  Int64
 58   QS212AV      7387 non-null   Int64
 59   QS212AB      7387 non-null   Int64
 60   QS212B       10312 non-null  Int64
 61   QS212BV      1662 non-null   Int64
 62   QS212BB      1662 non-null   Int64
 63   QS212C       10312 non-null  Int64
 64   QS212CV      425 non-null    Int64
 65   QS212CB      425 non-null    Int64
 66   QS212D       10312 non-null  Int64
 67   QS212DV      196 non-null    Int64
 68   QS212DB      196 non-null    Int64
 69   QS212E       10312 non-null  Int64
 70   QS212EV      553 non-null    Int64
 71   QS212EB      553 non-null    Int64
 72   QS212F       10312 non-null  Int64
 73   QS212FV      38 non-null     Int64
 74   QS212FB      38 non-null     Int64
 75   QS212G       10312 non-null  Int64
 76   QS212GV      1316 non-null   Int64
 77   QS212GB      1316 non-null   Int64
 78   QS212O       10312 non-null  Int64
 79   QS212XV      123 non-null    Int64
 80   QS212XB      123 non-null    Int64
 81   QS212Z       10312 non-null  Int64
 82   QS213U       31467 non-null  Int64
 83   QS213C       28434 non-null  Int64
 84   QS214U       28434 non-null  Int64
 85   QS214C       34018 non-null  object
 86   QS215U       31467 non-null  Int64
 87   QS215C       13797 non-null  Int64
 88   QS216U       13797 non-null  Int64
 89   QS216C       34018 non-null  object
 90   QS217U       31467 non-null  Int64
 91   QS217C       5415 non-null   Int64
 92   QS218U       5415 non-null   Int64
 93   QS218C       34018 non-null  object
 94   QS219U       31467 non-null  Int64
 95   QS219C       22778 non-null  Int64
 96   QS220U       22778 non-null  Int64
 97   QS220CV      34018 non-null  object
 98   QS220CC      2517 non-null   Int64
 99   QS200        31467 non-null  Int64
 100  QS201        4929 non-null   Int64
 101  QS302C       4817 non-null   Int64
 102  QS303        4909 non-null   Int64
 103  QS304        8186 non-null   Int64
 104  QS306        8186 non-null   Int64
 105  QS311        4769 non-null   Int64
 106  QS312U       3920 non-null   Int64
 107  QS312C       3811 non-null   Int64
 108  QS313        3920 non-null   Int64
 109  QS301        8186 non-null   Int64
 110  QS302U       4909 non-null   Int64
 111  QS403        24717 non-null  Int64
 112  QS404        20135 non-null  Int64
 113  QS406        28366 non-null  Int64
 114  QS409        11122 non-null  Int64
 115  QS410U       4046 non-null   Int64
 116  QS410C       4011 non-null   Int64
 117  QS411        13014 non-null  Int64
 118  QS412U       10209 non-null  Int64
 119  QS412C       10126 non-null  Int64
 120  QS413        10209 non-null  Int64
 121  QS415        5994 non-null   Int64
 122  QS416U       1524 non-null   Int64
 123  QS416C       1510 non-null   Int64
 124  QS401        30227 non-null  Int64
 125  QS402        30227 non-null  Int64
 126  QS500        31457 non-null  Int64
 127  QS501U       2871 non-null   Int64
 128  QS501C       2832 non-null   Int64
 129  QS503        17690 non-null  Int64
 130  QS505A       28961 non-null  Int64
 131  QS505B       28961 non-null  Int64
 132  QS505C       28961 non-null  Int64
 133  QS505D       28961 non-null  Int64
 134  QS506        28961 non-null  Int64
 135  QS603        22866 non-null  Int64
 136  QS604        5530 non-null   Int64
 137  QS606        9520 non-null   Int64
 138  QS607        9520 non-null   Int64
 139  QS608        9520 non-null   Int64
 140  QS609        9520 non-null   Int64
 141  QS610        9520 non-null   Int64
 142  QS611        9520 non-null   Int64
 143  QS601A       9503 non-null   Int64
 144  QS601B       9503 non-null   Int64
 145  QS700A       31452 non-null  Int64
 146  QS700B       31452 non-null  Int64
 147  QS700C       31452 non-null  Int64
 148  QS700D       31452 non-null  Int64
 149  QS700E       31452 non-null  Int64
 150  QS700F       31452 non-null  Int64
 151  QS700G       31452 non-null  Int64
 152  QS700H       31452 non-null  Int64
 153  QS700I       31452 non-null  Int64
 154  QS702        16485 non-null  Int64
 155  QS703        31452 non-null  Int64
 156  QS704A       9961 non-null   Int64
 157  QS704B       9961 non-null   Int64
 158  QS704C       9961 non-null   Int64
 159  QS704D       9961 non-null   Int64
 160  QS704E       9961 non-null   Int64
 161  QS704F       9961 non-null   Int64
 162  QS704G       9961 non-null   Int64
 163  QS704H       9961 non-null   Int64
 164  QS704I       9961 non-null   Int64
 165  QS706        9942 non-null   Int64
 166  QS707        31452 non-null  Int64
 167  QS709        31452 non-null  Int64
 168  QS710        20807 non-null  Int64
 169  QS711        20807 non-null  Int64
 170  QS713        3889 non-null   Int64
 171  QS714        3889 non-null   Int64
 172  QS715        506 non-null    Int64
 173  QS716        3889 non-null   Int64
 174  QS717        3889 non-null   Int64
 175  QS719        1130 non-null   Int64
 176  QS720        1130 non-null   Int64
 177  QS721        1130 non-null   Int64
 178  QS722        945 non-null    Int64
 179  QS723        1130 non-null   Int64
 180  QS724        807 non-null    Int64
 181  QS725        738 non-null    Int64
 182  QS726        1130 non-null   Int64
 183  QS727        1130 non-null   Int64
 184  QS728        1130 non-null   Int64
 185  QS729        1130 non-null   Int64
 186  QS730        28873 non-null  Int64
 187  QS900        34018 non-null  object
 188  QS901        34018 non-null  object
 189  QS902        31449 non-null  Int64
 190  QS903S       31451 non-null  Int64
 191  QS903D       31451 non-null  Int64
 192  QS905S       31451 non-null  Int64
 193  QS905D       31451 non-null  Int64
 194  QS906        31451 non-null  Int64
 195  QS25C1       31484 non-null  Int64
 196  QS25C2       31484 non-null  Int64
 197  QS25C3       31484 non-null  Int64
 198  QS25C4       31484 non-null  Int64
 199  QS25C5       31484 non-null  Int64
 200  QS25C6       31484 non-null  Int64
 201  QS907        34018 non-null  object
 202  QS908        31451 non-null  Int64
 203  QS413A       13014 non-null  Int64
 204  QS413B       2095 non-null   Int64
 205  QS413B_A     2022 non-null   Int64
 206  QS413C       2095 non-null   Int64
 207  QS413D       13014 non-null  Int64
 208  QS413E       1438 non-null   Int64
 209  QS413E_A     1425 non-null   Int64
 210  QS413F       1438 non-null   Int64
 211  QS506B       16301 non-null  Int64
 212  QS708_A      1260 non-null   Int64
 213  QS708_AA     1260 non-null   Int64
 214  QS708_AB     1260 non-null   Int64
 215  QS708_B      1260 non-null   Int64
 216  QS708_C      1260 non-null   Int64
 217  QS708_D      1260 non-null   Int64
 218  QS708_E      1260 non-null   Int64
 219  QS708_EA     1260 non-null   Int64
 220  QS708_F      1260 non-null   Int64
 221  QS708_G      1260 non-null   Int64
 222  QS708_H      1260 non-null   Int64
 223  QS708_I      1260 non-null   Int64
 224  QS708_J      1260 non-null   Int64
 225  QS708_X      1260 non-null   Int64
 226  QS708_Y      1260 non-null   Int64
 227  QS731_A      40 non-null     Int64
 228  QS731_AA     28 non-null     Int64
 229  QS731_AB     28 non-null     Int64
 230  QS731_B      40 non-null     Int64
 231  QS731_C      40 non-null     Int64
 232  QS731_D      40 non-null     Int64
 233  QS731_E      40 non-null     Int64
 234  QS731_EA     28 non-null     Int64
 235  QS731_F      40 non-null     Int64
 236  QS731_G      40 non-null     Int64
 237  QS731_H      40 non-null     Int64
 238  QS731_I      40 non-null     Int64
 239  QS731_J      40 non-null     Int64
 240  QS731_X      40 non-null     Int64
 241  QS731_Y      40 non-null     Int64
 242  PESO15_AMAS  34018 non-null  object
dtypes: Int64(222), int64(11), object(10)
memory usage: 70.3+ MB

In [72]:
Modulo1640_CSALUD01_2024_M = drop_high_null_columns(Modulo1640_CSALUD01_2024_M , threshold=0.45)
Modulo1640_CSALUD01_2024_M.info(verbose = True, show_counts = True)

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 34018 entries, 0 to 34017
Data columns (total 94 columns):
 #   Column       Non-Null Count  Dtype
---  ------       --------------  -----
 0   ID1          34018 non-null  int64
 1   HHID         34018 non-null  int64
 2   QHCLUSTER    34018 non-null  int64
 3   QHNUMBER     34018 non-null  int64
 4   QHHOME       34018 non-null  int64
 5   QSNUMERO     34018 non-null  int64
 6   QSINTM       34018 non-null  int64
 7   QSINTY       34018 non-null  int64
 8   QSTOTVISIT   34018 non-null  int64
 9   QSRESULT     34018 non-null  int64
 10  QSRESINF     34018 non-null  int64
 11  QS20C        31487 non-null  Int64
 12  QSSEXO       31487 non-null  Int64
 13  QSMEF        31487 non-null  Int64
 14  QSDIA        31484 non-null  Int64
 15  QS22M        31484 non-null  Int64
 16  QS22A        31484 non-null  Int64
 17  QS23         31484 non-null  Int64
 18  QS24         31484 non-null  Int64
 19  QS25N        30374 non-null  Int64
 20  QS25AG       30362 non-null  Int64
 21  QS25A        26370 non-null  Int64
 22  QS25AA       31484 non-null  Int64
 23  QS25BB       31484 non-null  Int64
 24  QS26         31484 non-null  Int64
 25  QS27         34018 non-null  object
 26  QS100        31481 non-null  Int64
 27  QS102        31481 non-null  Int64
 28  QS107        31481 non-null  Int64
 29  QS109        31481 non-null  Int64
 30  QS206        31467 non-null  Int64
 31  QS207U       28886 non-null  Int64
 32  QS207C       28525 non-null  Int64
 33  QS208        28886 non-null  Int64
 34  QS209        21129 non-null  Int64
 35  QS210        21129 non-null  Int64
 36  QS212T       34018 non-null  object
 37  QS213U       31467 non-null  Int64
 38  QS213C       28434 non-null  Int64
 39  QS214U       28434 non-null  Int64
 40  QS214C       34018 non-null  object
 41  QS215U       31467 non-null  Int64
 42  QS216C       34018 non-null  object
 43  QS217U       31467 non-null  Int64
 44  QS218C       34018 non-null  object
 45  QS219U       31467 non-null  Int64
 46  QS219C       22778 non-null  Int64
 47  QS220U       22778 non-null  Int64
 48  QS220CV      34018 non-null  object
 49  QS200        31467 non-null  Int64
 50  QS403        24717 non-null  Int64
 51  QS404        20135 non-null  Int64
 52  QS406        28366 non-null  Int64
 53  QS401        30227 non-null  Int64
 54  QS402        30227 non-null  Int64
 55  QS500        31457 non-null  Int64
 56  QS505A       28961 non-null  Int64
 57  QS505B       28961 non-null  Int64
 58  QS505C       28961 non-null  Int64
 59  QS505D       28961 non-null  Int64
 60  QS506        28961 non-null  Int64
 61  QS603        22866 non-null  Int64
 62  QS700A       31452 non-null  Int64
 63  QS700B       31452 non-null  Int64
 64  QS700C       31452 non-null  Int64
 65  QS700D       31452 non-null  Int64
 66  QS700E       31452 non-null  Int64
 67  QS700F       31452 non-null  Int64
 68  QS700G       31452 non-null  Int64
 69  QS700H       31452 non-null  Int64
 70  QS700I       31452 non-null  Int64
 71  QS703        31452 non-null  Int64
 72  QS707        31452 non-null  Int64
 73  QS709        31452 non-null  Int64
 74  QS710        20807 non-null  Int64
 75  QS711        20807 non-null  Int64
 76  QS730        28873 non-null  Int64
 77  QS900        34018 non-null  object
 78  QS901        34018 non-null  object
 79  QS902        31449 non-null  Int64
 80  QS903S       31451 non-null  Int64
 81  QS903D       31451 non-null  Int64
 82  QS905S       31451 non-null  Int64
 83  QS905D       31451 non-null  Int64
 84  QS906        31451 non-null  Int64
 85  QS25C1       31484 non-null  Int64
 86  QS25C2       31484 non-null  Int64
 87  QS25C3       31484 non-null  Int64
 88  QS25C4       31484 non-null  Int64
 89  QS25C5       31484 non-null  Int64
 90  QS25C6       31484 non-null  Int64
 91  QS907        34018 non-null  object
 92  QS908        31451 non-null  Int64
 93  PESO15_AMAS  34018 non-null  object
dtypes: Int64(73), int64(11), object(10)
memory usage: 26.8+ MB

In [73]:
# QS25AA,QS25BB,QS25C1,QS25C2,QS25C3,
# QS25C4,QS25C5,QS25C6,QS26,QS27,
# QS29A,QS29B,QS100,QS101,QS102,
# QS109,QS111,QS200,QS201,QS202,
# QS206,QS208,QS209,QS210,QS212T,
# QS212A,
# QS212B,
# QS212C,
# QS212D,
# QS700AQS212E,QS212F,QS212G,QS303,
# QS313,QS407,QS409,QS411,QS700A,QS700B,
# QS700AC,QS700AD,QS700AE,QS700AF,
# QS700AG,QS700AH,QS700AI,QS702,QS703,QS704A,QS704B, QS704C,QS704D, QS704E, QS704F,
#  QS704G, QS704H, QS704I,QS706,QS707,QS709,QS710,QS711,


# Ensure CASEID is string
target_final["CASEID_9d"] = (
    target_final["CASEID"]
    .astype(str)     # convert to string
    .str.strip()     # remove extra spaces
    .str[:9]         # take first 9 characters
)

# If you want numeric again (preserves the 9 digits correctly)
target_final["CASEID_9d"] = (
    target_final["CASEID_9d"].astype(int))

target_final = target_final[~target_final['CASEID_9d'].duplicated(keep=False)]

Modulo1640_CSALUD01_2024_M = Modulo1640_CSALUD01_2024_M.merge(target_final, right_on= 'CASEID_9d', left_on  = 'HHID', how = 'left')
Modulo1640_CSALUD01_2024_M.info(verbose=True, show_counts=True)

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 34018 entries, 0 to 34017
Data columns (total 97 columns):
 #   Column          Non-Null Count  Dtype
---  ------          --------------  -----
 0   ID1             34018 non-null  int64
 1   HHID            34018 non-null  int64
 2   QHCLUSTER       34018 non-null  int64
 3   QHNUMBER        34018 non-null  int64
 4   QHHOME          34018 non-null  int64
 5   QSNUMERO        34018 non-null  int64
 6   QSINTM          34018 non-null  int64
 7   QSINTY          34018 non-null  int64
 8   QSTOTVISIT      34018 non-null  int64
 9   QSRESULT        34018 non-null  int64
 10  QSRESINF        34018 non-null  int64
 11  QS20C           31487 non-null  Int64
 12  QSSEXO          31487 non-null  Int64
 13  QSMEF           31487 non-null  Int64
 14  QSDIA           31484 non-null  Int64
 15  QS22M           31484 non-null  Int64
 16  QS22A           31484 non-null  Int64
 17  QS23            31484 non-null  Int64
 18  QS24            31484 non-null  Int64
 19  QS25N           30374 non-null  Int64
 20  QS25AG          30362 non-null  Int64
 21  QS25A           26370 non-null  Int64
 22  QS25AA          31484 non-null  Int64
 23  QS25BB          31484 non-null  Int64
 24  QS26            31484 non-null  Int64
 25  QS27            34018 non-null  object
 26  QS100           31481 non-null  Int64
 27  QS102           31481 non-null  Int64
 28  QS107           31481 non-null  Int64
 29  QS109           31481 non-null  Int64
 30  QS206           31467 non-null  Int64
 31  QS207U          28886 non-null  Int64
 32  QS207C          28525 non-null  Int64
 33  QS208           28886 non-null  Int64
 34  QS209           21129 non-null  Int64
 35  QS210           21129 non-null  Int64
 36  QS212T          34018 non-null  object
 37  QS213U          31467 non-null  Int64
 38  QS213C          28434 non-null  Int64
 39  QS214U          28434 non-null  Int64
 40  QS214C          34018 non-null  object
 41  QS215U          31467 non-null  Int64
 42  QS216C          34018 non-null  object
 43  QS217U          31467 non-null  Int64
 44  QS218C          34018 non-null  object
 45  QS219U          31467 non-null  Int64
 46  QS219C          22778 non-null  Int64
 47  QS220U          22778 non-null  Int64
 48  QS220CV         34018 non-null  object
 49  QS200           31467 non-null  Int64
 50  QS403           24717 non-null  Int64
 51  QS404           20135 non-null  Int64
 52  QS406           28366 non-null  Int64
 53  QS401           30227 non-null  Int64
 54  QS402           30227 non-null  Int64
 55  QS500           31457 non-null  Int64
 56  QS505A          28961 non-null  Int64
 57  QS505B          28961 non-null  Int64
 58  QS505C          28961 non-null  Int64
 59  QS505D          28961 non-null  Int64
 60  QS506           28961 non-null  Int64
 61  QS603           22866 non-null  Int64
 62  QS700A          31452 non-null  Int64
 63  QS700B          31452 non-null  Int64
 64  QS700C          31452 non-null  Int64
 65  QS700D          31452 non-null  Int64
 66  QS700E          31452 non-null  Int64
 67  QS700F          31452 non-null  Int64
 68  QS700G          31452 non-null  Int64
 69  QS700H          31452 non-null  Int64
 70  QS700I          31452 non-null  Int64
 71  QS703           31452 non-null  Int64
 72  QS707           31452 non-null  Int64
 73  QS709           31452 non-null  Int64
 74  QS710           20807 non-null  Int64
 75  QS711           20807 non-null  Int64
 76  QS730           28873 non-null  Int64
 77  QS900           34018 non-null  object
 78  QS901           34018 non-null  object
 79  QS902           31449 non-null  Int64
 80  QS903S          31451 non-null  Int64
 81  QS903D          31451 non-null  Int64
 82  QS905S          31451 non-null  Int64
 83  QS905D          31451 non-null  Int64
 84  QS906           31451 non-null  Int64
 85  QS25C1          31484 non-null  Int64
 86  QS25C2          31484 non-null  Int64
 87  QS25C3          31484 non-null  Int64
 88  QS25C4          31484 non-null  Int64
 89  QS25C5          31484 non-null  Int64
 90  QS25C6          31484 non-null  Int64
 91  QS907           34018 non-null  object
 92  QS908           31451 non-null  Int64
 93  PESO15_AMAS     34018 non-null  object
 94  CASEID          17548 non-null  object
 95  premature_flag  17548 non-null  float64
 96  CASEID_9d       17548 non-null  float64
dtypes: Int64(73), float64(2), int64(11), object(11)
memory usage: 27.5+ MB

In [74]:
target_final.shape, target_final.CASEID_9d.nunique(),Modulo1640_CSALUD01_2024_M.shape,Modulo1640_CSALUD01_2024_M.HHID.nunique()

((17548, 3), 17548, (34018, 97), 34018)

In [75]:
df_categorical_1640_CSALUD01  = fill_missing_with_mode(Modulo1640_CSALUD01_2024_M)

# df_categorical_CSALUD01_cod= target_encode_dataframe(df_categorical_1640_CSALUD01,target_col='premature_flag', 
#                             smoothing=0.3, min_samples_leaf=20)


df_categorical_CSALUD01_cod, encoding_map_CSALUD01, encoder_CSALUD01 = target_encode_dataframe_map(df_categorical_1640_CSALUD01,
                                                               target_col='premature_flag', id_col='CASEID')
    
df_categorical_CSALUD01_cod.head()

✅ Encoded 95 categorical columns.

,CASEID,ID1,HHID,QHCLUSTER,QHNUMBER,QHHOME,QSNUMERO,QSINTM,QSINTY,QSTOTVISIT,...,QS25C2,QS25C3,QS25C4,QS25C5,QS25C6,QS907,QS908,PESO15_AMAS,CASEID_9d,premature_flag
0,325503101 2,0.099614,0.099614,0.000000,0.089878,0.099428,0.106197,0.106833,0.099614,0.082160,...,0.099720,0.099551,0.099786,0.099599,0.099614,0.174104,0.099186,0.099614,0.000000,1.0
1,325503101 2,0.099614,0.099614,0.135800,0.101314,0.099283,0.108374,0.098561,0.099614,0.082953,...,0.099771,0.099548,0.099760,0.099507,0.099595,0.227688,0.099209,0.099614,0.000076,0.0
2,325503101 2,0.099581,0.099581,0.135793,0.086320,0.099317,0.089479,0.088385,0.099581,0.083762,...,0.099757,0.099595,0.099779,0.099562,0.099702,0.063592,0.099020,0.099581,0.000076,0.0
3,325504701 2,0.099581,0.099581,0.135793,0.116297,0.099317,0.089479,0.088385,0.099581,0.083762,...,0.099757,0.099595,0.099779,0.099562,0.099702,0.101991,0.099020,0.000000,0.099581,0.0
4,325505001 1,0.099581,0.099581,0.152901,0.107403,0.099324,0.109245,0.092258,0.099581,0.132320,...,0.099668,0.099529,0.099771,0.099462,0.099591,0.083561,0.099315,0.000000,0.099581,0.0

In [76]:
df_categorical_CSALUD01_cod.drop(columns=['HHID'], inplace = True)

Modulo1640_CSALUD01_2024_M_clear_v3 = pd.concat([df_categorical_CSALUD01_cod, df_categorical_1640_CSALUD01[['HHID']], ], axis=1)
Modulo1640_CSALUD01_2024_M_clear_v3.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 34018 entries, 0 to 34017
Data columns (total 97 columns):
 #   Column          Non-Null Count  Dtype
---  ------          --------------  -----
 0   CASEID          34018 non-null  object
 1   ID1             34018 non-null  float64
 2   QHCLUSTER       34018 non-null  float64
 3   QHNUMBER        34018 non-null  float64
 4   QHHOME          34018 non-null  float64
 5   QSNUMERO        34018 non-null  float64
 6   QSINTM          34018 non-null  float64
 7   QSINTY          34018 non-null  float64
 8   QSTOTVISIT      34018 non-null  float64
 9   QSRESULT        34018 non-null  float64
 10  QSRESINF        34018 non-null  float64
 11  QS20C           34018 non-null  float64
 12  QSSEXO          34018 non-null  float64
 13  QSMEF           34018 non-null  float64
 14  QSDIA           34018 non-null  float64
 15  QS22M           34018 non-null  float64
 16  QS22A           34018 non-null  float64
 17  QS23            34018 non-null  float64
 18  QS24            34018 non-null  float64
 19  QS25N           34018 non-null  float64
 20  QS25AG          34018 non-null  float64
 21  QS25A           34018 non-null  float64
 22  QS25AA          34018 non-null  float64
 23  QS25BB          34018 non-null  float64
 24  QS26            34018 non-null  float64
 25  QS27            34018 non-null  float64
 26  QS100           34018 non-null  float64
 27  QS102           34018 non-null  float64
 28  QS107           34018 non-null  float64
 29  QS109           34018 non-null  float64
 30  QS206           34018 non-null  float64
 31  QS207U          34018 non-null  float64
 32  QS207C          34018 non-null  float64
 33  QS208           34018 non-null  float64
 34  QS209           34018 non-null  float64
 35  QS210           34018 non-null  float64
 36  QS212T          34018 non-null  float64
 37  QS213U          34018 non-null  float64
 38  QS213C          34018 non-null  float64
 39  QS214U          34018 non-null  float64
 40  QS214C          34018 non-null  float64
 41  QS215U          34018 non-null  float64
 42  QS216C          34018 non-null  float64
 43  QS217U          34018 non-null  float64
 44  QS218C          34018 non-null  float64
 45  QS219U          34018 non-null  float64
 46  QS219C          34018 non-null  float64
 47  QS220U          34018 non-null  float64
 48  QS220CV         34018 non-null  float64
 49  QS200           34018 non-null  float64
 50  QS403           34018 non-null  float64
 51  QS404           34018 non-null  float64
 52  QS406           34018 non-null  float64
 53  QS401           34018 non-null  float64
 54  QS402           34018 non-null  float64
 55  QS500           34018 non-null  float64
 56  QS505A          34018 non-null  float64
 57  QS505B          34018 non-null  float64
 58  QS505C          34018 non-null  float64
 59  QS505D          34018 non-null  float64
 60  QS506           34018 non-null  float64
 61  QS603           34018 non-null  float64
 62  QS700A          34018 non-null  float64
 63  QS700B          34018 non-null  float64
 64  QS700C          34018 non-null  float64
 65  QS700D          34018 non-null  float64
 66  QS700E          34018 non-null  float64
 67  QS700F          34018 non-null  float64
 68  QS700G          34018 non-null  float64
 69  QS700H          34018 non-null  float64
 70  QS700I          34018 non-null  float64
 71  QS703           34018 non-null  float64
 72  QS707           34018 non-null  float64
 73  QS709           34018 non-null  float64
 74  QS710           34018 non-null  float64
 75  QS711           34018 non-null  float64
 76  QS730           34018 non-null  float64
 77  QS900           34018 non-null  float64
 78  QS901           34018 non-null  float64
 79  QS902           34018 non-null  float64
 80  QS903S          34018 non-null  float64
 81  QS903D          34018 non-null  float64
 82  QS905S          34018 non-null  float64
 83  QS905D          34018 non-null  float64
 84  QS906           34018 non-null  float64
 85  QS25C1          34018 non-null  float64
 86  QS25C2          34018 non-null  float64
 87  QS25C3          34018 non-null  float64
 88  QS25C4          34018 non-null  float64
 89  QS25C5          34018 non-null  float64
 90  QS25C6          34018 non-null  float64
 91  QS907           34018 non-null  float64
 92  QS908           34018 non-null  float64
 93  PESO15_AMAS     34018 non-null  float64
 94  CASEID_9d       34018 non-null  float64
 95  premature_flag  34018 non-null  float64
 96  HHID            34018 non-null  object
dtypes: float64(95), object(2)
memory usage: 25.2+ MB

In [ ]:
save_file(Modulo1640_CSALUD01_2024_M_clear_v3, output_file = "Modulo1640_CSALUD01_2024_M_clear_v3.csv")

save_txt(encoding_map_CSALUD01, dir="data\\interim",output_file="encoding_map_CSALUD01.txt")

✅ File saved successfully at: c:\Users\linoc\OneDrive\Encoder\03_partos\02_scripts\Premature_model\data\interim\encoding_map_CSALUD01.txt