In [5]:
# This is timport datarobot as dr
import pandas as pd
import numpy as np
from datetime import datetime
from scipy.stats import mode
import seaborn as sns
import matplotlib.pyplot as plt
import numpy as np
from sklearn.preprocessing import MinMaxScaler
import sys, os
from pathlib import Path



# Go up one directory from "notebooks" to project root
project_root = os.path.abspath(os.path.join(os.getcwd(), ".."))
sys.path.append(project_root)

#from scripts.modeling import (rank_models   )

In [6]:
import sys
print(sys.executable)

!{sys.executable} -m pip install xgboost

c:\Users\linoc\AppData\Local\Programs\Python\Python39\python.exe
Requirement already satisfied: xgboost in c:\users\linoc\appdata\local\programs\python\python39\lib\site-packages (2.1.4)
Requirement already satisfied: numpy in c:\users\linoc\appdata\local\programs\python\python39\lib\site-packages (from xgboost) (1.26.4)
Requirement already satisfied: scipy in c:\users\linoc\appdata\local\programs\python\python39\lib\site-packages (from xgboost) (1.13.1)

[notice] A new release of pip is available: 24.0 -> 25.2
[notice] To update, run: python.exe -m pip install --upgrade pip

# 1 Ingests Data

In [7]:
# Build base directory (go up one level from current /02_scripts)
base_dir = os.path.dirname(os.getcwd())   # → c:\Users\linoc\OneDrive\Encoder\03_partos
base_dir_raw =  Path(base_dir)
base_dir_raw= str(base_dir_raw.parents[1])

In [8]:
# Build the path to the target CSV
csv_path_Modulo1631_REC91_2024_M_clear = os.path.join(base_dir,"data\\interim", "Modulo1631_REC91_2024_M_clear.csv")
csv_path_Modulo1635_RE516171_2024_M_clear = os.path.join(base_dir,"data\\interim", "Modulo1635_RE516171_2024_M_clear.csv")
csv_path_Modulo1632_RE223132_2024_M_clear = os.path.join(base_dir,"data\\interim", "Modulo1632_RE223132_2024_M_clear.csv")
csv_path_Modulo1633_REC41_2024_fil_clear_v2 = os.path.join(base_dir,"data\\interim", "Modulo1633_REC41_2024_fil_clear_v2.csv")
csv_path_Modulo1633_REC94_2024_fil_clear_v2 = os.path.join(base_dir,"data\\interim", "Modulo1633_REC94_2024_fil_clear_v2.csv")
csv_path_Modulo1640_CSALUD01_2024_M_clear = os.path.join(base_dir,"data\\interim", "Modulo1640_CSALUD01_2024_M_clear.csv")
csv_path_target_final = os.path.join(base_dir,"data\\interim", "target_final.csv")

# Load the CSV into a DataFrame
Modulo1631_REC91_2024_M_clear = pd.read_csv(csv_path_Modulo1631_REC91_2024_M_clear, low_memory=False)
Modulo1635_RE516171_2024_M_clear= pd.read_csv(csv_path_Modulo1635_RE516171_2024_M_clear, low_memory=False)
Modulo1632_RE223132_2024_M_clear= pd.read_csv(csv_path_Modulo1632_RE223132_2024_M_clear, low_memory=False)
Modulo1633_REC41_2024_fil_clear_v2= pd.read_csv(csv_path_Modulo1633_REC41_2024_fil_clear_v2, low_memory=False)
Modulo1633_REC94_2024_fil_clear_v2= pd.read_csv(csv_path_Modulo1633_REC94_2024_fil_clear_v2, low_memory=False)
Modulo1640_CSALUD01_2024_M_clear= pd.read_csv(csv_path_Modulo1640_CSALUD01_2024_M_clear, low_memory=False)
target_final = pd.read_csv(csv_path_target_final, low_memory=False)


print(Modulo1631_REC91_2024_M_clear.shape)
print(Modulo1635_RE516171_2024_M_clear.shape)
print(Modulo1632_RE223132_2024_M_clear.shape)
print(Modulo1633_REC41_2024_fil_clear_v2.shape)
print(Modulo1633_REC94_2024_fil_clear_v2.shape) 
print(Modulo1640_CSALUD01_2024_M_clear.shape) 
print(target_final.shape)

(37117, 132)
(34252, 63)
(34252, 65)
(16983, 463)
(16983, 280)
(34018, 153)
(18335, 5)

In [9]:
Modulo1633_REC41_2024_fil_clear_v2.info(verbose=True, show_counts=True    
                                  )

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 16983 entries, 0 to 16982
Data columns (total 463 columns):
 #    Column          Non-Null Count  Dtype
---   ------          --------------  -----
 0    BIDX_x          16983 non-null  float64
 1    M6              16983 non-null  float64
 2    M7              16983 non-null  float64
 3    M8              16983 non-null  float64
 4    M9              16983 non-null  float64
 5    M11             16983 non-null  float64
 6    M13             16983 non-null  float64
 7    M14             16983 non-null  float64
 8    premature_flag  16983 non-null  int64
 9    M2A             16983 non-null  float64
 10   M2B             16983 non-null  float64
 11   M2C             16983 non-null  float64
 12   M2D             16983 non-null  float64
 13   M2E             16983 non-null  float64
 14   M2G             16983 non-null  float64
 15   M2K             16983 non-null  float64
 16   M2N             16983 non-null  float64
 17   M3A             16983 non-null  int64
 18   M3B             16983 non-null  int64
 19   M3C             16983 non-null  int64
 20   M3D             16983 non-null  int64
 21   M3E             16983 non-null  int64
 22   M3G             16983 non-null  int64
 23   M3H             16983 non-null  int64
 24   M3K             16983 non-null  int64
 25   M3N             16983 non-null  int64
 26   M17             16983 non-null  int64
 27   M54             16983 non-null  float64
 28   M57E            16983 non-null  float64
 29   M57F            16983 non-null  float64
 30   M57G            16983 non-null  float64
 31   M57I            16983 non-null  float64
 32   M57J            16983 non-null  float64
 33   M57K            16983 non-null  float64
 34   M57L            16983 non-null  float64
 35   M57M            16983 non-null  float64
 36   M57O            16983 non-null  float64
 37   M57P            16983 non-null  float64
 38   M57Q            16983 non-null  float64
 39   M57S            16983 non-null  float64
 40   M57X            16983 non-null  float64
 41   M66             16983 non-null  int64
 42   BIDX_1          16983 non-null  int64
 43   BIDX_2          16983 non-null  int64
 44   BIDX_3          16983 non-null  int64
 45   BIDX_4          16983 non-null  int64
 46   ID1_2024        16983 non-null  int64
 47   MIDX_1          16983 non-null  int64
 48   MIDX_2          16983 non-null  int64
 49   MIDX_3          16983 non-null  int64
 50   MIDX_4          16983 non-null  int64
 51   M1_0            16983 non-null  int64
 52   M1_1            16983 non-null  int64
 53   M1_2            16983 non-null  int64
 54   M1_3            16983 non-null  int64
 55   M1_4            16983 non-null  int64
 56   M1_5            16983 non-null  int64
 57   M1_7            16983 non-null  int64
 58   M1_8            16983 non-null  int64
 59   M1_<NA>         16983 non-null  int64
 60   M1A_0           16983 non-null  int64
 61   M1A_1           16983 non-null  int64
 62   M1A_2           16983 non-null  int64
 63   M1A_3           16983 non-null  int64
 64   M1A_4           16983 non-null  int64
 65   M1A_5           16983 non-null  int64
 66   M1A_6           16983 non-null  int64
 67   M1A_7           16983 non-null  int64
 68   M1A_8           16983 non-null  int64
 69   M1A_<NA>        16983 non-null  int64
 70   M1B_1           16983 non-null  int64
 71   M1B_10          16983 non-null  int64
 72   M1B_11          16983 non-null  int64
 73   M1B_12          16983 non-null  int64
 74   M1B_2           16983 non-null  int64
 75   M1B_3           16983 non-null  int64
 76   M1B_4           16983 non-null  int64
 77   M1B_5           16983 non-null  int64
 78   M1B_6           16983 non-null  int64
 79   M1B_7           16983 non-null  int64
 80   M1B_8           16983 non-null  int64
 81   M1B_9           16983 non-null  int64
 82   M1B_98          16983 non-null  int64
 83   M1B_<NA>        16983 non-null  int64
 84   M1D_1           16983 non-null  int64
 85   M1D_10          16983 non-null  int64
 86   M1D_11          16983 non-null  int64
 87   M1D_12          16983 non-null  int64
 88   M1D_13          16983 non-null  int64
 89   M1D_14          16983 non-null  int64
 90   M1D_15          16983 non-null  int64
 91   M1D_16          16983 non-null  int64
 92   M1D_17          16983 non-null  int64
 93   M1D_18          16983 non-null  int64
 94   M1D_2           16983 non-null  int64
 95   M1D_20          16983 non-null  int64
 96   M1D_22          16983 non-null  int64
 97   M1D_24          16983 non-null  int64
 98   M1D_25          16983 non-null  int64
 99   M1D_27          16983 non-null  int64
 100  M1D_3           16983 non-null  int64
 101  M1D_4           16983 non-null  int64
 102  M1D_5           16983 non-null  int64
 103  M1D_6           16983 non-null  int64
 104  M1D_7           16983 non-null  int64
 105  M1D_8           16983 non-null  int64
 106  M1D_9           16983 non-null  int64
 107  M1D_98          16983 non-null  int64
 108  M1D_<NA>        16983 non-null  int64
 109  M5_0            16983 non-null  int64
 110  M5_1            16983 non-null  int64
 111  M5_10           16983 non-null  int64
 112  M5_11           16983 non-null  int64
 113  M5_12           16983 non-null  int64
 114  M5_13           16983 non-null  int64
 115  M5_14           16983 non-null  int64
 116  M5_15           16983 non-null  int64
 117  M5_16           16983 non-null  int64
 118  M5_17           16983 non-null  int64
 119  M5_18           16983 non-null  int64
 120  M5_19           16983 non-null  int64
 121  M5_2            16983 non-null  int64
 122  M5_20           16983 non-null  int64
 123  M5_21           16983 non-null  int64
 124  M5_22           16983 non-null  int64
 125  M5_23           16983 non-null  int64
 126  M5_24           16983 non-null  int64
 127  M5_25           16983 non-null  int64
 128  M5_26           16983 non-null  int64
 129  M5_27           16983 non-null  int64
 130  M5_28           16983 non-null  int64
 131  M5_29           16983 non-null  int64
 132  M5_3            16983 non-null  int64
 133  M5_30           16983 non-null  int64
 134  M5_31           16983 non-null  int64
 135  M5_32           16983 non-null  int64
 136  M5_33           16983 non-null  int64
 137  M5_34           16983 non-null  int64
 138  M5_35           16983 non-null  int64
 139  M5_36           16983 non-null  int64
 140  M5_37           16983 non-null  int64
 141  M5_38           16983 non-null  int64
 142  M5_39           16983 non-null  int64
 143  M5_4            16983 non-null  int64
 144  M5_40           16983 non-null  int64
 145  M5_41           16983 non-null  int64
 146  M5_42           16983 non-null  int64
 147  M5_43           16983 non-null  int64
 148  M5_44           16983 non-null  int64
 149  M5_45           16983 non-null  int64
 150  M5_46           16983 non-null  int64
 151  M5_47           16983 non-null  int64
 152  M5_48           16983 non-null  int64
 153  M5_49           16983 non-null  int64
 154  M5_5            16983 non-null  int64
 155  M5_50           16983 non-null  int64
 156  M5_51           16983 non-null  int64
 157  M5_52           16983 non-null  int64
 158  M5_53           16983 non-null  int64
 159  M5_54           16983 non-null  int64
 160  M5_55           16983 non-null  int64
 161  M5_56           16983 non-null  int64
 162  M5_57           16983 non-null  int64
 163  M5_58           16983 non-null  int64
 164  M5_59           16983 non-null  int64
 165  M5_6            16983 non-null  int64
 166  M5_7            16983 non-null  int64
 167  M5_8            16983 non-null  int64
 168  M5_9            16983 non-null  int64
 169  M5_94           16983 non-null  int64
 170  M5_98           16983 non-null  int64
 171  M10_1           16983 non-null  int64
 172  M10_2           16983 non-null  int64
 173  M10_3           16983 non-null  int64
 174  M15_11          16983 non-null  int64
 175  M15_12          16983 non-null  int64
 176  M15_21          16983 non-null  int64
 177  M15_22          16983 non-null  int64
 178  M15_23          16983 non-null  int64
 179  M15_24          16983 non-null  int64
 180  M15_25          16983 non-null  int64
 181  M15_26          16983 non-null  int64
 182  M15_27          16983 non-null  int64
 183  M15_31          16983 non-null  int64
 184  M15_32          16983 non-null  int64
 185  M15_41          16983 non-null  int64
 186  M15_42          16983 non-null  int64
 187  M15_96          16983 non-null  int64
 188  M18_1           16983 non-null  int64
 189  M18_2           16983 non-null  int64
 190  M18_3           16983 non-null  int64
 191  M18_4           16983 non-null  int64
 192  M18_5           16983 non-null  int64
 193  M18_8           16983 non-null  int64
 194  M19A_0          16983 non-null  int64
 195  M19A_1          16983 non-null  int64
 196  M19A_2          16983 non-null  int64
 197  M19A_8          16983 non-null  int64
 198  M19A_<NA>       16983 non-null  int64
 199  M27_0           16983 non-null  int64
 200  M27_3           16983 non-null  int64
 201  M28_0           16983 non-null  int64
 202  M28_1           16983 non-null  int64
 203  M28_2           16983 non-null  int64
 204  M28_4           16983 non-null  int64
 205  M29_0           16983 non-null  int64
 206  M29_1           16983 non-null  int64
 207  M29_2           16983 non-null  int64
 208  M29_4           16983 non-null  int64
 209  M35_0           16983 non-null  int64
 210  M35_1           16983 non-null  int64
 211  M35_10          16983 non-null  int64
 212  M35_11          16983 non-null  int64
 213  M35_12          16983 non-null  int64
 214  M35_14          16983 non-null  int64
 215  M35_15          16983 non-null  int64
 216  M35_16          16983 non-null  int64
 217  M35_18          16983 non-null  int64
 218  M35_2           16983 non-null  int64
 219  M35_20          16983 non-null  int64
 220  M35_3           16983 non-null  int64
 221  M35_4           16983 non-null  int64
 222  M35_5           16983 non-null  int64
 223  M35_6           16983 non-null  int64
 224  M35_7           16983 non-null  int64
 225  M35_8           16983 non-null  int64
 226  M35_9           16983 non-null  int64
 227  M35_<NA>        16983 non-null  int64
 228  M36_0           16983 non-null  int64
 229  M36_1           16983 non-null  int64
 230  M36_10          16983 non-null  int64
 231  M36_11          16983 non-null  int64
 232  M36_12          16983 non-null  int64
 233  M36_13          16983 non-null  int64
 234  M36_14          16983 non-null  int64
 235  M36_15          16983 non-null  int64
 236  M36_16          16983 non-null  int64
 237  M36_18          16983 non-null  int64
 238  M36_2           16983 non-null  int64
 239  M36_20          16983 non-null  int64
 240  M36_24          16983 non-null  int64
 241  M36_3           16983 non-null  int64
 242  M36_4           16983 non-null  int64
 243  M36_5           16983 non-null  int64
 244  M36_6           16983 non-null  int64
 245  M36_7           16983 non-null  int64
 246  M36_8           16983 non-null  int64
 247  M36_9           16983 non-null  int64
 248  M36_<NA>        16983 non-null  int64
 249  M38_0           16983 non-null  int64
 250  M38_1           16983 non-null  int64
 251  M38_8           16983 non-null  int64
 252  M38_<NA>        16983 non-null  int64
 253  M39_0           16983 non-null  int64
 254  M39_1           16983 non-null  int64
 255  M39_2           16983 non-null  int64
 256  M39_3           16983 non-null  int64
 257  M39_4           16983 non-null  int64
 258  M39_5           16983 non-null  int64
 259  M39_6           16983 non-null  int64
 260  M39_7           16983 non-null  int64
 261  M39_8           16983 non-null  int64
 262  M39_<NA>        16983 non-null  int64
 263  M42A_0          16983 non-null  int64
 264  M42A_1          16983 non-null  int64
 265  M42A_8          16983 non-null  int64
 266  M42A_<NA>       16983 non-null  int64
 267  M42C_0          16983 non-null  int64
 268  M42C_1          16983 non-null  int64
 269  M42C_8          16983 non-null  int64
 270  M42C_<NA>       16983 non-null  int64
 271  M42D_0          16983 non-null  int64
 272  M42D_1          16983 non-null  int64
 273  M42D_8          16983 non-null  int64
 274  M42D_<NA>       16983 non-null  int64
 275  M42E_0          16983 non-null  int64
 276  M42E_1          16983 non-null  int64
 277  M42E_8          16983 non-null  int64
 278  M42E_<NA>       16983 non-null  int64
 279  M43_0           16983 non-null  int64
 280  M43_1           16983 non-null  int64
 281  M43_8           16983 non-null  int64
 282  M43_<NA>        16983 non-null  int64
 283  M44_0           16983 non-null  int64
 284  M44_1           16983 non-null  int64
 285  M44_8           16983 non-null  int64
 286  M44_<NA>        16983 non-null  int64
 287  M45_0           16983 non-null  int64
 288  M45_1           16983 non-null  int64
 289  M45_8           16983 non-null  int64
 290  M45_<NA>        16983 non-null  int64
 291  M47_0           16983 non-null  int64
 292  M47_1           16983 non-null  int64
 293  M47_8           16983 non-null  int64
 294  M47_<NA>        16983 non-null  int64
 295  M48_0           16983 non-null  int64
 296  M48_1           16983 non-null  int64
 297  M48_8           16983 non-null  int64
 298  M48_<NA>        16983 non-null  int64
 299  M55A_0          16983 non-null  int64
 300  M55A_1          16983 non-null  int64
 301  M55A_8          16983 non-null  int64
 302  M55B_0          16983 non-null  int64
 303  M55B_1          16983 non-null  int64
 304  M55B_8          16983 non-null  int64
 305  M55C_0          16983 non-null  int64
 306  M55C_1          16983 non-null  int64
 307  M55C_8          16983 non-null  int64
 308  M55E_0          16983 non-null  int64
 309  M55E_1          16983 non-null  int64
 310  M55E_8          16983 non-null  int64
 311  M55F_0          16983 non-null  int64
 312  M55F_1          16983 non-null  int64
 313  M55F_8          16983 non-null  int64
 314  M55G_0          16983 non-null  int64
 315  M55G_1          16983 non-null  int64
 316  M55G_8          16983 non-null  int64
 317  M55H_0          16983 non-null  int64
 318  M55H_1          16983 non-null  int64
 319  M55H_8          16983 non-null  int64
 320  M55I_0          16983 non-null  int64
 321  M55I_1          16983 non-null  int64
 322  M55I_8          16983 non-null  int64
 323  M55X_0          16983 non-null  int64
 324  M55X_1          16983 non-null  int64
 325  M55X_8          16983 non-null  int64
 326  M55Z_0          16983 non-null  int64
 327  M55Z_1          16983 non-null  int64
 328  M55Z_8          16983 non-null  int64
 329  M60_0           16983 non-null  int64
 330  M60_1           16983 non-null  int64
 331  M60_8           16983 non-null  int64
 332  M60_<NA>        16983 non-null  int64
 333  M67_100         16983 non-null  int64
 334  M67_101         16983 non-null  int64
 335  M67_102         16983 non-null  int64
 336  M67_103         16983 non-null  int64
 337  M67_104         16983 non-null  int64
 338  M67_105         16983 non-null  int64
 339  M67_106         16983 non-null  int64
 340  M67_107         16983 non-null  int64
 341  M67_108         16983 non-null  int64
 342  M67_109         16983 non-null  int64
 343  M67_110         16983 non-null  int64
 344  M67_111         16983 non-null  int64
 345  M67_112         16983 non-null  int64
 346  M67_113         16983 non-null  int64
 347  M67_114         16983 non-null  int64
 348  M67_115         16983 non-null  int64
 349  M67_116         16983 non-null  int64
 350  M67_117         16983 non-null  int64
 351  M67_118         16983 non-null  int64
 352  M67_119         16983 non-null  int64
 353  M67_120         16983 non-null  int64
 354  M67_121         16983 non-null  int64
 355  M67_122         16983 non-null  int64
 356  M67_123         16983 non-null  int64
 357  M67_201         16983 non-null  int64
 358  M67_202         16983 non-null  int64
 359  M67_203         16983 non-null  int64
 360  M67_204         16983 non-null  int64
 361  M67_205         16983 non-null  int64
 362  M67_206         16983 non-null  int64
 363  M67_207         16983 non-null  int64
 364  M67_209         16983 non-null  int64
 365  M67_215         16983 non-null  int64
 366  M67_301         16983 non-null  int64
 367  M67_302         16983 non-null  int64
 368  M67_303         16983 non-null  int64
 369  M67_304         16983 non-null  int64
 370  M67_<NA>        16983 non-null  int64
 371  M68_11          16983 non-null  int64
 372  M68_12          16983 non-null  int64
 373  M68_13          16983 non-null  int64
 374  M68_14          16983 non-null  int64
 375  M68_15          16983 non-null  int64
 376  M68_21          16983 non-null  int64
 377  M68_96          16983 non-null  int64
 378  M68_<NA>        16983 non-null  int64
 379  M69_11          16983 non-null  int64
 380  M69_12          16983 non-null  int64
 381  M69_21          16983 non-null  int64
 382  M69_22          16983 non-null  int64
 383  M69_23          16983 non-null  int64
 384  M69_24          16983 non-null  int64
 385  M69_25          16983 non-null  int64
 386  M69_26          16983 non-null  int64
 387  M69_27          16983 non-null  int64
 388  M69_31          16983 non-null  int64
 389  M69_32          16983 non-null  int64
 390  M69_41          16983 non-null  int64
 391  M69_42          16983 non-null  int64
 392  M69_96          16983 non-null  int64
 393  M69_<NA>        16983 non-null  int64
 394  M70_0           16983 non-null  int64
 395  M70_1           16983 non-null  int64
 396  M70_8           16983 non-null  int64
 397  M70_<NA>        16983 non-null  int64
 398  M71_100         16983 non-null  int64
 399  M71_101         16983 non-null  int64
 400  M71_102         16983 non-null  int64
 401  M71_103         16983 non-null  int64
 402  M71_104         16983 non-null  int64
 403  M71_105         16983 non-null  int64
 404  M71_106         16983 non-null  int64
 405  M71_107         16983 non-null  int64
 406  M71_108         16983 non-null  int64
 407  M71_109         16983 non-null  int64
 408  M71_110         16983 non-null  int64
 409  M71_111         16983 non-null  int64
 410  M71_112         16983 non-null  int64
 411  M71_113         16983 non-null  int64
 412  M71_114         16983 non-null  int64
 413  M71_115         16983 non-null  int64
 414  M71_116         16983 non-null  int64
 415  M71_117         16983 non-null  int64
 416  M71_118         16983 non-null  int64
 417  M71_119         16983 non-null  int64
 418  M71_120         16983 non-null  int64
 419  M71_122         16983 non-null  int64
 420  M71_123         16983 non-null  int64
 421  M71_201         16983 non-null  int64
 422  M71_202         16983 non-null  int64
 423  M71_203         16983 non-null  int64
 424  M71_204         16983 non-null  int64
 425  M71_205         16983 non-null  int64
 426  M71_206         16983 non-null  int64
 427  M71_207         16983 non-null  int64
 428  M71_208         16983 non-null  int64
 429  M71_209         16983 non-null  int64
 430  M71_212         16983 non-null  int64
 431  M71_213         16983 non-null  int64
 432  M71_215         16983 non-null  int64
 433  M71_301         16983 non-null  int64
 434  M71_302         16983 non-null  int64
 435  M71_303         16983 non-null  int64
 436  M71_304         16983 non-null  int64
 437  M71_312         16983 non-null  int64
 438  M71_999         16983 non-null  int64
 439  M71_<NA>        16983 non-null  int64
 440  M72_11          16983 non-null  int64
 441  M72_12          16983 non-null  int64
 442  M72_13          16983 non-null  int64
 443  M72_14          16983 non-null  int64
 444  M72_15          16983 non-null  int64
 445  M72_21          16983 non-null  int64
 446  M72_96          16983 non-null  int64
 447  M72_<NA>        16983 non-null  int64

In [10]:
target_final.head()

               CASEID  BIDX  Q220A  premature  premature_flag
0        325503101  2     1      7          1               1
1        325504701  2     1      9          0               0
2        325505001  1     1      9          0               0
3        325508901  2     1      9          0               0
4        325509701  2     1      9          0               0

In [11]:
RANK_Modulo1631_REC91_2024_M_clear = ['SREGION','CASEID',
'S108N',
'S119',
'S119D',
'S704N',
'S816W',
'S816G',
'S816B',
'S816AL',
'S500B',
# 'S229A1',
# 'S229Y',
# 'S229A'
]

RANK_Modulo1635_RE516171_2024_M_clear =['CASEID',
    'V704',
'V715',
'V501',
'V716',
'V511',
'V631',
'V732',
'V504',
'V743F',
'V531',
'V525',
'V717',
'V743E',
'V743A',
'V702',
'V721',
'V705',

]
RANK_Modulo1632_RE223132_2024_M_clear = ['CASEID',
    'V212',
'V228',
'V218',
'V208',
'V217',
'V364',

]

RANK_Modulo1633_REC41_2024_fil_v2 =['CASEID',
    'M14',
'M13',
'M17',
'M1',
'M18',
'M19',
'M19A',
'M2C',
'M3C',
'M3G',
'M42A',
'M42B',
'M42C',
'M42D',
'M42E',
'M43',
'M44',
'M45',
'M46',
'M47',
'M48',
'M49A',
'M49B',
'M49C',
'M49D',
'M49X',
'M49Z',
'M57A',
'M57B',
'M60',
'M3A',
'M57I',
'M3H',
'M57O',
'M57G',
'M3B',
'M57M',
'M57K',
'M57X',
'M2B',
'M57Q',
'M57E',

]
RANK_Modulo1633_REC94_2024_fil_clear_v2 = ['CASEID',
'S410B',
'S411B',
'S411F',
'S411G',
'S411H',
'S411I',
'S411J',
'S411K',
'QI422A_A',
'QI422A_B',
'QI422A_C',
'QI422A_D',
'S426E',
'S426GE',
'S411BA',
'S413',
'S441',
'S411DA',
'S411EA',
'S411CA',
'S422I',


]
RANK_Modulo1640_CSALUD01_2024_M_clear =['HHID',
    'QS25N',
'QS22A',
'QS27_A',
'QS102',
'QS27_B',
'QS207C',
'QS109',
'QS27_BD',
'QS25AA',
'QS25BB',
'QS406',
'QS100',
#'QS103U',
'QS107',
# 'QS110U',
# 'QS202',
# 'QS203U',
# 'QS204C',
# 'QS205U',
'QS206',
'QS27_D',
'QS27_BC',
'QS25A',
'QS27_E',
'QS27_ ',
'QS25C5',
'QS25C3',

]

In [12]:
Modulo1631_REC91_2024_M_clear[RANK_Modulo1631_REC91_2024_M_clear].head()

,SREGION,CASEID,S108N,S119,S119D,S704N,S816W,S816G,S816B,S816AL,S500B
0,0.666667,325503101 2,0.4,1.0,0.061856,0.2,0,0,0,0,0
1,0.666667,325503101 4,0.4,1.0,0.061856,0.4,0,0,0,0,0
2,0.666667,325503901 2,0.4,1.0,0.061856,0.4,0,0,1,0,0
3,0.666667,325504701 2,0.4,1.0,0.061856,0.4,0,0,0,0,0
4,0.666667,325505001 1,0.2,1.0,0.061856,0.2,0,0,0,0,0

In [13]:
Modulo1635_RE516171_2024_M_clear[RANK_Modulo1635_RE516171_2024_M_clear].head()

,CASEID,V704,V715,V501,V716,V511,V631,V732,V504,V743F,V531,V525,V717,V743E,V743A,V702,V721,V705
0,325503101 2,0.876289,0.352941,0.4,0.589474,0.461538,0.333333,0.0,0.0,0.333333,0.607143,0.607143,0.0,0.2,0.25,1.000000,1.0,0.888889
1,325503101 4,0.618557,0.647059,0.0,0.589474,0.346154,0.000000,0.0,0.0,0.333333,0.000000,0.000000,0.0,0.2,0.25,0.833333,1.0,0.444444
2,325503901 2,0.618557,0.647059,0.0,0.589474,0.346154,0.000000,0.0,0.0,0.333333,0.000000,0.000000,0.0,0.2,0.25,0.833333,1.0,0.444444
3,325504701 2,0.969072,0.647059,0.4,0.589474,0.423077,0.000000,0.0,0.0,0.333333,0.642857,0.642857,0.0,0.4,0.25,0.833333,1.0,0.666667
4,325505001 1,0.793814,0.352941,0.4,0.589474,0.230769,0.666667,0.0,0.0,0.000000,0.571429,0.571429,0.0,0.2,0.50,1.000000,1.0,0.888889

In [14]:
Modulo1632_RE223132_2024_M_clear[RANK_Modulo1632_RE223132_2024_M_clear].head()

               CASEID  V212  V228      V218  V208      V217      V364
0        325503101  2  0.44     0  0.285714   0.5  0.285714  0.333333
1        325503101  4  0.36     0  0.000000   0.0  1.000000  0.666667
2        325503901  2  0.36     0  0.000000   0.0  0.714286  0.666667
3        325504701  2  0.36     0  0.285714   0.5  1.000000  0.333333
4        325505001  1  0.24     0  0.285714   0.5  0.571429  0.000000

In [15]:
# keep all columns where name contains any of the patterns
pattern = '|'.join([f'^{x}' for x in RANK_Modulo1633_REC41_2024_fil_v2])  # start-with pattern
# Add rule for exact match 'MIDX'
pattern = f'({pattern})|(^MIDX$)'
Modulo1633_REC41_2024_fil_clear_v2 = Modulo1633_REC41_2024_fil_clear_v2.filter(regex=pattern, axis=1)
Modulo1633_REC41_2024_fil_clear_v2.info(verbose = True)

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 16983 entries, 0 to 16982
Data columns (total 146 columns):
 #    Column     Dtype
---   ------     -----
 0    M11        float64
 1    M13        float64
 2    M14        float64
 3    M2B        float64
 4    M2C        float64
 5    M3A        int64
 6    M3B        int64
 7    M3C        int64
 8    M3G        int64
 9    M3H        int64
 10   M17        int64
 11   M57E       float64
 12   M57G       float64
 13   M57I       float64
 14   M57K       float64
 15   M57M       float64
 16   M57O       float64
 17   M57Q       float64
 18   M57X       float64
 19   M1_0       int64
 20   M1_1       int64
 21   M1_2       int64
 22   M1_3       int64
 23   M1_4       int64
 24   M1_5       int64
 25   M1_7       int64
 26   M1_8       int64
 27   M1_<NA>    int64
 28   M1A_0      int64
 29   M1A_1      int64
 30   M1A_2      int64
 31   M1A_3      int64
 32   M1A_4      int64
 33   M1A_5      int64
 34   M1A_6      int64
 35   M1A_7      int64
 36   M1A_8      int64
 37   M1A_<NA>   int64
 38   M1B_1      int64
 39   M1B_10     int64
 40   M1B_11     int64
 41   M1B_12     int64
 42   M1B_2      int64
 43   M1B_3      int64
 44   M1B_4      int64
 45   M1B_5      int64
 46   M1B_6      int64
 47   M1B_7      int64
 48   M1B_8      int64
 49   M1B_9      int64
 50   M1B_98     int64
 51   M1B_<NA>   int64
 52   M1D_1      int64
 53   M1D_10     int64
 54   M1D_11     int64
 55   M1D_12     int64
 56   M1D_13     int64
 57   M1D_14     int64
 58   M1D_15     int64
 59   M1D_16     int64
 60   M1D_17     int64
 61   M1D_18     int64
 62   M1D_2      int64
 63   M1D_20     int64
 64   M1D_22     int64
 65   M1D_24     int64
 66   M1D_25     int64
 67   M1D_27     int64
 68   M1D_3      int64
 69   M1D_4      int64
 70   M1D_5      int64
 71   M1D_6      int64
 72   M1D_7      int64
 73   M1D_8      int64
 74   M1D_9      int64
 75   M1D_98     int64
 76   M1D_<NA>   int64
 77   M10_1      int64
 78   M10_2      int64
 79   M10_3      int64
 80   M15_11     int64
 81   M15_12     int64
 82   M15_21     int64
 83   M15_22     int64
 84   M15_23     int64
 85   M15_24     int64
 86   M15_25     int64
 87   M15_26     int64
 88   M15_27     int64
 89   M15_31     int64
 90   M15_32     int64
 91   M15_41     int64
 92   M15_42     int64
 93   M15_96     int64
 94   M18_1      int64
 95   M18_2      int64
 96   M18_3      int64
 97   M18_4      int64
 98   M18_5      int64
 99   M18_8      int64
 100  M19A_0     int64
 101  M19A_1     int64
 102  M19A_2     int64
 103  M19A_8     int64
 104  M19A_<NA>  int64
 105  M42A_0     int64
 106  M42A_1     int64
 107  M42A_8     int64
 108  M42A_<NA>  int64
 109  M42C_0     int64
 110  M42C_1     int64
 111  M42C_8     int64
 112  M42C_<NA>  int64
 113  M42D_0     int64
 114  M42D_1     int64
 115  M42D_8     int64
 116  M42D_<NA>  int64
 117  M42E_0     int64
 118  M42E_1     int64
 119  M42E_8     int64
 120  M42E_<NA>  int64
 121  M43_0      int64
 122  M43_1      int64
 123  M43_8      int64
 124  M43_<NA>   int64
 125  M44_0      int64
 126  M44_1      int64
 127  M44_8      int64
 128  M44_<NA>   int64
 129  M45_0      int64
 130  M45_1      int64
 131  M45_8      int64
 132  M45_<NA>   int64
 133  M47_0      int64
 134  M47_1      int64
 135  M47_8      int64
 136  M47_<NA>   int64
 137  M48_0      int64
 138  M48_1      int64
 139  M48_8      int64
 140  M48_<NA>   int64
 141  M60_0      int64
 142  M60_1      int64
 143  M60_8      int64
 144  M60_<NA>   int64
 145  CASEID     object
dtypes: float64(13), int64(132), object(1)
memory usage: 18.9+ MB

In [16]:
# keep all columns where name contains any of the patterns
pattern = '|'.join([f'^{x}' for x in RANK_Modulo1633_REC94_2024_fil_clear_v2])  # start-with pattern
Modulo1633_REC94_2024_fil_clear_v2_filter = Modulo1633_REC94_2024_fil_clear_v2.filter(regex=pattern, axis=1)
Modulo1633_REC94_2024_fil_clear_v2_filter.info(verbose = True)

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 16983 entries, 0 to 16982
Data columns (total 136 columns):
 #    Column         Dtype
---   ------         -----
 0    S411DA         float64
 1    S411CA         float64
 2    S422I          float64
 3    S411EA         float64
 4    S411BA         float64
 5    S413           float64
 6    S426E          float64
 7    S426GE         float64
 8    S441           int64
 9    S410B_1        int64
 10   S410B_2        int64
 11   S410B_3        int64
 12   S410B_4        int64
 13   S410B_5        int64
 14   S410B_6        int64
 15   S410B_7        int64
 16   S410B_8        int64
 17   S410B_9        int64
 18   S410B_98       int64
 19   S410B_<NA>     int64
 20   S411B_0        int64
 21   S411B_1        int64
 22   S411B_8        int64
 23   S411B_<NA>     int64
 24   S411F_0        int64
 25   S411F_1        int64
 26   S411F_8        int64
 27   S411F_<NA>     int64
 28   S411G_0        int64
 29   S411G_1        int64
 30   S411G_8        int64
 31   S411G_<NA>     int64
 32   S411H_0        int64
 33   S411H_1        int64
 34   S411H_8        int64
 35   S411H_<NA>     int64
 36   S411I_0        int64
 37   S411I_1        int64
 38   S411I_8        int64
 39   S411I_<NA>     int64
 40   S411J_0        int64
 41   S411J_1        int64
 42   S411J_8        int64
 43   S411J_<NA>     int64
 44   S411K_0        int64
 45   S411K_1        int64
 46   S411K_8        int64
 47   S411K_<NA>     int64
 48   S411BA_0       int64
 49   S411BA_1       int64
 50   S411BA_2       int64
 51   S411BA_3       int64
 52   S411BA_4       int64
 53   S411BA_5       int64
 54   S411BA_6       int64
 55   S411BA_7       int64
 56   S411BA_8       int64
 57   S411BA_9       int64
 58   S411BA_98      int64
 59   S411BA_<NA>    int64
 60   S411CA_0       int64
 61   S411CA_1       int64
 62   S411CA_2       int64
 63   S411CA_3       int64
 64   S411CA_4       int64
 65   S411CA_5       int64
 66   S411CA_6       int64
 67   S411CA_7       int64
 68   S411CA_8       int64
 69   S411CA_9       int64
 70   S411CA_98      int64
 71   S411CA_<NA>    int64
 72   S411DA_0       int64
 73   S411DA_1       int64
 74   S411DA_2       int64
 75   S411DA_3       int64
 76   S411DA_4       int64
 77   S411DA_5       int64
 78   S411DA_6       int64
 79   S411DA_7       int64
 80   S411DA_8       int64
 81   S411DA_9       int64
 82   S411DA_98      int64
 83   S411DA_<NA>    int64
 84   S411EA_0       int64
 85   S411EA_1       int64
 86   S411EA_2       int64
 87   S411EA_3       int64
 88   S411EA_4       int64
 89   S411EA_5       int64
 90   S411EA_6       int64
 91   S411EA_7       int64
 92   S411EA_8       int64
 93   S411EA_9       int64
 94   S411EA_98      int64
 95   S411EA_<NA>    int64
 96   S422I_0        int64
 97   S422I_1        int64
 98   S422I_10       int64
 99   S422I_12       int64
 100  S422I_14       int64
 101  S422I_15       int64
 102  S422I_16       int64
 103  S422I_18       int64
 104  S422I_2        int64
 105  S422I_20       int64
 106  S422I_24       int64
 107  S422I_3        int64
 108  S422I_30       int64
 109  S422I_36       int64
 110  S422I_4        int64
 111  S422I_5        int64
 112  S422I_6        int64
 113  S422I_60       int64
 114  S422I_7        int64
 115  S422I_8        int64
 116  S422I_80       int64
 117  S422I_9        int64
 118  S422I_98       int64
 119  S422I_<NA>     int64
 120  QI422A_A_1     int64
 121  QI422A_A_2     int64
 122  QI422A_A_8     int64
 123  QI422A_A_<NA>  int64
 124  QI422A_B_1     int64
 125  QI422A_B_2     int64
 126  QI422A_B_8     int64
 127  QI422A_B_<NA>  int64
 128  QI422A_C_1     int64
 129  QI422A_C_2     int64
 130  QI422A_C_8     int64
 131  QI422A_C_<NA>  int64
 132  QI422A_D_1     int64
 133  QI422A_D_2     int64
 134  QI422A_D_<NA>  int64
 135  CASEID         object
dtypes: float64(8), int64(127), object(1)
memory usage: 17.6+ MB

In [17]:
Modulo1640_CSALUD01_2024_M_clear[RANK_Modulo1640_CSALUD01_2024_M_clear].head()

,HHID,QS25N,QS22A,QS27_A,QS102,QS27_B,QS207C,QS109,QS27_BD,QS25AA,...,QS100,QS107,QS206,QS27_D,QS27_BC,QS25A,QS27_E,QS27_,QS25C5,QS25C3
0,325503101,0.4,0.729412,1,1.0,0,0.342857,1.0,0,1.000000,...,1.0,1.0,0.0,0,0,1.0,0,0,1.0,1.0
1,325503901,0.4,0.964706,0,1.0,1,0.371429,1.0,0,1.000000,...,0.0,0.0,1.0,0,0,1.0,0,0,1.0,1.0
2,325504001,0.4,0.400000,1,1.0,0,0.371429,1.0,0,1.000000,...,0.0,1.0,1.0,0,0,0.8,0,0,1.0,1.0
3,325504701,0.4,0.776471,1,1.0,0,0.342857,1.0,0,1.000000,...,0.0,0.0,0.0,0,0,1.0,0,0,1.0,1.0
4,325505001,0.2,0.811765,1,1.0,0,0.457143,1.0,0,0.888889,...,1.0,1.0,0.0,0,0,0.8,0,0,1.0,1.0

# 2 Consolidate Datasets

In [18]:
target_final.CASEID.nunique()

18335

In [19]:
data_train = target_final.merge(Modulo1631_REC91_2024_M_clear[RANK_Modulo1631_REC91_2024_M_clear].rename(
    columns={col: f"REC91_{col}" if col not in ["CASEID"] else col for col in Modulo1631_REC91_2024_M_clear[RANK_Modulo1631_REC91_2024_M_clear].columns}),
                                 on='CASEID', 
                                 how='left')
data_train.CASEID.nunique()

18335

In [20]:
data_train.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 18335 entries, 0 to 18334
Data columns (total 15 columns):
 #   Column          Non-Null Count  Dtype
---  ------          --------------  -----
 0   CASEID          18335 non-null  object
 1   BIDX            18335 non-null  int64
 2   Q220A           18335 non-null  int64
 3   premature       18335 non-null  int64
 4   premature_flag  18335 non-null  int64
 5   REC91_SREGION   18335 non-null  float64
 6   REC91_S108N     18335 non-null  float64
 7   REC91_S119      18335 non-null  float64
 8   REC91_S119D     18335 non-null  float64
 9   REC91_S704N     18335 non-null  float64
 10  REC91_S816W     18335 non-null  int64
 11  REC91_S816G     18335 non-null  int64
 12  REC91_S816B     18335 non-null  int64
 13  REC91_S816AL    18335 non-null  int64
 14  REC91_S500B     18335 non-null  int64
dtypes: float64(5), int64(9), object(1)
memory usage: 2.1+ MB

In [21]:
data_train = data_train.merge(Modulo1635_RE516171_2024_M_clear[RANK_Modulo1635_RE516171_2024_M_clear].rename(
    columns={col: f"RE516171_{col}" if col not in ["CASEID"] else col for col in Modulo1635_RE516171_2024_M_clear[RANK_Modulo1635_RE516171_2024_M_clear].columns}),
                                 on='CASEID', 
                                 how='left')
data_train.CASEID.nunique()

18335

In [22]:
data_train = data_train.merge(Modulo1633_REC41_2024_fil_clear_v2.rename(
    columns={col: f"REC41_{col}" if col not in ["CASEID"] else col for col in Modulo1633_REC41_2024_fil_clear_v2.columns}),
                                 on='CASEID', 
                                 how='left')
data_train.CASEID.nunique()

18335

In [24]:
data_train.info(verbose = True,show_counts=True)

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 18335 entries, 0 to 18334
Data columns (total 177 columns):
 #    Column           Non-Null Count  Dtype
---   ------           --------------  -----
 0    CASEID           18335 non-null  object
 1    BIDX             18335 non-null  int64
 2    Q220A            18335 non-null  int64
 3    premature        18335 non-null  int64
 4    premature_flag   18335 non-null  int64
 5    REC91_SREGION    18335 non-null  float64
 6    REC91_S108N      18335 non-null  float64
 7    REC91_S119       18335 non-null  float64
 8    REC91_S119D      18335 non-null  float64
 9    REC91_S704N      18335 non-null  float64
 10   REC91_S816W      18335 non-null  int64
 11   REC91_S816G      18335 non-null  int64
 12   REC91_S816B      18335 non-null  int64
 13   REC91_S816AL     18335 non-null  int64
 14   REC91_S500B      18335 non-null  int64
 15   RE516171_V704    18335 non-null  float64
 16   RE516171_V715    18335 non-null  float64
 17   RE516171_V501    18335 non-null  float64
 18   RE516171_V716    18335 non-null  float64
 19   RE516171_V511    18335 non-null  float64
 20   RE516171_V631    18335 non-null  float64
 21   RE516171_V732    18335 non-null  float64
 22   RE516171_V504    18335 non-null  float64
 23   RE516171_V743F   18335 non-null  float64
 24   RE516171_V531    18335 non-null  float64
 25   RE516171_V525    18335 non-null  float64
 26   RE516171_V717    18335 non-null  float64
 27   RE516171_V743E   18335 non-null  float64
 28   RE516171_V743A   18335 non-null  float64
 29   RE516171_V702    18335 non-null  float64
 30   RE516171_V721    18335 non-null  float64
 31   RE516171_V705    18335 non-null  float64
 32   REC41_M11        16983 non-null  float64
 33   REC41_M13        16983 non-null  float64
 34   REC41_M14        16983 non-null  float64
 35   REC41_M2B        16983 non-null  float64
 36   REC41_M2C        16983 non-null  float64
 37   REC41_M3A        16983 non-null  float64
 38   REC41_M3B        16983 non-null  float64
 39   REC41_M3C        16983 non-null  float64
 40   REC41_M3G        16983 non-null  float64
 41   REC41_M3H        16983 non-null  float64
 42   REC41_M17        16983 non-null  float64
 43   REC41_M57E       16983 non-null  float64
 44   REC41_M57G       16983 non-null  float64
 45   REC41_M57I       16983 non-null  float64
 46   REC41_M57K       16983 non-null  float64
 47   REC41_M57M       16983 non-null  float64
 48   REC41_M57O       16983 non-null  float64
 49   REC41_M57Q       16983 non-null  float64
 50   REC41_M57X       16983 non-null  float64
 51   REC41_M1_0       16983 non-null  float64
 52   REC41_M1_1       16983 non-null  float64
 53   REC41_M1_2       16983 non-null  float64
 54   REC41_M1_3       16983 non-null  float64
 55   REC41_M1_4       16983 non-null  float64
 56   REC41_M1_5       16983 non-null  float64
 57   REC41_M1_7       16983 non-null  float64
 58   REC41_M1_8       16983 non-null  float64
 59   REC41_M1_<NA>    16983 non-null  float64
 60   REC41_M1A_0      16983 non-null  float64
 61   REC41_M1A_1      16983 non-null  float64
 62   REC41_M1A_2      16983 non-null  float64
 63   REC41_M1A_3      16983 non-null  float64
 64   REC41_M1A_4      16983 non-null  float64
 65   REC41_M1A_5      16983 non-null  float64
 66   REC41_M1A_6      16983 non-null  float64
 67   REC41_M1A_7      16983 non-null  float64
 68   REC41_M1A_8      16983 non-null  float64
 69   REC41_M1A_<NA>   16983 non-null  float64
 70   REC41_M1B_1      16983 non-null  float64
 71   REC41_M1B_10     16983 non-null  float64
 72   REC41_M1B_11     16983 non-null  float64
 73   REC41_M1B_12     16983 non-null  float64
 74   REC41_M1B_2      16983 non-null  float64
 75   REC41_M1B_3      16983 non-null  float64
 76   REC41_M1B_4      16983 non-null  float64
 77   REC41_M1B_5      16983 non-null  float64
 78   REC41_M1B_6      16983 non-null  float64
 79   REC41_M1B_7      16983 non-null  float64
 80   REC41_M1B_8      16983 non-null  float64
 81   REC41_M1B_9      16983 non-null  float64
 82   REC41_M1B_98     16983 non-null  float64
 83   REC41_M1B_<NA>   16983 non-null  float64
 84   REC41_M1D_1      16983 non-null  float64
 85   REC41_M1D_10     16983 non-null  float64
 86   REC41_M1D_11     16983 non-null  float64
 87   REC41_M1D_12     16983 non-null  float64
 88   REC41_M1D_13     16983 non-null  float64
 89   REC41_M1D_14     16983 non-null  float64
 90   REC41_M1D_15     16983 non-null  float64
 91   REC41_M1D_16     16983 non-null  float64
 92   REC41_M1D_17     16983 non-null  float64
 93   REC41_M1D_18     16983 non-null  float64
 94   REC41_M1D_2      16983 non-null  float64
 95   REC41_M1D_20     16983 non-null  float64
 96   REC41_M1D_22     16983 non-null  float64
 97   REC41_M1D_24     16983 non-null  float64
 98   REC41_M1D_25     16983 non-null  float64
 99   REC41_M1D_27     16983 non-null  float64
 100  REC41_M1D_3      16983 non-null  float64
 101  REC41_M1D_4      16983 non-null  float64
 102  REC41_M1D_5      16983 non-null  float64
 103  REC41_M1D_6      16983 non-null  float64
 104  REC41_M1D_7      16983 non-null  float64
 105  REC41_M1D_8      16983 non-null  float64
 106  REC41_M1D_9      16983 non-null  float64
 107  REC41_M1D_98     16983 non-null  float64
 108  REC41_M1D_<NA>   16983 non-null  float64
 109  REC41_M10_1      16983 non-null  float64
 110  REC41_M10_2      16983 non-null  float64
 111  REC41_M10_3      16983 non-null  float64
 112  REC41_M15_11     16983 non-null  float64
 113  REC41_M15_12     16983 non-null  float64
 114  REC41_M15_21     16983 non-null  float64
 115  REC41_M15_22     16983 non-null  float64
 116  REC41_M15_23     16983 non-null  float64
 117  REC41_M15_24     16983 non-null  float64
 118  REC41_M15_25     16983 non-null  float64
 119  REC41_M15_26     16983 non-null  float64
 120  REC41_M15_27     16983 non-null  float64
 121  REC41_M15_31     16983 non-null  float64
 122  REC41_M15_32     16983 non-null  float64
 123  REC41_M15_41     16983 non-null  float64
 124  REC41_M15_42     16983 non-null  float64
 125  REC41_M15_96     16983 non-null  float64
 126  REC41_M18_1      16983 non-null  float64
 127  REC41_M18_2      16983 non-null  float64
 128  REC41_M18_3      16983 non-null  float64
 129  REC41_M18_4      16983 non-null  float64
 130  REC41_M18_5      16983 non-null  float64
 131  REC41_M18_8      16983 non-null  float64
 132  REC41_M19A_0     16983 non-null  float64
 133  REC41_M19A_1     16983 non-null  float64
 134  REC41_M19A_2     16983 non-null  float64
 135  REC41_M19A_8     16983 non-null  float64
 136  REC41_M19A_<NA>  16983 non-null  float64
 137  REC41_M42A_0     16983 non-null  float64
 138  REC41_M42A_1     16983 non-null  float64
 139  REC41_M42A_8     16983 non-null  float64
 140  REC41_M42A_<NA>  16983 non-null  float64
 141  REC41_M42C_0     16983 non-null  float64
 142  REC41_M42C_1     16983 non-null  float64
 143  REC41_M42C_8     16983 non-null  float64
 144  REC41_M42C_<NA>  16983 non-null  float64
 145  REC41_M42D_0     16983 non-null  float64
 146  REC41_M42D_1     16983 non-null  float64
 147  REC41_M42D_8     16983 non-null  float64
 148  REC41_M42D_<NA>  16983 non-null  float64
 149  REC41_M42E_0     16983 non-null  float64
 150  REC41_M42E_1     16983 non-null  float64
 151  REC41_M42E_8     16983 non-null  float64
 152  REC41_M42E_<NA>  16983 non-null  float64
 153  REC41_M43_0      16983 non-null  float64
 154  REC41_M43_1      16983 non-null  float64
 155  REC41_M43_8      16983 non-null  float64
 156  REC41_M43_<NA>   16983 non-null  float64
 157  REC41_M44_0      16983 non-null  float64
 158  REC41_M44_1      16983 non-null  float64
 159  REC41_M44_8      16983 non-null  float64
 160  REC41_M44_<NA>   16983 non-null  float64
 161  REC41_M45_0      16983 non-null  float64
 162  REC41_M45_1      16983 non-null  float64
 163  REC41_M45_8      16983 non-null  float64
 164  REC41_M45_<NA>   16983 non-null  float64
 165  REC41_M47_0      16983 non-null  float64
 166  REC41_M47_1      16983 non-null  float64
 167  REC41_M47_8      16983 non-null  float64
 168  REC41_M47_<NA>   16983 non-null  float64
 169  REC41_M48_0      16983 non-null  float64
 170  REC41_M48_1      16983 non-null  float64
 171  REC41_M48_8      16983 non-null  float64
 172  REC41_M48_<NA>   16983 non-null  float64
 173  REC41_M60_0      16983 non-null  float64
 174  REC41_M60_1      16983 non-null  float64
 175  REC41_M60_8      16983 non-null  float64
 176  REC41_M60_<NA>   16983 non-null  float64
dtypes: float64(167), int64(9), object(1)
memory usage: 24.8+ MB

In [ ]:
data_train = data_train.merge(Modulo1633_REC41_2024_fil_v2_filter.rename(
    columns={col: f"REC41_{col}" if col not in ["CASEID"] else col for col in Modulo1633_REC41_2024_fil_v2_filter.columns}),
                                 on='CASEID', 
                                 how='left')
data_train.CASEID.nunique()