In [1]:
# This is timport datarobot as dr
import pandas as pd
import numpy as np
from datetime import datetime
from scipy.stats import mode
import seaborn as sns
import matplotlib.pyplot as plt
import numpy as np
from sklearn.preprocessing import MinMaxScaler
import sys, os
from pathlib import Path
from functools import reduce
import pandas as pd



# Go up one directory from "notebooks" to project root
project_root = os.path.abspath(os.path.join(os.getcwd(), ".."))
sys.path.append(project_root)

In [2]:

# Build base directory (go up one level from current /02_scripts)
base_dir = os.path.dirname(os.getcwd())   # → c:\Users\linoc\OneDrive\Encoder\03_partos
base_dir_raw =  Path(base_dir)
base_dir_raw= str(base_dir_raw.parents[1])

# Build the path to the target CSV
csv_path_Modulo1633_REC41_2024_fil = os.path.join(base_dir,"data\\interim", "Modulo1633_REC41_2024_fil_v3.csv")
csv_path_Modulo1633_REC94_2024_fil = os.path.join(base_dir,"data\\interim", "Modulo1633_REC94_2024_fil_v3.csv")
# Build the path to the target CSV
csv_path_Modulo1631_REC91_2024 = os.path.join(base_dir_raw,"01_raws", "2024", "968-Modulo1631", "968-Modulo1631", "REC91_2024.csv")
csv_path_Modulo1632_RE223132_2024= os.path.join(base_dir_raw,"01_raws", "2024", "968-Modulo1632", "968-Modulo1632", "RE223132_2024.csv")
csv_path_Modulo1635_RE516171_2024 = os.path.join(base_dir_raw,"01_raws", "2024", "968-Modulo1635", "968-Modulo1635", "RE516171_2024.csv")
csv_path_Modulo1640_CSALUD01_2024 = os.path.join(base_dir_raw,"01_raws", "2024", "968-Modulo1640", "968-Modulo1640", "CSALUD01_2024.csv")

# Load the dataset
Modulo1633_REC41_2024_fil = pd.read_csv(csv_path_Modulo1633_REC41_2024_fil, low_memory=False)
Modulo1633_REC94_2024_fil = pd.read_csv(csv_path_Modulo1633_REC94_2024_fil, low_memory=False)
Modulo1631_REC91_2024 = pd.read_csv(csv_path_Modulo1631_REC91_2024, low_memory=False)
Modulo1632_RE223132_2024 = pd.read_csv(csv_path_Modulo1632_RE223132_2024, low_memory=False)
Modulo1635_RE516171_2024 = pd.read_csv(csv_path_Modulo1635_RE516171_2024, low_memory=False)
Modulo1640_CSALUD01_2024 = pd.read_csv(csv_path_Modulo1640_CSALUD01_2024, low_memory=False)

Modulo1633_REC41_2024_fil.shape, Modulo1633_REC94_2024_fil.shape, Modulo1631_REC91_2024.shape, Modulo1632_RE223132_2024.shape, Modulo1635_RE516171_2024.shape

((18335, 89), (18335, 54), (37117, 343), (34252, 149), (34252, 84))

In [3]:
csv_path_target_final = os.path.join(base_dir,"data\\interim", "target_final.csv")

# Load the dataset
target_final = pd.read_csv(csv_path_target_final,usecols = ['CASEID','premature_flag'], low_memory=False)

# Ensure CASEID is string
target_final["CASEID_9d"] = (
    target_final["CASEID"]
    .astype(str)     # convert to string
    .str.strip()     # remove extra spaces
    .str[:9]         # take first 9 characters
)

# If you want numeric again (preserves the 9 digits correctly)
target_final["CASEID_9d"] = (
    target_final["CASEID_9d"].astype(int))

target_final = target_final[~target_final['CASEID_9d'].duplicated(keep=False)]

target_final.head()

               CASEID  premature_flag  CASEID_9d
0        325503101  2               1  325503101
1        325504701  2               0  325504701
2        325505001  1               0  325505001
3        325508901  2               0  325508901
4        325509701  2               0  325509701

In [4]:
RANK_Modulo1631_REC91_2024_M_clear = ['SREGION','CASEID',
'S108N',
'S119',
'S119D',
'S704N',
'S816W',
'S816G',
'S816B',
'S816AL',
'S500B',
# 'S229A1',
# 'S229Y',
# 'S229A'
]



RANK_Modulo1635_RE516171_2024_M_clear =['CASEID',
    'V704',
'V715',
'V501',
'V716',
'V511',
'V631',
'V732',
'V504',
'V743F',
'V531',
'V525',
'V717',
'V743E',
'V743A',
'V702',
'V721',
'V705',


]
RANK_Modulo1632_RE223132_2024_M_clear = ['CASEID',
    'V212',
'V228',
'V218',
'V208',
'V217',
'V364',

]

RANK_Modulo1633_REC41_2024_fil_v2 =['CASEID',
    'M14',
'M13',
#'M17',
'M1',
#'M18',
#'M19',
'M19A',
'M2C',
#'M3C',
#'M3G',
'M42A',
# 'M42B',
'M42C',
'M42D',
'M42E',
'M43',
'M44',
'M45',
#'M46',
'M47',
'M48',
# 'M49A',
# 'M49B',
# 'M49C',
# 'M49D',
# 'M49X',
# 'M49Z',
# 'M57A',
# 'M57B',
'M60',
#'M3A',
'M57I',
#'M3H',
'M57O',
'M57G',
#'M3B',
'M57M',
'M57K',
'M57X',
'M2B',
'M57Q',
'M57E',
]


RANK_Modulo1633_REC94_2024_fil_clear_v2 = ['CASEID',
'S410B',
'S411B',
'S411F',
'S411G',
'S411H',
'S411I',
'S411J',
'S411K',
'QI422A_A',
'QI422A_B',
'QI422A_C',
'QI422A_D',
#'S426E',
#'S426GE',
'S411BA',
'S413',
'S441',
'S411DA',
'S411EA',
'S411CA',
'S422I',


]
RANK_Modulo1640_CSALUD01_2024_M_clear =['HHID',
    'QS25N',
'QS22A',
'QS27',
'QS102',
# 'QS27_B',
'QS207C',
'QS109',
# 'QS27_BD',
'QS25AA',
'QS25BB',
'QS406',
'QS100',
#'QS103U',
'QS107',
# 'QS110U',
# 'QS202',
# 'QS203U',
# 'QS204C',
# 'QS205U',
'QS206',
# 'QS27_D',
# 'QS27_BC',
'QS25A',
# 'QS27_E',
# 'QS27_ ',
'QS25C5',
'QS25C3',

]

In [5]:
target_final.head()

               CASEID  premature_flag  CASEID_9d
0        325503101  2               1  325503101
1        325504701  2               0  325504701
2        325505001  1               0  325505001
3        325508901  2               0  325508901
4        325509701  2               0  325509701

In [7]:

# Suponha que os seus DataFrames se chamem:
dfs = [Modulo1633_REC41_2024_fil[RANK_Modulo1633_REC41_2024_fil_v2], 
       Modulo1633_REC94_2024_fil[RANK_Modulo1633_REC94_2024_fil_clear_v2], 
       Modulo1631_REC91_2024[RANK_Modulo1631_REC91_2024_M_clear], 
       Modulo1632_RE223132_2024[RANK_Modulo1632_RE223132_2024_M_clear],
       Modulo1635_RE516171_2024[RANK_Modulo1635_RE516171_2024_M_clear],
       target_final]

# Nome da coluna usada como chave
key = "CASEID"  # ou "CASEID", conforme o seu caso

# Faz merge sucessivo de todos os DataFrames pela chave
data  = reduce(lambda left, right: pd.merge(left, right, on=key, how='inner'), dfs)
#data = data.merge(Modulo1640_CSALUD01_2024, on ='HHID', how='left')

data.info(verbose =True)

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 17548 entries, 0 to 17547
Data columns (total 79 columns):
 #   Column          Non-Null Count  Dtype
---  ------          --------------  -----
 0   CASEID          17548 non-null  object
 1   M14             14314 non-null  float64
 2   M13             14204 non-null  float64
 3   M1              14314 non-null  float64
 4   M19A            16079 non-null  float64
 5   M2C             14314 non-null  float64
 6   M42A            14204 non-null  float64
 7   M42C            14204 non-null  float64
 8   M42D            14204 non-null  float64
 9   M42E            14204 non-null  float64
 10  M43             14204 non-null  float64
 11  M44             13635 non-null  float64
 12  M45             14314 non-null  float64
 13  M47             14314 non-null  float64
 14  M48             14314 non-null  float64
 15  M60             14314 non-null  float64
 16  M57I            14204 non-null  float64
 17  M57O            14204 non-null  float64
 18  M57G            14204 non-null  float64
 19  M57M            14204 non-null  float64
 20  M57K            14204 non-null  float64
 21  M57X            14204 non-null  float64
 22  M2B             14314 non-null  float64
 23  M57Q            14204 non-null  float64
 24  M57E            14204 non-null  float64
 25  S410B           14140 non-null  float64
 26  S411B           14204 non-null  float64
 27  S411F           14204 non-null  float64
 28  S411G           14204 non-null  float64
 29  S411H           14204 non-null  float64
 30  S411I           14204 non-null  float64
 31  S411J           14204 non-null  float64
 32  S411K           14204 non-null  float64
 33  QI422A_A        14314 non-null  float64
 34  QI422A_B        13814 non-null  float64
 35  QI422A_C        3828 non-null   float64
 36  QI422A_D        3713 non-null   float64
 37  S411BA          13909 non-null  float64
 38  S413            14314 non-null  float64
 39  S441            16251 non-null  float64
 40  S411DA          12521 non-null  float64
 41  S411EA          13311 non-null  float64
 42  S411CA          13988 non-null  float64
 43  S422I           13652 non-null  float64
 44  SREGION         17548 non-null  int64
 45  S108N           17548 non-null  object
 46  S119            17548 non-null  object
 47  S119D           17548 non-null  object
 48  S704N           17548 non-null  object
 49  S816W           17548 non-null  object
 50  S816G           17548 non-null  object
 51  S816B           17548 non-null  object
 52  S816AL          17548 non-null  object
 53  S500B           17548 non-null  object
 54  V212            17548 non-null  object
 55  V228            17548 non-null  int64
 56  V218            17548 non-null  int64
 57  V208            17548 non-null  int64
 58  V217            17548 non-null  int64
 59  V364            17548 non-null  int64
 60  V704            17548 non-null  object
 61  V715            17548 non-null  object
 62  V501            17548 non-null  int64
 63  V716            17548 non-null  object
 64  V511            17548 non-null  object
 65  V631            17548 non-null  object
 66  V732            17548 non-null  object
 67  V504            17548 non-null  object
 68  V743F           17548 non-null  object
 69  V531            17548 non-null  int64
 70  V525            17548 non-null  int64
 71  V717            17548 non-null  int64
 72  V743E           17548 non-null  object
 73  V743A           17548 non-null  object
 74  V702            17548 non-null  object
 75  V721            17548 non-null  object
 76  V705            17548 non-null  object
 77  premature_flag  17548 non-null  int64
 78  CASEID_9d       17548 non-null  int32
dtypes: float64(43), int32(1), int64(11), object(24)
memory usage: 10.5+ MB

In [8]:
Modulo1640_CSALUD01_2024.head()

,ID1,HHID,QHCLUSTER,QHNUMBER,QHHOME,QSNUMERO,QSINTM,QSINTY,QSTOTVISIT,QSRESULT,...,QS731_E,QS731_EA,QS731_F,QS731_G,QS731_H,QS731_I,QS731_J,QS731_X,QS731_Y,PESO15_AMAS
0,2024,325503101,3255,31,1,2,5,2024,1,1,...,,,,,,,,,,157182.172077703
1,2024,325503901,3255,39,1,2,5,2024,1,1,...,,,,,,,,,,200845.215117424
2,2024,325504001,3255,40,1,1,5,2024,1,1,...,,,,,,,,,,432165.467953967
3,2024,325504701,3255,47,1,1,5,2024,1,1,...,,,,,,,,,,162338.353517329
4,2024,325505001,3255,50,1,2,5,2024,2,1,...,,,,,,,,,,162338.353517329

In [9]:
data= data.merge(Modulo1640_CSALUD01_2024, right_on= 'HHID', left_on  = 'CASEID_9d', how = 'left')
data.info(verbose=True, show_counts=True)

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 17548 entries, 0 to 17547
Data columns (total 337 columns):
 #    Column          Non-Null Count  Dtype
---   ------          --------------  -----
 0    CASEID          17548 non-null  object
 1    M14             14314 non-null  float64
 2    M13             14204 non-null  float64
 3    M1              14314 non-null  float64
 4    M19A            16079 non-null  float64
 5    M2C             14314 non-null  float64
 6    M42A            14204 non-null  float64
 7    M42C            14204 non-null  float64
 8    M42D            14204 non-null  float64
 9    M42E            14204 non-null  float64
 10   M43             14204 non-null  float64
 11   M44             13635 non-null  float64
 12   M45             14314 non-null  float64
 13   M47             14314 non-null  float64
 14   M48             14314 non-null  float64
 15   M60             14314 non-null  float64
 16   M57I            14204 non-null  float64
 17   M57O            14204 non-null  float64
 18   M57G            14204 non-null  float64
 19   M57M            14204 non-null  float64
 20   M57K            14204 non-null  float64
 21   M57X            14204 non-null  float64
 22   M2B             14314 non-null  float64
 23   M57Q            14204 non-null  float64
 24   M57E            14204 non-null  float64
 25   S410B           14140 non-null  float64
 26   S411B           14204 non-null  float64
 27   S411F           14204 non-null  float64
 28   S411G           14204 non-null  float64
 29   S411H           14204 non-null  float64
 30   S411I           14204 non-null  float64
 31   S411J           14204 non-null  float64
 32   S411K           14204 non-null  float64
 33   QI422A_A        14314 non-null  float64
 34   QI422A_B        13814 non-null  float64
 35   QI422A_C        3828 non-null   float64
 36   QI422A_D        3713 non-null   float64
 37   S411BA          13909 non-null  float64
 38   S413            14314 non-null  float64
 39   S441            16251 non-null  float64
 40   S411DA          12521 non-null  float64
 41   S411EA          13311 non-null  float64
 42   S411CA          13988 non-null  float64
 43   S422I           13652 non-null  float64
 44   SREGION         17548 non-null  int64
 45   S108N           17548 non-null  object
 46   S119            17548 non-null  object
 47   S119D           17548 non-null  object
 48   S704N           17548 non-null  object
 49   S816W           17548 non-null  object
 50   S816G           17548 non-null  object
 51   S816B           17548 non-null  object
 52   S816AL          17548 non-null  object
 53   S500B           17548 non-null  object
 54   V212            17548 non-null  object
 55   V228            17548 non-null  int64
 56   V218            17548 non-null  int64
 57   V208            17548 non-null  int64
 58   V217            17548 non-null  int64
 59   V364            17548 non-null  int64
 60   V704            17548 non-null  object
 61   V715            17548 non-null  object
 62   V501            17548 non-null  int64
 63   V716            17548 non-null  object
 64   V511            17548 non-null  object
 65   V631            17548 non-null  object
 66   V732            17548 non-null  object
 67   V504            17548 non-null  object
 68   V743F           17548 non-null  object
 69   V531            17548 non-null  int64
 70   V525            17548 non-null  int64
 71   V717            17548 non-null  int64
 72   V743E           17548 non-null  object
 73   V743A           17548 non-null  object
 74   V702            17548 non-null  object
 75   V721            17548 non-null  object
 76   V705            17548 non-null  object
 77   premature_flag  17548 non-null  int64
 78   CASEID_9d       17548 non-null  int32
 79   ID1             17548 non-null  int64
 80   HHID            17548 non-null  int64
 81   QHCLUSTER       17548 non-null  int64
 82   QHNUMBER        17548 non-null  int64
 83   QHHOME          17548 non-null  int64
 84   QSNUMERO        17548 non-null  int64
 85   QSINTM          17548 non-null  int64
 86   QSINTY          17548 non-null  int64
 87   QSTOTVISIT      17548 non-null  int64
 88   QSRESULT        17548 non-null  int64
 89   QSNINOS         17548 non-null  object
 90   QSRESINF        17548 non-null  int64
 91   QS20C           17548 non-null  object
 92   QSSEXO          17548 non-null  object
 93   QSMEF           17548 non-null  object
 94   QSDIA           17548 non-null  object
 95   QS22M           17548 non-null  object
 96   QS22A           17548 non-null  object
 97   QS23            17548 non-null  object
 98   QS24            17548 non-null  object
 99   QS25N           17548 non-null  object
 100  QS25AG          17548 non-null  object
 101  QS25A           17548 non-null  object
 102  QS25G           17548 non-null  object
 103  QS25AA          17548 non-null  object
 104  QS25BB          17548 non-null  object
 105  QS26            17548 non-null  object
 106  QS27            17548 non-null  object
 107  QS28            17548 non-null  object
 108  QS29A           17548 non-null  object
 109  QS29B           17548 non-null  object
 110  QS100           17548 non-null  object
 111  QS101           17548 non-null  object
 112  QS102           17548 non-null  object
 113  QS103U          17548 non-null  object
 114  QS103C          17548 non-null  object
 115  QS104           17548 non-null  object
 116  QS105           17548 non-null  object
 117  QS106           17548 non-null  object
 118  QS107           17548 non-null  object
 119  QS108           17548 non-null  object
 120  QS109           17548 non-null  object
 121  QS110U          17548 non-null  object
 122  QS110C          17548 non-null  object
 123  QS111           17548 non-null  object
 124  QS112           17548 non-null  object
 125  QS113           17548 non-null  object
 126  QS202           17548 non-null  object
 127  QS203U          17548 non-null  object
 128  QS203C          17548 non-null  object
 129  QS204U          17548 non-null  object
 130  QS204C          17548 non-null  object
 131  QS205U          17548 non-null  object
 132  QS205C          17548 non-null  object
 133  QS206           17548 non-null  object
 134  QS207U          17548 non-null  object
 135  QS207C          17548 non-null  object
 136  QS208           17548 non-null  object
 137  QS209           17548 non-null  object
 138  QS210           17548 non-null  object
 139  QS211U          17548 non-null  object
 140  QS211C          17548 non-null  object
 141  QS212T          17548 non-null  object
 142  QS212A          17548 non-null  object
 143  QS212AV         17548 non-null  object
 144  QS212AB         17548 non-null  object
 145  QS212B          17548 non-null  object
 146  QS212BV         17548 non-null  object
 147  QS212BB         17548 non-null  object
 148  QS212C          17548 non-null  object
 149  QS212CV         17548 non-null  object
 150  QS212CB         17548 non-null  object
 151  QS212D          17548 non-null  object
 152  QS212DV         17548 non-null  object
 153  QS212DB         17548 non-null  object
 154  QS212E          17548 non-null  object
 155  QS212EV         17548 non-null  object
 156  QS212EB         17548 non-null  object
 157  QS212F          17548 non-null  object
 158  QS212FV         17548 non-null  object
 159  QS212FB         17548 non-null  object
 160  QS212G          17548 non-null  object
 161  QS212GV         17548 non-null  object
 162  QS212GB         17548 non-null  object
 163  QS212O          17548 non-null  object
 164  QS212XV         17548 non-null  object
 165  QS212XB         17548 non-null  object
 166  QS212Z          17548 non-null  object
 167  QS213U          17548 non-null  object
 168  QS213C          17548 non-null  object
 169  QS214U          17548 non-null  object
 170  QS214C          17548 non-null  object
 171  QS215U          17548 non-null  object
 172  QS215C          17548 non-null  object
 173  QS216U          17548 non-null  object
 174  QS216C          17548 non-null  object
 175  QS217U          17548 non-null  object
 176  QS217C          17548 non-null  object
 177  QS218U          17548 non-null  object
 178  QS218C          17548 non-null  object
 179  QS219U          17548 non-null  object
 180  QS219C          17548 non-null  object
 181  QS220U          17548 non-null  object
 182  QS220CV         17548 non-null  object
 183  QS220CC         17548 non-null  object
 184  QS200           17548 non-null  object
 185  QS201           17548 non-null  object
 186  QS302C          17548 non-null  object
 187  QS303           17548 non-null  object
 188  QS304           17548 non-null  object
 189  QS305U          17548 non-null  object
 190  QS305C          17548 non-null  object
 191  QS306           17548 non-null  object
 192  QS307           17548 non-null  object
 193  QS308           17548 non-null  object
 194  QS309           17548 non-null  object
 195  QS311           17548 non-null  object
 196  QS312U          17548 non-null  object
 197  QS312C          17548 non-null  object
 198  QS313           17548 non-null  object
 199  QS301           17548 non-null  object
 200  QS302U          17548 non-null  object
 201  QS403           17548 non-null  object
 202  QS404           17548 non-null  object
 203  QS406           17548 non-null  object
 204  QS407           17548 non-null  object
 205  QS409           17548 non-null  object
 206  QS410U          17548 non-null  object
 207  QS410C          17548 non-null  object
 208  QS411           17548 non-null  object
 209  QS412U          17548 non-null  object
 210  QS412C          17548 non-null  object
 211  QS413           17548 non-null  object
 212  QS415           17548 non-null  object
 213  QS416U          17548 non-null  object
 214  QS416C          17548 non-null  object
 215  QS401           17548 non-null  object
 216  QS402           17548 non-null  object
 217  QS500           17548 non-null  object
 218  QS501U          17548 non-null  object
 219  QS501C          17548 non-null  object
 220  QS503           17548 non-null  object
 221  QS505A          17548 non-null  object
 222  QS505B          17548 non-null  object
 223  QS505C          17548 non-null  object
 224  QS505D          17548 non-null  object
 225  QS506           17548 non-null  object
 226  QS603           17548 non-null  object
 227  QS604           17548 non-null  object
 228  QS606           17548 non-null  object
 229  QS607           17548 non-null  object
 230  QS608           17548 non-null  object
 231  QS609           17548 non-null  object
 232  QS610           17548 non-null  object
 233  QS611           17548 non-null  object
 234  QS601A          17548 non-null  object
 235  QS601B          17548 non-null  object
 236  QS700A          17548 non-null  object
 237  QS700B          17548 non-null  object
 238  QS700C          17548 non-null  object
 239  QS700D          17548 non-null  object
 240  QS700E          17548 non-null  object
 241  QS700F          17548 non-null  object
 242  QS700G          17548 non-null  object
 243  QS700H          17548 non-null  object
 244  QS700I          17548 non-null  object
 245  QS702           17548 non-null  object
 246  QS703           17548 non-null  object
 247  QS704T          17548 non-null  object
 248  QS704A          17548 non-null  object
 249  QS704B          17548 non-null  object
 250  QS704C          17548 non-null  object
 251  QS704D          17548 non-null  object
 252  QS704E          17548 non-null  object
 253  QS704F          17548 non-null  object
 254  QS704G          17548 non-null  object
 255  QS704H          17548 non-null  object
 256  QS704I          17548 non-null  object
 257  QS706           17548 non-null  object
 258  QS707           17548 non-null  object
 259  QS709           17548 non-null  object
 260  QS710           17548 non-null  object
 261  QS711           17548 non-null  object
 262  QS713           17548 non-null  object
 263  QS714           17548 non-null  object
 264  QS715           17548 non-null  object
 265  QS716           17548 non-null  object
 266  QS717           17548 non-null  object
 267  QS719           17548 non-null  object
 268  QS720           17548 non-null  object
 269  QS721           17548 non-null  object
 270  QS722           17548 non-null  object
 271  QS723           17548 non-null  object
 272  QS724           17548 non-null  object
 273  QS725           17548 non-null  object
 274  QS726           17548 non-null  object
 275  QS727           17548 non-null  object
 276  QS728           17548 non-null  object
 277  QS729           17548 non-null  object
 278  QS730           17548 non-null  object
 279  QFIN            17548 non-null  object
 280  QS8INICIO       17548 non-null  object
 281  QS900           17548 non-null  object
 282  QS901           17548 non-null  object
 283  QS902           17548 non-null  object
 284  QS903S          17548 non-null  object
 285  QS903D          17548 non-null  object
 286  QS905S          17548 non-null  object
 287  QS905D          17548 non-null  object
 288  QS906           17548 non-null  object
 289  QS25C1          17548 non-null  object
 290  QS25C2          17548 non-null  object
 291  QS25C3          17548 non-null  object
 292  QS25C4          17548 non-null  object
 293  QS25C5          17548 non-null  object
 294  QS25C6          17548 non-null  object
 295  QS907           17548 non-null  object
 296  QS908           17548 non-null  object
 297  QS413A          17548 non-null  object
 298  QS413B          17548 non-null  object
 299  QS413B_A        17548 non-null  object
 300  QS413C          17548 non-null  object
 301  QS413D          17548 non-null  object
 302  QS413E          17548 non-null  object
 303  QS413E_A        17548 non-null  object
 304  QS413F          17548 non-null  object
 305  QS506B          17548 non-null  object
 306  QS708_A         17548 non-null  object
 307  QS708_AA        17548 non-null  object
 308  QS708_AB        17548 non-null  object
 309  QS708_B         17548 non-null  object
 310  QS708_C         17548 non-null  object
 311  QS708_D         17548 non-null  object
 312  QS708_E         17548 non-null  object
 313  QS708_EA        17548 non-null  object
 314  QS708_F         17548 non-null  object
 315  QS708_G         17548 non-null  object
 316  QS708_H         17548 non-null  object
 317  QS708_I         17548 non-null  object
 318  QS708_J         17548 non-null  object
 319  QS708_X         17548 non-null  object
 320  QS708_Y         17548 non-null  object
 321  QS731_A         17548 non-null  object
 322  QS731_AA        17548 non-null  object
 323  QS731_AB        17548 non-null  object
 324  QS731_B         17548 non-null  object
 325  QS731_C         17548 non-null  object
 326  QS731_D         17548 non-null  object
 327  QS731_E         17548 non-null  object
 328  QS731_EA        17548 non-null  object
 329  QS731_F         17548 non-null  object
 330  QS731_G         17548 non-null  object
 331  QS731_H         17548 non-null  object
 332  QS731_I         17548 non-null  object
 333  QS731_J         17548 non-null  object
 334  QS731_X         17548 non-null  object
 335  QS731_Y         17548 non-null  object
 336  PESO15_AMAS     17548 non-null  object
dtypes: float64(43), int32(1), int64(22), object(271)
memory usage: 45.1+ MB

In [10]:
data[data['premature_flag']==1]['QS27'].value_counts()

QS27
A     2169
B      706
       390
BD      52
C       38
E       17
BE       6
D        6
BC       4
Name: count, dtype: int64

In [11]:
data['S411F'].value_counts()

S411F
1.0    14159
0.0       39
8.0        6
Name: count, dtype: int64

In [12]:
data[data['premature_flag']==1]['S411F'].value_counts()

S411F
1.0    2725
0.0       9
8.0       1
Name: count, dtype: int64

In [14]:
data['M2C'].value_counts()

M2C
1.0    12780
0.0     1534
Name: count, dtype: int64

In [15]:
data[data['premature_flag']==1]['M60'].value_counts()

M60
0.0    2595
1.0     160
8.0       5
Name: count, dtype: int64

In [16]:
data['M60'].value_counts()

M60
0.0    13473
1.0      790
8.0       51
Name: count, dtype: int64

In [18]:
from scripts.utils import (save_file) 
save_file(data, dir = "data\\outputs", output_file = "data_consolidado.csv")